### ISSUE TITLE
Improving partner heath check

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#100]
## I want

we are working on some improvements in our monitoring especially on the system-monitoring regarding our partners. Ideally, we would like to use the following features for that:

- HTTP REST call with client Authentication
- Reply with a list of all organizations for the client:
- Organization identifier / Name
- Flag active/inactive
- Timestamp of last push
- Timestamp of last received command (API-call)
- Timestamp of the last health-check
- Register additional address for already existing health-report (sending it to our receive-push address and additionally to a system-monitoring address)

It is a kind of wish list. So please let me know what is/will be possible to implement.

Best regards,
Simon

## Use cases

system monitoring

**Comment by dario-hd** [comment]
Could you please elaborate on the use case? It's unclear what you want to achieve...
