### ISSUE TITLE
Timestamp for Changes of Daily Prices in the rateplan API

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#101]
## Question

Where can I find a precise timestamp when I adjust a daily price in a rateplan in the frontend?
How can I reproduce the exact changes (Timestamp) we make in the daily prices in specific rateplan? 

## Background

In the Rateplan API we receive a "from" and "to" timestamp in "rates", but I think thats the day, the rateplan is valid:
Example: https://api.apaleo.com/rateplan/v1/rate-plans/AUGSBURG-MAX1M/rates?from=2019-03-16&to=2019-03-22

**Comment by patrickHermannLimeHouse** [comment]
Do you have any update for me?

**Comment by dario-hd** [comment]
If got it correctly you want to know when a rate was modified, right?

**Comment by patrickHermannLimeHouse** [comment]
yes, thats correct :)

Kind regards
Sabine

[image: Limehome GmbH] <https://htmlsig.com/t/000001E5963Y>

Dr. Sabine Pagel | Head of Analytics & Pricing
sabine.pagel@limehome.de | +49 (0) 171 2113 515

Limehome GmbH
C/O Werk 1,
Atelierstrasse 29,
81671 München
www.limehome.de

[image: htmlsig.com] <https://htmlsig.com/t/000001E9WFX6>

This e-mail including any attachments is confidential and may be
privileged. It may be read, copied and used only by the intended recipient.
If you have received it in error please contact the sender immediately and
delete this message. Any unauthorized use or dissemination of this message
in whole or in parts is strictly prohibited.

ᐧ

Am Di., 26. März 2019 um 13:33 Uhr schrieb dario-hd <
notifications@github.com>:

**Comment by dario-hd** [comment]
Currently, such information is not available via API...
