### ISSUE TITLE
Payment data

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#103]
## Question

Where can I find a concrete payment via the swagger/ in your data?

## Background

Yesterday I made a payment for test purposes (folio id : RMEXQNLB-1-1):
![image](https://user-images.githubusercontent.com/42251140/55063012-68bc1e00-5077-11e9-8fb4-88fc8045751e.png)

I tried to find this payment in 
https://api.apaleo.com/finance/v1/payment-tasks?propertyId=BW249

But I didnt find it (txt. attached)
[190327 testing Payments.txt](https://github.com/apaleo/api/files/3012334/190327.testing.Payments.txt)

**Comment by pgrm** [comment]
hello @patrickHermannLimeHouse 

Payment tasks are meant for charging credit cards, which is an asynchronous process. You can read more about the introduction of the API in our announcement: https://github.com/apaleo/announcements/issues/4

You'll find all payments within the folio resource. This also includes completed payment tasks (successfully charged credit cards)

So the correct URL where you'll find all the data is `https://api.apaleo.com/finance/v1/folios/RMEXQNLB-1-1`
