### ISSUE TITLE
Requesting information regarding notification timestamp

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#104]
## Question

I need the timestamp information for **unit-assigned notification** of the following reservation-ids:
KWSKNQKV-1
AYOKCLTL-1
AVQPWHKB-1
UACGPBQC-1
MQXFQABH-1
IQVZJUEU-1

## Background

We have noticed some problems in the occurrence of events in our process and thus we want to identify the problem precisely. For doing that we want to know the time when the notification of the unit-assigned was sent out from your system. 

Thanks,
Anika

**Comment by dmitry-urenev** [comment]
@patrickHermannLimeHouse according to our article about notifications each notification should have the `timestamp`, which corresponds to the time when the event was created.
https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo

**Comment by patrickHermannLimeHouse** [comment]
Yes, we understand the logic but we would request you to kindly share the concrete timestamps.
You can share it via email as well to anika.goyal@limehome.de

Thanks a lot!

**Comment by andreastubbe** [comment]
Hello @patrickHermannLimeHouse , we don't store this information anywhere (and therefor cannot share it with you ;) )
