### ISSUE TITLE
In apaleo properties api I Need the property name in English and German language. 

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#105]
Hi ,
In apaleo property api I need the property name in both the language(English and German).
How can I do this?

**Comment by andreastubbe** [comment]
Check the API docs (https://api.apaleo.com/swagger/#/) for `/inventory/v1/properties/{id}` as an example: just pass `all` as the language query-parameter. Works the same way for all endpoints that support returning multi-language data.

**Comment by patrickHermannLimeHouse** [comment]
Thanks @andreastubbe

**Comment by limehome-dev** [comment]
For getting property name in english and german I have to hit api call for each property.
can i get all properties together with english and german language?

**Comment by ozonni** [comment]
@limehome-dev you can set `languages` = `all` to get all translations

**Comment by limehome-dev** [comment]
I want all properties in one hit
like this
inventory/v1/properties?languages=all

**Comment by ozonni** [comment]
unfortunately get list of properties api doesn't give you all languages at once. You need to query each property separately if you want to get additional data.

**Comment by limehome-dev** [comment]
OK thanks
