### ISSUE TITLE
Unexpected response notification api

### ISSUE THREAD

**Issue by BrunoStardekk** [apaleo/api#106]
Im working on activating a notification for hotels. 

Everything seems to work:
- Send the endpoint to `https://notifications.apaleo.com/v1/subscriptions`
- I receive the healthcheck, respond to it with a 200 OK 
- But I get a 500 error back for the `https://notifications.apaleo.com/v1/subscriptions` request

Trying it through swagger I get a 403 (apaleo-tracking-id: 0HLLNCN7S4GCR:00000001)

That's not alot of info but that all I have.. If you need more please let me know

**Comment by randyrod** [comment]
Hi BrunoStardekk,

Thanks for reaching out.

Could you please provide us the following information so we can track this:

1. The tracking id of the request when you get the 500.
2. The payload body that you are sending to the end point.
3. The HTTP method that you are using for each request (GET, POST, etc).
4. The full url path that you are using.

If you can provide the whole body of the request, that would be great. Just make sure to NOT post your private token here.

Thanks in advance.

**Comment by BrunoStardekk** [comment]
1. The tracking id of the request when you get the 500.

Im not getting anything back. Content is just empty.

2. The payload body that you are sending to the end point.

My test hotel example:
```
{
  "endpointUrl": "https://login.e-mailinglist.be/api/Reservations/SendApaleoConfirmationMail",
  "topic": "Reservation",
  "propertyId": "STARDEKKEL"
}
```

3. The HTTP method that you are using for each request (GET, POST, etc).

Using a POST

4. The full url path that you are using.

Not 100% sure what url you mean but my initial request is to
`https://notifications.apaleo.com/v1/subscriptions`

**Comment by randyrod** [comment]
Hi Bruno,

I think we have found the issue causing this response. Could you please try to make the request now?

**Comment by BrunoStardekk** [comment]
Im still getting a 500, InternalServerError.

Trying to trigger it through swagger in the hopes to get a tracking id but not luck. Also still no content in the responses of my subscriptions request.

**Comment by randyrod** [comment]
Ok so we have determined the issue, and the solution is a bit more complicated than what we thought.

We are working on fixing it, and we will keep you informed through here on the progress.

Sorry for the inconveniences this may cause.

**Comment by BrunoStardekk** [comment]
Hi randyrod,

Do you have any updates regarding this issue?

Thanks

**Comment by randyrod** [comment]
Hi BrunoStardekk,

We are still working on the solution to this problem. We're in the middle of prettying up our notification service, internally.

Will give you an update on it as soon as possible.

Sorry for the inconveniences.

**Comment by randyrod** [comment]
Hey @BrunoStardekk,

We are done with the changes on our end, and now you should be able to successfully create a subscription, and delete a subscription using the `SubscriptionId`. 

Please give it a try, everything should've stayed the same in the outside, we made sure that we only straightened the internals.
