### ISSUE TITLE
Connect only return access token

### ISSUE THREAD

**Issue by tuergeist** [apaleo/api#109]
## Question

When following Step 2 of https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0#connect
I only get an `access_token`, no refresh or id token. Thus I cannot follow the refresh procedure later on

## Background

Try to connect new app (mountlytics) to apaleo

**Comment by andreastubbe** [comment]
Can you send me the full response you get? Just x-out the tokens.

**Comment by tuergeist** [comment]
Here we go
`{"access_token":"xxx","expires_in":3600,"token_type":"Bearer"}`

**Comment by andreastubbe** [comment]
Wild guess (should have asked for the request you send, too :) ):

> Note that 'refresh_token' will only be present in the response if you included the 'offline_access' scope.

**Comment by tuergeist** [comment]
? offline_access for an API ?
Steht hier nicht so https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0#connectscreen

**Comment by andreastubbe** [comment]
It's an odd name, but one The Internet chose, not we. It means the user (human) is 'offline', not sitting there and clicking okay or connect. The machine making the calls is obviously still online.

The info is on the page, but not in the most obvious place.

-- but more importantly, did that help, does it work now?
