### ISSUE TITLE
Knowing which new properties we have access to after oauth

### ISSUE THREAD

**Issue by eloihdez** [apaleo/api#11]
## Question

How is it possible to know which property ids are we being authorized to during the oauth process? Are we supposed to perform one GET before auth and one after to see the diff?

I need to map those property ids to the ones we have in our app.

Thank you

**Comment by eloihdez** [comment]
Okay, got it. Then I need a refresh token for each account right?

**Comment by ozonni** [comment]
correct, you get access/refresh token per account.
