### ISSUE TITLE
Another callback URI for development

### ISSUE THREAD

**Issue by tuergeist** [apaleo/api#110]
## I want

to have another (or a variable) URI for development. This is different from the URI we provided to Andrea for integration.

## Use cases

Development takes place on local machines (reversed via ngrok) or development servers, but never on production systems. At least on our side :)

**Comment by andreastubbe** [comment]
You can have as many redirect URLs as you want, and add local ones. Just send it over, and we can add it to your client.

**Comment by tuergeist** [comment]
`127.0.0.1:5000` :)

**Comment by andreastubbe** [comment]
new client is on its way and should be there in a few minutes! Credentials will stay the same.
