### ISSUE TITLE
List of scopes

### ISSUE THREAD

**Issue by tuergeist** [apaleo/api#111]
## Question

Where can I find a "complete" list of scopes including their identifiers useable for the authorize call

## Background

There is 0 (zero) documentation about it. Google didn't find anything as well.

**Comment by andreastubbe** [comment]
You can find the scopes in the documentation of each API resource / method. Normally you know which APIs you want to call, and then just look up the scope.

If you want the full list, you could have fun with regex and get it from the swagger.json: https://api.apaleo.com/swagger/inventory-v1/swagger.json (and similar for each of the modules).

`Scopes required: '(^')+'` => get $1.
