### ISSUE TITLE
Cannot auth againt notification service / via swagger

### ISSUE THREAD

**Issue by tuergeist** [apaleo/api#113]
## Question

I cannot auth agains notification service here https://notifications.apaleo.com/swagger/index.html#/Subscriptions/V1SubscriptionsPost
Hit authorize button, enter client_id/secret I always get an **auth error*

![image](https://user-images.githubusercontent.com/506530/55725631-63af8500-5a0e-11e9-8086-870c08041179.png)

**Comment by tuergeist** [comment]
For me it's unclear how to auth against this service at all. Bearer token doesn't work either. No doc found.

**Comment by andreastubbe** [comment]
It works like for the core api.apaleo.com/swagger - did you get it working there? When getting the token, then this token works the same in all services. For notifications, you'll have to specify the scope `notifications:subscriptions.manage`

**Comment by tuergeist** [comment]
works now
