### ISSUE TITLE
Notification service only subscribeable once

### ISSUE THREAD

**Issue by tuergeist** [apaleo/api#114]
There is no (working) delete or patch endpoint for notifications. Thus a notification once registered lives forever.

This makes testing even harder, if not impossible.

```HTTP/1.1 422 Unprocessable Entity
Apaleo-Tracking-Id: 0HLLS6OQBD3B2:00000001
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 08 Apr 2019 15:52:09 GMT
Server: nginx
Transfer-Encoding: chunked

{
    "message": "Subscription is already enabled for another endpoint",
    "type": "EnabledForAnotherEndpoint"
}
```

## Proposal

Just overwrite the old subscription

**Comment by andreastubbe** [comment]
We're in the middle of prettying up our notification service, internally. Once we're done, deleting will be available again. Will let you know as soon as it's there.

Until then, there's unfortunately nothing I can do to help you. If you're just starting on the integration, I would very highly recommend to start at the other end of what you're building, not at notifications.

Sorry about that, please accept this annoying "under construction" gif as an apology:
![Under_construction_graphic](https://user-images.githubusercontent.com/5329373/55740143-c151ca80-5a2a-11e9-9bb1-ce29ac2266fc.gif)

But seriously, we're working on bringing this back as quickly as we can.

**Comment by tuergeist** [comment]
Hmm. Notifications are the very beginning for us as we avoid polling as much as we can. Thus, what else than notifications could do this job? 

I'll wait then.

**Comment by andreastubbe** [comment]
No, the API should stay stable. Just changing the guts.

You should definitely go for notifications, but if you don't want to be blocked right now in developing, you can do everything that's coming after you received the notification - getting the reservations and processing them.

**Comment by tuergeist** [comment]
Done :)

**Comment by randyrod** [comment]
Hey @tuergeist,

We have made it possible now to delete the subscriptions using their specific `SubscriptionId` with the following endpoint: `/v1/subscriptions/{id}` in the notification API, then you can create a new one if required using the same endpoint and data model that you were using before. 

As @andreastubbe said everything stayed the same, the only thing that we changed were the guts. Sorry for keeping you waiting for these enhancements.

If you have further questions feel free to let us know.
