### ISSUE TITLE
Notifications endpoint 404

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#115]
I've tried to subscribe a hotel to Apaleo with this endpoint: https://notifications.apaleo.com/v1/subscriptions

`{"endpointUrl":"myurl", "topic":"Reservation", "propertyId":"MUC"}`

The Response is: `Net::HTTPNotFound 404 Not Found `
Tracking-ID: 0HLLT16L999MV:00000001

I wanted to check if the endpoint is correct, but swagger is also unavailable.

I've tried to test it with Postman. Don't know why, but this worked.
Tracking-ID: 0HLLT16L999QA:00000001

Could you tell me wat was wrong?

**Comment by andreastubbe** [comment]
The notifications service is having some hick-ups and is sometimes not available for short times (right now, it's back again). We're working on improving the stability. Until then, sorry for the bad experience.
