### ISSUE TITLE
Data Updation in Timeslices

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#116]
## Question

We are working with the reservations timeslices data (https://api.apaleo.com/booking/v1/reservations?expand=timeSlices) and we want to understand the data updation concept in case of reservation modifications like

1) Shortening a stay
2) Adding another guest or subtracting a guest
3) Cancellation during stay
4) Prolonging a stay
5) Any other price changes during stay like due to refunds, discount code etc.

We would specifically like to know the changes that occur in gross amount/ net amount due to the above scenarios.

Thanks!

**Comment by dario-hd** [comment]
Do you mean using notification?

**Comment by patrickHermannLimeHouse** [comment]
Yes, does the notification inform us about those changes and also, in general, how the data is changed after the above changes.

**Comment by dario-hd** [comment]
Currently, you will only get the id of the changed reservation. Then, you would need to retrieve the reservation yourself to actually see the what changed. You can find more info [here](https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo).

**Comment by patrickHermannLimeHouse** [comment]
and does the gross amount of a particular slice reflects the change like decrease in amount in case of refund?

**Comment by dario-hd** [comment]
If the price of a particular time slice was modified, yes.
