### ISSUE TITLE
strange character in access token

### ISSUE THREAD

**Issue by ServicePlusGmbH** [apaleo/api#117]
while connect flow we received following character in the access token 

	ࠁ

**Comment by ozonni** [comment]
@ServicePlusGmbH do you have a timestamp when it happened?

**Comment by ServicePlusGmbH** [comment]
While setting up MUC for Philip between 12:40 an 13:00 o'clock. Andrea must know it in detail

**Comment by ozonni** [comment]
@ServicePlusGmbH i don't see any failures in our logs for this time period. Could you please share more data with us, you can create zendesk issue a provide the token with this symbol.

**Comment by ServicePlusGmbH** [comment]
I'll try my best but I can not guarantee because the token is not fully copiable and the logs are not complete because of this character
