### ISSUE TITLE
First step of the OAuth mechanism

### ISSUE THREAD

**Issue by dbajet** [apaleo/api#118]
## Question

Trying to follow the guide on https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0, for the Step 1 I created:

https://identity.apaleo.com/connect/authorize?response_type=code&scope=properties.read&client_id=ClientIDProvided&redirect_uri=TheURLToTheApp&state=12345

And rather than to see the consent screen,  I received an error: Request Id: 0HLLVBC37PFI6:0000018D

Any idea what am I doing wrong here?

(I doubt this is the right forum to disclose my `ClientIDProvided` and `TheURLToTheApp`, I assume that can be found with the Request Id)

**Comment by hospitalityPulse** [comment]
You can close this issue: I have provided a misspelled redirect uri.

**Comment by dbajet** [comment]
You can close this issue: I have provided a misspelled redirect uri.
