### ISSUE TITLE
API Key for Adyen Integration

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#119]
## Question
Which User are you using for our Adyen/ Apaleo Integration? 
We are using ws@company.hotellimehouse.
Do you have another one?
Thanks!
Sabine

## Background

we want to receive our data from the Adyen API for Accounting reasons and we want to change the API Key. We want to make sure that this will not affect your Adyen integration for us

**Comment by pgrm** [comment]
hello @patrickHermannLimeHouse the adyen configuration can be changed from within apaleo in https://app.apaleo.com/account/payment there you can see, that apaleo is using the same user

**Comment by patrickHermannLimeHouse** [comment]
Hi!
Thanks for the fast aswer. This was very helpful!
Greets
Sabine

[image: Limehome GmbH] <https://htmlsig.com/t/000001E5963Y>

Dr. Sabine Pagel | Head of Analytics & Pricing
sabine.pagel@limehome.de | +49 (0) 171 2113 515

Limehome GmbH
C/O Werk 1,
Atelierstrasse 29,
81671 München
www.limehome.de

[image: htmlsig.com] <https://htmlsig.com/t/000001E9WFX6>

This e-mail including any attachments is confidential and may be
privileged. It may be read, copied and used only by the intended recipient.
If you have received it in error please contact the sender immediately and
delete this message. Any unauthorized use or dissemination of this message
in whole or in parts is strictly prohibited.

ᐧ

Am Di., 16. Apr. 2019 um 19:00 Uhr schrieb Peter Grman <
notifications@github.com>:
