### ISSUE TITLE
Auth FAQ

### ISSUE THREAD

**Issue by aprooks** [apaleo/api#12]
1. OAuth (apaleo.connect) is not working and what is the difference with token auth?

We provide 2 ways of authentication. 
* Direct token request https://apaleo.com/getting-started-with-apaleo-apis/ will give you access to a single account.
* OAuth https://apaleo.com/connect-your-app-with-oauth-2-0/ is a generic way of accessing an account, but apaleo users will have to confirm your application have permissions to access data in Apaleo. 

OAuth won't work when you try to use client_id which is used for a token request. Send us a request via https://apaleo.com/api-credentials/ to request a new client id. Be sure to provide redirect URLs as well. 

There could be several URLs (for example for testing and production). Just a [sub-]domain name will not work

2. When confirming authentication only a single scope is shown in "Application Access" token.

Scope in a callback url must be a string with scopes separated by space. Instead of 
"/connect/authorize?scope=units.read&scope=units.manage" url should be like "/connect/authorize?scope="units.read units.manage"

3. I have admin scope but cannot authenticate via swagger of notifications service.

Notifications service uses it's own set of scopes and ignores "admin". Email us with your client_id to request scopes change. Also, we never give admin access for production usage, so it might reasonable to ask for a subset of scopes you intend to use for your application in production. 

4. I have OAuth but would like to use some new scopes.

In this case, hotelier must give you permissions to use new scopes. This can be achieved by the following flow:

* Let's say apaleo creates an endpoint with new scopes, which your application would like to use.
* Application developer notifies hotelier, that re-authorization is required (e-mail, UI, whatever) and provides a link to a page with a connect button which will ask for new scopes. For convenience, it can be a different page, let's say "http://example.com/apaleo/re-authenticate".
* When hotelier confirms authentication with the new set of permissions, your application will receive new token, which should replace an old one. 

During this process, there is no need to clean up an old token, so that your application will be working. New features should only be enabled after you receive a new set of permissions

This re-auth page must be white listed by apaleo, so be sure to send it to us in advance. 

5. I want to go to production!

Cool! At first, we will have a go-live call, discuss API and how you use it, what scopes your application uses and if all goes well, we will send you production keys. Be sure to email us beforehand to schedule a meeting.

**Comment by aprooks** [comment]
UPD: added a flow to request new scopes when using OAuth.

**Comment by TomaszFitulski** [comment]
Hi Alexander,

I have register on https://apaleo.com/api-credentials/
My username is: tomasz.fitulski@yieldplanet.com

Next step:
https://blog.apaleo.com/developer/getting-started-with-apaleo-apis
Get access for your app


Request your very own client credentials that lets you play with the API in your test account.

This part is done as above:

Use it

apaleo APIs are protected using OAuth2 - the de-facto standard for API security. Here's a short guide to get you started:

Step 1: To get access to our APIs, you need to use your client id and secret to obtain an access token.

Combine your client id and secret into a string, separated by colon yourClientId:YourClientSecret and encode with Base64. This will result in one long string

I don't understand step 1. How can I get my client id and secret id to generate access token, if you don't provide it to me?

BR
TF

**Comment by andreastubbe** [comment]
Tomasz, you received a follow-up email after requesting credentials, asking for the scopes and redirect URL.
Check https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0, in the section "consent screen" for more information.
For scopes, if you are implementing a channel manager, you will probably only need to make the calls listed in the channel integration guide, but please review if you need more.
Check the APIs linked from api.apaleo.com. See the little picture for an example where you can find them.
<img width="355" alt="scopes" src="https://user-images.githubusercontent.com/5329373/51917804-9f134f00-23e0-11e9-9224-8ba6d48b7ed6.png">

**Comment by TomaszFitulski** [comment]
Hi Andrea,

Question from my developer:

offline_access   - to refresh tokens
distribution:subscriptions.manage -  Crud on subscriptions
unitgroups.read - get unit groups for mapping
rateplans.read - get rate plans for mapping


About Redirect URL (https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0)

if Redirect URL	 (from  Consent screen section) must be same as redirect_uri (in Step 1: Get the user's authorization)
then 
it will be 
https://secure.yieldplanet.com/XMLServices/Apaleo/Authorization.ashx
this endpoint will read code from your request and finally redirect user to https://channelmanager.yieldplanet.com/Setup/Partners
 

if Redirect URL	 (from  Consent screen section) can be != redirect_uri (in Step 1: Get the user's authorization)
Redirect URL	 from  Consent screen section will be https://channelmanager.yieldplanet.com/Setup/Partners

 
btw - should uri from redirect_uri in Step 1: Get the user's authorization be the same for all requests or can we add query string parameters to it? 
For example https://secure.yieldplanet.com/XMLServices/Apaleo/Authorization.ashx?qry1=321@qry2=3213 ?

**Comment by andreastubbe** [comment]
Thanks, that's all that's needed. The query string is not possible, and the URL is the "redirect_uri". Your client will be on it's way to you soon!
