### ISSUE TITLE
Konfigurierbares tools für den post von payments in abhängigkeit der rateplans

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#121]
## I want

to be able to post payments depending on the rateplan

## Use cases
- build our own logic for our refundable tarifs, when the payment should be made. We would like to post each payment for reservations within the nonrefundable rateplans 2 weeks before arrival date, for example

## Examples

see usecase

Kind regards
Sabine

**Comment by andreastubbe** [comment]
Hi Sabine,

That should be pretty straightforward to build.

Check https://github.com/apaleo/announcements/issues/4 for the general flow. You'll need to pass a folioId. To get the correct folio for a reservation, you can ask the folio API. Filter by reservationId, and "onlyMain". One thing to look out for are virtual CCs from Expedia or BDC - they might not be "active" yet, and will complain when you try getting the money.

Cheers,
Andrea
