### ISSUE TITLE
"Invalid Scope" when querying for token

### ISSUE THREAD

**Issue by jordanl17** [apaleo/api#122]
## Question

We were setup with the notifications scopes, however when we post to `https://identity.apaleo.com/connect/token`, we receive `"error": "invalid_scope"`
## Background

We post the following using POSTMAN:

```
POST /connect/token HTTP/1.1
Host: identity.apaleo.com
Authorization: Basic xxx
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: 6cb2e1f2-bf2b-4afa-978d-3d0d5477adc2
grant_type=client_credentialsclient_secret=xxxclient_id=BHPeoplescope=notifications%3Aadmin
```

Thanks for any help

**Comment by dmitry-urenev** [comment]
Hey @jordanl17 `POST /connect/token` api doesn't accept the list of scopes as a parameter. You need to provide authorisation code instead. It already contains the information about scopes. Please check our article for more info: https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0

**Comment by jordanl17** [comment]
Thanks @dmitry-urenev I've since managed to receive an authorisation code from following step one of the article. We now are completing step 2, but receive a "error": "invalid_grant" response.
<img width="682" alt="Screen Shot 2019-04-20 at 22 47 20" src="https://user-images.githubusercontent.com/20559627/56462629-763a9e80-63be-11e9-99f5-363635684d80.png">

**Comment by ozonni** [comment]
@jordanl17 i see some requests failed because you tried to exchange the auth code several times.
The auth code can be used only once. After that it's not valid.

Also i see some successful requests, meaning you managed to get access&refresh token?

**Comment by jordanl17** [comment]
We managed to get access after a few attempts. We had success when we set the redirect_uri exactly equal to our redirect url, rather than encoding it.
