### ISSUE TITLE
Night Audit Function in Housekeeping Role

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#123]
## Question

Is the night audit function working while i click the "Start"-Button in Apaleo?

What happens when i am clicking this button? It does not lead to a "Access denied" side like a click on "View arrivals" does.

We at limehome have automized the night audit. Did my "test-click" interfere our process?

## Background

I mean the following Pop-Up you get when clicking on "Start night audit": https://imgur.com/zsTkLKo

I am currently checking the role model you offer us at https://apaleo.zendesk.com/hc/en-us/articles/360001498771-User-roles. 

i tried how apaleo looks like in the role of a housekeeping person. Here i came across the night audit function.

Thanks a lot,

Patrick

**Comment by andreastubbe** [comment]
Whether you trigger the night audit using the button or with the automation, the same API endpoint is called. Two things happen, one harmless, the other... depends on your configuration:
- all charges on all folios which have the "business day" set to now or earlier are posted to accounting. Whether you do that a little earlier is not super relevant, and you can also repeat it multiple times without breaking anything (please don't, though, there's quite some computing that is happening in the background)
- reservations that were supposed to arrive today, but haven't check in yet are set to no-show (but this is configurable, so it might be that nothing happens there). That can lead to no-showing some reservations that are just late arrivals.

And yeah, housekeeping shouldn't have access to that. We'll check and revise our roles and access rights.
