### ISSUE TITLE
Optional Parameter for "GET /booking/v1/reservations/{id}/service-offers"

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#127]
## I want

It would be great to have a query parameter to get also sold offers.
`GET /booking/v1/reservations/{id}/service-offers?addSoldOffers=true`
(Just for example)

## Use cases

We want to offer services yes, but also show which services are already booked to inform the guest.

## What I do

Currently I get all possible services with 
`GET rateplan/v1/services?propertyId=BER&onlySoldAsExtras=true`
Then I'm merging the list with the infromation from
`GET booking/v1/reservations/{id}?expand=services`

Benjamin told me that this way is very outdated. But with 
`GET /booking/v1/reservations/{id}/service-offers` 
I have to do the same. Only that I merge this data with the sold services.
`GET /booking/v1/reservations/{id}/services`

Is there another, better, way to handle it?

**Comment by dario-hd** [comment]
If you also want to show the already booked services there's currently a no better way to do it other than merging the response from those endpoints.
