### ISSUE TITLE
Unable to subscribe the property for now end point

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#128]
Hi,
I am getting the the below error when I try to subscribe the property using https://webhook.apaleo.com.
{
  "messages": [
    "A subscription for PropertyId: AACHEN and topic: Reservation already exists"
  ]
}

**Comment by andreastubbe** [comment]
Hi there,

as the error message tells you, the subscription fails because you already have one. It also doesn't make a whole lot of sense to have more than one subscription for a service.

If you don't like the old subscription anymore and want to replace it, you can:
- GET /subscriptions, to retrieve all subscriptions you have
- DELETE the one you want to replace
- POST a new one.

**Comment by limehome-dev** [comment]
@andreastubbe 
Could you please tell me why I am not getting the Folio Notification for any property. While I have subscribe it for topic Folio earlier.

**Comment by pgrm** [comment]
@limehome-dev unfortunately we can't until you provide us with more data.

- What is the `apaleo-tracking-id` of the request with which you created the subscription?
- What is your subscription ID?
- What is the client id + account code + property id for which you created the subscription?

Which Folio Notifications would you expect to get? So far we only dispatch notifications if the balance of a folio changed.

**Comment by limehome-dev** [comment]
Sorry I can not have apaleo-tracking-id and subscription ID
client id is : price-app-limehouse
property id: AACHEN

**Comment by pgrm** [comment]
I'm sorry, but you guys asked for an endpoint to retrieve existing subscriptions and you don't use it? The endpoint was announced in https://github.com/apaleo/announcements/issues/18

You should watch that repository to get updates about API changes.

Taking your client id and secret you can authorize here: https://webhook.apaleo.com/swagger/ to retrieve the list of existing subscriptions. Then you'd see that your subscription ID is `c37ca25c-8075-45aa-90b6-894fcae8381e` and the endpoint you provided, to which we are sending the webhooks is `https://example.com/` which is definitely an error on your side, as I don't expect that you own the domain `example.com`.
