### ISSUE TITLE
Tax Details Object

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#13]
## Question

How do we get tax details for reservations returned from `GET booking/v1/bookings`?

## Background

For the `GET booking/v1/offers` endpoint there is a object named `taxDetails`, but this is not present for get bookings.

**Comment by lukeclifton** [comment]
@pgrm ok thanks for the info

**Comment by dario-hd** [comment]
Hi @lukeclifton, what's the use case for this? Did you consider that there could be some manual charges added to the reservation? Did you consider that some charges could be moved out from the reservation? Do you need to display those charges?

To us, it seems that such information is more about folios and not the reservation itself.

**Comment by lukeclifton** [comment]
Is adding `taxDetails` to GET reservations endpoint no longer in the backlog?

**Comment by dario-hd** [comment]
@lukeclifton we just added the tax details to the reservation API.

**Comment by lukeclifton** [comment]
thanks @dario-hd

**Comment by oluyoung** [comment]
i'm having trouble finding the API doc with the taxDetails in the reservations endpoint. can you help point that out, because I also checked the response data when i make a request to the reservation endpoint i do not get the taxDetails either. Thank you
