### ISSUE TITLE
Notifications for changes in rateplans

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#130]
## I want

to monitor our price change to identify the influence of a change and the offered price on the number of bookings 

## Use cases

we are changing our prices at least 2 times a day. This change per se and the concrete price are influencing the number of bookings. Therefore I would like to receive a notification as soon as any kind of change takes place in any kind of rateplan. With this notification, we can build a history of prices set in our rateplans with concrete timestamps. Then we can compare the timestamp of a booking and the timestamp of the prices to analyse the influence.

## Examples

see Use cases

## What I do

see Use cases

**Comment by dario-hd** [comment]
Hi @limehome-dev, thanks for this. We will consider it, but don't plan to implement this soon. In the meanwhile, we already have something that you could use. You can check our [distribution guide](https://blog.apaleo.com/developer/channel-integration-guide) specifically the _Getting ARI data_ section. I hope this helps.
