### ISSUE TITLE
In apaleo Folio notification could not understand type 'balnace-changed'

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#131]
Hi,
I received the notification for folio id 'NSWLDDIU-1-1' twice as 'balance-changed'. But I did not see any change in balance amount. could you please let me know why this is happening. 
Also please let me know what is 'charge-posted' notification type?

**Comment by rliman** [comment]
Hi!

You could receive 2 identical notifications for balance change, since we don't guarantee exactly once delivery. If you do need to process those events exactly once, you can distinguish them by `id` and cache those ids.
Also right now we don't put payload in those events, so in order to get the real balance, you have to call our API.

As for `charge-posted` event -- please, ignore that. It'll be removed soon.

**Comment by limehome-dev** [comment]
I call the api for that folio id but balance is same on both time.
eg. 'balance': {'amount': 0.0, 'currency': 'EUR'} for type 'balance-changed'

**Comment by pgrm** [comment]
Hello @limehome-dev could you please send us the IDs of those events? Otherwise we can't investigate the issue.

When you retrieved the Folio, did you verify if charges or payment have been added to it? The balance can stay the same, if there were multiple actions on that Folio between your calls.

**Comment by limehome-dev** [comment]
folio id is : NSWLDDIU-1-1 and QHZOXIWD-2-1
notification type is : balance-changed

**Comment by pgrm** [comment]
@limehome-dev those are entity IDs of the folios. It would be much easier if you could give us the event IDs of the events which you claim were delivered faulty to you. 

An event id is in the webhook payload and looks like this: `"id": "ec5a1fe4-331c-450a-915c-5caa231cc825"`

we'll try to figure out what was going on, given the information you provided us with, but we won't be able to give you a definitive answer if you won't be able to provide us with the event IDs. 

Maybe you at least have a timestamp, when you received those events / performed the request? That would help us giving you a more specific answer.

**Comment by pgrm** [comment]
@limehome-dev we looked at it.

- For the folio NSWLDDIU-1-1 - The folio was created with a non 0 balance and the amount was automatically captured immediately. Which means, by the time you processed those webhook events, the data for the original event didn't exist anymore, that's why you got twice the same folio. This is unfortunately and unsolvable issue, as you're requesting the up to date information and can't get historic data, but the event delivery works correctly.

- For the folio QHZOXIWD-2-1 - there were actually 2 events for 2 different folios for 2 different reservations within the same booking QHZOXIWD. The other event was delivered for the folio QHZOXIWD-1-1

**Comment by limehome-dev** [comment]
for folio id
the event ids are : bf02ff05-e6b3-4687-813e-79feffc9af39 , eacada4f-3c6a-45f6-97cb-d029cb4b9f0b.
I immediately create the history as soon as notification occurred.  But in history table I am seeing that 
the balance is 0

**Comment by pgrm** [comment]
@limehome-dev yes, those are the events that we've found. We're currently working on improving the delivery time of webhooks, but you are basically racing against our payment provider.

You have automated payment activated, that means, that we charge the credit card for the reservation as soon as the reservation is created. If the payment provider confirms the credit card charge quicker, than you requesting the folio, then you've lost the race. This problem cannot be solved with the current solution.

We are also thinking about delivering data with the webhooks. In that case you won't need to query the folio anymore, and the history will just show up for you. But that will take time until it's implemented.

**Comment by limehome-dev** [comment]
Hi!
is there any update on that topic?
It is still a issue for us.
To stop the race against the payment provide I would like to check 2 possibilities:
- can we delay the automatic payment process within Apaleo for a certain time period? e.g. 5 min?
- if we will post our payments instead of using the automation. Do we still run into the same problem?
https://github.com/apaleo/announcements/issues/4

What do you recommend us to solve the webhook-problem?

**Comment by pgrm** [comment]
@limehome-dev 

> can we delay the automatic payment process within Apaleo for a certain time period? e.g. 5 min?

no

> if we will post our payments instead of using the automation. 

yes, you could do that. The folio contains a field `allowedPayment` which you can use to trigger the payment task. However, keep in mind that some virtual credit cards from OTAs are only available at a later time. apaleo's automation takes this into account, to trigger the payment once the virtul credit card is active. I don't think, there is currently an event available that you could listen on to have a comparable functionality. But I can check to add it.

> Do we still run into the same problem? apaleo/announcements#4

Which problem do you mean?

Generally, delivering data via webhooks will come and it will be the easiest way to implement what you need. We'll also improve the guarantees of webhook deliveries. But it will take a while until it's released. In the meanwhile, 

- we can check if we can add an event for active credit card added to the reservation, so you can implement your own payment automation
- you can try to determine the old balance based on the posted payment and charges, in case you got 2 simultaneous notifications
