### ISSUE TITLE
I need to create a new rate plan in apaleo test system

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#132]
Hi,
I have created the property 'Aachen' in test system. 
I need to create a new rate plan for it. 
How can I create a rate plan for it?

**Comment by rliman** [comment]
Hi

To create RatePlan you need to call an endpoint `POST https://api.apaleo.com/rateplan/v1/rate-plans`. Here's a body example:

```
{
  "code": "NONREF_DBL",
  "propertyId": "MUC",
  "unitGroupId": "MUC-DBL",
  "cancellationPolicyId": "MUC-FLE",
  "channelCodes": [
    "Direct",
    "BookingCom",
    "Ibe"
  ],
  "serviceType": "Accommodation",
  "vatType": "Reduced",
  "corporateRateCode": "APA55100",
  "timeSliceDefinitionId": "MUC-NIGHT",
  "name": {
    "de": "Nicht Stornierbar",
    "en": "Non Refundable"
  },
  "description": {
    "de": "Nicht Stornierbar",
    "en": "Non Refundable"
  },
  "minGuaranteeType": "PM6Hold",
  "bookingPeriods": [
    {
      "from": "2019-04-30T13:05:01.4787485+02:00",
      "to": "2019-05-14T13:05:01.4787485+02:00"
    },
    {
      "from": "2019-05-17T13:05:01.4787485+02:00",
      "to": "2019-07-06T13:05:01.4787485+02:00"
    }
  ],
  "restrictions": {
    "minAdvance": {
      "hours": 12,
      "days": 180
    },
    "maxAdvance": {
      "months": 24
    }
  },
  "pricingRule": {
    "baseRatePlanId": "MUC-NONREF_SGL",
    "type": "Absolute",
    "value": 20
  },
  "surcharges": [
    {
      "adults": 2,
      "type": "Absolute",
      "value": 10
    }
  ],
  "ageCategories": [
    {
      "id": "MUC-BABY",
      "surcharges": [
        {
          "adults": 1,
          "value": 20
        }
      ]
    }
  ],
  "includedServices": [
    {
      "serviceId": "MUC-BRKF",
      "grossPrice": {
        "amount": 10,
        "currency": "EUR"
      }
    }
  ],
  "subAccountId": "MUC-DBL"
}
```

Also, since you have an account, you can play with API with https://api.apaleo.com/swagger

**Comment by andreastubbe** [comment]
Or, use the UI: https://apaleo.zendesk.com/hc/en-us/articles/360001744291-Setting-Up-Rate-Plans

**Comment by limehome-dev** [comment]
I have tried but it is giving response
{
  "messages": [
    "Name has unsupported translations.",
    "Description has unsupported translations."
  ]
}

**Comment by rliman** [comment]
It means that you've provided translations, which are not configured in your account.
The rules are:
- You always have to provide translations, which are marked as mandatory in your account.
- You can't provide translations, which you haven't added to your account, e.g. if you configured only English, you can't create rate plan with Spanish description.

You can see configured language list in `GET https://api.apaleo.com/settings/v1/languages`

**Comment by limehome-dev** [comment]
curl -X PUT --header 'Content-Type: application/json-patch+json' --header 'Accept: application/json' --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5NTkyRDA5RTRERkQzNzVGNEIzRTFDNjNGN0QzQjU4NzU5REJFREYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJHVmt0Q2VUZjAzWDBzLUhHUDMwN1dIV2R2dDgifQ.eyJuYmYiOjE1NTcyMzM0OTUsImV4cCI6MTU1NzIzNzA5NSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5hcGFsZW8uY29tIiwiYXVkIjpbImh0dHBzOi8vaWRlbnRpdHkuYXBhbGVvLmNvbS9yZXNvdXJjZXMiLCJhcGkiXSwiY2xpZW50X2lkIjoic3dhZ2dlci11aSIsInN1YiI6IjQwOTM5NjcyLTk5OWEtNDcyNy1hMDVmLTQ2MjZjYmM3YmUzYiIsImF1dGhfdGltZSI6MTU1NzIwMzQyOCwiaWRwIjoibG9jYWwiLCJuYW1lIjoiYWNjb3VudHNAbGltZWhvbWUuZGUiLCJhY2NvdW50X2NvZGUiOiJDUEtVIiwicm9sZSI6IkFjY291bnRBZG1pbiIsInNjb3BlIjpbImFkbWluIl0sImFtciI6WyJwd2QiXX0.UqYvqK6KSP2NO9nX5tBh3oAJ-e39MG2v1L9U8b-itUYlYntC5E5mfeV__vWNqRpoTbCwKk6iZPWdtrstRRz5BA88rl11FBwQJdb2tngvUUxKX5JhEtYZZmMq-rsBrQti6G2kosecXgmHDdNzl2j7eBQkQmONSd28uylgN2avp0YAfX3VCxulHOkgvLl0Ucgx8WB272-lE77HQ3FLQC0qN-81nezdcnT39d219l5-6XbtbauD2LnDDBuzZR72Kl3aRbYOX1r_Fn1qWbwbSaMvoiH1gJv1rAIpUG5937goAyB7eZvJ1MjE6DPGKqyMTcev1SFRjOVOemb8_PJLMcLYOQ' -d '{ \ 
   "rates": [ \ 
     { \ 
       "from": "2019-05-07T17:00:00+02:00", \ 
       "to": "2019-06-08T11:00:00+02:00", \ 
       "price": { \ 
         "amount": 123.5, \ 
         "currency": "EUR" \ 
       }, \ 
       "restrictions": { \ 
         "minLengthOfStay": 1, \ 
         "maxLengthOfStay": 30, \ 
         "closed": false, \ 
         "closedOnArrival": true, \ 
         "closedOnDeparture": true \ 
       } \ 
     } \ 
   ] \ 
 }' 'https://api.apaleo.com/rateplan/v1/rate-plans/001-RATETEST/rates'
For above request I am getting the below message

{
  "messages": [
    "Some rates might be missing or the `from` and `to` for some of them do not match the expected date and time. Do not try to construct the rates, better first request the rates for a certain time range and just fill in the price and restrictions."
  ]
}



Response code : 422

**Comment by rliman** [comment]
It seems like you're trying to construct rate manually which you shouldn't do. Instead you have to call `GET https://api.apaleo-staging.com/rateplan/v1/rate-plans/{ratePlanId}/rates?from=<>&to=<>`

**Comment by limehome-dev** [comment]
I need to change the rate for rate-plan-id '001-RATETEST' for date from '2019-05-08' to 2019-05-15.
how can I do this

**Comment by rliman** [comment]
You cal that get request, as a response you get an array of `rate`s with configured `from` and `to`. Then you specify in those objects the `price` you want to set:

```
{
  "rates": [
    {
      "from": "2019-05-07T17:00:00+02:00",
      "to": "2019-05-08T11:00:00+02:00",
      "price": {
        "amount": 123.5,
        "currency": "EUR"
      },
      "restrictions": {
        "minLengthOfStay": 1,
        "maxLengthOfStay": 30,
        "closed": false,
        "closedOnArrival": true,
        "closedOnDeparture": true
      }
    }
  ]
}
```

If you have any other questions, please read [this guide](https://blog.apaleo.com/developer/rms-integration-guide)

**Comment by limehome-dev** [comment]
I have check but I am getting same response.

**Comment by rliman** [comment]
You are sending 1 rate when you should send 2

**Comment by limehome-dev** [comment]
could you give me sample example

**Comment by rliman** [comment]
Have you read [this guide](https://blog.apaleo.com/developer/rms-integration-guide)? It has all the information you need, I can't add anything on top of that. If you follow it step by step, you'll get what you want.

**Comment by limehome-dev** [comment]
Ok Thanks

**Comment by limehome-dev** [comment]
Now I can update the price. but for the below request I am not able to set the price

curl 'https://api.apaleo.com/rateplan/v1/rate-plans/001-RATETEST/rates' -X PUT -H 'origin: https://api.apaleo.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5NTkyRDA5RTRERkQzNzVGNEIzRTFDNjNGN0QzQjU4NzU5REJFREYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJHVmt0Q2VUZjAzWDBzLUhHUDMwN1dIV2R2dDgifQ.eyJuYmYiOjE1NTcyOTg4NzgsImV4cCI6MTU1NzMwMjQ3OCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5hcGFsZW8uY29tIiwiYXVkIjpbImh0dHBzOi8vaWRlbnRpdHkuYXBhbGVvLmNvbS9yZXNvdXJjZXMiLCJhcGkiXSwiY2xpZW50X2lkIjoic3dhZ2dlci11aSIsInN1YiI6IjQwOTM5NjcyLTk5OWEtNDcyNy1hMDVmLTQ2MjZjYmM3YmUzYiIsImF1dGhfdGltZSI6MTU1NzI4NzE3MywiaWRwIjoibG9jYWwiLCJuYW1lIjoiYWNjb3VudHNAbGltZWhvbWUuZGUiLCJhY2NvdW50X2NvZGUiOiJDUEtVIiwicm9sZSI6IkFjY291bnRBZG1pbiIsInNjb3BlIjpbImFkbWluIl0sImFtciI6WyJwd2QiXX0.ggiXlLmTmXvF7QgH7Wi1QL0KL0ptBWD_iLCj5WMwGHymA2rS259VFclGObD89SC3IG4a8PnuMw0J0RrVjGx9WGyCT1d_Lj2X8XyWubJSdTLf9FnbF2L5KAC1N5-t_jPeNGFwEproPFHV-jfQ_Aj8VmAWCnTGFZzWipbTIQVVGL3pRZHIdiLT5zXBkrlxJ99iOqnBkaXbaPBQfnecybZpyvqYeVgyaKFBGpjlgjaPKUGYr7mix7EFnJmqmQMasX0nO6yBZHyB19vSHo0cWLp49xxbuMeDtXks-HD8StHhAH_OoABOgK04_jd2DkgiZGMoi_BPRWoiI_Ch-Q8R2rq1Ig' -H 'content-type: application/json-patch+json' -H 'accept: */*' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'referer: https://api.apaleo.com/swagger/' -H 'authority: api.apaleo.com' --data-binary $'{\n  "rates": [\n    {\n      "from": "2019-10-26T14:00:00+02:00",\n      "to": "2019-10-27T11:00:00+02:00",\n      "price": {\n        "amount": 91.84,\n        "currency": "EUR"\n      },\n      "calculatedPrices": [      ]\n    }    \n  ],\n  "count": 1\n}' --compressed

I am getting the below error for above request
{"messages":["Some rates might be missing or the `from` and `to` for some of them do not match the expected date and time. Do not try to construct the rates, better first request the rates for a certain time range and just fill in the price and restrictions."]}

**Comment by limehome-dev** [comment]
Also one more thing I am not able push the price with time.
eg. I have to pass the date from and date to like
"from": "2019-10-26T14:00:00+02:00", "to": "2019-10-27T11:00:00+02:00"

Can I pass this without time?

**Comment by dario-hd** [comment]
You always have to use `GET /rateplan/v1/rate-plans/{id}/rates` first and use the response, modified based on your needs, as body for the `PUT /rateplan/v1/rate-plans/{id}/rates` request. Apparently, you are not doing that because this is the result of the GET request for your rate plan:

```
curl -X GET --header 'Accept: application/json' --header 'Authorization: XYZ' 'https://api.apaleo.com/rateplan/v1/rate-plans/001-RATETEST/rates?from=2019-10-26&to=2019-10-26&pageNumber=1&pageSize=100'
```

```
{
  "rates": [
    {
      "from": "2019-10-26T14:00:00+02:00",
      "to": "2019-10-27T11:00:00+01:00",
      "price": {
        "amount": 100,
        "currency": "EUR"
      },
      "calculatedPrices": [
        {
          "adults": 2,
          "price": {
            "amount": 200,
            "currency": "EUR"
          }
        },
        {
          "adults": 3,
          "price": {
            "amount": 220,
            "currency": "EUR"
          }
        },
        {
          "adults": 4,
          "price": {
            "amount": 250,
            "currency": "EUR"
          }
        }
      ]
    }
  ],
  "count": 1
}
```

Notice the different timezone in the `from` and `to`. On 2019-10-27 the time zone changes; that's why you shouldn't set it yourself and use the response from our API which considers such cases.

I hope this helps.
