### ISSUE TITLE
OAuth invalid_client when requesting for access token

### ISSUE THREAD

**Issue by lujenia** [apaleo/api#133]
## Question

Hi,

I am trying to set up the oAuth2 flow, but I am stuck at exchanging the authorization code for the access token. I am sending a POST request with all the neccessary info (client_id, client_secret, code, encoded redirect_uri) but always receive a Status 400 Bad Request with error "invalid_client". The api credentials were requested via https://apaleo.com/api-credentials. The Redirect URL works fine (I am receiving the authorization code) and redirect_uri matches exactly the redirect_uri of the /authorize call. What could be wrong here?

Thanks :)

**Comment by ozonni** [comment]
@lujenia i don't see much in our logs. Could you please also share the request you send?

**Comment by lujenia** [comment]
> @lujenia i don't see much in our logs. Could you please also share the request you send?

It's solved! I figured it out while copying the request for you. I put the data in the parameters and not in the body. I changed it and now it works :)

**Comment by lujenia** [comment]
I sent you an email with the client id
