### ISSUE TITLE
How to update invoice address?

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#135]
## Question

What is the correct endpoint to update the invoice address of a reservation or booking?

## Background

We want to update the invoice address before creating an invoice.

**Comment by dmitry-urenev** [comment]
Hello @c2ofh, 
the invoice address is taken from the folio,  and you need to use `PATCH /finance/v1/folios/{id}` endpoint to update `debitor` property of the `FolioModel`. 

Example payload:

````json
[
  {"op":"replace","path":"/debitor/address/addressLine1","value":"Lorem Ipsum"},
  {"op":"replace","path":"/debitor/name","value":"Mustermann"},
  {"op":"replace","path":"/debitor/firstName","value":"Max"}, 
  {"op":"replace","path":"/debitor/title","value":"Mr"}
] 
````

**Comment by c2ofh** [comment]
Hey @dmitry-urenev 

Is this not valid?

```
{"value": 
  {
  "address": { "addressLine1": "Bismarckstraße 41", 
               "postalCode": "73760", 
               "city": "Ostfildern", 
               "countryCode": "DE" }, 
  "company": { "name": "CODE2ORDER" }
 },
 "path": "debitor",
 "op": "replace"
}
```

**Comment by c2ofh** [comment]
Sees to be valid, but It's forbidden for me.
Which permission is missing? 
apaleo-tracking-id: "0HLMKF8HG9LOG:0000003E"

**Comment by dmitry-urenev** [comment]
@c2ofh according to swagger definition you need also `folios.manage` scope 
`https://api.apaleo.com/swagger/#!/Folio/FinanceFoliosByIdPatch`

**Comment by bennetone** [comment]
@c2ofh Should we add the scope `folios.manage` to your client?

**Comment by c2ofh** [comment]
@bennetone I wrote @andreastubbe a message, maybe she added the scope already :) I will test it in a few minutes.
