### ISSUE TITLE
inventory/v1/properties  403 Forbidden 

### ISSUE THREAD

**Issue by gatmanmihai** [apaleo/api#136]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)
0HLMOAG604ETJ:00000204

**Code**
GET /inventory/v1/properties?pageNumber=1&amp; pageSize=100 HTTP/1.1
Host: api.apaleo.com
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5NTkyRDA5RTRERkQzNzVGNEIzRTFDNjNGN0QzQjU4NzU5REJFREYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJHVmt0Q2VUZjAzWDBzLUhHUDMwN1dIV2R2dDgifQ.eyJuYmYiOjE1NTc5MDk5NjEsImV4cCI6MTU1NzkxMzU2MSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5hcGFsZW8uY29tIiwiYXVkIjpbImh0dHBzOi8vaWRlbnRpdHkuYXBhbGVvLmNvbS9yZXNvdXJjZXMiLCJhcGkiXSwiY2xpZW50X2lkIjoiNHN1aXRlc0Nvbm5lY3QiLCJzY29wZSI6WyJwcm9wZXJ0aWVzLnJlYWQiXX0.Q2XHHlqo8Op9z7Y11bc6CqgiuIftbT3JdhWGxpkHLC1dP_LSAOplwytnPWQ-4tE32PQiz0zc3Qtn3wIaXBBmfJwecR7j21bD3gpvvNu-PzzJQL2-lBYJvm1zE5YLnZu48h4AKC1sViuWZXRh3ik9e8StlIX_inChhcAuR1woOxgL0cpkYtXkpXVU6BtspVLhNgv2Gm23QEMOcINEygpzI8enKBn8GJDaIbxSkSV-QdQ60BBLC-dnJU1d45WNT4s2GQXzdGQ8HtX5VXaO7T031eHNA3qtnzbDrUxAT_6WYeESm9-Bi91jja-8AFkemO94oQqEhWcn4bYUzDwBQMU5ig
User-Agent: PostmanRuntime/7.11.0
Cache-Control: no-cache
Postman-Token: 59abb5d5-1baf-4e54-8c33-81205c0a5c2a,0d1ec7c5-8551-4728-b3a6-dc227bfcc613
Host: api.apaleo.com
accept-encoding: gzip, deflate
Connection: keep-alive
cache-control: no-cache

**Expected behavior:**
A success response.

**Actual behavior:**
403 Forbidden.

**Related Issues:**

**Comment by ozonni** [comment]
@gatmanmihai you have to use `OAuth 2.0 authorization flow`. Instead you issued token using `ClientCredentials` flow. Please check this guide for more information: https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0
