### ISSUE TITLE
Payment throught check-in/out app

### ISSUE THREAD

**Issue by eloihdez** [apaleo/api#14]
Imagine a customer pays and checks out via our mobile application.
Are these the exact steps to be performed in apaleo's api, or am I missing anything?

1- Folio action / close (i've seen balance must be 0, how do I set it to 0?)
2- Reservation action / check out

Thank you

**Comment by eloihdez** [comment]
>  had some charges not yet covered he should contact the front desk 

In case we process the payment, what call should we perform?

**Comment by aprooks** [comment]
https://api.apaleo.com/swagger/#!/FolioActions/FinanceFolio_actionsByFolioIdPaymentsPost this one
