### ISSUE TITLE
'noShowTime' and 'cancellationTime' Revenue Calculation

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#140]
## Question

Let's say a booking (https://api.apaleo.com/swagger/#!/Reservation/BookingReservationsByIdGet) has three 'timeSlices'.

Questions:
1) **Can 'noShowTime' be set for a 'timeSlice' different from day 1?**
2) **If 1) is yes, then assume 'noShowTime' is set to day 2. Does this mean the revenue will be distributed as follows:**

**- Day 1: Normally**
**- Day 2: No-show fee**
**- Day 3: 0 (no-show fee has already been applied)**

3) **The same question but for 'cancellationTime' and 'cancellationFee'.**

**Comment by bennetone** [comment]
Hey @YouJinTou,

let me answer your questions:

1) Depending on how the hotel operates the `noShowTime` can be any time after the arrival. Usually hotels have a night audit process and set reservations to no show at that point, so it will be during the first time slice aka night. Some hotels do the processing of no shows on the next morning, but still this is usually during the first night. So in most cases you are right, but sometimes they might do the no-show processing a little bit later that day, so you cannot rely on this fact.

2) In the case the `noShowTime` is for the second or a later time slice or even after the departure, there is no rule how the revenues are distributed. The hotel might decide to waive all fees to keep a recurring guest happy, who knows. What you see on the reservation (time slices and extra services) is the original value of the reservation. The actual revenues and the distribution to the business days you can only get from the folios. Consider that sometimes hotels might also forget to process a no-show immediately or first post the no-show fee and try to collect the money from the guest and 2 weeks later they agree with the guest to cancel the fee or discount it. apaleo only captures when the revenues are posted, but how to distribute them to the proper nights would be up to you to decide. Usually the sum of all no-show fees should go the first night.

3) A reservation can be cancelled anytime, before the stay (which might be the most common case), but also during the stay or even after the stay. Regarding the cancellation fee all from above also applies here. To get the actual revenues and not the original value of the reservation you have to look into the folios. The only difference is that cancellation fees are distributed proportionally to all the originally booked nights of the reservation. Also this is up to you to decide how to treat it best in the case of revenue management.

I hope I could clear the skies a little bit for you. Feel free to come back with more questions if you are still unsure.

Cheers!

PS:. When reading the revenues from the folio you need to filter all the revenues that have been moved into this reservation in case on guest pays for multiple rooms. For revenue management it is not relevant you actually paid for the revenues, right?!
