### ISSUE TITLE
assign room blank

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#141]
`Apaleo-Tracking-Id`: 0HLMVGQBTOPJK:000000A4

url: https://api.apaleo.com/booking/v1/reservation-actions/FNAEIHHN-1/assign-unit
The response is blank, but there are over 40 free rooms.

**Expected behavior:**

A response

**Actual behavior:**

Response is blank

**Comment by dario-hd** [comment]
Hi @c2ofh, thanks for reporting this! I checked the logs and this happened because the reservation is already in the past and you cannot assign a unit to such reservation. I hope this helps, we will fix this anyway.

**Comment by c2ofh** [comment]
hey @dario-hd thank you for your response. you're right. the rate plan was until 17:00 so I was too late.
