### ISSUE TITLE
Consistent API output's for translations

### ISSUE THREAD

**Issue by koskiOvaa** [apaleo/api#142]
## I want

GET /booking/v1/reservations return payload's "unit" part to be similar to GET /inventory/v1/units/{id} return payload when it comes to description.

Currently GET /booking/v1/reservations's and /booking/v1/reservations/{id}'s output has

`
...
"unit": {
 "id": "MUC-MTA",
 "name": "A.101",
 "description": "Standard room."
}
...
`

GET /inventory/v1/units/{id}'s output has

`
{
  "id": "MUC-YTO",
  "name": "1.001",
  "description": {
    "en": "First Floor Room 1",
    "de": "1.OG Zimmer 1"
 },
 ...
}
`

## Use cases

I don't need to remember and to request to ask scope units.read. 

I would not need to read the unit's possible translations from a unit's endpoint for each reservation.

## Examples

Would be cool to have this for GET /booking/v1/reservations's and /booking/v1/reservations/{id}'s output:

`
...
"unit": {
 "id": "MUC-MTA",
 "name": "A.101",
 "description": {
    "en": "First Floor Room 1",
    "de": "1.OG Zimmer 1"
 },
}
...
`

**Comment by bennetone** [comment]
Hey @koskiOvaa 

thanks for your question. When you request a reservation we assume you already know in which language you want to receive the content. To receive the name and description for sub resources in the language of choice you can use the standard `Accept-Language` header. See the following example, where you will receive all translatable content in Finish:

```
curl -X GET \
  https://api.apaleo.com/booking/v1/reservations/HNGEQFPN-1 \
  -H 'Accept-Language: fi' \
  -H 'Authorization: Bearer <your token>' \
  -H 'accept-encoding: gzip, deflate'
```

Does this help for your use case?

Cheers!

**Comment by bennetone** [comment]
One thing to add here. If you request content in a language that is not configured for the account you are connected to the API will deliver the content in the default language of the account, which usually is in English.

**Comment by koskiOvaa** [comment]
Ah! Excellent. I did not even think of trying Accept-Language. 

Awesome. Will work perfectly.
