### ISSUE TITLE
Guests with id

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#144]
## Question

Why does guests don't have a unique id?

## Background

It would be easier to update guest data, if there is a unique identifier.
Especially for group bookings the array index could not be fail-safe.

**Comment by dmitry-urenev** [comment]
Hi @c2ofh,  because we don't support Guest Profiles yet. 
Why do you update guest data in the group booking using the array index? You know all reservation ids in the group booking, right?, so the easiest way to do it - to use the PATCH request for a certain reservation:

```
PATCH /booking/v1/reservations/{id}
[{"op":"replace","path":"/primaryGuest", "value":{ ... }]
```

**Comment by c2ofh** [comment]
@dmitry-urenev 
Yes, I'm working with the array index, but I asked only to get the information, why it's not supported. ;)
