### ISSUE TITLE
Minimum and maximum length of stay

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#145]
## Question

Do restrictions on a rate stop bookings from going through if a rate with a restriction is going through?

**Comment by bennetone** [comment]
Hey @oluyoung,

sorry for the late response. The MinLOS and MaxLOS restrictions in apaleo are arrival based, so a MinLOS of 3 on June 14th will require guests to stay 3 nights when they are arriving on June 14th, but no if they are arriving on June 13th and staying through June 14th.
