### ISSUE TITLE
Ability to return user to a specified tab, after finishing the interaction in the 3rd party iframe

### ISSUE THREAD

**Issue by pboettner** [apaleo/api#146]
## Use cases
When a user goes to a 3rd party tab, once (s)he completes her interaction on it, the user needs to manually return to the previous tab, respectively the main work tab for the user role. It would make for a more fluid integration if this could be programmatically combined into the completion of the interaction in the 3rd party tab.

 Extra clicks, make the system appear somewhat clunky.
-->

## What I do

 Profiler/upsell system

**Comment by pgrm** [comment]
hello @pboettner thx for your feedback. We are thinking about adding the ability for apaleo One integrations to also control the navigation of the main apaleo UI, we just don't have a polished concept for it yet. But I'll keep this feedback in mind and let you know, once we'll have a preview API for it available.

**Comment by pgrm** [comment]
@pboettner we've finished the feature and updated the documentation about it, check out https://dev.apaleo.com/guides/start/apaleo-one/client-details#navigation - please let me know in case something doesn't work or is unclear in the documentation

Cheers, Peter
