### ISSUE TITLE
Test hotels and rservations

### ISSUE THREAD

**Issue by softground** [apaleo/api#148]
## Question

Can you please populate our test account with some hotels and reservations? Our test account user is stefan@rosedalelivery.com.

## Background

We are trying to implement a transportation service module in a tab on the reservation details level. It's about Chauffeur Express, you can find more about us here: https://chauffeur.express

**Comment by pgrm** [comment]
hello @softground could you share with me your account code maybe?

I'll create your test data first thing tomorrow morning, cheers!

**Comment by softground** [comment]
Hello,

Account code is: PYHQ

Thank you!

**Comment by pgrm** [comment]
hello @softground your account contains now our 3 test properties with configured rate plans and ~200 reservations in total. Good luck :smile_cat:
