### ISSUE TITLE
UI Integration

### ISSUE THREAD

**Issue by softground** [apaleo/api#149]
## Question

We are trying to implement an UI Integration on the ReservationDetailsTab, we are folowing this guide https://blog.apaleo.com/developer/ui-integration-guide
We have this UI Integration set:
{
  "uiIntegrations": [
    {
      "label": "Chauffeur Express",
      "iconSource": "https://chauffeur.express/images/chauffeur.express.png",
      "sourceUrl": "https://apaleo.chauffeur.express/authorized/index.php",
      "sourceType": "Private",
      "target": "ReservationDetailsTab"
    }
  ],
  "count": 1
}

Headers:

{
  "apaleo-tracking-id": "0HLN97655I1FP:00000002",
  "content-encoding": "gzip",
  "content-type": "application/json; charset=utf-8",
  "date": "Thu, 06 Jun 2019 12:16:22 GMT",
  "server": "nginx",
  "x-firefox-spdy": "h2"
}

When I oper a reservation in the apaleo account, the url (https://apaleo.chauffeur.express/authorized/index.php) is called with no parameters. I made it to always return the same result:

{"url":"https:\/\/myaccount.chauffeur.express","expTimestamp":1559909931}

So from what I understood in the reservation page I should have a new tab called "Chauffeur Express" with the content returned by https:\\myaccount.chauffeur.express

But there is no new tab on the reservation tab....

What am I doing wrong?
Apaleo account ID is PYHQ

<img width="1385" alt="Screen Shot 2019-06-06 at 15 47 02" src="https://user-images.githubusercontent.com/7448054/59033836-5b3ec380-8872-11e9-9055-df8303c59f70.png">
<img width="1423" alt="Screen Shot 2019-06-06 at 15 46 46" src="https://user-images.githubusercontent.com/7448054/59033837-5b3ec380-8872-11e9-8f43-11aa2e38a782.png">

## Background

We are trying to implement a transportation service module in a tab on the reservation details level. It's about Chauffeur Express, you can find more about us here: https://chauffeur.express

**Comment by pgrm** [comment]
@softground the expTimestamp needs to be a string in the format ISO 8601 such as `"2019-06-06T12:55:38Z"`

**Comment by softground** [comment]
Got it, it's working now, we will have to design it in a way to fit in the
iframe. I see that the final url is called with the reservationID
parameter, so using that id we should be able to pre-populate most of the
fields in our forms with the information from the reservation details.
What I don't understand is how this will be added to a real apaleo user...
because now I added it from here https://integration.apaleo.com/swagger/,
being logged in with the test apaleo account.

**Comment by pgrm** [comment]
The intended way would be to add it automatically during the connect flow. So whenever the users connects apaleo to Chauffeur Express, they immediately get the tab. But of course you can also trigger the integration from your UI
