### ISSUE TITLE
Distribution API questions

### ISSUE THREAD

**Issue by jimmyvallecillos** [apaleo/api#15]
## Question

•	What should we return if an ARI request turns to an error ?
•	What does RatePlanListModel's Count property stand for ?
•	It is wrote in your [Channel Integration Guide](https://apaleo.com/channel-integration-guide/) that the propertyId is only unique within one apaleo account, so when we push reservations how do you know which property is concerned since we do not transmit the accountId within this message ?

**Comment by swiesener** [comment]
- What do you mean by "ARI request"? Do you mean an ARI push from apaleo to your endpoint? In that case you might return 2xx all the time.
- The Count stands for the number of items in the returned RatePlanList.
- API credentials are valid for accessing one specific account (hotel chain) at a time - so transmitting just the property ID will clearly identify the property
