### ISSUE TITLE
How to Subscribe to Topics Webhook?

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#150]
## Question

It's in the title

## Background

I tried creating a subscription at [POST] https://webhook.apaleo.com/v1/subscriptions using an 'Authentication Bearer ...' header. The access token was valid (I had just generated it).
Here's what I got:
headers:{'Date': 'Mon, 10 Jun 2019 13:08:40 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'nginx', 'WWW-Authenticate': 'Bearer error="invalid_token", error_description="The audience is invalid"', 'Apaleo-Tracking-Id': '0HLNAQ9753A5C:00000001'}

**Comment by DsAekb** [comment]
Hi @YouJinTou,

This happens because you don't have the scope to create webhook subscriptions. Do you want us to add it?

**Comment by YouJinTou** [comment]
Yes, please.

**Comment by DsAekb** [comment]
Hi @YouJinTou ,

We added necessary scopes, could you confirm if it works now?

**Comment by YouJinTou** [comment]
Confirmed.
