### ISSUE TITLE
Creating an ARI Subscription

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#151]
## Question

What information is invalid?

## Background

I tried to create an ARI subscription at [POST] https://distribution.apaleo.com/v1/subscriptions with the following:

`{
  "propertyId": "PACEDEMO",
  "channelCode": "ChannelManager",
  "endpointUrl": "https://ec2-3-14-150-195.us-east-2.compute.amazonaws.com:5000/ari/apaleo/incoming",
  "fullSyncPeriod": "PT60M",
  "deltaSyncPeriod": "PT5M",
  "ratePlanIds": [
    "PACEDEMO-RP1"
  ],
  "numberOfDays": 365,
  "enabled": true
}`

I received a 422 ['Provided value is invalid'] response. I had set the 'Authorization Bearer ...' header with a valid access token.

**Comment by DsAekb** [comment]
Hi @YouJinTou 

The message is indeed not helpful at all. We will fix that in the nearest future.
However, it seems that `channelCode` value couldn't be parsed correctly. Please make sure that it has the correct value and try again.

**Comment by YouJinTou** [comment]
@DsAekb I've tried both 'ChannelManager' and 'BookingCom' (as per the examples in your Swagger spec). None of them work.

**Comment by DsAekb** [comment]
@YouJinTou thank you for your response. We are investigating and will get back to you soon.

**Comment by DsAekb** [comment]
@YouJinTou I think I could find the reason for your issue. You get the message like that because the whole body you send is invalid. That is because you didn't provide content type. Please add the following header to your request: `Content-Type: application/json`.

**Comment by YouJinTou** [comment]
I added the `Content-Type: application/json` header. Still no luck.

**Comment by YouJinTou** [comment]
This worked, thank you!
