### ISSUE TITLE
Trying to Refresh Access Token

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#152]
## Question

Why can't I refresh the access token for PACEDEMO? It worked just fine yesterday.

## Background

I keep getting 400 'invalid_request' when trying to refresh my access token. Here's the payload:

{"client_id": "[CLIENT_ID]", "client_secret": "[CLIENT_SECRET]", "grant_type": "refresh_token", "refresh_token": "[REFRESH_TOKEN]"}

I'm attaching the 'Content-Type: application/json' header. I tried with 'application/x-www-form-urlencoded' as well.

**Comment by DsAekb** [comment]
Hi @YouJinTou ,

We added new scopes to your client. Do you probably try to get access token with an old refresh token? To request new scopes you should request a new refresh token first. Maybe [this](https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0) will also be helpful.

**Comment by YouJinTou** [comment]
That was the problem. Thank you!
