### ISSUE TITLE
New scope request

### ISSUE THREAD

**Issue by softground** [apaleo/api#155]
## Question

Hello,

I think we need access for the 'properties.read' scope on our client id. When I try to connect with the 'properties.read' scope it returns error:  unauthorized_client
We need it to get the property details, name, address etc.
Our client id is ChauffeurExpressConnect.

Thank you!

## Background

We are trying to implement a transportation service module in a tab on the reservation details level. It's about Chauffeur Express, you can find more about us here: https://chauffeur.express

**Comment by randyrod** [comment]
Hi @softground,

We have added the required scope. Please test.

Regards
