### ISSUE TITLE
Not Receiving Webhook/Notification Pushes

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#156]
## Question

How do we start receiving ARI/bookings pushes from you?

## Background
The endpoints below have whitelisted 34.240.36.71. I've tried creating/modifying reservations as well as rate plans. The endpoints do not even get hit.

__ARI__
ARI subscription ID: P0KNOZL7
ARI endpoint: https://ec2-3-14-150-195.us-east-2.compute.amazonaws.com/ari/apaleo/incoming

__BOOKINGS__
Bookings subscription ID (webhook): 91c0f9cc-1234-4170-9928-333fcffd3dfc
Bookings endpoint: https://ec2-3-14-150-195.us-east-2.compute.amazonaws.com/bookings/apaleo

**Comment by randyrod** [comment]
Hi @YouJinTou,

From our logs I can see that our health checks from webhook for the subscription (91c0f9cc-1234-4170-9928-333fcffd3dfc) are getting timeout.

```Failed to deliver health check to https://ec2-3-14-150-195.us-east-2.compute.amazonaws.com/bookings/apaleo (91c0f9cc-1234-4170-9928-333fcffd3dfc)```

If I personally navigate to the url `https://ec2-3-14-150-195.us-east-2.compute.amazonaws.com/bookings/apaleo` I get a `405 status code`, can you check if there could be any routing issues causing that?

If you have further questions let us know.
