### ISSUE TITLE
Using channel codes when retrieving services

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#157]
## Question

How is the parameter `channelCodes` used to filter the results when retrieving services?

## Background

In our test account we have a service that is only associated to two channels ("Direct" and "Ibe"). However, this service is included in the returned services when using the following URLs:

`https://api.apaleo.com/rateplan/v1/services?propertyId=BER&channelCodes=BookingCom`
`https://api.apaleo.com/rateplan/v1/services?propertyId=BER&channelCodes="BookingCom"`
`https://api.apaleo.com/rateplan/v1/services?propertyId=BER&channelCodes=["BookingCom"]`

I guess there's something wrong in the way we're using the parameter?

**Comment by msmeza** [comment]
Interestingly, Swagger-UI seems to return the correct services, but calling the URL seen there through curl returns the service that is not associated with "BookingCom". Perhaps this is an issue with the scopes of the user used to authenticate the curl requests?

**Comment by msmeza** [comment]
Never mind. It turns out there was an issue in the way I was calling curl on my machine. :disappointed:

**Comment by bennetone** [comment]
Okay, good to hear you were able to resolve the problem!
