### ISSUE TITLE
ARI Notification Push Endpoint Structure

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#158]
## Question

What should the endpoint for an ARI push notification look like?

## Background

Currently, I have it as '/apaleo/incoming?token=<token>'. Should it be something else? I'm talking about the token that you send along specifically.

**Comment by bennetone** [comment]
Dear @YouJinTou 

When you register a subscription for ARI data you should specify a token that allows you to verify it is an authorized request. Most subscriber register a UID as a token, but it is up to you.

**Comment by YouJinTou** [comment]
Do I register that token in the 'endpointUrl' parameter I send to you or somewhere else?

**Comment by ozonni** [comment]
@YouJinTou there is no dedicated way to provide the token for your ARI notification endpoint. It has to be inside the `endpointUrl`. We just take the url you configured as `endpointUrl` and send `POST` request with a json payload.

**Comment by YouJinTou** [comment]
Thanks.
