### ISSUE TITLE
0px height for the 3rd party iframe on small width

### ISSUE THREAD

**Issue by dbajet** [apaleo/api#159]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)

**Code**  In the Account and for any property Dashboard, when the size of the window changes, the responsive CSS modifies the size and placements of the menus, cards... this is great.
Unfortunately when the width goes under 570px, the 3rd party iFrame loses its `min-height` of 350px and its content becomes invisible.

**Expected behavior:** Keeping the some `min-height` for the 3rd party iframe

**Actual behavior:** The 3rd party iframe has a height of 0px.

**Related Issues:** 

![image](https://user-images.githubusercontent.com/5107006/59564981-3381f500-9002-11e9-9500-74c8540c4ae8.png)

**Comment by andreastubbe** [comment]
Thanks for reporting, @dbajet ! We'll look into it.

**Comment by andreastubbe** [comment]
Fixed! Thanks again.
