### ISSUE TITLE
Cancel booking endpoint

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#16]
## Question

Is there a endpoint to cancel a `booking`? (not just cancelling each reservation)

I thought i saw this was a possibility before but cannot see it now?

**Comment by bennetone** [comment]
Hi @lukeclifton 
There is no such API call available to cancel a whole booking. You need to cancel the reservation one by one.

**Comment by lukeclifton** [comment]
@bennetone ok thanks
