### ISSUE TITLE
Availability Call

### ISSUE THREAD

**Issue by workmatrix** [apaleo/api#160]
## Question

Looking for an availability Call ... I am using "/booking/v1/available-unit-groups" but I do not get pricing information ... just room availability. How do i get prices for the specific rooms/days returned.

**Comment by andreastubbe** [comment]
Two ways to do this, depending on your use case:

### 1. Static prices using the rates APIs:
- get all rate plans with `/rateplan/v1/rate-plans`
- use the rate plan ID to get rates with `/rateplan/v1/rate-plans/{id}/rates`

Note that rates can be subject to restrictions, so the price which is returned is not necessarily available. For example, discounted rates when you stay longer than 7 days and arrive on a Thursday.
This makes sense for some sort of rate calendar.

### 2. Prices for a specific reservation request
- request offers with `/booking/v1/offers`. Pass all the info that a user would enter when making a booking: arrival, departure, persons, ...

This is taking all restrictions and room availabilities into account, and returns all rooms with prices for the specified parameters.

**Comment by andreastubbe** [comment]
Or, like #161

**Comment by workmatrix** [comment]
ok... thanks. I believe for the availability call its best to use /booking/v1/offers ... assuming that "offers" is room related (I was not looking at this one- since I expected "additional offers/services)... but looking at the response it looks like this is the "availability" call
