### ISSUE TITLE
Receiving Pushes for Deleted Webhook (Bookings) Subscriptions

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#162]
## Question

Why am I receiving notifications for subscriptions I've made in the past and subsequently deleted?

## Background

Here's the ONLY bookings subscription I currently have: 43c25fe5-9a5d-459a-87d8-11257a3366e3
But I keep receiving pushes for two others as well (I don't know the ID's, but the endpoints contain these UUIDs): 
dab69cd5-3fc0-4136-b6e1-eb7e28e6e347
455c2887-5d7c-4165-b4df-7f5e03f3c045

**Comment by pgrm** [comment]
Hello @YouJinTou those are webhook messages, which were already in the state to be delivered and couldn't be successfully delivered. At the moment we retry for 24h. Deleting the subscription unfortunately has only an effect on new webhook messages, but not existing ones. In the afternoon you should stop receiving those messages.

We are working on improving webhook delivery and will take this into consideration.
