### ISSUE TITLE
New scope request

### ISSUE THREAD

**Issue by softground** [apaleo/api#163]
## Question

Hello,

we need "offline_access", to use the refresh tokens.

Thank you!

## Background

We are trying to implement a transportation service module in a tab on the reservation details level. It's about Chauffeur Express, you can find more about us here: https://chauffeur.express

**Comment by dario-hd** [comment]
What's your client id?

**Comment by softground** [comment]
Our client id is: ChauffeurExpressConnect
Also I think we need these scopes, for the UI integration: 
Scopes required: 'integration:ui-integrations.admin, integration:ui-integrations.manage'.

But I'm not sure about that... to push our new tab to the reservation details, do we need to use the Bearer Token to call "/integration/v1/ui-integrations/{target}"?

Thank you!

**Comment by dario-hd** [comment]
I checked your client and you are allowed to request offline access. Yes, you need to authenticate to call such endpoint. And, you already have the `integration:ui-integrations.manage` scope.

**Comment by softground** [comment]
Got it, thanks!

**Comment by dario-hd** [comment]
👍
