### ISSUE TITLE
Notification of invoice creation event - webhooks 

### ISSUE THREAD

**Issue by ruitguerra** [apaleo/api#164]
## I want
The addition of an event type "Invoice created" in the notification API 

## Use cases

What do you want to use this for?
To send an invoice to the guest automatically when the guest checks out and the invoice is  created 
When the invoice is created in Apaleo, a third party app is notified of this event (provided it has subscribed to it  :-), and can GET the invoice (ex PDF) via the apaleo api in order to send it to the guest via email  or other type of message. 
NOTE: When an invoice is created it cannot be modified (legal rule in European countries). Therefore this should be a once only event. 

What shortcomings exist with current approaches?
Currently if we wanted to automate sending an invoice to the guest, we have unsatisfactory options.

For example we have to rely on other event notifications like "check-out", but if the invoice is not created at that moment, then it cannot be sent to the guest. Kepping track of this is cumbersome and would force the implementation of a retry system. 

OR we would need to poll the Apaleo API th check for the availability of the invoice, which increases resource usage and is not appropriate for "on the fly / near real time" processing. 

## Examples
Examples of benefits: 
-Automate the sending of digital invoices to guests to cut on time at the reception desk 
-Use the invoice message to prolong the guest experience and facilitate paperless expenses management 
-Propose personalized loyalty benefits in the message sending the invoice 
-Improve the guest optin rate
-Improve the registration of guest emails and telephone numbers

## What I do

The HotelAppz Guest management platform, which brings personalized automations to guest journey messaging, marketing and loyalty. And making it do cool things using Apaleo's great API :-)

**Comment by dario-hd** [comment]
Hi @ruitguerra, sounds reasonable. We are planning to publish such event in the near future.

**Comment by andreastubbe** [comment]
Hi @ruitguerra , we added it. Find the updated documentation here: https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo
