### ISSUE TITLE
Market/Source codes for reservations

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#166]
Does Apaleo have the ability to assign market or source codes for a reservation? Create/edit such codes? Display property performance per such code?

I only see reservation's "Channel Code" which looks like source code.

**Comment by andreastubbe** [comment]
Hi @Denitz , we do not have market codes.
For the source of a reservation, we do have the following:
- ChannelCode, one of ['Direct', 'BookingCom', 'Ibe', 'ChannelManager']
- Source, which is set by the ChannelManager, and has detailed information about the actual channel (like Expedia, TripAdvisor, etc.)

You can filter the property performance report by ChannelCode, but not by source.
