### ISSUE TITLE
Cancellation Fee for 'Free cancellation until check-in' Policy

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#168]
## Question

When I get reservation VREWKRUR-1 from the API, why is the ['cancellationFee']['fee']['amount'] not 0 but instead the full amount of the reservation (even though the cancellation policy is 'Free cancellation until check-in')?

**Comment by mri-apaleo** [comment]
The amount indicates the pre-calculated cancellation fee based on the property settings. It has nothing to do with the underlying policy and will not be posted automatically upon cancellation in such a case.

**Comment by bennetone** [comment]
And if you check the due date it should be set to the check-in time.
