### ISSUE TITLE
Rate Plan Create/Update not Triggering Notifications

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#171]
## Question

Why do we not receive notifications when we create/update a rate plan?

## Background

ARI subscription ID: 0QDEG2LO

**Comment by pgrm** [comment]
@YouJinTou do you mean ARI or webhook notifications?

**Comment by YouJinTou** [comment]
@pgrm ARI notifications.

**Comment by ozonni** [comment]
@YouJinTou as i can see, today at 2019-06-24 12:06:25.6223 we sent you prices update for one of the rate plans and you successfully acknowledged it. Could you please provide more information about the missing updates? What was updated, when and so on.

**Comment by YouJinTou** [comment]
Okay, turns out we were receiving them with some delay. Apologies.
