### ISSUE TITLE
How do we pass our own ID ref when creating a booking?

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#172]
## Question

How do we pass our own ID ref when creating a booking?

## Background

We have a `bookingRequestId` that we would like to associate with each newly created booking.

**Comment by swiesener** [comment]
If you mean an external reservation ID, you can use the endpoint post /booking/v1/bookings and use the field externalCode in the CreateReservationModel.

**Comment by lukeclifton** [comment]
Perfect. Thanks @swiesener.
