### ISSUE TITLE
reservations : externalCode

### ISSUE THREAD

**Issue by marc-air-agents** [apaleo/api#173]
## Question

I'm trying to Get the externalCode from GET /booking/v1/bookings. According to the documentation it should be in the reservations object. But when I GET filtered by 
reservation ID the returned object does not contain a reservations object. Is there any way to get the externalCode (ie. if the booking came from AirBnb then can I get the AirBnb booking reference?)

## Background

Trying to build a report of bookings - created, arrival, guest name .... and external booking reference

**Comment by swiesener** [comment]
It should work the way you assume. Maybe a booking with your reservation ID doesn't exist?

**Comment by marc-air-agents** [comment]
Hi Stephan,

Thanks for this.
After further investigation I am a step closer to where I am trying to get to - but still missing 1 vital piece of data from the API.
I have a reservation - id = ABCDEFGH-1
I can get data from the API either by 
https://api.apaleo.com/booking/v1/bookings?reservationId=ABCDEFGH-1

or

https://api.apaleo.com/booking/v1/bookings/ABCDEFGH


Either way the data returned from the API does not contain the Source or the ExternalCode. These are the 2 items that I need.
I can see that they exist when I log on to the Apaleo site and view reservation ABCDEFGH, but I am unable to retrieve these items via the API.

Is there any way that I can achieve this?

Many Thanks,
Marc

**Comment by pgrm** [comment]
hello @marc-air-agents - it seems to me like you try to get a reservation, but you keep retrieving the booking

Check https://api.apaleo.com/swagger/ to find other APIs calling get `https://api.apaleo.com/booking/v1/reservations/ABCDEFGH-1` should bring you closer

**Comment by marc-air-agents** [comment]
Yes - got it now.
Many thanks
