### ISSUE TITLE
OAuth: how to identify account?

### ISSUE THREAD

**Issue by srserx** [apaleo/api#174]
## Question

When login through Apaleo's OAuth, how can identify which account does the received token belong to? In other words: where can I find the unique ID of an account, when login with OAuth?

Could it be the "id_token" field in the token response?:

`{
  "id_token": "eyJhbGc...BkM2RkZ",
  "access_token": "eyJhbGc...91bnRBZ",
  "expires_in": 3600,
  "token_type": "Bearer",
  "refresh_token": "07fabbd...f7b74bc"
}`

## Background

When login with OAuth, I would like to know whether this account already exists in my system or not, and for this I need a unique identifier.

**Comment by pgrm** [comment]
Hello @srserx 

it's a claim called `account_code` and it's part of the token. You have 2 tokens there. You can analyze them using https://jwt.io/

Although they write

> [...] We do not record tokens, all validation and debugging is done on the client side.

it's probably best to be cautions and not post production tokens of real customers there, but you can always use those from your test account to see which data is stored in there to better understand how you can use them with your OAuth library

**Comment by srserx** [comment]
Thanks @pgrm ! I will take a look but looks like that's what I needed.
