### ISSUE TITLE
UI integration - PropertyDashboardCard target not found

### ISSUE THREAD

**Issue by srserx** [apaleo/api#176]
## Question

I'm trying to create an integration using https://integration.apaleo.com/integration/v1/ui-integrations/PropertyDashboardCard

The target PropertyDashboardCard is documented in your integration guide https://blog.apaleo.com/developer/ui-integration-guide

But the response I get from your side is `{
    "messages": [
        "target: The value 'PropertyDashboardCard' is not valid."
    ]
}`

Is your documentation outdated? Or am I missing something?

**Comment by randyrod** [comment]
Hi @srserx,

Thanks for reaching out. You are correct that target does not exists, there is a typo on the guide, thanks for pointing it out we will fix it asap.

The target that you are looking for is  `DashboardPropertyContext`

Sorry for the inconvenience.
