### ISSUE TITLE
Need ability to pass net-amounts in booking-post (field timeslices)

### ISSUE THREAD

**Issue by detcoGbR** [apaleo/api#177]
## I want

We try to connect an external channel to apaleo, however we only get the ```amountBeforeTax``` for each day, and the total ```amountAfterTax``` and ```Taxes``` only for the whole reservation.

With this info, I am not able to completely fill the request for POST /v1/booking (distribution-api) / POST /booking/v1/bookings (core-api), since the field reservations[x].timeslices[y].totalAmount.amount should be the gross-amount.

## Possible Fix

A possible fix could be either supporting a boolean-flag ```taxInclusive``` (default ```true```) in ```TimeSliceModel``` or ```AmountModel```, or a field ```totalAmountBeforeTax``` in ```TimeSliceModel``` (as alternative to ```totalAmount```)

**Comment by swiesener** [comment]
The ARI push (or delta push) is delivering gross amounts to your endpoints. Have a look at https://blog.apaleo.com/developer/channel-integration-guide. That's what you need to create bookings/reservations.

**Comment by ozonni** [comment]
@detcoGbR this is from Expedia documentation. As you can see it depends on the hotel setup. For now apaleo api only supports gross prices, therefore you need to make sure that the hotel has rates with taxes included configured on Expedia.

![image](https://user-images.githubusercontent.com/25206121/60870944-18d22300-a232-11e9-89ea-67dd50fb9100.png)

**Comment by detcoGbR** [comment]
Ok, I mainly read the schema/attribute-names (amountBeforeTax).
The description in the docs can be read as they would pass a gross-amount in the "amountBeforeTax"-attribute, which sounds weird.
Or they can (optionally) instead pass an amountAfterTax-attribute, that is not mentioned in the schema/docs. (The OTA-Schema expedia is building on has both attributes, but expedia stripped that out)
I probably have to check with expedia, how that really works.

**Comment by ozonni** [comment]
@detcoGbR i think you need to check it with Expedia, since it is their API
