### ISSUE TITLE
Where can I get the public key to verify a JWT access token?

### ISSUE THREAD

**Issue by thomasjosefreiter** [apaleo/api#178]
## Question

I am at a loss: Where do I get a hold of the public key to verify the authenticty of the token I have received...?

## Background

I am implementing the OAuth flow and I have successfully received a JWT access token. I can decode it an the details (header, payload, claims, etc.) look fine.
The token header states "alg": "RS256", so I assume it was signed asymmetrically.
So, I would like to verify the signature of the access token that I have received...

**Comment by pgrm** [comment]
Hello @thomasjosefreiter - did you already check https://identity.apaleo.com/.well-known/openid-configuration ? - maybe we're missing a link to it. Anyhow, when you open it, you should see a JSON document with links to everything you desire. Including to the JWKS endpoint - https://identity.apaleo.com/.well-known/openid-configuration/jwks which should contain the keys.

Hope this helps

**Comment by thomasjosefreiter** [comment]
Nope, I have not seen that before. But this is exaclty what was looking for! ;-)
Perfect, thanks!
