### ISSUE TITLE
Connection for channel manager

### ISSUE THREAD

**Issue by BobPurple** [apaleo/api#179]
## Question

Hi, 
I'm working to integrate our channel manager RoomCloud with Apaleo. I need to start getting connection, but I suppose I don't need Oauth authentication just because is UI based. Instead I'm thinking of using this call: 
curl -X POST -d "grant_type=client_credentials" -H "content-type: application/x-www-form-urlencoded" -H "Authorization: Basic <your encoded credentials>" https://identity.apaleo.com/connect/token

Is it correct?

## Background

Java developer

**Comment by ozonni** [comment]
@BobPurple regardless of type of your application, you need to implement apaleo connect (Oauth). Especially for channel manager app, because you need to have offline access to make API calls (e.g. create reservation, cancel reservation).

There are couple of guidelines that will help you during the integration:

https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0
https://blog.apaleo.com/developer/channel-integration-guide

**Comment by BobPurple** [comment]
We tried connecting via Oauth with this call:
https://identity.apaleo.com/connect/authorize?
    response_type=code&
    scope=YOUR_SCOPE&
    client_id=YOUR_CLIENT_ID&
    redirect_uri=https://your_app/callback&
    state=YOUR_RANDOM_VALUE

but we received an html login form as a reply, so we received a graphic response instead of a json/xml response.

Where do we find in the documentation how to proceed at this point?

**Comment by andreastubbe** [comment]
Hi @BobPurple, this is good, that's exactly how it should be! This is a link to a HTML page, meant for people and not code.

It's all explained in the connect guide @ozonni sent you, but let me walk you through the flow. The whole OAuth thing can be a bit confusing when doing it the first time - sure was for me.

The most important thing to keep in mind is that the connect flow and the actual integration are different - the connect flow is something that every hotel goes through exactly once, and it's doing nothing else but giving you the access rights to this hotel's account in apaleo.

## This is how:
The hotel logs in to their apaleo account, and then goes on that page which can be reached through this link you posted. This is all done by the hotel, all in the browser.
```
https://identity.apaleo.com/connect/authorize?
response_type=code&
scope=YOUR_SCOPE&
client_id=YOUR_CLIENT_ID&
redirect_uri=https://your_app/callback&
state=YOUR_RANDOM_VALUE
```

Here, they click on "connect", and then our infrastructure will call your `redirect URL` with all the information you need to proceed. While you develop, you can take on the role of the hotel, with your own apaleo test account.

This is basically where your development work starts, on the redirect URL. The guide lists all the details, like the response you get and what to do with it, so I won't repeat them here.

I hope this helps getting you started,
Andrea
