### ISSUE TITLE
Add / remove services to a existing reservation 

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#18]
## Question

Does the api currently provide ability to add / remove services to a existing booking which has a `Confirmed` status?

**Comment by bennetone** [comment]
Hey @lukeclifton 

There is the POST /booking/v1/reservations/{id}/amend call, which is already deprecated and will be removed on Dec 31st this year. The new API for booking services to existing reservations is under development right now.

**Comment by c2ofh** [comment]
@bennetone Are there any news? 
We've used  `POST /booking/v1/reservations/{id}/amend` to add Services with the `extraServiceIds` key in the payload.
Now I can't find any solution to handle those requests in the future.
The recommended `PUT /booking/v1/reservation-actions/{id}/amend` looks like it can't handle services with id's.

**Comment by bennetone** [comment]
Hey @c2ofh!

Unfortunately we had some other topics to finish first before we were able to start with the services API. We started with this already and introduced 2 new endpoints to get offers for extra services that you can add to a new booking or to an already existing reservations:

```
GET /booking/v1/service-offers
GET /booking/v1/reservations/{id}/service-offers
```

Right now we are working on a new API that allows you to book services to an already existing reservation. I expect this to be on the NSFW version until Nov 30th 2018.

**Comment by c2ofh** [comment]
Hi @bennetone 
Is the new NSFW Version available? I can't find a suitable endpoint.

**Comment by bennetone** [comment]
Hi @c2ofh

this API is already available and even in version 1.

`PUT /bookings/v1/resetvation-actions/book-service`

**Comment by c2ofh** [comment]
@bennetone 
Perfect, thank you!
