### ISSUE TITLE
GET /booking/v1/reservations, Parameter status

### ISSUE THREAD

**Issue by RalfXenoData** [apaleo/api#182]
## Question

GET /booking/v1/reservations
Parameter: status
was beduetet  Confirmed oder  inHouse?
Ich möchte nur die Reservierungen sehen auf die ich von der Kasse buchen kann.

**Comment by mri-apaleo** [comment]
"Confirmed" bedeuted, dass der Gast noch nicht angereist ist.
"inHouse" bedeutet, der Gast wurde eingecheckt.

In Deinem Fall möchtest Du also alle Reservierungen, die den Status "inHouse" haben.
Du kannst theoretisch auf alle Folios buchen, die offen sind.

**Comment by RalfXenoData** [comment]
Wenn ich bei unserem Demo-Hotel Staus Inhouse abrufe bekomme ich keine Reservierungen,

Der Kellner frägt den Gast. 
"Wie ist ihre Zimmernummer?"
Die Kasse muss jetzt prüfen ob das Zimmer bebuchbar wäre - wie ist dann der Workflow?

**Comment by mri-apaleo** [comment]
Schalte im Demo Hotel am Besten den automatischen Check-In / Check-out ein. Dann werden die Reservierungen automatisch eingecheckt. Einfach im Frontend innerhalb des Hotels in Settings --> Automation springen und dort jeweils den Schalter auf Aktiv setzen.
URL ist z.B. app.apaleo.com/MUC/settings/automation.

Für den manuellen Check-In kannst Du im Frontend auf in das jeweilige Property springen, dort unter Reservations einige Reservierungen mittels dem Menü (3 Punkte) einchecken.
