### ISSUE TITLE
Getting HTTP 422 for [PUT] /rateplan/v1/rate-plans/{id}/rates

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#183]
## Question

How can I fix this?

## Background

I pulled this from the GET endpoint: 

`{
  "rates": [
    {
      "from": "2019-09-18T15:00:00+01:00",
      "to": "2019-09-19T11:00:00+01:00",
      "price": {
        "amount": 55,
        "currency": "EUR"
      },
      "includedServicesPrice": {
        "amount": 55,
        "currency": "EUR"
      },
      "restrictions": {
        "closed": true,
        "closedOnArrival": false,
        "closedOnDeparture": false
      }
    }
  ],
  "count": 1
}`

Then I updated it like this using the PUT endpoint: 
`{
  "rates": [
    {
      "from": "2019-09-18T15:00:00+01:00",
      "to": "2019-09-19T11:00:00+01:00",
      "price": {
        "amount": "48.00",
        "currency": "EUR"
      },
      "includedServicesPrice": {
        "amount": 55,
        "currency": "EUR"
      },
      "restrictions": {
        "closed": true,
        "closedOnArrival": false,
        "closedOnDeparture": false
      }
    }
  ]
}`

I received this error: 
`422 Unprocessable entity: 
{
  "messages": [
    "1 rate(s) exceed the total of included services (55)"
  ]
}`

I tried removing `includedServicesPrice` from the payload as `[PUT] /rateplan/v1/rate-plans/{id}/rates` doesn't even define it in its model, but the error was the same.

**Comment by andreastubbe** [comment]
This is because the price you set to 48 - but the total for all the included services (breakfasts etc.) is already 55. That would mean your room price is `-7`, and we don't allow that.

The services are defined on the rate plan, and cannot be removed from the rates themselves.
