### ISSUE TITLE
Strange notification behaviour

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#184]
Today I've checked our apaleo income log. 

First of all, I rembember "accountId":"RRQL" but I don't think, that I have access to it. I think it was the hotel from the fair last march. The requests was sended to a hotel which do not exist in our system, anymore. Cause I don't know how to cancel this subscription, I return status 200 when I don't know the hotel, to get not flooded by another attempts.

What will be the best way if there is an uncanceled subscription, and I don't have any access to it?
Usually the System cancels all subscriptions on it's own, but maybe there are unhandled possibilities.

Another thing is, why do I get the Requests all at the same time? This is a Testhotel which isn't active, I guess, and there are 13 check-ins at once?

I thought, maybe the timestamp could help me out, maybe it contains the timestamp from the first try, and this is the next attempt to send me the message.
1563030015273 is in Realtime: 14.06.51500 - 05:14:33

when I remove the last 3 digits, the timestamp is correct. 
1563030015 is in Realtime: 13.07.2019 - 17:00:15

**Log**

```
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "NOCOVLEL-1"
 body: "{"id":"f95d2789-64d7-4c46-9f89-beffe54bb2d2","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015273,"data":{"entityId":"NOCOVLEL-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "CLBRZSND-1"
 body: "{"id":"0474b3a3-c40e-4c39-86f9-a4c727ec2306","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030016593,"data":{"entityId":"CLBRZSND-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "ZJJCDKQR-1"
 body: "{"id":"5f3660d7-291f-418a-9550-714ce77e7ee1","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015483,"data":{"entityId":"ZJJCDKQR-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "ZCPNUINH-1"
 body: "{"id":"f8f768b0-8401-45d3-a313-99bb6ae46b8a","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030016313,"data":{"entityId":"ZCPNUINH-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "XMOOHXGL-1"
 body: "{"id":"68589d88-ce13-47d6-bdcb-c8bb2cab3546","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015423,"data":{"entityId":"XMOOHXGL-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "BEEIOUII-1"
 body: "{"id":"81d2462b-adbe-4d26-902c-f08f4c526f5f","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030016030,"data":{"entityId":"BEEIOUII-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "PKOKHHJH-1"
 body: "{"id":"932d8cf8-a13f-45e7-a634-ec858f75b294","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030016173,"data":{"entityId":"PKOKHHJH-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "TLMYYJCX-1"
 body: "{"id":"aef6974e-8c2d-4ee0-a9cc-17abbf3e256c","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015916,"data":{"entityId":"TLMYYJCX-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "LWXKJYHQ-1"
 body: "{"id":"83fa4932-d477-406c-886a-07f7480d4e23","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015751,"data":{"entityId":"LWXKJYHQ-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "QMGZXXMP-1"
 body: "{"id":"0ce64ac6-e8ac-422b-802c-cf63ac8adce1","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030013833,"data":{"entityId":"QMGZXXMP-1"}}"}
{url: "https://my-url.com/F59NSNQ7mm1C3Mw1rfKutEmB"
 time: "2019-07-13 17:00:20 +0200"
 reservation: "CCZOFYCC-1"
 body: "{"id":"3e2d189d-5d12-4fea-a6ef-0ac4b857b841","topic":"Reservation","type":"checked-in","accountId":"RRQL","propertyId":"BER","timestamp":1563030015666,"data":{"entityId":"CCZOFYCC-1"}}"}
```

**Comment by randyrod** [comment]
Hi @c2ofh,

In order to stop getting events for the subscription, you can delete such subscription.

You can make a request to `GET https://webhook.apaleo.com/v1/subscriptions` which will bring you all the subscriptions that are registered for you. With that list you can find the Id of the subscription that is pointing to that property.

Once you have the ID for the subscription you can make a call to `DELETE https://webhook.apaleo.com/v1/subscriptions/{id}` replacing `{id}` with your subscription Id.

This should delete this subscription and you should stop receiving those events.

If you have further questions, feel free to let us know.

Regards,
Randy

**Comment by c2ofh** [comment]
@randyrod thank you, I will give it a try.
Could you also answer why I recieve for one Hotel the same message twice.

```
{url: "https://my-url.com/1J5Kqw8gxMQ8AeN7t376B4vP"
 time: "2019-07-15 10:19:26 +0200"
 reservation: "KQSJRBLX-1"
 body: "{"id":"062bebf4-3914-430c-a8ee-e3a24c1a54ac","topic":"Reservation","type":"created","accountId":"OXHV","propertyId":"ZJUAM","timestamp":1563178757726,"data":{"entityId":"KQSJRBLX-1"}}"}
{url: "https://my-url.com/1J5Kqw8gxMQ8AeN7t376B4vP"
 time: "2019-07-15 10:19:26 +0200"
 reservation: "KQSJRBLX-1"
 body: "{"id":"062bebf4-3914-430c-a8ee-e3a24c1a54ac","topic":"Reservation","type":"created","accountId":"OXHV","propertyId":"ZJUAM","timestamp":1563178757726,"data":{"entityId":"KQSJRBLX-1"}}"}

{url: "https://my-url.com/1J5Kqw8gxMQ8AeN7t376B4vP"
 time: "2019-07-15 10:23:06 +0200"
 reservation: "KIKEMUBV-1"
 body: "{"id":"b7b13756-9638-4e38-ac03-f11af95b50cf","topic":"Reservation","type":"created","accountId":"OXHV","propertyId":"ZJUAM","timestamp":1563178980419,"data":{"entityId":"KIKEMUBV-1"}}"}
{url: "https://my-url.com/1J5Kqw8gxMQ8AeN7t376B4vP"
 time: "2019-07-15 10:23:06 +0200"
 reservation: "KIKEMUBV-1"
 body: "{"id":"b7b13756-9638-4e38-ac03-f11af95b50cf","topic":"Reservation","type":"created","accountId":"OXHV","propertyId":"ZJUAM","timestamp":1563178980419,"data":{"entityId":"KIKEMUBV-1"}}"}
```

this causes some problems on our site.

**Comment by randyrod** [comment]
Hey @c2ofh,

Yeah that is something that can happen, we have a guarantee delivery of `at least once` so there can be duplicates in some slim occasions.

It is all mentioned in the guide here: https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo
and as mentioned in the guide, you can avoid processing duplicates based on the `Id` field.

Hope the information is helpful.

**Comment by c2ofh** [comment]
Hey @randyrod 
sorry I have to reopen the issue.
How do I authenticate this request?
`GET https://webhook.apaleo.com/v1/subscriptions`

By a token from a random subscription?

and is _webhook.apaleo.com_ the same as _notifications.apaleo.com_?

**Comment by randyrod** [comment]
Hey @c2ofh,

No worries, we are here to help.

webhook.apaleo is the replacement of notifications.apaleo, in the outside it is basically the same, we just made sure to only change the guts for better reliability.

That being said, you can authenticate the same way you used to do it with notifications. Basically you can follow the same process as to any api like described here by providing your access token in the headers https://blog.apaleo.com/developer/getting-started-with-apaleo-apis
