### ISSUE TITLE
/subscriptions 401 error

### ISSUE THREAD

**Issue by chrismei87** [apaleo/api#186]
clientId : MyHotelStatsConnect

Hi guys,
During the oauth process we added the "notifications:subscriptions.manage" but we are unable to send a GET to /subscriptions :

 Client error: `GET https://webhook.apaleo.com/v1/subscriptions` resulted in a `401 Unauthorized` response

Can you check if we have the correct authorizations?

Thanks,
Chris

**Comment by randyrod** [comment]
Hey @chrismei87,

A 401 only means that the token you are using is wrong. Can you provide us maybe with the trackingId you get after making the request.

Regards,
Randy

**Comment by chrismei87** [comment]
Hi randyrod,
Thank you to not close this case, we still encounter this issue.
Please note that we send this request directly from our http client. 
GET on https://webhook.apaleo.com/v1/subscriptions
and we receive a http 401 Unauthorized. I cannot provide any trackingId as we only receive http error code.

All other requests are running as expected.
We updated our scope by adding "notifications:subscriptions.manage", we redid the oauth flow with no issue at all.

Regards,
Chris

**Comment by randyrod** [comment]
Hey @chrismei87,

Sorry for the inconvenience.

Could you please send us the token that you are using for the request to support@apaleo.com

That way we can validate to make sure that the token you are using.

Regards,
Randy
