### ISSUE TITLE
Add a external payment

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#187]
`Apaleo-Tracking-Id`: 0HLO9OS3T5M46:00000125

**Expected behavior:**

after posting a payment task I would expect the balance to be 0

**Actual behavior:**

the payment service failed:

{
  "id": "PQMBAEMU-1-2-2",
  "property": {
    "id": "MUC"
  },
  "folioId": "PQMBAEMU-1-2",
  "merchantReference": "PQMBAEMU-1",
  "amount": {
    "amount": 20,
    "currency": "EUR"
  },
  "status": "Failure",
  "failureCode": "Failed",
  "failureReason": "Payment service has failed to process a payment.",
  "terminalId": "T400"
}

**Comment by randyrod** [comment]
HI @SimonBigelmayr,

We have looked into this and noticed that your account did not have test payment enabled. We have enabled it, and now you can proceed to test.

Use this for testing with CVC: 4111 1111 1111 1111 (CVC: 737) - Expiry 10/2020

Use this for testing without CVC: 4111 1111 4555 1142 - Expiry 10/2020

I will close this issue now, but if you have further questions about this it can be dully reopened.

Regards,
Randy
