### ISSUE TITLE
Display of childrenAges wrong/irritating

### ISSUE THREAD

**Issue by detcoGbR** [apaleo/api#189]
I don't know if this is the correct channel to report this, since it is not the API but more a display-bug in the frontend, however it made me think I did something wrong when creating the reservation in the API.

When multiple children are on the reservation, their ages are displayed in the frontend without seperator, which looks funny.
**Code**
The reservation was created like this (and a GET on the reservation shows them the same):
```json
      "adults": 2,
      "childrenAges": [
        6,
        7
      ],
```
**Expected behavior:**
The children should be clearly shown as "6" and "7"
**Actual behavior:**
It looks like one very old child ;-) :
![image](https://user-images.githubusercontent.com/48287756/61466366-12525280-a97a-11e9-8251-89ea691e3af2.png)

**Environment:**
If relevant, this was tested with Chrome on Linux and Firefox on Linux.

**Comment by dario-hd** [comment]
@detcoGbR thanks for reporting this, we will fix it right away! For such things, you can use our zendesk next time.
