### ISSUE TITLE
Account/Group/Chain ID

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#19]
## Question

In APIs such as Apaleo's, it's not uncommon to have and entity, or at least an identifier that associates all the properties that belong to the same group. Unfortunately, Apaleo's API doesn't seem to provide such an identifier. Does such an identifier/entity exist in Apaleo's domain model? If so, how can it be retrieved through the API?

## Background

For us it's important to be able to identify all properties that belong to the same group in an automated and reliable way, but at the moment it's not very clear how we can achieve that goal through Apaleo's API. We could assume that all properties that belong to the same group will always be returned by the properties endpoint, but we're not sure that such an assumption would hold true for all cases (for example, it could be that properties in the same account don't belong to the same group, or that properties within the same group don't have a common account).

**Comment by pgrm** [comment]
Hello @msmeza,

apaleo currently doesn't have a built in support for complicated chain structures with multiple hierarchies.

As I see it, for now, these structures could be modeled in 2 ways in apaleo:

- either flat, everything is in one account, at which point you might need to store a configuration on your side, which properties you want to process (together / at all)
- the chain will create an account for each group. Sophisticated reporting solutions or CRMs which can handle complex cross property and chain structure could in that case retrieve the data from those multiple accounts which would be configured.

@bennetone might have some additional comments on that
