### ISSUE TITLE
Create custom payment method in CreatePaymentModel

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#190]
## I want

Would it be possible to add a custom payment method in the CreatePaymentModel? As I can see there is already "BookingCom" listed. As we are doing the payment ourself through our own payment providers and just register it through the "POST /finance/v1/folio-actions/{folioId}/payments" call, it would make sense to add a new method "hotelbird".

## Use cases
Thus, the apaleo clients could easily see what payment was done through us and what was done through the reception. This would make accounting easier for apaleo clients.

**Comment by dario-hd** [comment]
Hi, we handle the payment ourselves. Why do you want to use a custom payment provider? In this way, you will lose the information whether the payment was done via VISA or Mastercard. Anyway, why would you need to distinguish between your custom payment method and others?

**Comment by SimonBigelmayr** [comment]
Hello Dario, 
That is exactly the problem: WE (hotelbird) handle the payment ourself. Currently, we do not have a business logic for triggering the payment via the PMS. When the user triggers the payment in our app, we trigger the payment with our payment provider. After successful payment, we synchronize the payment to the PMS. 
We would like to keep this logic because it works quite well for us... It is similar to "BookingCom". If the payment is handled by them you also do not know if the payment was done via VISA or Mastercard.

**Comment by andreastubbe** [comment]
Hi Simon,
> It is similar to "BookingCom". If the payment is handled by them you also do not know if the payment was done via VISA or Mastercard.
Not really. "BookingCom" means that they are collecting the money and periodically transfer it to the hotel's bank account. BDC does not post the payments to apaleo when they have been done, and they do not tell anyone how the guest was paying them.

You can simply post the payment after you collected it, specifying the payment method that was actually used.

> the apaleo clients could easily see what payment was done through us and what was done through the reception. This would make accounting easier for apaleo clients.
I see more value in knowing which cards or payment methods were used, not which app was technically triggering and posting the payment. VISA is VISA, no matter whether it was card-present, online, or using integrated apps. In accounting you don't care much about the technical means by which a payment was done.

**Comment by SimonBigelmayr** [comment]
Thanks.
