### ISSUE TITLE
Uncaught error if pspReference is duplicate in "POST /payments"

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#191]
`Apaleo-Tracking-Id`: 0HLOCC3GC3FO9:000001A1

**Use case**

When a reservation has more that one folio, we will sum up all remaining balances of the folios and trigger only one payment with our payment provider. Thus, the pspReference is unique at the payment-provider side but this unique Id should be used for both folios on the apaleo side. When we try to synchronize these successful payments to apaleo we receive a non-descriptive message back.
I found out that the call succeeds if I do I small change in the "pspReference". It looks like you are having a unique-constraint on this value. Thus, the first payment-sync work but the second not because it has the same pspReference as the first.

1. if the pspReference is unique on the payment provider side does it really need to be unique at the PMS side, too? If a guest has eg 4 folios, this requires 4 single credit card payments. Is there a chance to change this and make it eg. unique per reservation?
2. If not, we could use the real pspReference + the folio_id as pspReference. This would result in eg ch_1EyxCbJl3EXviHb9jB9FWS5B_ACWADHVT-1-1 instead of ch_1EyxCbJl3EXviHb9jB9FWS5B as pspReference on your side. What do you think about this solution

**Expected behavior:**

`{
  "messages": [
    "No duplicate pspReference allowed"
  ]
}
`

**Actual behavior:**
response object:
```
{
  "type": "about:blank",
  "status": 500
}
```

**Comment by nfidirko** [comment]
Hi @SimonBigelmayr,

thanks for reporting the problem.
Indeed, it's not mandatory for the `pspReference` to be unique.
So, we'll fix the issue and let you know when it's done.

**Comment by SimonBigelmayr** [comment]
Great, let me know.

**Comment by nfidirko** [comment]
Hi @SimonBigelmayr, we've deployed and checked the fix.
Now you should be able to create several payments with the same `PspReference`.
Please confirm if it works for your side, too.
