### ISSUE TITLE
APIs for the following use case

### ISSUE THREAD

**Issue by dmitry-urenev** [apaleo/api#195]
@hqrevenue wanted to ask here #194: 

## Question
Could you please help us locate the suitable APIs for the following use case:
I have looked at https://api.apaleo.com/swagger/, but could not find an endpoint which gives the following data. Occupancy forecast for a time range, ideally for 365 days in the future with following attributes:

• TargetDate
• TotalRooms
• DefinitiveSold
• Tentative
• ADR
• RevPar

## Background
As per our email conversation, this is for Apaleo integration with HQ plus.

**Comment by dmitry-urenev** [comment]
@hqrevenue please check out our reports API. With that one you can get all required attributes 
`GET /reports/v1/reports/property-performance`

**Comment by hqrevenue** [comment]
@dmitry-urenev Thank you. Where can I find the documentation for this api?

**Comment by dmitry-urenev** [comment]
@hqrevenue  We don't have other documentation besides Swagger: https://api.apaleo.com/swagger 
Because it already provides all technical documentation and details. Explore it:

1. Select service that you are interested in

![image](https://user-images.githubusercontent.com/7558366/61940023-e4ca6200-af94-11e9-84e3-a93f55b8aafb.png)

2. Click on some endpoint url to expand details

![image](https://user-images.githubusercontent.com/7558366/61940238-45f23580-af95-11e9-98a8-27b768224a90.png)

3. In the details you can find description of the query parameters, returned models, status codes, examples and even create requests: 
![image](https://user-images.githubusercontent.com/7558366/61940699-463f0080-af96-11e9-934e-aa47ec7e7d0a.png)
