### ISSUE TITLE
Invalid grant when obtain access token from authorization code

### ISSUE THREAD

**Issue by henryngoo** [apaleo/api#196]
Hi the support team,

We have implemented to integrate apaleo OAuth2 via the docs https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0 and have an issue regarding to exchanging the authorization code for an access token (at Step 2)
Please reference the report in more details below and let us know what we're missing.

**Steps**
- Request:  `https://identity.apaleo.com/connect/authorize?response_type=code&scope=properties.read&client_id=IdemConnect&redirect_uri=[FILTERED_ REDIRECT_URI]&state=e9Sqopen2Mw4OaUV`
- Navigate to Login Screen and enters the login account
- Logged in success and redirect to `FILTERED_REDIRECT_URI` with param `authorization_code` obtained `2c806d29580da8f9335ad88a8ad3faf5d9219c20c722134cdeceb9f62dc24e1b`
- At `FILTERED_REDIRECT_URI` we implemented to obtain access token via `grant_type`  set to `authorization_code`

```
curl -X POST \
  https://identity.apaleo.com/connect/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=authorization_code&client_id=IdemConnect&client_secret=[FILTERED_CLIENT_SECRET]&code=2c806d29580da8f9335ad88a8ad3faf5d9219c20c722134cdeceb9f62dc24e1b'
```

**Expected behavior:**
Obtaining token data including: `access_token` and `refresh_token` in response

**Actual behavior:**
Returned an error in response
`{'error': 'invalid_grant'}`

**Related Issues:**

**Comment by andreastubbe** [comment]
It looks like you're missing `redirect_uri=YOUR_URL_ENCODED_REDIRECT_URI` in your call.
You'll have to do the connecting again, as the `authorization code` expires after a while.

**Comment by henryngoo** [comment]
Hi @andreastubbe 
It works but the response did not contain `refresh_token` after requesting api call with the grant `authorization_code`. Please you could take a look at payload below.

**Request:**
```
{
    "code": "037f1f40e517b11702e1080f8c29c1712b8ffaa4e045fe9a95209127900912af",
    "client_secret": [Filtered],
    "grant_type": "authorization_code",
    "client_id": "IdemConnect",
    "redirect_uri": [Filtered]
}
```

**Response:**
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5NTkyRDA5RTRERkQzNzVGNEIzRTFDNjNGN0QzQjU4NzU5REJFREYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJHVmt0Q2VUZjAzWDBzLUhHUDMwN1dIV2R2dDgifQ.eyJuYmYiOjE1NjQ3MTg5NTYsImV4cCI6MTU2NDcyMjU1NiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5hcGFsZW8uY29tIiwiYXVkIjpbImh0dHBzOi8vaWRlbnRpdHkuYXBhbGVvLmNvbS9yZXNvdXJjZXMiLCJhcGkiXSwiY2xpZW50X2lkIjoiSWRlbUNvbm5lY3QiLCJzdWIiOiI1NmI0ODAyNi1mNWMzLTRkMWMtOGEwZS1iZjhmMzBiMWRkYzciLCJhdXRoX3RpbWUiOjE1NjQ3MTc5NzEsImlkcCI6ImxvY2FsIiwibmFtZSI6ImhlbnJ5QGlkZW1sYWJzLmNvbSIsImFjY291bnRfY29kZSI6IkJTU0IiLCJyb2xlIjoiUHJvcGVydHlBZG1pbiIsInByb3BlcnR5IjoiSURFTTEiLCJzY29wZSI6WyJwcm9wZXJ0aWVzLnJlYWQiXSwiYW1yIjpbInB3ZCJdfQ.FIOZlgv6s0UH5PA2csM1eifZp5ghlALapLRRBpI_x-hYABddUY-S1LZNBpwYp85ooaY4nRNhBtCtWYbcv8yzUyMObvSogr6arwLhbof7MuiYZ6VwQFbLwbgwmQ0dXWL2PVUZZShOdlqVUTEfBeJMv2NYABW-Up1aOV13PbjLsvePDEgw30rD9adzFI4r4TjrjyDCdML-xPjE3X8djh10SSTm61LXqJko2Hjc-6EHAiC_dCisKhl6L9uOMPcETeJeomFAfLsOgW8t5c9buumbsEP7YngKCLb46M7313WLN34QgQksVdFJVISLEPSFrcSJQRx2sSoy24LkF7wYehsz9g",
    "token_type": "Bearer",
    "expires_in": 3600
}
```

**Comment by henryngoo** [comment]
Hi @andreastubbe could you please troubleshoot and tell me what root cause related to this issue. We already implemented what described in Step 2 `exchange the authorization code for an access token` but no `refresh_token` returned in response.
We are going to launch and demo to customer but got stuck in step 2.
Thank you.

**Comment by ozonni** [comment]
@henryngoo you need to add `offline_access` into requested scopes, then you will get `refresh_token`

**Comment by henryngoo** [comment]
Well it works
Thanks @ozonni
