### ISSUE TITLE
Authorization fail with token

### ISSUE THREAD

**Issue by BobPurple** [apaleo/api#197]
We logged in through OAUTH by sending the hotel a URL with scope parameter set on: offline_access. We received the code and from that we receive the refresh token. We received the access token through the refresh token, but when we use it (for reservations or ARI subscriptions requests), we receive a reply that says we are unauthorized. Can you tell us why?

**Comment by andreastubbe** [comment]
Need a bit more info.
- Did you specify any other scopes or just "offline access"?
- The response you get is a 401 or 403?
- What's your client ID?
- how long between requesting an access token and using it? It expires after a while.

**Comment by BobPurple** [comment]
We solved the problem. In the browser we signed out from the PMS before linking the oauth page and now it works. The page asking the permissions for ARI and reservations now shows up.
