### ISSUE TITLE
ui-integrations error

### ISSUE THREAD

**Issue by chrismei87** [apaleo/api#198]
Hi Support team,

We are finalizing the integration with ui-integrations service.
We try to POST a new integration but we receive an error message :

POST https://integration.apaleo.com/integration/v1/ui-integrations/DashboardPropertyContext

{"code":"MainDashboard","label":"MyHotelStats","iconSource":"https:\/\/superurl.com\/assets\/img\/smalllogo.png","sourceUrl":"https:\/\/superurl.com\/dashboard\/13?atoken=aea62Ua8XWNLZmyBbfHbnJpxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdV77rQmHDuY2HWJdsTYVuanTb","sourceType":"Private","propertyIds":["BER"]}

422 Unprocessable Entity
Response: {"messages":["Unexpected character encountered while parsing value: <. Path '', line 0, position 0."]}

Can you help us with this?

Note : If we clearly understand, the sourceURL will indicate the url for the iframe that will appear in your extranet.

Best,
Chris

**Comment by andreastubbe** [comment]
Hi Chris,

The error message is a masterpiece of usability, sorry about that.
What it’s supposed to say is “the data which is returned when we call the URL cannot be passed.”
We validate it because we don’t want to display errors to the hotels.

Best,
Andrea

**Comment by andreastubbe** [comment]
> sourceURL will indicate the url for the iframe that will appear in your extranet.
Not quite. Check https://blog.apaleo.com/developer/ui-integration-guide again, "Private integrations". To keep things secure, this URL should return 

```
{
    "url": "string",
    "expTimestamp": "datetime"
}
```

Not just the page content

**Comment by chrismei87** [comment]
Hi Andrea,

No problem, we are developers too :)
I checked and the link works in our side, it's just an html page.
What kind of data do you expect in return from this URL ?

Best,
Chris

**Comment by pgrm** [comment]
@chrismei87 you are registering a private URL - the private URL should return a JSON object with the public URL. Please check the section **Private integrations** in https://blog.apaleo.com/developer/ui-integration-guide

if you want to return the HTML page directly, you need to register it as a public integration.

The idea of those private integrations with private URLs is to provide the user with a single sign on mechanism. If you just register a public URL it means either, the user needs to log in extra in your iframe (degraded user experience) or you are providing public information within the apaleo UI - which might be totally fine. 

Of course, if you have an integration which wouldn't be accessible from the internet, like a locally running service communicating with an on premise device, you always need to use the public integration method.

**Comment by chrismei87** [comment]
Hi @pgrm , thank you for the integration guide.
FYI we implemented a Public integration for a better experience, and it works now.

Users can build such a dashboard in our app :
![DailyDashboard](https://user-images.githubusercontent.com/27995680/62107817-bf956680-b2a8-11e9-8100-62f110c5d575.png)

Do you know how can we display it in a bigger block in the PropertyDashboardContext instead of a small block on the bottom right ?

Thank you,
Chris

**Comment by pgrm** [comment]
that's cool @chrismei87 - as long as they are logged in with your app all the time, it should work nicely.

To put a bigger tile on the dashboard and let the users re-arrange the dashboard is something we are thinking about, how to adjust it best for the users.

Until then, you could provide multiple tiles into the dashboard context, if you want - with different numbers. And you can also put the full page as a menu item under reports `PropertyMenuReports`

There's also an open issue here, which we are going to follow up in the next weeks, to be able to trigger a navigation on the UI from within the iframe: https://github.com/apaleo/api/issues/146 - that way you'll be able to let the user click on the tile on the dashboard, to navigate them to your integration in `PropertyMenuReports`

**Comment by chrismei87** [comment]
Thank you @pgrm , other solutions sound interesting too, I think we will focus our integration on PropertyMenuReports and PropertyMenuApps.

Can we setup multiple links in `PropertyMenuReports` ?
Do you have a `AccountMenuApps` ?

**Comment by pgrm** [comment]
>  Do you have a `AccountMenuApps` ?

no, not yet, but it will come in August. We can keep this issue opened, and I'll let you know here directly, once it's available

**Comment by chrismei87** [comment]
We now send ui-integration for `PropertyMenuReports` and `PropertyMenuApps` and it looks great, thank you !

**Comment by pgrm** [comment]
@chrismei87 sorry for coming back to you so late - we do have now `AccountMenuApps` (already for a while, just forgot to update this issue 😊 )
