### ISSUE TITLE
Basic authorization stopped working for simple Excel VBA code?

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#20]
## Question

Did something change or was updated in the basic authorization flow? Calling  https://identity.apaleo.com/connect/token and exchanging client credentials for access_key. 

## Background

We have been using the following basic code snippet following Apaleos documentation. For the last 2 months this worked smoothly without any problems.

_Set objWinHTTP = CreateObject("WinHttp.WinHttpRequest.5.1")
Url = "https://identity.apaleo.com/connect/token" 
objWinHTTP.Open "POST", Url, False
encodedCred = "Basic OUR_BASE_64_ENCODED_CREDS" 
objWinHTTP.SetRequestHeader "content-type", "application/x-www-form-urlencoded"
objWinHTTP.SetRequestHeader "Authorization", encodedCred
objWinHTTP.Send "grant_type=client_credentials"_ 

Thanks a lot in advance!

**Comment by dario-hd** [comment]
From our side, nothing changed in this regards. Could you please provide your client id and the response you got?

**Comment by patrickHermannLimeHouse** [comment]
Thanks. Client-id: price-app-limehouse. I do not receive a response however I receive the following VBA Error Message: _Laufzeitfehler '-2147012866 (80072efe)': Die Serververbindung wurde aufgrund eines Fehlers beendet._

**Comment by dario-hd** [comment]
That looks like a connection issue. Are you behind a firewall or something?

**Comment by patrickHermannLimeHouse** [comment]
Hi. Yes it might be a connection issue however I have the same firewalls as before and the error also occurs on my colleagues server. Could there be another reason for the connection issue? thx

**Comment by dario-hd** [comment]
Actually, I tried to run your code with valid credentials and it's working fine:

![untitled](https://user-images.githubusercontent.com/14803089/46018702-c678a900-c0da-11e8-8d60-80dbbae121a6.png)

What do you get when you enter https://identity.apaleo.com/connect/token in the browser?

**Comment by patrickHermannLimeHouse** [comment]
![image](https://user-images.githubusercontent.com/42251140/46023360-c2ea1f80-c0e4-11e8-8596-bcec513301f0.png)

I am getting an invalid request error. Did my client ID or secret got changed? Or are they still valid?

**Comment by dario-hd** [comment]
That's ok because the request to get the token is a POST request. I just wanted to see what you get...it seems you can reach the URL.

**Comment by dario-hd** [comment]
Have you tried getting the token in another way? E.g. using Postman? Just to exclude connection problems...

**Comment by patrickHermannLimeHouse** [comment]
Thanks Dario. I tried Postman as can be seen in the snapshot. Still the same error code.
![image](https://user-images.githubusercontent.com/42251140/46027784-f7fb6f80-c0ee-11e8-930e-bc234069dfba.png)

**Comment by patrickHermannLimeHouse** [comment]
![image](https://user-images.githubusercontent.com/42251140/46028627-64776e00-c0f1-11e8-9ec4-ab717149c5ae.png)
As I am now running the POST request with the headers and the body: 
![image](https://user-images.githubusercontent.com/42251140/46028672-82dd6980-c0f1-11e8-99d1-5c0e70f83c1b.png)
It is now working on Postman.

**Comment by dario-hd** [comment]
It could be that it’s related to macro protection settings in Excel, maybe? That’s the only thing I could think of. I’m not sure we can help you further :)
