### ISSUE TITLE
How do I get an Access Token?

### ISSUE THREAD

**Issue by marcelcel** [apaleo/api#200]
hallo apaleo Team,

I'm working on the integration into dailypoint.

Unfortunately I did not find out in the documentation how to authenticate myself. Which function with which parameters do I have to use ?

**Comment by ozonni** [comment]
@marcelcel do you already have API credentials?

Here is a guide on how to connect your app with OAuth2: https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0

**Comment by globalw** [comment]
Hello,

so encoding the client-id and -secret with base64 i was making that POST request as described in 

https://blog.apaleo.com/developer/getting-started-with-apaleo-apis

so the exact command on my ubuntu 16.04 is 

`curl -X POST -d "grant_type=client_credentials" -H "content-type: application/x-www-form-urlencoded" -H "Authorization: Basic $(echo -n 'Client-ID:Client-Secret' | base64)" https://identity.apaleo.com/connect/token`

my response is 

`{"error":"invalid_client"}`

am i forgetting something or maybe my credentials aren't activated?

**Comment by bennetone** [comment]
Hi @globalw 

we actually forgot to activate your API client, sorry for that. I just activated it and you should be able to retrieve your authorizaiton token in about 5 to 10 minutes.

Kind Regards,
Benjamin
