### ISSUE TITLE
Invoice language fallback

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#202]
## I want

A fallback to english if the invoice template is not defined in the guest language.

## Use cases

Sergio is a guest from spain, Sergio's preferred language is spanish.
On Check-out Sergio checks his invoice positions. I also try to show him "Breakfast" in spanish, but it's not defined, so apaleo returns the english name. 👍 

Now I want to create his invoice, with `{"languageCode": "es"}`.
The API returns:

> Cannot create invoice

When I try `{"languageCode": "de"}` or `{"languageCode": "en"}` the invoice will be created.

Is it possible to use the fallback language as when I get the service names?

And are the invoice languages "hardcoded" german and english or is there a possibility to define an invoice in spanish for example?

**Comment by bennetone** [comment]
Hi @c2ofh 

the languages an invoice can be generated for are depending on the country the property is located in. We support the mandatory languages for the respective country (like e.g. French, Italian and German for Switzerland) and then the most common foreign languages. You can call the following API to get the supported languages for a specific country:

`https://rendering.apaleo.com/invoices/v1/configuration/supported-languages?isoCountryCode=de`

If you find the preferred language of the guest in this list, then you can generate the invoice in this language. If not, you would need to fall back to a meaningful default, which might be English in the most countries.

Cheers,
Benjamin
