### ISSUE TITLE
reset test account

### ISSUE THREAD

**Issue by marc-air-agents** [apaleo/api#206]
## Question

I created my test account in June - and you populated it with reservations.
Is it possible to re-populate it with more future bookings - all of the original bookings are now history so if I search by todays date I get nothing

Many Thanks,
Marc

**Comment by DsAekb** [comment]
Hello @marc-air-agents,

We've just created new reservations. Please check.

Best regards,
Stanislav

**Comment by marc-air-agents** [comment]
Hi Stanislav,
Yes - that’s just what I wanted.
Many Thanks
Marc
