### ISSUE TITLE
Recomended way to subscribe to new properties using https://webhook.apaleo.com?

### ISSUE THREAD

**Issue by koskiOvaa** [apaleo/api#208]
## Question

What is the best way for a service to subscribing for events of _new_ properties created by Apaleo Customer?

## Background

Use case: 

An Apaleo Customer uses also Service X which implements the features of the awesome api.apaleo.com. To make things smooth and quicker, also webhooks are used.

However, during the happy customership, Apaleo Customer adds a new property. What is the best way for Service X to subscribe for events of this new property?

Should Service X for example just poll the properties (GET /inventory/v1/properties) of the customer periodically and subscribe/unsubscribe to webhooks accordingly?

Is there a way for Service X to just get "all the reservation events"?

**Comment by randyrod** [comment]
Hi @koskiOvaa,

I'm happy to inform that we have just released the new filter management for the webhook subscriptions, that would allow you to create subscriptions that will work for all the customer's properties.

You can read more about it in the announcement notes: https://github.com/apaleo/announcements/issues/35

Hope you have a great day!
