### ISSUE TITLE
How do I retrieve new scopes for my existing client ID and secret?

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#21]
Hello Community. How can I request new scopes such as Distribution & Notification API scopes for my existing client ID and secret? Alternatively, do I need to request a new client ID and a new secret. Thx

**Comment by aprooks** [comment]
Hello @patrickHermannLimeHouse,

send us an email to support@apaleo.com with clien_id and a new set of scopes required. We will review and change your scopes. You don't have to request new client_id/secret if you are working with the same account.

Alex.
