### ISSUE TITLE
Get cancellation fee description in specific language

### ISSUE THREAD

**Issue by LucaDe** [apaleo/api#210]
## Question
When creating cancellation fees it's possible to translate their name and description. When getting a reservation by its id (Reservation/BookingReservationsByIdGet) a ReservationCancellationFeeModel is returned. Is it possible to specify the language the name + description of this model should have?

**Comment by pgrm** [comment]
hello @LucaDe, YES IT IS 😄 

we're using the standardized [`Accept-Language` Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) for this
