### ISSUE TITLE
book-service - no service booked

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#211]
`Apaleo-Tracking-Id`: 0HLPSF7MTQ41P:00000003

I'm trying to add a service to an existing reservation:

PUT `https://api.apaleo.com/booking/v1/reservation-actions/WJBCWRAS-1/book-service`
PAYLOAD `{"serviceId": "BER-BRKF"}`

The response is 204 "No Content" without any message, but the service was not added to the reservation.

**Comment by bennetone** [comment]
Hi @c2ofh 

I checked the reservation in the system and it has the breakfast booked.

You sent the request to book the breakfast twice. The tracking id above is related to the second call. When the service is already booked we just return 204 and do nothing.

![image](https://user-images.githubusercontent.com/25197867/65224310-37bb2400-dac3-11e9-95bf-0e6635eebaf3.png)
