### ISSUE TITLE
Block API : created date and revenue breakdown

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#212]
## Question

Dear Apaleo Team,

Got 2 questions on "Block" API : 
- Actually there is no "created" and "modified" date field in this API. Would it be possible to add this?
- To determine revenue breakdown (room, food, other), we need to get the rateplan, substract the services, use the vat API to get the vat amount, etc. Is there any simpler solution I missed?

Best regards

Jean

**Comment by dmitry-urenev** [comment]
Hi @jeanatpi ,

- we do not expose "created" and "modified" dates for blocks. Only for bookings (group and booking has 1:1 relation and you can get that information knowing group id). 
-  unfortunately we do not have revenue forecasting for groups and blocks right now, so keep do what you are doing to get these numbers. But we think about implementing so called contracts, which would allow as to do the forecast and breakdown in a very easy way.  

Could tell us more about your use case for revenue breakdown? 

With best wishes, 
Dmitry / apaleo Team

**Comment by jeanatpi** [comment]
Hi @dmitry-urenev,

Thanks for your quick answer.

For blocks we would have been interested in having the date when the block was created. So use it as a king of "reservation date".

For revenue breakdown our goal is to have a revenue breakdown for : 

- room revenue
- food revenue (food & beverages)
- other revenue (wifi, parking, extra services, etc.)

Ideally each one with it's vat_amount or percentage.

**Comment by bennetone** [comment]
Hi @jeanatpi 

first I would like to get the terminology right. A lot of systems call what we consider a group booking a block. So I could imagine that the created and modified timestamp of the booking is sufficient for your use case and you can consider it the "reservation date".

Regarding the revenue forecast. Right now you could take the grossDailyRate per block and sum it up for the number of nights and blocked units. If you really want to split out the different revenues (room, f&b and other), you would actually have to understand the setup of the rate plans and do service fee calculations, which I think is really error-prone.

As @dmitry-urenev already mentioned we are planning to introduce so-called contracts for group bookings, which will sum up how many rooms are contracted for how many nights and what price. Also we will over time allow to add services to those contracts. With that available we would also add forecasts for the different revenues. The blocks are just for managing the availability, so you could have contracted 10 rooms and already know that only 7 will be picked, but the conditions of the contract require the booker to still pay for the 10. Those things cannot be covered by the implementation you proposed.

Hope this information helps you to specify a first version of forecasting group business and just watch our [announcements ](https://github.com/apaleo/announcements)to be up to date when group contracts are coming.
