### ISSUE TITLE
Delete an obsolete subscription

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#214]
## Question

There is a subscription active, which sends a lot of push messages.
Unfortunately I cannot find a hotel in our system for which the subscription was used for.

It would be great if you could add the subscription_id to each push message, Then it would be possible to unsubscribe the messages by this id.

Or could you unsubscribe this subscriptions for me?

Are you able to find the Subscription by this values?
message ids:
```
e93ef1c1-94a6-4dba-8c8a-1da20d1a1550
bf4e332f-8012-4822-9c58-b424fb60caf3
fda740fd-a3b3-4909-81ab-811aadb9a9b1
ce5f4971-422a-4401-9c3b-3db4f6bdae05
3dc9c3f5-2398-4be9-93aa-58f1a4766f82
77165bdf-8377-4203-b509-30e664996527
d74a7c2d-e58f-43ea-80be-7feef5d40a74
fd33e249-8bfb-4c03-be5d-e9aa95a58c8f
9bbea5c8-a6f7-4030-8c7f-9ab15ccfac98
0f03d306-3433-45a4-8f24-c234871d9e9c
112ce46c-b3c1-4768-8f9f-f30d8197bb0a
```
accountId
```
RVQP
```
propertyId
```
FIRSTAPART
```

## Background

Normally the subscriptions will be unsubscribed when a hotel is deleted (for example an old demo version of our solution).
Maybe the unsubscription was not successful in this case.

**Comment by andreastubbe** [comment]
Try `f05f2bfc-1524-4aab-b5fe-7b13a8e4023f` - I see a lot of failed health-checks for this subscription, and it's for RVQP and a code2order URL.

**Comment by c2ofh** [comment]
Hey Andrea,

I forgot... I cannot send an unsubscribe request, cause I don't have a valid token for this request.
No hotel, no token information. 😆 
So the subscription_id is useless in this case :(

**Comment by andreastubbe** [comment]
You have a point there... :)
We'll have a look tomorrow morning. After midnight is not a good time for deleting things.

**Comment by pgrm** [comment]
@c2ofh we've deleted your subscription, and soon you should stop receiving requests from us 😄
