### ISSUE TITLE
Issues exchanging token for refresh token. 

### ISSUE THREAD

**Issue by calumpwebb** [apaleo/api#215]
There seems to be an issue when trying to post to the apaleo token auth server.

We got some valid access tokens and tried posting to get a refresh token but this is failing. 

Can we get some information why this is giving us a 400?

note: times are UTC

![image](https://user-images.githubusercontent.com/6991398/65880738-2f4bce80-e38a-11e9-88da-1efc5140c459.png)

**Comment by randyrod** [comment]
Hi @calumpwebb,

Thanks for reaching out.

You can check the following guide for what you are trying to do: https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0#connect

Specially you can take a look at step 2 of the connect section, where you can see the expected body for your request in the table that is in the guide.

If you have further questions let us know.

Regards

**Comment by calumpwebb** [comment]
hey @randyrod thanks for your help.

it looks like our redirect url changed on the website and the backend that auths sends the request wasn't updated so was still sending the old redirect url.

Thanks for the help! (the docs made me realise that probably one of the fields we was sending was wrong)

**Comment by randyrod** [comment]
I'm glad the guide was of use for you.

I will be closing this issue now, however, If you have any other questions feel free to reach out.
