### ISSUE TITLE
ARI Subscription Fails with OverNight Error

### ISSUE THREAD

**Issue by YouJinTou** [apaleo/api#216]
## Question

Is this described somewhere, or should I always filter for `OverNight` rate plans only?

## Background

When I try to create an ARI subscription for a property that has a `DayUse` rate plan, I get the following error: `Subscription can only have \'OverNight\' rate plans.`

**Comment by randyrod** [comment]
Hi @YouJinTou,

Thanks for reaching out. Currently we do not support ARI subscriptions for `DayUse` rate plans. So your assumption is correct, you must filter those rate plans out for the subscription.

If you have further questions, feel free to contact us.

Randy.
