### ISSUE TITLE
OAuth2: Mitigation of necessary CORS Proxy for OAuth Client possible?

### ISSUE THREAD

**Issue by 23RoMax** [apaleo/api#217]
## Question
Hi together,

the undocumented endpoint /connect/token (could not find the endpoint in swagger) does not provide CORS Headers and preflight fails as a result. Although this might be expected due to me trying implementing the OAuth Client fully in the frontend, I was wondering whether there is another implementation available on your side, to keep the implementation rather lightweight, as I'm building a very simple frontend to list all guests of a property / Can I get the access_token on a CORS enabled endpoint?

--> I'm aware of the security implications of such an endpoint as it exposes the Base64 encoded API Secret in the frontend on successful logins, which only happens when the credentials to the system are known in the first place (see firebase auth in Background). Just asking whether this or an alternative solution is available e.g. login via credentials...

## Background

I'm building a simple & lightweight application (vue.js) listing all guests of a property for a client that implements a digital "Klingelschild" in all his properties. The go-to solution is:

- The frontend is behind a firebase auth
- Properties will be selectable
- Fetching the new guests every 12 hours per property
- Displaying a list of the guests hosted in the properties units
- As lightweight as possible
- Autonomous handling as client is not always on site
- Preferably no own backend necessary
- Preferably no third-party OAuth client necessary

**Comment by andreastubbe** [comment]
Hi @23RoMax , you could theoretically use the same mechanism as the apaleo UI - we don't have this documented though, give us some time to do that.

**Comment by 23RoMax** [comment]
Hi @andreastubbe,

Thank you for the quick answer.
Highly appreciate the effort 👍

**Comment by 23RoMax** [comment]
Hi @andreastubbe ,

Any news on the topic/docs?

**Comment by andreastubbe** [comment]
Yes, but you won't like them :(
Turns out that the mechanism we use for our UI has been deprecated - *so very much* deprecated, that it isn't even documented anymore. We'll first need to adjust it on our side, and then make it public.

Unless you can wait for some weeks or months, I'm afraid you'll have to resort to what we already have. Which requires a server-side component.

**Comment by 23RoMax** [comment]
Alright, no worries, I will just setup a server sided implementation for this.

Thank you for the quick answer and have a nice weekend!
