### ISSUE TITLE
API/Webhook for Services

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#218]
I want an API/webhook to identify whether a reservation has requested for extra services. 

Background:
Currently we can get the extra services added to a reservation using /booking/v1/reservations/{id}/services API. However, we need to run through all reservations to identify which ones have extra services. The services can be requested after the reservation is created, and it results in redundant API calls. 

Recommendations:
1. Addition of Extra Services flag to reservations API
2. Generate webhooks when an extra service is created
3. API to get a list of reservations attached to a particular Extra Service ID

**Comment by ozonni** [comment]
@limehome-dev when extra service is added or removed from reservation, it is represented by `amended` event. By listening `amended` event you can query reservation details and see if any changes to extra services were made. Should reduce number of API calls.
