### ISSUE TITLE
invalid scope: items.read

### ISSUE THREAD

**Issue by MSRobert** [apaleo/api#219]
`Apaleo-Tracking-Id`: 0HLQC0339I2OR:000006B1

**Code**
Hi, it seems like the scope "items.read" is not valid any more. Was there any change in the API? I cannot see, what this scope was initially needed for and do not know, if we need it for our integration app to function.

https://identity.apaleo.com/connect/authorize?response_type=code&scope=offline_access%20subledger.read%20transactions.export%20folios.read%20invoices.read%20items.read%20properties.read%20rates.read%20rateplans.read%20offers.read%20groups.read%20blocks.read%20units.read%20unitgroups.read%20availability.read%20reservations.read%20services.read&client_id=VASHospitalityManager&redirect_uri=https://vasintelligentsolutions.azurewebsites.net/&state=919c40e2-8feb-47a4-b533-fbd782482656

**Expected behavior:**
authorized client

**Actual behavior:**
error message: invalid scope

**Related Issues:**

**Comment by ozonni** [comment]
@MSRobert the `Items` api was deprecated and removed. Just don't request `items` scopes anymore. Should fix your issue.
