### ISSUE TITLE
Where is cancellationFee in GET /booking/v1/reservations response?

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#22]
## Question

Where is the `cancellationFee` object in the GET `/booking/v1/reservations` response?

## Background

The `cancellationFee` object is present in the response for GET `/booking/v1/bookings` when the reservation is expanded. But missing for the above endpoint?

**Comment by lukeclifton** [comment]
This is quite urgent for us as we require the use of the `status` param for GET `/booking/v1/reservations` but also need the `cancellationFee`. 
This is for the new 'manage booking feature' we are working on currently for UP IBE.

**Comment by ozonni** [comment]
@lukeclifton makes sense also have this information in `/booking/v1/reservations` api. I will put it to our backlog and prioritize it.

**Comment by ozonni** [comment]
@lukeclifton we just released a new version of api to production. Now reservation has `cancellationFee` and `noShowFee` as well
