### ISSUE TITLE
more demo data for our test hotels

### ISSUE THREAD

**Issue by MSRobert** [apaleo/api#220]
## I want

Hi, could you please add more demo data to our test hotels BER and MUC for our account BQGH? Please add as much data as you can!

## Use cases

We are creating data analytics apps and need more data to show relevant KPIs. 

## Examples

can you add data for 2018 and 2019?

**Comment by ozonni** [comment]
@MSRobert we can create reservations with arrival day starting from today. If you need some other data, i would recommend you to write small script that prepares it for you using apaleo API.

How many reservation would you like us to create?

**Comment by MSRobert** [comment]
@ozonni I will try to load some data using the api. For the time being, please create reservations from today until 12 month in the future.

**Comment by ozonni** [comment]
@MSRobert we created some reservations in both properties. Enjoy!
