### ISSUE TITLE
PATCH reservation request was malformed and could not be parsed

### ISSUE THREAD

**Issue by ozonni** [apaleo/api#221]
Hello, I am currently experiencing some challenges with modify reservations made via API https://api.apaleo.com/swagger/#!/Reservation/BookingReservationsByIdPatch the error I'm getting is " The JSON patch document was malformed and could not be parsed. " I have tried debugging the error but I'm having some issues with it, an example of PATCH request that modifies primary guest was sent to me but I am still getting errors.

**Comment by ozonni** [comment]
The request that you send was not a valid PATCH request.

Here is an example of PATCH request that modifies primary guest:
```json
{
    "value": {
        "firstName": "Tester",
        "lastName": "Testerrrr",
        "email": "changed@example.com",
        "birthDate": "1960-11-25",
        "preferredLanguage": "ru"
    },
    "path": "primaryGuest",
    "op": "replace"
}
```

**Comment by philcz16** [comment]
I'm still having the same error sending the example patch file you provided

**Comment by ozonni** [comment]
@philcz16 the PATCH request body is an array of operations, the whole payload should be like this
```json
[
    {
        "value": {
            "firstName": "Tester",
            "lastName": "Testerrrr",
            "email": "changed@example.com",
            "birthDate": "1960-11-25",
            "preferredLanguage": "ru"
        },
        "path": "primaryGuest",
        "op": "replace"
    }
]
```
