### ISSUE TITLE
Please reactivate subscriptions via Swagger API

### ISSUE THREAD

**Issue by lapair** [apaleo/api#222]
`Apaleo-Tracking-Id`: 0HLQEA6IH4AQ1:00000001

**Expected behavior:**
```
    config: {
      url: 'https://webhook.apaleo.com/v1/subscriptions',
      method: 'post',
      data: '{"endpointUrl":"https://x.y.z","topics":["Folio"]}',
      headers: { ... }
```
Create a webhook pointing to `https://x.y.z` for Folios

**Actual behavior:**
```
  response: {
    status: 401,
    statusText: 'Unauthorized',
```

This worked a few weeks ago

I've been told:
```
Subscriptions are per app and creating subscriptions for the swagger UI do not make sense, so creating subscriptions via swagger was switched off on purpose. If you have any more questions or comments, I copied in Peter, he is overseeing the Webhooks and other infrastructure parts of apaleo.
```

I was happy to use my own credentials through the web interface (as this is a one off setup), rather than writing specific code. But even with code, using my API key I am getting
the 401 errors above - even for a GET request - which works with the web interface and my apaleo user details!

Please advise ASAP

Thanks

lLeo

**Comment by andreastubbe** [comment]
HI @lapair , can you let me know the clientID you are using? 401 means "Unauthorized" (you can look up the codes on https://blog.apaleo.com/developer/it-doesnt-work-troubleshooting-the-apaleo-api).

**Comment by lapair** [comment]
hi @andreastubbe This is for `AirAgents` is that what you mean?

These credentials used to work for webhooks - they still work for the other swagger api's, e.g. GET on inventory

**Comment by andreastubbe** [comment]
Just checked your client, and it did indeed not have the scope to use webhooks. I added `notifications:subscriptions.manage`, should work now.
