### ISSUE TITLE
Net daily rate and expand reservation with charges/folios

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#223]
## I want

1) Blocks to have a net daily rate
2) Reservation to be expanded with charges (and folios), i.e. expand=charges,folios

## Use cases

1) We use net rates and (expected) revenues almost exclusively without VAT, since 99% of our customers need/want to know their net revenues.
2) For revenue calculation we need to know/get all charges on a reservation. Through the 
/booking/v1/reservations we use a dateFilter to only get changed reservations since the last time we visited. For these we need to get the charges. Now we have to make (2 + number of folios) API calls to get them (get reservations, get related folios, get each folios with the charges).

## What I do

Developer of RevControl

**Comment by pgrm** [comment]
Hello @remywrevcontrol 

unfortunately, it's not possible to expand folios for reservations.

Did you have a look at our reports API it contains quite a lot of data, so you don't need to aggregate it yourself. Specifically there is `get /reports/v1/reports/property-performance` and `get /reports/v1/reports/revenues`

`property-performance` gives you projected revenue, while `revenues` gives you precise revenue information for the past.

**Comment by remywrevcontrol** [comment]
What about my question about getting the net daily rate in the blocks?

**Comment by pgrm** [comment]
@remywrevcontrol you should be able to find all the information you need for upcoming revenues inside the `property-performance` report. This information also includes net revenue for blocks, as well as upcoming reservations.

**Comment by remywrevcontrol** [comment]
I need it for the specific block, not the total.

**Comment by dario-hd** [comment]
That's currently not supported. We planned to enhance the block API and we will consider this. In the meanwhile, you could calculate the net value yourself. The block is for a specific rate plan, which has information about the VAT. Beware, that you would need to exclude the rate plan services amount if any.
