### ISSUE TITLE
Modified date in a reservation

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#224]
## Question

Is the "modified" datetime in a reservation set to the "created" datetime when a reservation is created?
Is the "modified" datetime changed in a reservation if something other than the reservation is add/changed/removed (like a charge)?

## Background

I want to use the dateFilter "Modification" for reservations, so that I can asked "give me all reservations were modified/amended since datetime X".

**Comment by pgrm** [comment]
Hello @remywrevcontrol 

no, modified date in reservation is not updated if the folios of the reservation change (charges / payments are added / moved / refunded).

We have webhooks, with which you can subscribe to be notified about folio and reservation changes, as well as new reservations. You could afterwards fetch the data, whenever something changed.

**Comment by remywrevcontrol** [comment]
Webhooks have disadvantages and therefore we do not use them.

**Comment by pgrm** [comment]
I'm sorry to hear that, unfortunately that's the only option to get the latest folio details.

Could you please elaborate what the disadvantages of our webhooks in particular would be?

**Comment by remywrevcontrol** [comment]
To name the general disadvantages: There is no standard in webhooks, so for every PMS we would need to make specific endpoints. With a webhook you are dependent on security, reliability and availability from both sides, not just one side. For example, if we are not receiving messages, is that because there is nothing new or if you are having internal problems. Other example, if we are having downtime due to maintenance, we don't know what we have missed. Just to name a few.

**Comment by pgrm** [comment]
@remywrevcontrol we have set up a flow in which we can guarantee you at least once delivery of webhooks. If you can't process the item, we retry delivering it for 24h. So as long as your downtime lis less than 24h, you should be ok. We are also sending you health check pings every minute. Based on those you would know that our system is up and running.

Regarding security, at the moment we only send you the ID of the affected entity, so there is no possibility to inject wrong data into your system, in case somebody would hijack your security token from our services.
