### ISSUE TITLE
API to obtain invoice data

### ISSUE THREAD

**Issue by VOXEL-COE** [apaleo/api#225]
## Question

We have already activated a testing APALEO account (coe@voxelgroup.net) and we have created several invoices.
Next step, it will be to analyse your API in order to design our connection. I have accessed to https://api.apaleo.com/ but I’m afraid I’m not able to find the API (“function”) to call in order to get invoices data.
Can you provide me some help?

**Comment by swiesener** [comment]
Hi,

In order to get a fast response, pls. use https://github.com/apaleo/api/issues to ask questions or post issues with the API.

There you will directly reach our product team. I’m on the road often and cannot answer timely.

Cheers,

Stephan

**Comment by swiesener** [comment]
On api.apaleo.com go to the section Business APIs and click on apaleo Core. The Swagger online documentation opens and on the upper right dropdown you select Finance V1.

There you find all endpoint to access guest folios.

Best,

Stephan

**Comment by VOXEL-COE** [comment]
Thanks Stephan. I have found it!!
