### ISSUE TITLE
Documentation with the complete API response

### ISSUE THREAD

**Issue by VOXEL-COE** [apaleo/api#226]
## Question
Do you have a documentation containing the complete response of
GET /finance/v1/invoices
GET /finance/v1/invoices/{id}
?

## Background
We are willing to create a connection with your system in order to get invoices information to later send them electronically to final customers.
We have a testing account where we have created several invoices. Nevertheless, we are not able to obtain invoices with all data (ie Company ID, client voucher...).
Having this complete documentation will help us.

**Comment by NadiaStav** [comment]
Our API documentation is stored in **swagger**. You'll find the responses you're looking for in the **finance** module.

![image](https://user-images.githubusercontent.com/34134445/67381047-8f99ee80-f58b-11e9-98b5-4fac66702a3d.png)

`GET /finance/v1/invoices`

![image](https://user-images.githubusercontent.com/34134445/67380792-287c3a00-f58b-11e9-931d-6141131834e2.png)

`GET /finance/v1/invoices/{id}`

![image](https://user-images.githubusercontent.com/34134445/67380939-637e6d80-f58b-11e9-8711-0d2c5fc6c6e9.png)

**Comment by VOXEL-COE** [comment]
Thanks. I have found it: I must click on "Model"
_(Sorry.. it is the first time I use swagger)_
