### ISSUE TITLE
Send a rate for a specific date

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#227]
## Question

If we send a rate for a specific date and rate plan, do we need to send the rate for that with a timeslice? Also, if we are only updating the minLOS restrictions, do we need to send ALL rate data every time?

## Background

We only send rates for a (arrival) date. Since the rate plan already defines the used timeslice check-in check-out time for that rate plan, there should be no reason to send the timeslice each time.
If we have to do that, that would mean that for every rate we send, we need to fetch the rateplan first to get the timeslice. That would mean extra (unnecessary IMHO) calls to the Apaleo API.

**Comment by bennetone** [comment]
Dear @remywrevcontrol 

we also offer an PATCH API for the rates. This would allow you to only change the prices or restrictions you want to adjust.

Here is a [related ticket ](https://github.com/apaleo/api/issues/209#issuecomment-532107689)that might answer your question.

Here is the documentation about JSON PATCH: http://jsonpatch.com/

Cheers,
@bennetone

**Comment by remywrevcontrol** [comment]
Thank you for pointing this out. I have a question about the PATCH command. How do I send multiple rates and minLOS changes over a specific period in ONE SINGLE call for a specific rate plan XXX?

For example:
A rate of 110 and minLOS of 3 on 2019-10-24 and a rate of 120 and minLOS of 2 on 2019-10-27. No changes on other (in between) dates.

I would expect to send:
RatePlanId  = XXX
From = 2019-10-24
To = 2019-10-27

Patches are:
['op' => 'replace',
'path' => 'price/amount',
'value' => 110
'from' => '2019-10-24'].

['op' => 'replace',
'path' => 'restrictions/minLengthOfStay',
'value' => 3
'from' => '2019-10-24'].

['op' => 'replace',
'path' => 'price/amount',
'value' => 120
'from' => '2019-10-27'].

['op' => 'replace',
'path' => 'restrictions/minLengthOfStay',
'value' => 2
'from' => '2019-10-27'].

However what happens is that then all the rates from 2019-10-24 up to (including) 2019-10-27 will all be set to 120 and minLOS of 2.

**Comment by bennetone** [comment]
Dear @remywrevcontrol 

the PATCH operations are applied in order and the last one wins. The `from` parameter in the PATCH specification is only used for the copy operation, for all other operations it is not used.

When you are using PATCH rates, then you can do the same changes for all rates within the specified time range for the specified rate plans. By specifying the weekdays you can define the changes should only be done for specific weekdays.

If you want to set different prices and restrictions for different dates the best option is to use the PUT rates API. Here the flow is as described in the guide. Load all rates for a specific rate plan (especially as you should not calculate the from and to for each rate yourself), do your modifications and send the result back. You would have to do this per rate plan:
![image](https://user-images.githubusercontent.com/25197867/67466057-b406d100-f646-11e9-9ba1-6163cc17f788.png)

Please be aware that PUT is an idempotent operation and will overwrite the rates completely with the data you send.

**Comment by bennetone** [comment]
Thank for those details!

As you can easily send modifications for 365 days in one PUT request per rate plan I am sure you will not get to the API limits. For a hotel that has 10 unit groups and 4 public rate plans and all are managed independently from RevControl it would be 40 time GET rates and 40 times PUT rates a couple of times a day. This will definitely not be an issue.

You know that you can send in rates for multiple days in one PUT rates call, right? You need to do it per rate plan.

**Comment by remywrevcontrol** [comment]
Yes I know, but as said, we will not take the risk of overwriting settings that we are not "allowed" to control. So we will be using PATCH only...

**Comment by bennetone** [comment]
Dear @remywrevcontrol 

I would definitely not recommend to use the PATCH for your use case. I don't see which risk you are talking about. If your implementation ensures you are only modifying fields you are controling and leave the rest untouched and you secure this by automated tests, then I really don't see how using PUT could be an issue. Especially if you load the data right before you modify and send it back. I can tell you that other revenue management systems are using the same mechanism.
