### ISSUE TITLE
We need to change redirect_uri

### ISSUE THREAD

**Issue by ikrav4ic** [apaleo/api#229]
## Question
Client Id: HKeeperConnect
New redirect_uri:  pmsintegration.hkeeper.global

**Comment by andreastubbe** [comment]
Hi, `https://pmsintegration.hkeeper.global` ?

**Comment by ikrav4ic** [comment]
Yes
ssl will start work soon
I understand correctly, this url will be as a success page after authorization.
And the connect url https://hkeeper.us/content/apaleo will stay?

**Comment by andreastubbe** [comment]
Done! If it doesn't work, let us know.

**Comment by ikrav4ic** [comment]
Still redirect to https://hkeeper.us/content/apaleo after successful authorization

**Comment by andreastubbe** [comment]
Do you pass the new redirect URL in your call? Then it should work

**Comment by ikrav4ic** [comment]
Sorry
Everything is okay
My mistake :)
