### ISSUE TITLE
OAuth Step 1: Get the user’s authorization

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#23]
## Question

In the page "Connect your app with OAuth 2.0" (https://apaleo.com/connect-your-app-with-oauth-2-0/), step one includes the following sentence:

`To begin the authorization code flow, your app should first send the user to the authorization URL`

However, this URL doesn't seem to contain any information that would specify the account for which authorization is being requested. How can we ensure that we're requesting authorization for a specific account? Since our integration is supposed to initiate the authorization process, how do we even know how to identify a given account at the beginning of the process?

From what I understand, Apaleo customers can enable apps through the store, but it's not very clear to me how the initial part of the process works. If a customer clicks the connect button of our app, how do we know the account to which the user is connected, and how do we make use of this information when requesting authorization?

**Comment by ozonni** [comment]
When you make `Authorize` button on your website, you don't know in advance who is going to click on it. It could be different users from different accounts. Once you got the token after authorization flow , you can call `GET /account/v1/accounts/current` api to get an information about the account that you just got access to.

**Comment by ozonni** [comment]
Additionally after `GET /account/v1/accounts/current` api call, you can make a mapping between your `tenant` code and apaleo `accountCode` along with the token to enable lookup by your `tenant` code.

**Comment by msmeza** [comment]
I see. Let's say that at some point three users belonging to three different accounts click on the button at roughly the same time. I guess we will need to call the authorization URL three times, so that we get the relevant code during each call? How are timing and validity issues handled? Let's say that there's a problem on the second call and on your side it looks as though the code was delivered, but on our side it looks like it wasn't, how can we ensure we get the two remaining codes properly?

**Comment by ozonni** [comment]
Once the user is redirected back to `redirect_uri` after the authorization, you need to make sure that you don't lose the `authorization code` in order to exchange it for the token. If by going to `redirect_uri` the user gets error page, most probably he will retry to open it or start authorization flow again.
