### ISSUE TITLE
How to use dateFilter (including From and To dates)

### ISSUE THREAD

**Issue by VOXEL-COE** [apaleo/api#230]
## Question
I don't understand how to use the parameter dateFilter. Could you help me to get the equivalent sentence to 
https://api.apaleo.com/finance/v1/invoices?creationDateFrom=2019-10-14&creationDateTo=2019-10-23&propertyId=BER
... but using the dateFilter parameter?

Thanks

**Comment by andreastubbe** [comment]
https://github.com/apaleo/announcements/issues/38 has some examples, does this help?

**Comment by VOXEL-COE** [comment]
Yes!! I got it:
https://api.apaleo.com/finance/v1/invoices?dateFilter=lte_2019-10-23%2C%20gte_2019-10-14&propertyId=BER

Thanks andreastubbe
