### ISSUE TITLE
How to get the customer reference ("voucher") of a B2B invoice

### ISSUE THREAD

**Issue by VOXEL-COE** [apaleo/api#231]
## Question
Is there a way to get the reservation "voucher" (the TTOO or TMC reservation ID/customer reference) related to a B2B invoice?

*B2B invoice means an invoice for Expedia, Hotelbeds, Kuoni, etc..

## Background
We are willing to develop a connection to get APALEO invoices in order to send them electronically to their final customers.
Some of these customers are TTOO (Tour operators) or TMCs. Whenever they get a reservation, they get to the hotel their reservation ID (usually called "voucher" or customer reference).
Whenever these customer receive hotel invoices they ask for this ID... that's why it is important for us to get this information.

**Comment by dario-hd** [comment]
I think what you are looking for is the `externalCode`. Beware that some channel managers are using this field to set their own unique id, so, for example, the original Expedia id is lost.

**Comment by VOXEL-COE** [comment]
Hi Dario... where is this externalCode? I don't find it at the invoices APIs.

**Comment by dario-hd** [comment]
You can use the booking API to search for reservations by external code and then you can use the finance API to get invoices by reservation id.

**Comment by VOXEL-COE** [comment]
Hi Dario,
Can you be more specific? 
If a have the "reservationId" related to an invoice... what API call should I do to get the externalCode of this reservationId?

I have just check this API GET /booking/v1/reservations/{id} ... but I don't find it.

**Comment by dario-hd** [comment]
The `GET /booking/v1/reservations` API allows you to find a reservation by `externalCode`. The response of this API will include the id of the reservation:

```
{
  "reservations": [
    {
      "id": "XPGMSXGF-1",
     ...
    }
}
```

Then, you can use the `GET /finance/v1/invoices` API to get invoices for that reservation id.

**Comment by VOXEL-COE** [comment]
Hi Dario,

Now I have found it. Thanks:

  "externalCode": "812864414|369",
  "channelCode": "BookingCom",

Thanks
