### ISSUE TITLE
Connect receiving unauthorized_client

### ISSUE THREAD

**Issue by lxalln** [apaleo/api#234]
I amtrying to connect our app with Apaleo and am following this guide:

https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0

This is the identity url that I am producing:

`https://identity.apaleo.com/connect/authorize?client_id=[clientId]p&redirect_uri=https://dev.[domain]:44392/integrations/apaleo/auth&scope=account.read%20folios.read%20payments.create&state=ec78149c4eac488fb1fde3ad4655da9b`

I get an unhelpful error screen back:
![Screenshot from 2019-11-10 09-37-56](https://user-images.githubusercontent.com/2781908/68541947-d5352480-039d-11ea-9caf-9525028b5544.png)

In previous OAuth integrations that I have done (dozens now), it is quite common that the `redirect_uri` to be setup within the app. Which would be my first guess that https://dev.[domain]:44392 (my local dev url) is not setup, but I am guessing.

In the setup email I had from your rep the scope was suggested at 'admin' rather than the specific scopes that I require, I tried that, same error.

**Comment by randyrod** [comment]
Hi @lxalln,

Thanks for reaching out. From our logs I can see that your guess is correct. It is failing because the `redirect_uri` is invalid.

```
ERROR|Invalid redirect_uri: "https://dev.giftup.app:44392/integrations/apaleo/auth"
```

Randy.

**Comment by lxalln** [comment]
Hi Randy,

Thanks for the quick response. 
What is my best way forward with this?
We have 3 environments, production (which is I am guessing is the `redirect_uri` that you have on file), beta and dev.

Should I be submitting requests for 3 different apps? (That is what I would usually do for other integrations we do).

Who should I be speaking to? We are in contact with Stephan regarding the integration.

Alex

**Comment by ozonni** [comment]
@lxalln could you please provide all the callback urls you would like to have for your client? there is no need to create multiple clients, it can stay just one. Please sent an email to `support@apaleo.com` with the callback urls.
