### ISSUE TITLE
Channel manager questions

### ISSUE THREAD

**Issue by a-rostovskiy** [apaleo/api#235]
## Question

Hey, we are creating a channel manager integration with apaleo and we have a few questions. Could you help us with them?:
- In our system we store availability dates for each unit (in our case, room), but, as we undestand, ARI data from apaleo contains only number of free units on a specific day. Is there any way to get available dates for each unit? Or maybe you know, how other channels solved a similar problem?
- We have a strict list of available services for every unit (like wifi or cleaning service), but in apaleo user can set any service with any name and key. This means that we cannot create mapping for the correct import servicemen of units from apaleo into our service. So how can we automatically determine which service on apaleo is associated with one of services from our system?

Thank you

**Comment by ozonni** [comment]
@a-rostovskiy 
- apaleo has availability per unit group (e.b. `Double`, `Single`). The same way most of the channel work
- There is a [Services` api](https://api.apaleo.com/swagger/) (Rate Plan v1 module) where you can get list of configured services filtered by channel and then do the mapping on your side.

Please check our [Channel Integration Guide](https://blog.apaleo.com/developer/channel-integration-guide) where you can find all necessary information on how to implement channel integration.

**Comment by a-rostovskiy** [comment]
@ozonni, thank you for your answer.

- As I see in the model from [`/booking/v1/reservations`](https://api.apaleo.com/swagger/#!/Reservation/BookingReservationsGet), the reservation also relates to a specific unit. Does this mean that there is a way to get all availability dates (or, alternatively, already reserved dates) for a specific unit? If not, can there be a way to get the maximum date range for a unit group (or units) when at least one unit can be reserved?
- Yes, we have checked this API, and it returns fields with which we could create a mapping, but they all can have any value that the user can specify, and we cannot match these services with a strict list of services from our system. For example, a wifi service may have the code “Wifi”, “WF”, “Wi-Fi” or just “W” and we cannot based on this code, automatically determine that this service is really WiFi. We can only get serviceType, which still does not help us determine what kind of service it is. So based on which field can we create a mapping?

> Please check our Channel Integration Guide where you can find all necessary information on how to implement channel integration.

Yes, we have checked [this guide](https://blog.apaleo.com/developer/channel-integration-guide) and we solved most of the problems thanks to it. But there are still some questions with which we would like to receive your advice.

**Comment by ozonni** [comment]
@a-rostovskiy 
- There is `GET /booking/v1/available-units` api where you can get the list of available units for a specific property and time period. Could you describe what are you trying to achieve?

- Right, services are user-defined and you can't rely on codes or id's. The proper way would be to have configuration UI where people can map services from apaleo to services in your system as a part of configuration process

**Comment by a-rostovskiy** [comment]
@ozonni 

> There is GET /booking/v1/available-units api where you can get the list of available units for a specific property and time period. Could you describe what are you trying to achieve?

In our system for each room, we store intervals of dates at which the booker can reserve a room. For example:
```

{
    "availableDates": [
        {
            "from": "2021-02-16",
            "to": "2021-05-19"
        },
        {
            "from": "2021-06-26",
            "to": "2022-02-19"
        }
    ]
}

```
So, if a room contains these `availableDates` values, then the user can reserve a room only between these dates. And to correct import units and properties into our system, we need to calculate and regularly update the dates available for booking for each unit. For this, we need an endpoint to get availability date ranges, or at least to get date ranges when each unit is already reserved. Is there a similar endpoint in apaleo, or how would you recommend the easiest way to get these dates?

> Right, services are user-defined and you can't rely on codes or id's. The proper way would be to have configuration UI where people can map services from apaleo to services in your system as a part of configuration process. In the end you need to have mapping table: ServiceId from apaleo - ServiceId in your system

That has helped, thank you a lot.

**Comment by ozonni** [comment]
@a-rostovskiy 
usually all channel integrations use [Distribution API ](https://distribution.apaleo.com/swagger/) and there you can create a `Subscription` for availability and rates. Apaleo will push availability, rates and restrictions information to you for each day and also will send any updates right away.

In those ARI notifications you get availability per unit group (e.g. `Double`). As i mentioned, in apaleo availability is unit group based. In the end, you will be able to know how many rooms of a certain group is available for each day.

Does it make sense?

**Comment by a-rostovskiy** [comment]
@ozonni
Yes, we've got it out of [this guide](https://blog.apaleo.com/developer/channel-integration-guide). We could calculate the availability date ranges based on whether there is at least one available unit for every day received from ARI notifications. In other words, if there is a free unit for one day, then there is an available room for booking for that day and thus we could create availability date ranges.

But what if there is a situation when the apaleo user has two rooms, one of which is booked for one month, and the other for the next month. With the implementation above, we will determine that for a unit group that contains these units, we can create a booking for two months, although in fact there will be free two different rooms for two different months.

How else can we use this subscription to avoid this case?

**Comment by ozonni** [comment]
@a-rostovskiy you are right, in this case the person that books a room for 2 month in a row will have to move from one room to another, which is legit case.

**Comment by a-rostovskiy** [comment]
Got it, thanks for your help!
