### ISSUE TITLE
Unexpected character encountered while parsing value: c. Path error while updating Unit info

### ISSUE THREAD

**Issue by ikrav4ic** [apaleo/api#236]
## Question

Hello,
I've tried to update unit information (condition type). As a result, I've got a message
{"messages":[": Unexpected character encountered while parsing value: c. Path '', line 0, position 0."]}
I've tried to run updating both by curl and drupal_http_request. The result is the same.

**Comment by andreastubbe** [comment]
Can you post the request you are sending? The json payload?

**Comment by ikrav4ic** [comment]
`//Drupal version
$result = drupal_http_request('https://api.apaleo.com/inventory/v1/units/BER-NCY', [
    'method' => 'PATCH',
    'headers' => ['Content-Type' => 'application/json-patch+json', 'Authorization' => 'Bearer ' . variable_get('hk_apaleo_access_token')],
    'data' => drupal_http_build_query([
      'condition' => 'Dirty',
    ]),
  ]);

//Curl version
$ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, 'https://api.apaleo.com/inventory/v1/units/BER-NCY');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');

  $headers = array();
  $headers[] = 'Content-Type: application/json';
  $headers[] = 'Authorization: Bearer ' . variable_get('hk_apaleo_access_token');

  $data = [
    'condition' => 'Dirty'
  ];
  curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  curl_exec($ch);
  curl_close($ch);
`

**Comment by andreastubbe** [comment]
Thanks! The reason why this call is failing, is because the data is not in json patch format.

This is the json that you have to pass:
 ```
[{
  "value": 'Dirty',
  "path": '/condition',
  "op": 'replace'
}]
```

http://jsonpatch.com/ has more info, and lots of examples. My favourite page to look up the details on patching.

**Comment by ikrav4ic** [comment]
Now I get a result as 
Replace is not allowed for path condition

**Comment by andreastubbe** [comment]
I think the path is wrong. If you check the model you get when calling `GET /inventory/v1/units/{id}`, you'll see that the `condition` is a field in `status`. Try specifying 
`/status/condition` as the path

**Comment by ikrav4ic** [comment]
Thanks
Everything is working now
