### ISSUE TITLE
Not receiving  reservation updates through the notification service

### ISSUE THREAD

**Issue by sdeblimehome** [apaleo/api#239]
**Expected behavior:** We are using the apaleo notification service which is supposed to update us on any new reservations made

**Actual behavior:** Since Today morning 2 am we are only receiving system notifications and not getting any reservation notifications  

Not sure if something is broken or the service is down.

**Comment by pgrm** [comment]
hello, @sdeblimehome - yes we did have a hick up with the webhook delivery, but it's working since noon again. I can see that you are receiving and acknowledging webhooks from us, so everything seems to be fine on our side.

**Comment by sdeblimehome** [comment]
Thank you for your response @pgrm . Yes it is working fine as of now on our end as well.
