### ISSUE TITLE
BlockUnitsModel purpose

### ISSUE THREAD

**Issue by msmeza** [apaleo/api#24]
## Question

It's not very clear to us what the purpose of `BlockUnitsModel` in `available-unit-groups` is. Would you mind explaining it?

**Comment by ozonni** [comment]
When you request availability breakdown for unit groups, you also get an information about blocked units of the specific unit group.

```
BlockUnitsModel {
    definite (integer): The number of units which are definitely blocked ,
    tentative (integer): The number of units which are tentatively blocked ,
    picked (integer): The number of units which are picked from blocked ,
    remaining (integer): The number of units which are remaining blocked
}
```

**Comment by msmeza** [comment]
Thank you for your reply, @ozonni!

Unfortunately it doesn't look like my question was very clear. What I meant was to ask what the purpose of blocking units is, and how we can find it out programmatically.

**Comment by ozonni** [comment]
Blocks functionality belongs to the Group business. Sometimes you would like to block inventory for upcoming group and when the group arrives to the hotel, you can easily pick up reservations from the specific blocks. Block & Group api could be found under `Apaleo Booking API - not safe for work`.

**Comment by msmeza** [comment]
Thank you!

Can you perhaps describe how this functionality is intended to be in the production API, that currently doesn't have support for groups (at least not in the same way as the NSFW version)?

**Comment by ozonni** [comment]
The Block & Group API is under the development right now and not intended to be used in production. Unfortunately i can't tell you exact date when this API is going to be part of `v1`.

**Comment by msmeza** [comment]
Then perhaps the presence of `BlockUnitsModel` in `availability-unit-groups` in the production API is not intended?

![image](https://user-images.githubusercontent.com/29439179/47087200-ae98ce80-d21b-11e8-876e-6e80108fb549.png)

**Comment by ozonni** [comment]
Good point, please ignore `BlockUnits` part from `availability-unit-groups` api response.
