### ISSUE TITLE
Webhook Subscriptions for multiple properties

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#240]
Hi, 

there is another huge problem.
The problem is following. There is one user. with 3 properties.
When the user subscribes to one hotel, the other hotel get the same subscription, too...

It's not possible to connect 2 properties in our solution to 2 properties at apaleo.

The current subscriptin_id: ae80f248-f9f7-49a3-a7e3-ff95afdd38da
When I connect the other hotel, this susbscription is gone.
I send another endpoint while subsrcibring. Is it not possible anymore?

**Comment by pgrm** [comment]
@c2ofh - I can't really follow you. I don't see any errors in the logs, and I can see your client deleting subscriptions it created before. They don't seem to be disappearing on their own.

**Comment by c2ofh** [comment]
Hi @pgrm 
In our Solution: Mr. Miller got 2 Properties. 
In Apaleo. Mr Miller got 2 Properties. \o/

Now Mr. Miller connects Hotel #1 to Apaleo and chooses the property id of Hotel #1 to subscribe to.
Hotel #1 Subscription ID: abc-def-12345, Endpoint refers to Hotel #1

Then Mr. Miller switch to the other property and want to connect this property also.
Hotel #2 Subscription ID: def-ghi-67890, Endpoint refers to Hotel #2
Hotel #1 Subscription ID: def-ghi-67890, Endpoint refers to Hotel #2

I hope now it's more clear, what the problem is.
The User cannot add a second subscription for another property, the present subscription will be overwritten.

**Comment by pgrm** [comment]
@c2ofh thx for the detailed example, but that doesn't reflect what I can see in the logs. Here is what I can see in the logs (all executed by your client):

POST Subscription for Hotel #1 with Endpoint #1 - ID abc-def-12345
// ... a bunch of GET, where the correct subscription is returned
DELETE subscription abc-def-12345
POST subscription for Hotel #2 with Endpoint #2 - ID def-ghi-67890
// ... a bunch of GET again
DELETE subscription def-ghi-67890
POST subscription for Hotel #1 with Endpoint #1 - ID qwe-rtz-09876
....

For instance, including the timestamps (all in UTC):

- GET 2019-11-22 12:04:58.2783
- GET 2019-11-22 12:04:58.4940
- DELETE 2019-11-22 12:04:58.6428
- POST 2019-11-22 12:04:58.7906

or another one:

- GET 2019-11-22 16:24:18.4578
- GET 2019-11-22 16:24:18.5879
- DELETE 2019-11-22 16:24:18.7390
- POST 2019-11-22 16:24:18.8753

It's almost as if you had implemented to delete whichever subscription exists before creating a new one. Could you please double check the behavior you are describing using swagger UI or postman, to make sure that it isn't an issue on your side?

**Comment by c2ofh** [comment]
Hi @pgrm 

thank you for your support and your provided logs. I was able to find the the problem.
Something little caused the problem. Now it's working like before.
