### ISSUE TITLE
Can I get those reports with the API?

### ISSUE THREAD

**Issue by damienleefr** [apaleo/api#241]
## Question
I need for data integration purpose to retrieve certain reports and I'm wondering whether that can be done with the API:

**1. Production by company/agent**
Need to retrieve it each month for the previous month
Fields:
Company/Agent   ID | Company/Agent Name | Room Nights | Room Revenue | F&B Revenue | Other Revenue

**2. Hotel performance**
Need to retrieve it each month for the previous month
Fields:
out of   order count | number paying guests | complimentary and house use room   nights | room nights | room revenue | inventory | occupancy % | ARR | RevPAR

**3. Production by room type**
Need to retrieve it each month for the previous month
Fields:
room type name/code | room nights | room revenue

**4. Production by nationality**
Need to retrieve it each month for the previous month
Fields:
Nationality   name / code | Room Nights | Room Revenue

**5. On the Book Report**
Need to get it daily, for the next 90 days
Fields:
Date | Rooms Confirmed | Occupancy Confirmed % | Rooms Tentative | Occupancy Tentative % | Rooms Confirmed + Tentative | Occupancy Confirmed + Tentative

**Comment by dmitry-urenev** [comment]
@damienleefr have you already took a look at our  `/reports/v1/reports/property-performance`API? Please check swagger documentation, probably it's exactly what you need! 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/7558366/69800865-5e3dbf80-11d6-11ea-83bd-5e27e8f14b15.png">

**Comment by damienleefr** [comment]
Hi Dimitri,
Yes, I checked it.
One question, does this /reports/v1/reports/property-performance API applies for both past and future periods? 
It matches most of our needs for Hotel Performance report (#2) except:
- Complimentary and House Use Room Nights count
- Total number of guests
However, it doesn't seem to match our needs for the other reports needed.

**Comment by dario-hd** [comment]
Hi,

as you can imagine, it's quite difficult to offer reports that will satisfy all audiences. Currently, what we can offer in terms of reporting is here:

![image](https://user-images.githubusercontent.com/14803089/70042750-b94d2900-15bf-11ea-9593-97a61e0f7f3d.png)

Anyway, our API is flexible enough to allow you to build a custom reporting solution.

If you could share with us more details about the integration you are trying to build we might be able to give you more tips.

**Comment by damienleefr** [comment]
Hi,
Our requirements are straight forward, as explained in the initial message. The purpose is to easily and automatically integrate data from the PMS to generate reports within a third party application.
Hence we need to know how far we can go with the API and for which reports needed will it work.
Alternatively, we will consider pulling standard or custom reports from the PMS based on a schedule or manually for reports that can't be retrieved with the API.

One important question, for report no5 **On the Book Report**, we need to get it daily, for the next 90 days. This one is critical as we need it on a daily basis.
Can that be done with the API? And does this /reports/v1/reports/property-performance API applies for both past and future periods?

Fields required for this report:
Date | Rooms Confirmed | Occupancy Confirmed % | Rooms Tentative | Occupancy Tentative % | Rooms Confirmed + Tentative | Occupancy Confirmed + Tentative

**Comment by dario-hd** [comment]
Hi, the property performance API is for both past and future.
