### ISSUE TITLE
Offers endpoint shows availability for a date that can't be booked?

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#242]
**`Apaleo-Tracking-Id`: (for the request which didn't work as expected)** 

Offers: `0HLRJB9GPE4E9:000004A4`
Rejected booking: `0HLRJV28JSOS6:000002B0`

**Code**

N/A

**Expected behaviour:**

Apaleo either doesn't show availability or does accept the reservation

**Actual behavior:**

Apaleo gives availability then rejects the reservation with:

    The rate restrictions for this rate plan are not considered

You can replicate the issue by going here:

https://ibe-server.uphotel.agency/ibe-preview/18da5eed-0061-4cae-94eb-0ab711ffcf9c

And make a `Munich > Double > Flex` reservation for tomorrow

**Comment by dario-hd** [comment]
Hi @EdwardIII,

from the logs I see that you are trying to create a reservation for the `MUC-FLEX_DBL` rate plan, which is not returned from the offer request.

**Comment by EdwardIII** [comment]
Thanks @dario-hd 

Am I misunderstanding this API response then?

https://gist.github.com/EdwardIII/88cfb28f3ec21284d07ccbf82c26efa6#file-f-json-L61-L66

**Comment by dario-hd** [comment]
Well, the response for the offer tracking id you mentioned, was different. Actually, the two tracking ids you provided are for requests for two different accounts.

**Comment by EdwardIII** [comment]
Maybe I mixed the IDs up?

Would you like to have a call and look at our logs together?

You can also replicate the issue yourself here:

https://ibe-server.uphotel.agency/ibe-preview/18da5eed-0061-4cae-94eb-0ab711ffcf9c

And make a Munich > Double > Flex reservation for tomorrow

**Comment by dario-hd** [comment]
@EdwardIII with the new tracking ids you provided during our call we were able to reproduce and fix the issue. Thanks!
