### ISSUE TITLE
Cancelation Information

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#244]
## Question

The result of `GET booking/v1/reservations/#{reservation_id}` contains information about the cancelation possibilities. I need to get the name and description in the language of the guest.
But the code in cancelationFee cannot be used to request `GET settings/v1/cancellation-policies/#{code}`. What is now the best way to get these information, for example in german, if it's a german guest?

Could you add the `id` to the cancelationFee?

## Background

The booking confirmation mail should be in the language of the guest, if possible.
Therefore it would be great, to get the cancelation information also in the guest language.

**Comment by WinniX** [comment]
Hello @c2ofh 

Thank you for the question.
As for now, we don't return the "Cancellation Policy Id" in a reservation response, just a code. But we plan to add it in the future for better experience.

For now, I can offer you two ways to make it work:
1) Using "Accept-Language" header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
If you pass a desired language in this header, then you will get the reservation details in this certain language.

2) "Cancellation Policy Id" is automatically generated ID, which is actually "{propertyCode}-{cancellationPolicyCode}". For example,
Property code: MUC
Cancellation Policy code: FLEX
Cancellation Policy ID: MUC-FLEX
Then, you can pass this ID to the "GET /settings/v0-nsfw/cancellation-policies/{id}", for example:
GET /settings/v0-nsfw/cancellation-policies/MUC-FLEX
and pass "languages=['all']" or "languages=['de']" as a parameter. 

Let me know if this is what you are looking for.

Kind regards,
Eugene / apaleo Team

**Comment by c2ofh** [comment]
Hey Eugene,

thank you. That was helpful! :)

**Comment by WinniX** [comment]
Hello @c2ofh 

I am happy to tell you that from now we return `Cancellation Policy Id` as a part of reservation(s) response model. Feel free to try it out. 

Eugene / apaleo Team
