### ISSUE TITLE
Add Settings v1 API to scope

### ISSUE THREAD

**Issue by BonkBoy** [apaleo/api#245]
## Question

Hi there, would you be able to add the Settings v1 API to the scope of Up Hotel Agency? I have the Client ID if that helps but am unsure if I should post it here

## Background

Trying to access api.apaleo.com/settings/v1/city-tax but it keeps throwing Request failed with status code 403.

**Comment by pgrm** [comment]
hey @BonkBoy - I've added the new scope to your client. Keep in mind, that you'll need a new refresh token for the existing customers, which means, they'll need to reconnect and approved the additional scope on the consent screen.

Cheers, Peter

**Comment by BonkBoy** [comment]
Sorted, Thanks!
