### ISSUE TITLE
Service offers total gross price seems incorrect 

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#246]
`Apaleo-Tracking-Id`: 0HLRN67HHSOCP:0000007B

**Expected behavior:**

Total gross amount to reflect price for 1 adult and 2 children.

**Actual behavior:**

Seems like the total only reflects price for 1 adult?

**Comment by lukeclifton** [comment]
Any response on this? Thanks

**Comment by DsAekb** [comment]
Hello @lukeclifton ,

We see that you use `&childrenAges[]=6&childrenAges[]` currently apaleo api supports only comma separated format for arrays, please use it as fillowing: `&childrenAges=6,3`

Best regards
