### ISSUE TITLE
Some rates are missing

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#248]
A customer sent a message, that we do not display all rates.
We're using `GET "rateplan/v1/rate-plans?propertyId=HOPR"` and receiving 78 rates.

The customer say, that rates missing which ID's stats with "Bosch_" / "CT_" / "DB_" / "Firma_".
She called them company rates. Is there another request to get all "company rates"?
Does those rates even exist?

**Comment by pgrm** [comment]
Hello again @c2ofh 😄 

when you check https://api.apaleo.com/swagger/#!/Rate/RateplanRate_plansByIdRatesGet you can read

>  To be able to read rates for a corporate rate plan a client must additionally have the 'rateplans.read-corporate' scope.

I guess you are missing that scope? I can add it to your client, but then you have to make sure that you don't show corporate rates unintentionally to somebody else. Please let me know, when you are ready to have the extra scope on your client.

Cheers, Peter

**Comment by c2ofh** [comment]
Hi Peter,

yes today I'm busy for you, sorry.
Oh didn't knew that. Yes this scope is missing then. 

`GET /rateplan/v1/corporate-codes/codes`  would be the right request or?

The Rates are just for the mailing. To filter mails by it's rate. To send another confirmation, when the rate is HOPR-BAR for example.

**Comment by pgrm** [comment]
@c2ofh that's not a problem. I'll add that scope to your client tomorrow. Afterwards, people will need to re-approve your app again, so you get access to that data.

Regarding the endpoints, you shouldn't need to change anything, and simply start getting also corporate rate plans in the same get rate plans request. (I'll double check that tomorrow.)

The other endpoint you mentioned is for the codes for corporate rates. That's only relevant if you'd be creating reservations, so not for you.

**Comment by c2ofh** [comment]
Hey @pgrm 
thank you very much. This would be great, I'll prepare the OAuth today.
I trust you, that it will work after your scope-extension.

**Comment by pgrm** [comment]
@c2ofh it's there, when you re-connect your client to apaleo, you can request that additional scope, should get a new refresh token, and start getting all the rate plans.

**Comment by c2ofh** [comment]
@pgrm Hey Peter,
Me and the customer are very happy 👌
