### ISSUE TITLE
The HTTP resource that matches the request URI 'https://api.apaleo.com/booking/v1/bookings/' with API version '1' does not support HTTP method 'PATCH'

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#249]
We have gotten this error returned from Apaleo API:

HttpRequestError: {"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'https://api.apaleo.com/booking/v1/bookings/' with API version '1' does not support HTTP method 'PATCH'."}}

_**Can you please let us know what this really means?**_

According to Swagger this endpoint exists and is valid for API version 1?

<img width="977" alt="Screen Shot 2019-12-06 at 12 30 55" src="https://user-images.githubusercontent.com/7794283/70323298-55776a00-1824-11ea-8bc6-47ccef93ea2b.png">

**Comment by DsAekb** [comment]
Hello @lukeclifton,

There is no PATCH operation for https://api.apaleo.com/booking/v1/bookings/.
To use PATCH you should use https://api.apaleo.com/booking/v1/bookings/ **{id}**

Best regards

**Comment by lukeclifton** [comment]
Ok. We do pass an `id` but in this instance it must have been undefined. Thanks.
