### ISSUE TITLE
The specified condition was not met for 'Amount'.

### ISSUE THREAD

**Issue by lukeclifton** [apaleo/api#25]
**Expected behavior:**

When trying to cancel a reservation via:
`https://api.apaleo-staging.com/booking/v1/reservation-actions/GKRVBOFV-1/cancel`

We expect successful response

**Actual behavior:**
Instead we get the following response:
```
{
  "messages": [
    "The specified condition was not met for 'Amount'."
  ]
}
```
```
{
  "status": "422",
  "date": "Thu, 18 Oct 2018 10:21:54 GMT",
  "apaleo-tracking-id": "0HLHK2NSRGO68:00000002",
  "server": "nginx",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Location,Apaleo-Tracking-Id,Content-Disposition",
  "content-type": "application/json; charset=utf-8"
}
```

**Comment by ozonni** [comment]
Thank you for the feedback. I've created an issue in our backlog.

**Comment by ozonni** [comment]
The issue is fixed. Thank you again for the feedback.
