### ISSUE TITLE
Requesting invoice files

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#250]
`Apaleo-Tracking-Id`: 0HLRPLM1KU6HN:0000076C
`GET "finance/v1/invoices?reservationId=BJNRXPVF-1"`

I've created an invoice by using `POST finance/v1/invoices`
The Response was the invoice number BJNRXPVF-1-1. 👍 

Then I wanted to download the file and I receiving "204 No Content". But there should be an invoice present.

**Comment by randyrod** [comment]
Hi @c2ofh,

I checked our logs for that specific reservation id, and indeed there is no invoice. The Id that you provided `BJNRXPVF-1-1` is actually a folio id. 

After checking through our logs, based on that reservation, when you do the `POST finance/v1/invoices` you are getting a 422 error. 

The body of the error is: 
```json
{"messages":["To create an invoice, city, postal code and country code of the debitor / invoice recipient need to be set."]}
```
This message means that you must update the guest information and include the required fields.

Please always validate the response from our server.

Regards,
Randy
