### ISSUE TITLE
Service offers tax details

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#251]
Apaleo-Tracking-Id: 0HLRN67HHSOCP:0000007B

## Question

Is it possible to access tax details of service offers?

## Background

When calculating and displaying the total tax to the client on UP IBE we received a request that it may not be correct and we realise that that may be due to the extras tax amount not being returned as part of the response we get from "GET /booking/v1/service-offers" the way there is taxDetails returned from the offers.

**Comment by bennetone** [comment]
Dear @oluyoung,

let's take the following service offer as an example:

```
    {
      "service": {
        "id": "MUC-WLAN",
        "code": "WLAN",
        "name": "High-Speed WLAN",
        "description": "Upgrade the complimentary internet access to a high speed connection.",
        "pricingUnit": "Room",
        "defaultGrossPrice": {
          "amount": 5,
          "currency": "EUR"
        }
      },
      "count": 1,
      "totalAmount": {
        "grossAmount": 20,
        "netAmount": 16.8,
        "vatType": "Normal",
        "currency": "EUR"
      },
      "prePaymentAmount": {
        "amount": 20,
        "currency": "EUR"
      },
      "dates": [
        {
          "serviceDate": "2019-12-10",
          "amount": {
            "grossAmount": 10,
            "netAmount": 8.4,
            "vatType": "Normal",
            "currency": "EUR"
          },
          "isDefaultDate": true
        },
        {
          "serviceDate": "2019-12-11",
          "amount": {
            "grossAmount": 10,
            "netAmount": 8.4,
            "vatType": "Normal",
            "currency": "EUR"
          },
          "isDefaultDate": true
        }
      ]
    }
```

You do get the `totalAmount` which contains the gross and net if you book the service for all the default dates only. As on a service you cannot have mixed VAT there is no need for a `taxDetails` element.

For a regular offer this is different as you could get an offer for a package containing of accomodation for 7 percent and f&B for 19 percent, so a tax breakdown makes sense here.

Cheers,
@bennetone
