### ISSUE TITLE
Extend property performance to also deliver number of adults (and children)

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#252]
Hi,

would it be possible to also deliver the number of adults (and maybe children to have it complete) next to arrivals and departures (per business day) inside the property performance report?

This is a commonly provided standard information in every "PMS report" and several of your customer hotels have already asked for that add-on to be displayed inside our tool.

Thank you very much and best regards,
Tobi

**Comment by dario-hd** [comment]
Hi Tobi,

thank you for your feedback. It makes sense to expose those numbers, and we will consider exposing them in some sort of report in the future.
