### ISSUE TITLE
Correct way to pay invoice without adyen

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#253]
## Question

There are several ways to mark an invoice as paid.
`POST /finance/v1/folio-actions/{folioId}/payments`
`POST /finance/v1/folio-actions/{folioId}/captured-payment`
`PUT /finance/v1/invoice-actions/{id}/pay`

I guess the first 2 endpoints would only work with adyen cause of the pspreference, but is the third Endpoint correct, if a hotel is using concardis as payment provider and we collect the open amount by concardis.

Am I right in assuming that?

## Background

The guest should be able to pay the open amount during check-out.

**Comment by ozonni** [comment]
@c2ofh  `POST /finance/v1/folio-actions/{folioId}/payments` would be the right one. You can also post payments that are not processed by Adyen. Set the appropriate `method`, `amount` and `receipt` (to know where the payment comes from) and you are good to go.

**Comment by c2ofh** [comment]
Thank you ozonni :)
