### ISSUE TITLE
Add payment profile reference

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#254]
## I want

An additional field at payment profiles.
=> reference
It can contain the unique id for the payment instrument from a payment provider.
For example the "Payment Account Reference" from Adyen or "Payment Instrument" from Concardis.

## Use cases

Due to PCI complaints it's not possible to transfer raw creditcard data to apaleo.
But I can add anonymized data, receiving from the payment provider:
![image](https://user-images.githubusercontent.com/10913793/71448748-625eed80-2740-11ea-90e3-d115a98a83e1.png)

With a reference ID a hotel can really use this data. Even the payment provider is not Adyen, but Concardis, FreedomPay, Sixxpay,...

## What I do

When a guest checks-in the creditcard is the guarantee for the hotel.
We want to replace the task that the reception has to check the creditcard. 

So I'm implementing Adyen and Concardis. Some other providers will follow.

Btw. the [mentioned ](https://github.com/apaleo/api/issues/26#issuecomment-431814708) Adyen Web-SDK is outdated. I'm testing the [Adyen Web Components](https://docs.adyen.com/checkout/components-web). Can apaleo handle the response?

```
paymentMethod: {
  type: "scheme",
  encryptedCardNumber: "adyenjs_0_1_25$oknTma8w+JvFXr3+yR...",
  encryptedExpiryMonth: "adyenjs_0_1_25$pnlKbQrI1zo6NL9YrQV...",
  encryptedExpiryYear: "adyenjs_0_1_25$GDDT9LdV39zHnF7XcD5...",
  encryptedSecurityCode: "adyenjs_0_1_25$Hpu5R23/uJ6Q67SYJ..."
}
```

It would be great to have a guide in or blog for that highly complex process.

**Comment by bennetone** [comment]
Dear @c2ofh 

the best starting point to understand how to tokenize a credit card and store it on a reservation in apaleo is the IBE integration guide section about how to [get the money](https://blog.apaleo.com/developer/ibe-integration-guide#money).

The Web SDK is actually deprecated, you are right. The Drop In technology is just another UI framework based on the same underlying Checkout API.

When you tokenize a card you would make a [POST /payments](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/payments) call with an amount of 0,- EUR.

Be sure to set the following parameter in the request:
```
{
  ...,
  "configuration": {
    "cardHolderName": "REQUIRED"
  },
  "enableOneClick": false,
  "enableRecurring": true,
  "shopperReference": "575b0100-b261-4a36-94cb-eeb49f7c98d3",
  "shopperInteraction": "Ecommerce",
  "recurringProcessingModel": "UnscheduledCardOnFile"
}
```

Use the response from the callback to create the payload for the payment account to apaleo. You could for example set a payment account tokenized with the API call above to the reservation with ID SHJKDLOQ-1 like that:

```
curl -X PATCH --header 'Content-Type: application/json-patch+json' -d '[ \ 
   { \ 
     "value": { \ 
       "accountNumber": "1111", \ 
       "accountHolder": "John Doe", \ 
       "expiryMonth": "10", \ 
       "expiryYear": "2020", \ 
       "paymentMethod": "visa", \ 
       "payerEmail": "s.hopper%40test.com", \ 
       "payerReference": "575b0100-b261-4a36-94cb-eeb49f7c98d3", \ 
       "isVirtual": false        \ 
      }, \ 
     "path": "paymentAccount", \ 
     "op": "replace", \ 
   } \ 
 ]' 'https://api.apaleo.com/booking/v1/reservations/SHJKDLOQ-1'
```

Merry Xmas!

**Comment by c2ofh** [comment]
Hey @bennetone,

merry christmas \o/, thank you. now it's getting more clear. 
Could you add the scope "account.read" to my clients? 
Then I can get the account_id during connection to our system. 
"payments.create" would be also useful cause this will be the next step.

**Comment by bennetone** [comment]
Hey @c2ofh 

I added `account.read` to your clients. Regarding `payments.create` lets wait a little bit as we are going to rework the payments part in the Finance API in the first weeks in January and you would have to adjust your implemntation then to support the new APIs again.

And don't forget that there will soon be the API to generate [payment links](https://docs.adyen.com/checkout/pay-by-link) to send out to guests or make available as buttons in you web app. With this feature you might not need to have the payment form directly embedded in your app anymore.

Cheers,
Benjamin

**Comment by c2ofh** [comment]
Hey @bennetone 
Thank you for adding the scope.
Okay, I will wait for that. Yeah the payment link is a good project, but during that guarantee thing, I felt I'm not so far away to do this also directly in our ui. Was just some thoughts.

**Comment by c2ofh** [comment]
Hey @bennetone I wanted to try this case now in our staging area.
Therefore we're using the same client as in production. It seems that "account.read" is not unlocked.
Am I right?

```
unauthorized_client
Request Id: 0HLRVSO7NNGOM:000000FD
```

**Comment by pgrm** [comment]
@c2ofh - the correct name of the scope is `accounts.read` - seems like @bennetone had a typo there
