### ISSUE TITLE
Culture tax

### ISSUE THREAD

**Issue by marcuskober** [apaleo/api#255]
## Question

Is it possible to use your API to allow customers to add a certificate of exemption from the culture tax while booking a room?

## Background

We are building a website for a hotel based in cologne. The guests are mainly fair visitors, which don't have to pay the culture tax (Kulturförderabgabe). The operators of the hotel are looking for a convenient solution for their customers.

**Comment by nfidirko** [comment]
Hello @marcuskober,

Unfortunately, you can't do that.
There is no possibility to attach any files to a booking.

One of the options is to:
- add a comment to the reservation that one or more guests shouldn't pay the city tax;
- and remove the city tax on check-in by calling the `PUT /booking/v1/reservation-actions/{id}/checkin` with the parameter `withCityTax=false`.

Another option is to have rate plans which are not subject to city tax (the `isSubjectToCityTax` setting of a rate plan).
If a reservation is made for a rate plan which is not subject to city tax, then no city tax added when a reservation is created (you are still able to add it later in check-in).

**Comment by marcuskober** [comment]
Thank you!
