### ISSUE TITLE
Webhook event when a room clean status changes

### ISSUE THREAD

**Issue by eloihdez** [apaleo/api#257]
## I want

A webhook event when a room clean status changes

## Use cases

Notify guests when their room is inspected

## What I do

Polling that results in not being realtime and waste of resources

**Comment by dario-hd** [comment]
Hi @eloihdez,

that's a valid use case. We currently don't publish such events but we added this to our backlog ;)

**Comment by eloihdez** [comment]
Hi Dario, I would really appreciate if there could be an estimate for this, so that I could see if I need to look for another workaround or something. Thank you!

**Comment by dario-hd** [comment]
Good news! We just implemented it and deployed it. You should be able to receive events about units. As of now, we are only publishing the following events for units:
 * created
 * changed
 * deleted

We currently don't publish additional data about the change. It's up to you to fetch the unit via API and check its status. Refer to [this](https://apaleo.dev/guides/start/webhook/configuration) for more info.
