### ISSUE TITLE
Corporate rate plans access for IBE

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#260]
## Question

We seem to be having an issue with accessing offers with corporate codes.

Could you please help provide insight into this.

## Background

According to the docs, offers gotten from `https://api.apaleo.com/booking/v1/offers?corporateCode=CORPCODE`

have a property corporateCode for offers with that corporateCode.

There are two cases with this.

1. It works:

Apaleo tracking ID: 0HLSTODJC7SS9:00000005

```
  "request":{
    "url":"https://api.apaleo.com/booking/v1/offers",
    "params":{
      "propertyId":"MYST",
      "arrival":"2020-02-15",
      "departure":"2020-02-16",
      "adults":1,
      "promoCode":"mystyle01",
      "corporateCode":"mystyle01",
      "language":"en",
      "timeSliceTemplate":"OverNight",
      "channelCode":"Ibe"
    }
  }
```

2. Doesn't work even though we've confirmed rates are available, 
NOTE: When the same corporate code is set as a promo code it returns offers with the rate plan.

Apaleo tracking ID: 0HLSTODJC7UDH:00000006

```
  "request":{
    "url":"https://api.apaleo.com/booking/v1/offers",
    "params":{
      "propertyId":"BIE_HB",
      "arrival":"2020-02-18",
      "departure":"2020-02-23",
      "adults":1,
      "promoCode":"goldbeck02",
      "corporateCode":"goldbeck02",
      "language":"de",
      "timeSliceTemplate":"OverNight",
      "channelCode":"Ibe"
    }
  }
```

**Comment by XTVB** [comment]
Hi,

Thank you for providing this information, we are investigating the requests and will get back to you with a response about what's happening ASAP, thank you for your patience

**Comment by dario-hd** [comment]
Hi,

you can get unavailable offers by setting the `includeUnavailable` parameter to `true` to your request. If you do it, you will see that you will have some `validationMessages` for that offer:

![image](https://user-images.githubusercontent.com/14803089/72827930-f78bce00-3c7b-11ea-9acd-ff85a6c9194d.png)

That means that you have some restrictions on your rates, specifically you have max. length of stay restrictions of 6 days, but you are trying to get an offer for more than 6 days.

I hope this helps.

**Comment by oluyoung** [comment]
Hi,

I hope you don't mind a little back and forth.

But here's what i've found so far, the cases below happen when a ratePlan has both a promoCode and a corporateCode attached to it.

#### FINDINGS:

When promoCode and corporateCode are passed to `booking/v1/offers`

#### CASE 1:
Rate has SAME promo code `(MYCORP1)` and corporate code `(MYCORP1)` attached to it
###### RESPONSE:
Corporate code takes priority, so only passing promoCode param won’t work.

```
{
  "url":"https://api.apaleo.com/booking/v1/offers",
  "response":{
    "headers":{
      "date":"Wed, 22 Jan 2020 13:26:40 GMT",
      "apaleo-tracking-id":"0HLSV51P1VNJJ:00000095"
    }
  },
  "request":{
    "params":{
      "propertyId":"MYST",
      "arrival":"2020-02-18",
      "departure":"2020-02-20",
      "adults":1,
      "promoCode":"MYCORP1",
      "corporateCode":"MYCORP1",
      "language":"en",
      "timeSliceTemplate":"OverNight",
      "channelCode":"Ibe",
      "includeUnavailable": true
    }
  }
}
```

#### CASE 2: 
Rate has one promo code `(PROMO1)` that is DIFFERENT from corporate code `(MYCORP2)` attached to it.
###### RESPONSE:
It doesn’t get returned in offers even if `corporateCode: MYCORP2` is passed as a param.

```
{
  "url":"https://api.apaleo.com/booking/v1/offers",
  "response":{
    "headers":{
      "date":"Wed, 22 Jan 2020 13:25:42 GMT",
      "apaleo-tracking-id":"0HLSV51P1VNK9:000000F9"
    }
  },
  "request":{
    "params":{
      "propertyId":"MYST",
      "arrival":"2020-02-18",
      "departure":"2020-02-20",
      "adults":1,
      "promoCode":"MYCORP2",
      "corporateCode":"MYCORP2",
      "language":"en",
      "timeSliceTemplate":"OverNight",
      "channelCode":"Ibe",
      "includeUnavailable": true
    }
  }
}
```

#### CONCLUSION: 
1. I take it that corporate code takes priority over promo codes, so is it  better to pass both promoCode AND corporateCode as params to the `booking/v1/offers`?

2. Might be a bug. This happens even if `includeUnavailable: true` is passed.

**Comment by dario-hd** [comment]
Basically if you have a rate plan which has promo code attached **_AND_** a corporate code attached, then you will able to get the offer for such rate plan only by specifying both promo code and corporate code.

If a rate plan has only a promo code then, in order to get an offer for it, you will need to specify only the promo code.

If a rate plan has only a corporate code then, in order to get an offer for it, you will need to specify only the corporate code.

I hope this helps.
