### ISSUE TITLE
Also support field "source" with channelCode == Expedia

### ISSUE THREAD

**Issue by detcoGbR** [apaleo/api#261]
## I want

Currently the field "source" is only supported with channelCode == ChannelManager.
It would be nice to support them also for channelCode "Expedia", since the expedia-API is used for quite a lot (sub-)brands, which are already in the list of sources in https://api.apaleo.com/booking/v1/types/sources

## Use cases

Currently, we add those bookings with channelCode "ChannelManager", however we like to switch over to using "Expedia".
However, the information in the field "source" would be lost then.

Alternatively, we could also add them into the field "comment", however there is already a bunch of information from the original bookings that end up there.

**Comment by ozonni** [comment]
@detcoGbR we are going to add source for Expedia channel. It is in our backlog. Please subscribe to our 
[announcements ](https://github.com/apaleo/announcements) to get notified when it's done.

For now you can set channel to `Expedia` and leave the source.
