### ISSUE TITLE
Subscribe to 2 topics at the same time

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#262]
## Question

Am I able to subscribe to 2 topics at the same time, with the same url?  
In the documentation there is only the param `topic` and no `topics`

## Background

We want to subscribe to Reservation and Folio webhook - thank you for the debitor-changed extension :)

**Comment by pgrm** [comment]
@c2ofh yes that works, you can check the example value in our swagger:

```json
{
  "endpointUrl": "https://example.com",
  "topics": [
    "Reservation",
    "Folio"
  ],
  "propertyIds": [
    "MUC",
    "BER"
  ]
}
```

could you please let me know which documentation is outdated, so we can fix it? thank you

**Comment by c2ofh** [comment]
Hi @pgram just read [the blog](https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo)  
Thank you for the quick response.
