### ISSUE TITLE
Number of hotel guests per date?

### ISSUE THREAD

**Issue by nibon** [apaleo/api#264]
## Question

How to correctly fetch the number of hotel guests per date? The number should be the number of checked in heads (adults and children).

`[{"date": "2020-01-01", "hotel_guests": 79}, ...]`

## Background

We are currently using performance reports and to my knowledge I can't find this data in the response. Please correct me if I'm wrong. I also read #252 which seems to verify this data is not included.

Are there any other endpoints/scopes that could deliver these numbers indirectly or alternatively is this on the roadmap to be included in the performance report in a near future?

**Comment by ozonni** [comment]
@nibon we don't have a specific api for that but you can always use `GET ​/booking​/v1​/reservations` API to calculate that number.

**Comment by nibon** [comment]
Thank you for your reply. OK, and it sounds like it's not on the roadmap either?

Just to verify the calculation using the endpoint `GET ​/booking​/v1​/reservations`. To fetch all reservations during period between A and B, I use parameters `dateFilter=stay, from=A, to=B`.
To calculate the numbers it seems I should sum `adults * length(childrenAges)`. Is this number correctly showing **all guests** or should I use the `additionalGuests` field?

**Comment by ozonni** [comment]
@nibon we don't have it in our roadmap. Your approach is correct. `additionalGuests` doesn't represent number of people, but just contains the information about additional guests. So you don't need to count them.
