### ISSUE TITLE
Requesting data for 1 day from Reports v1

### ISSUE THREAD

**Issue by 23RoMax** [apaleo/api#265]
## Question

When requesting on v1 Reports (https://api.apaleo.com/swagger/index.html?urls.primaryName=Reports%20V1) for ordered services and setting from same as to in order to fetch data for a specific day only, the API returns a 422 with To must be greater than From.
How to fetch one day?

## Background

Example Request:

curl "https://api.apaleo.com/reports/v1/reports/ordered-services?propertyId=XYZ^&serviceIds=XYZ-112^&from=2020-02-01^&to=2020-02-01" -H "authority: api.apaleo.com" -H "accept: application/json, text/plain, */*" -H "authorization: AUTHTOKEN" -H "origin: http://192.168.1.27:8081"

**Comment by nfidirko** [comment]
Hello @23RoMax,

If you want to fetch ordered services report for 1 day only, you should add 1 day to the "to" parameter, like:
```
from=2020-02-01
to=2020-02-02 // +1 day
```
So, the "To" parameter is "The exclusive end date of the interval", as stated in the documentation.
It's also the default behavior for almost all the endpoints we have.

**Comment by 23RoMax** [comment]
Thank you!
Somehow I have overlooked the inclusive exclusive part which explains a lot!
