### ISSUE TITLE
Corporate Rates not being received

### ISSUE THREAD

**Issue by BonkBoy** [apaleo/api#266]
## Question

Hi, we've recently tried to set up a corporate rate on one of our IBEs and it doesn't seem to be returning when we make a call to `https://api.apaleo.com/booking/v1/offers`

## Background

This is the corp code in question:
![amvcorpcode](https://user-images.githubusercontent.com/25844054/73741098-77686c80-4741-11ea-92d3-ce8b0902ad40.png)

When we make the request, we only get back standard offers that have nothing to do with the corp code in question and the call to rate-plans is empty.

apaleo-tracking-id: 0HLT8I345C94C:0000013C
request: 
`"url":"https://api.apaleo.com/booking/v1/offers",
"params":
{
  "propertyId":"HIT",
  "arrival":"2020-02-10",
  "departure":"2020-02-12",
  "adults":1,
  "promoCode":"AMVI1",
  "corporateCode":"AMVI1",
  "language":"en",
  "timeSliceTemplate":"OverNight",
  "channelCode":"Ibe"
}`

apaleo-tracking-id: 0HLT8I345C95J:00000126
request:
`"url":"https://api.apaleo.com/rateplan/v1/rate-plans",
"params":
{
  "propertyId":"HIT",
  "channelCodes":"Ibe",
  "promoCodes":"AMVI1"
}`

When making this request with any combination of the promo code and corp code (i.e. just promoCode is set to AMVI1, or just corporateCode is set to AMVI1, or what is seen above), this is the response:

`response:
{
  "url":"https://api.apaleo.com/rateplan/v1/rate-plans",
  "status":204,
  "headers":
  {
    "date":"Tue, 04 Feb 2020 09:51:30 GMT",
    "connection":"close",
    "server":"nginx",
    "apaleo-tracking-id":"0HLT8I345C95J:00000126"
  },
  "data":""
}`

We also used the corp codes assigned to each rate to try and search for the corporate rates. 

Would you be able to show us the promo and corp codes on these rates:
AMVI1-CORPORATE2_STD
AMVI1-CORPORATE2_SUP
AMVI1-CORPORATE2_DLX

on this property:
HIT (Hausimtal)

**Comment by ozonni** [comment]
@BonkBoy you need to specify corporate code when calling Offers api (e.g. `AMVI1-CORPORATE2_D`). You were setting company code instead, which is not correct.

**Comment by BonkBoy** [comment]
@ozonni Sorted, thanks!
