### ISSUE TITLE
Automatic room / unit assignment

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#269]
Question:

How to auto-assign units to bookings that come in from IBEs or OTAs, assigned to a unit type? There is the auto-check in function but does it take care of unit auto-assignment, and is there a way to determine the order in which the units of a unit group get assigned?

Background:

We use automated locks with key codes that get sent to the guest only if the booking has a unit assigned. Rather than someone assigning the units manually a bot should do this, but preferably so that we can determine a "priority order" in which the bot should assign units from the available ones in the unit group.

**Comment by WinniX** [comment]
Hello @tmmartti 

First of all, I'd suggest looking into our [Reservation events](https://apaleo.dev/guides/start/webhook/configuration#events) (if you haven't done it yet).
These events allows you to take the full control on incoming reservations. 
Secondly, as for auto-assign function - it will randomly pick a unit from the unit group. Currently there is no way to preset the order for the units inside a unit group. 
If you have a custom logic for selecting units from the unit group, we can offer using regular assign unit function. This method receives a `unitId` as a parameter. To get a list of all units created, we have an endpoint `GET /inventory/v1/units`. There is a filter by property and unit group, that can be useful.

Hope this helps!

Eugene / apaleo Team

**Comment by tmmartti** [comment]
Thanks @WinniX!

So the auto-assign function picks a unit at which point? At the check in time?

**Comment by WinniX** [comment]
There is a background job running, which calls auto-assign unit exactly at arrival time and then, if unit was assigned successfully, we call check-in function.

**Comment by tmmartti** [comment]
Ok. Arrival time = the default check in time in property settings?

**Comment by pgrm** [comment]
@tmmartti that's the default arrival time, if none was explicitly defined, yes.

However, apaleo allows you to specify a specific arrival time, which you could get from the reservation's `arrival` field. But yes, for most reservations, this will be set to the default check in time.

**Comment by tmmartti** [comment]
All right. Can I determine a specific arrival time for all future bookings at once or does it need to be done per booking?

**Comment by pgrm** [comment]
@tmmartti the field `arrival` is also returned when you are getting the reservation list - so you can get a list of all reservations for the next week, for instance, and then you'll know the exact arrival time for each of them.

**Comment by tmmartti** [comment]
I suppose this one is gonna be a "no" but I'm still confirming: Can one change some setting so that arrival time gets defined as something else than the default for all future bookings?

**Comment by pgrm** [comment]
@tmmartti you cannot change the default arrival time to be something else than the check-in time, but you can define a new time slice definition with a different check in time. However, you can't change the time slice definition used for a given rate plan, so you'd need to create new rate plans to use these.

Also, keep in mind that we use arrival / departure times to calculate availability. So if your default check-out time currently is at 11:00 am, the check-in time of your new time slice definition must be after 11:00 am - so they wouldn't overlap

**Comment by tmmartti** [comment]
All right, so it is possible but with requires recreation of all rate plans (right? There is no way to update the default check in time? Again, I'm just confirming here, partially because there is some bit of work in remaking the rate plans.)

**Comment by pgrm** [comment]
no, there is no other way - it's bound to the timeslice definitions, and once a rate plan is created those can't be modified anymore.

**Comment by tmmartti** [comment]
Ok. But thanks for the replies!
