### ISSUE TITLE
401 error when updating guest

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#27]
I want to update guest data. It worked several weeks before without errors.
Now I get 401 Forbidden. 

**URL**: booking/v1/reservations/:reservation_id
**Method**: Patch
**Payload**: 
```ruby
[{:value=>
   {:title=>"Mr",
    :firstName=>"Firstname",
    :lastName=>"LastName",
    :email=>"name@gmail.com",
    :phone=>"01234567",
    :address=>{:addressLine1=>"Street 41", 
               :postalCode=>"123456", 
               :city=>"Cityname",
               :countryCode=>"DE"},
    :nationalityCountryCode=>"DE",
    :birthDate=>"1970-01-01"},
  :path=>"primaryGuest",
  :op=>"replace"}]
```

_The payload was anonymized for this issue._

The Bearer token is valid and expires in 45 minutes. Other requests are working fine.

**Comment by c2ofh** [comment]
@aprooks Mail was sent.

**Comment by aprooks** [comment]
Hi, I have checked and this client I'd is lacking a scope required for this operation.

I will update Scopes and sent you an update   via email.

**Comment by aprooks** [comment]
@c2ofh 	could you please check if status code returned was 401 or 403?

**Comment by aprooks** [comment]
I will close it for now, as our logs showed these were 403 errors.

If you see a 401 for a token which works on most requests but not others, feel free to submit a new bug report.
