### ISSUE TITLE
TextSearch filter for the endpoint `/booking/v1/bookings` to include emails in its search

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#270]
## I want

The textSearch filter for the endpoint `/booking/v1/bookings` to include emails in its search

## Use cases

We would like to use this to filter the reservations for a guest in our guest management dashboard

## Examples

`/booking/v1/bookings?textSearch=user@mailer.com`

**Comment by dario-hd** [comment]
Hi, thanks for your feedback, we will add it to our backlog.

**Comment by dmitry-urenev** [comment]
@oluyoung this feature was added, enjoy!
