### ISSUE TITLE
New scope request

### ISSUE THREAD

**Issue by asafofer** [apaleo/api#271]
## Question

Hey there,
I'm trying to access the "reservations.manage" and "reservations.assign-unit" scopes in my app.
I tried to get it by passing it to the identity API request (https://identity.apaleo.com/connect/token)

when navigating to the link I get a unauthorized_client error.

How do I add the scope to my account?

Thanks

## Background

my company's name is EasyWay

**Comment by randyrod** [comment]
Hey @asafofer,

It could be that your client does not have the scopes yet. Could you send your clientId and account code if possible to support@apaleo.com.

Thanks,
Randy

**Comment by randyrod** [comment]
Hey @asafofer,

I have added the `reservations.manage`  scope for your client. With this scope you will not need the `reservations.assign-unit` as you will also get access to those endpoints without the `assign-unit` scope.

If you need anything else or have further questions, please let me know.

Regards,
Randy

**Comment by randyrod** [comment]
Hi @asafofer,

Just for the record, I will add the reply I sent to you through the support account.

You must go through the consent screen again, and reauthorise your application with your test account. Then you will get the updated list of scopes.

**Comment by asafofer** [comment]
Hi, I went through the consent screen again and it didn't work

**Comment by randyrod** [comment]
Hey,

We can follow the steps in this guide https://apaleo.dev/guides/start/oath-connection/connect

After reauthorising your app, you should get an authorisation code not an access token, that comes in the second step.

Once you have that authorisation code, you follow step 2 as follows:
```
curl -X POST \
  https://identity.apaleo.com/connect/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&grant_type=authorization_code&code=YOUR_AUTHORIZATION_CODE&redirect_uri=YOUR_URL_ENCODED_REDIRECT_URI'
```
This will exchange that authorisation code for a new access token. That new access token should have the new scopes.

Regards,
Randy

**Comment by asafofer** [comment]
yup, that's exactly what I'm doing, I'm getting an access token, a refresh token, a string representation of the scope, which is still "reservations.read integration:ui-integrations.manage offline_access".

it looks like this:

{
        "access_token" : AN_ACCESS_TOKEN,
        "expires_in" : 3600,
        "token_type" : "Bearer",
        "refresh_token" : A_REFRESH_TOKEN,
        "scope" : "reservations.read integration:ui-integrations.manage offline_access"
}

it means that I still don't have the scope.

I'm using this access token to try to make a PATCH request to /booking/v1/reservations/ and I'm receiving a 403 Forbidden error

**Comment by randyrod** [comment]
Solved via emails.
