### ISSUE TITLE
Do corporate reservations only need a corporateCode attached?

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#272]
## Question

Do corporate reservations only need a corporateCode attached?

## Background

I find when making a request to `/booking/v1/bookings` with a ratePlan attached to a company, I find that if there is no attached companyId but an attached corporateCode, apaleo consequently attaches the company to the reservation automatically.

Is this the desired action?

Because if so according to my previous issue: https://github.com/apaleo/api/issues/267 this doing a check for the companies to get the company Id will not be needed

**Comment by XTVB** [comment]
Hey oluyoung, could you please provide the reservation ID that's produced when you do this so we can investigate.

Regards,
Abdu

**Comment by oluyoung** [comment]
Reservation ID: #UGQHZBSQ-1

```
request:

{ arrival: '2020-02-18',
 departure: '2020-02-19',
 adults: 1,
 childrenAges: [],
 channelCode: 'Ibe',
 primaryGuest:
  { title: 'Mr',
    firstName: 'test',
    middleInitial: undefined,
    lastName: 'TEST',
    email: 'TESTER@MAIL.COM',
    phone: '090810288012',
    address:
     { addressLine1: 'Carnival testing street',
       postalCode: 'test9082',
       city: 'Carnival test City',
       countryCode: 'GB' },
    company: {},
    preferredLanguage: 'en' },
 travelPurpose: undefined,
 timeSlices: [ { ratePlanId: 'BATES-BARSUITE' } ],
 services: [],
 externalCode: '5824ce46-141c-4e17-bdca-496a8a683e74-1',
 companyId: undefined,
 corporateCode: 'CORP4'
}
```

**Comment by oluyoung** [comment]
Hey @XTVB, Is there any update on this issue?

**Comment by nfidirko** [comment]
Hi @oluyoung ,

Yes, when you create a booking, setting only `corporateCode` would be enough. The company will be attached automatically.
 
A more accurate answer to #267 would be: you need to set either `corporateCode` or `companyId ` when you create a booking.

**Comment by oluyoung** [comment]
Thank you @nfidirko.
