### ISSUE TITLE
Wrong Unit Group Information

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#274]
Hi,

Property is "id": "1111111111", "code": "1111111111"
Reservation is "AJBYDCGF-1"

When we request the reservation the unit group differs inside the response.

`"unit": {"id": "1111111111-XNB", "name": "206", "description": "...", "unitGroupId": "1111111111-STX"}`
later in the response
`"unitGroup"=>{"id"=>"1111111111-STS", "code"=>"STS"...}`

The unit got the group "1111111111-ST**X**" and in the unitGroup information I get information for "1111111111-ST**S**"

**Comment by DsAekb** [comment]
Hi @c2ofh ,

It differs because the reservation is created originally for STS UnitGroup, and then later it was assigned the unit 206 from STX Unit group.

**Comment by c2ofh** [comment]
Hi @DsAekb 

thank you, but why does it then still contains the old unit group information?
Is it a bug? Cause I think the information is useless, if it was originally created with another group.

I think it's not good if I have to grab the ID from the unit to get the correct information.
We try to make as few GET requests as possible.

**Comment by dario-hd** [comment]
It is as designed. In this way, you know what was the originally booked unit group and still know what is the currently assigned unit group. You still have the unit group id in the unit so you have access to both values. If your concern is showing the unit group name, you can "cache" the unit groups and just lookup for the name.
