### ISSUE TITLE
Interfacing With RFID door lock

### ISSUE THREAD

**Issue by andreyhutasoit** [apaleo/api#276]
## I want

want to interfacing our lock system with Apaleo PMS. the Guest attendant can create key directly from Apaleo PMS afteer checkin the guest.  

## Use cases

This is to make the system integrate between Apaleo PMS and RFID door lock system. 
to make  A guest key, Duplicate key, Extend key and checkout

## Examples

When GSA do check in they can directly make a key from PMS so no need to create key from RFID door lock system. Also when the guest ask for additional key and extend stay duration.

## What I do

i can give the protocol to meet with our door lock system. It using TCP/IP for connection with specific port. please advise this request thanks

**Comment by pgrm** [comment]
Hello @andreyhutasoit it sounds to me like you are looking for the [apaleo One integrations](https://apaleo.dev/guides/start/apaleo-one/). With that, you can register a new tab in the reservation details screen for the hotel staff to create those keys. The server which will host your integration can be either co-located on site in the hotel, or in the cloud. Depending on the door lock system you need to integrate with. We even have apaleo One integrations which require dedicated hardware to be attached directly to the computer. The server than is installed directly on the computers of the front desk, where that dedicated hardware is available.

To know which room to create the key for, you'll need to access [the API](https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1) with the reservation ID which we provide to you as a query parameter in the iframe URL.

You can have a look at our sample app [oss-traces](https://github.com/apaleo/oss-traces/) which uses apaleo One integrations and apaleo Connect. The source code is licensed under the MIT license so feel free to copy from there any part you see fit to help you.
