### ISSUE TITLE
How to get room revenue by nationality?

### ISSUE THREAD

**Issue by damienleefr** [apaleo/api#277]
## Question

Hello,
I need to get the room revenue figures by nationality for a past period e.g. last month.
I didn't find that under the Report API.

**Comment by dario-hd** [comment]
Hi,

we currently don't have such a report. As you can imagine is not easy for us to provide a flexible way to slice and dice the data. That would be the job of a BI tool. What you can do is use our API to feed the BI tool and then aggregate the data as you like.

**Comment by damienleefr** [comment]
OK, I see.
And to aggregate the data, it should be from teh reservations API I guess?
Is Country  Code the right field? Hence it is the country of residence, not
the nationality?

Best regards
Damien

**Comment by dario-hd** [comment]
Yes, you should use the reservations API. How to aggregate is up to you, we actually have both `nationalityCountryCode` and `countryCode` which is the country of residence.

**Comment by damienleefr** [comment]
OK thanks, all clear.

Best regards
Damien

**Comment by dario-hd** [comment]
Happy to help ;)
