### ISSUE TITLE
A few model additions to prevent additional api requests

### ISSUE THREAD

**Issue by LucaDe** [apaleo/api#279]
## I want
In order to reduce the amount of api calls that we need, it would be great to have the following model changes / additions:

- ReservationItemModel / ReservationModel: BookingModel.bookerComment
   - often contains valuable ota information
- EmbeddedRatePlanModel: RatePlanModel.includedServices
   - needed in our reservation processing 
- FolioItemModel: FolioModel.charges, FolioModel. allowances, FolioModel. payments
   - needed for data export pipelines

Let me know what you think :)

**Comment by ozonni** [comment]
@LucaDe 
- Good suggestion and we are going to put it to our backlog
- `Embedded` models are meant to be simple (id, code, name) and adding included services info there would be to much
- You can already get charges but specifying (expand=charges). allowances and payments are coming soon

**Comment by LucaDe** [comment]
Hey Vasily, I know giving estimates is always hard, but is there a rough eta for the bookerComment, allowance/payment additions (days, weeks, months)?
 Esp. the the bookerComment is really harming us and forces us to do a lot more api requests

Thanks :)
