### ISSUE TITLE
Check-in 422 Response

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#28]
We want to check-in a guest.
The guest is still confirmed. Check-in day is today and a room was assigned.

**Code**
PUT-Request "booking/v1/reservation-actions/UQZPKOME-1/checkin"

**Expected behavior:**

The guest will be checked-in

**Actual behavior:**

API Response: 422 Unprocessable Entity

**Comment by andreastubbe** [comment]
Can you check the body of your response? 422 usually means that some (semantic) validation failed, and we do include the reason in the body. Like, for example,
```
{
  "messages": [
    "Check-In is only possible from the day of arrival to the booked departure time the latest."
  ]
}
```

**Comment by c2ofh** [comment]
The place was still occupied, because a guest was not checked_out 60 days before... 🙄
