### ISSUE TITLE
Couldn't create rateplan 

### ISSUE THREAD

**Issue by kekonen** [apaleo/api#281]
`Apaleo-Tracking-Id`: "|1a6b02b1-446439b0c2776016."
Request executed at 'Mon, 09 Mar 2020 19:20:48 GMT'

**Code**
POST request to /rateplan/v1/rate-plans

**Expected behavior:**
A new rateplan is created and apaleo returns 200 code

**Actual behavior:**
Request throws 500 error

I was making a request to create a rateplan which is quite similar to another rateplan but has different `code` and `name`. When I created that similar rateplan before(several weeks ago) it worked fine, but not any more. Could you, please take a look?

**Comment by XTVB** [comment]
Hi kekonen,

This is a bug that we're aware of and working on, we'll update you when we have it resolved.

Regards,
apaleo support

**Comment by kekonen** [comment]
Found issue in the code
