### ISSUE TITLE
Hotel only wants city tax only on first 21 days of availability

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#282]
## Question

We work with a hybrid hotel chain (apaleo account code `QOYB`). They have a property in Berlin. They say city tax should only apply to the first 21 days of the stay, however with our implementation they see tax for the entire duration even if it's longer than 21 days.

Is there some way we can work out what duration this tax should apply to, or maybe they can tweak something in their configuration?

**Comment by DsAekb** [comment]
Hi @EdwardIII 

Currently, there is no such configuration option to set how long the city tax should be charged.

Possible solutions could be:

1. Completely turn off the city tax option, calculate it manually and post as a direct charge.
2. Turn on city tax for the whole period of stay and do 100% allowance for city tax charges starting from the 22nd day.

**Comment by primehostgmbh** [comment]
Hello "Apaleoneers"
For Basel (and maybe whole Switzerland) we also strongly request the feature to limit the city tax for a certain amount of days (in Basel it is 30 days). The suggested workarounds will work pobably, but the balance for city tax will be difficult to maintain and digital worflows are destroyed. The only proper solution is to enable a limitation of  the city tax  by days.

**Comment by DsAekb** [comment]
Hi @primehostgmbh 

we have put this feature request in our backlog however we cannot tell you exactly when it will be implemented.

**Comment by dario-hd** [comment]
Hi @EdwardIII and @primehostgmbh, I'm happy to tell you that this feature was recently released. You can configure it via API:

```
PATCH https://api.apaleo.com/settings/v1/city-tax/MUC-TAX
[{
    "value": 21,
    "path": "/limit",
    "op": "replace"
}]
```

and/or UI:

![image](https://user-images.githubusercontent.com/14803089/87282927-0fd6fa00-c4f5-11ea-8803-3d0c99397bb2.png)

**Comment by EdwardIII** [comment]
@dario-hd Awesome! I'll get the hotel to set it up and see how it looks.
