### ISSUE TITLE
Subscription not sending webhooks

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#284]
We noticed, that we didn't received any uptdates so far.  
I tested to reconnected to apaleo, but still noch updates via webhook.

Subscription: a93c1e9a-7e9c-4088-afc3-65183de51053

**Comment by pgrm** [comment]
hello @c2ofh we see in our logs that our requests time out, could you check the subscribed service?

**Comment by c2ofh** [comment]
@pgrm Oh, it was really our fault. Sorry for the trouble.
