### ISSUE TITLE
Store a customer identifier with a booking

### ISSUE THREAD

**Issue by adimango** [apaleo/api#287]
## Question

Creating a booking using the API, is it possible to send a user/booker id or any custom field?

## Background

We would like to link the reservation to our customers once we receive a Webhook notification.

1. We post a create booking (with a user id)
2. We receive the notification for the booking creation
3. We fetch the booking and we would like to link it to our user id

**Comment by dario-hd** [comment]
Hi, what's the use case? Can't you store this mapping on your side?

**Comment by adimango** [comment]
Hi @dario-hd, we are evaluating a possible software design and the idea was to get the reservation for a service that doesn't send the booking request.

**Example:**
Service A: sends the booking request with the user-id
Service B: receives the the event for booking created
Service B: links the booking to the user-id

Does this help?

**Comment by dario-hd** [comment]
Yeah, we are aware of this need, but we currently don't have a way to store custom data. The topic is anyway under discussion.
