### ISSUE TITLE
Post company issue

### ISSUE THREAD

**Issue by so-dennisp** [apaleo/api#288]
Hi there,

i try to post a company (/rateplan/v1/companies), but get a 500 back everytime:

`{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occured while processing your request.","status":500,"traceId":"|64e7abdf-4ca38ec76ee5e28f."}`

Here is my JSON body:

```
{
   "code": "001",
   "propertyId": "BER",
   "name": "Superoffice GmbH",
   "taxId": "DE811752287",
   "address": {
      "addressLine1": "Martin-Schmeißer-Weg 3b",
      "postalCode": "44227",
      "city": "Dortmund",
      "countryCode": "DE"
   },
   "canCheckOutOnAr": true,
   "ratePlans": []
}
```

I don't see any particular issue there.

Could you please check the traceId?

Thanks!

Best,
Dennis

**Comment by bennetone** [comment]
Hi @so-dennisp 

the problem is the encoding of the special char "ß". This is how it shows up in our logs:

```
