### ISSUE TITLE
WebHooks Maintenances

### ISSUE THREAD

**Issue by Beonprice** [apaleo/api#289]
## Desired requirement
Adding maintenance webhooks to the API. Concretely to be notified about room types status changes
## Use cases
Get daily inventory for every room type. Using the maintenance webhook would be possible in realtime to be notified about room types status changes (for example, a room type with a certain number of out of order/ out of service rooms)

**Comment by bennetone** [comment]
Dear @Beonprice ,

thanks for your input. I agree that webhooks on maintenance status would be great. It is a little bit more complicated than events that are based on actual triggers, as the maintenance status of a unit changes based on the start or end time of a scheduled maintenance block. Still we will consider it in our future plans.

Thanks,
@bennetone
