### ISSUE TITLE
Connect API Issue

### ISSUE THREAD

**Issue by nuno-sousaHZ** [apaleo/api#291]
## Question

Hi,

We're having some issues using your Connect API.

Based on your documentation (https://apaleo.dev/guides/start/oath-connection/connect), we're having issues on the step 2, when we exchange the authorization code for the access token.

We're sending the following parameters : client_id, client_secret, grant_type, code and redirect_uri.

The result we get is a Bad Request with the message "{\"error\":\"invalid_grant\"}"

Can you help us with this?

Thank you in advance.

## Background

My company is HotelAppz

**Comment by bennetone** [comment]
Hi @nuno-sousaHZ!

Could you post your full request here, but masking or cutting out the client secret and the authorization code, please?

Invalid grant usually means you are trying a grant_type that is not configured for the respective API client id. So maybe you are using a client that is configured for the client credentials flow only in the  authorization code flow?

I saw another request in our logs related to the client `HotelAppzConnect`, but here the error message is `nvalid authorization code`.

It feels like you mixed up some API client credentials and authorization codes.

Regards,
@bennetone

**Comment by nuno-sousaHZ** [comment]
Thank you for your message.

Yes sure, consider below the full request :

Endpoint : https://identity.apaleo.com/connect/token

Form Parameters : 
client_id = "HotelAppzConnect"
client_secret = <secret>
grant_type = "authorization_code"
code = <code>
redirect_uri = <redirect_uri>

This issue is happening with any client that uses click & connect option.

**Comment by bennetone** [comment]
I only see `Invalid authorization code` in the logs, but I also see a success response for the same authorization code with the request time of `24/03/202015:35:45.590 +0100`. You can only use the authorization code once to exchange it for an access token and a refresh token. From that point on you should use the refresh token to request a new access token when the old one is expired.

Actually there are libraries out there that do offer the standard OAuth2 flows, maybe it would be an option for you to look into that?

Regards,
Benjamin

**Comment by nuno-sousaHZ** [comment]
Ok, thank you for the information.

That explains the fact that we have another log indicating that we were able to obtain the access token successfully but with yet another error.
This error is as follows: 
IDX10703: Unable to decode the 'header': <received access token> as Base64url encoded string.
IDX10702: Jwt header type specified, must be 'JWT' or 'http://openid.net/specs/jwt/1.0'. Type received: 'at + jwt'.

After this, we don't have any other logs related to this topic.

Thanks,
Nuno

**Comment by bennetone** [comment]
Is your problem then resolved at least regarding help you need from apaleo?

**Comment by nuno-sousaHZ** [comment]
No, not yet.

This was working properly until yesterday.

Can you confirm if something changed on your side regarding the token model which is returned by your connect api's endpoint (/token) ?

**Comment by bennetone** [comment]
Hey @nuno-sousaHZ,

we did not change anything regarding the way tokens are returned and we also didn't receive any issue reports from other apps. I am sorry that I cannot help you further in this regards.
