### ISSUE TITLE
422: The following properties with provided Ids do not exist...

### ISSUE THREAD

**Issue by cozzbie** [apaleo/api#292]
## Question

We have an issue where subscriptions fail with the error `The following properties with provided Ids do not exist: XXXXXX`

The property in question here does indeed exist on our account and the property id matches accordingly. We are not sure why apaleo sends back this error response. Some other properties on the same account work just fine.

Please advise.

**Comment by bennetone** [comment]
Hi @cozzbie,

thanks for reaching out. We are checking the logs and will come back to you with an answer as sson as we know more.

Kind Regards,
@bennetone

**Comment by cozzbie** [comment]
Thank you.

**Comment by bennetone** [comment]
Hi @cozzbie ,

you actually found a bug. We already identified the problem and will release the fix in the course of the day.

Kind Regards,
@bennetone

**Comment by cozzbie** [comment]
Thank you.

**Comment by randyrod** [comment]
Hi @cozzbie,

We have deployed the fix to the issue. Can you test now, and let us know if it works properly for you.

Thank you very much.

Regards,
@randyrod

**Comment by cozzbie** [comment]
Yes indeed. It works. Thanks
