### ISSUE TITLE
Post Booking work in swagger,postman but not with c#

### ISSUE THREAD

**Issue by seabdejelil** [apaleo/api#293]
Dear Apaleo Team,

i try to post a new booking with c# code by i have error response :
422 ( {"messages":["Booker: The Booker field is required.","Reservations: The Reservations field is required."]})
For  the same json file with swagger  and postman it works.

Can you help us with this?

Thank you in advance.

**Comment by dmitry-urenev** [comment]
Hey @seabdejelil most likely you need to check the Content-Type of the data you send
 It's seems it's `text/plain` but it must be `application/json`. Thats why server cannot parse the request body. 

Also please check this link: [Generate code snippets in Postman](https://learning.postman.com/docs/postman/sending-api-requests/generate-code-snippets). Might be helpful.

Let us know if the content-type setting doesn't help!

**Comment by seabdejelil** [comment]
the content-type is set to application/json and ContentEncoding to utf-8
but i receive error response
![Request_headers](https://user-images.githubusercontent.com/62707474/77670514-98ea1580-6f86-11ea-93a4-74c8de3af783.png)

thanks for you response

**Comment by nfidirko** [comment]
Hey @seabdejelil ,
I've checked now our backend sees your request, and it's a little confusing:
```
Content-Type: application/json; charset=utf-8
Host: api.apaleo.com
Content-Length: 110
Body: {"Headers":[{"Key":"Content-Type","Value":["application/json"]},{"Key":"Content-Encoding","Value":["utf-8"]}]}
```
So, the content-type is correct, but in the body, instead of the actual booking object, there is a collection of headers.
That's why I can suggest creating a C# snippet from Postman and trying to make a request using the generated code

**Comment by seabdejelil** [comment]
Hello,
i tried with HttpClient.PostAsync it works but not with PostAsJsonAsync
Thanks

**Comment by pgrm** [comment]
@seabdejelil please also have a look at our open source project https://github.com/apaleo/oss-traces/ there we are automatically generating C# clients via autorest. For instance for the booking API you can have a look at https://github.com/apaleo/oss-traces/tree/master/src/Clients/Traces.ApaleoClients/Booking

**Comment by seabdejelil** [comment]
@pgrm  thank you
