### ISSUE TITLE
Add an email field to the Folio Billing Adress information 

### ISSUE THREAD

**Issue by ruitguerra** [apaleo/api#294]
## I want

An email field added to the Folio/Billing Adress information block.

## Use cases

The email is necessary to record who the Invoice/Folio should be sent to, manually or automatically. 
For business customers this is often not the Guest email or the Booker email. Typically it is the email of the accounting department.
Currently there is no email field in the billing adress.
Our Apaleo clients have reported that since it is not possible to indicate the Folio/Invoice email adress, they have to teporarily modify the Booker or Guest email adress, which is bad practice since it means overwriting their real email.
NOTE: the Billing Email Adress information has to be includedin the API and in the "Guest Data Modified" notifications. 

## Examples

The Apaleo User records the new email in the Folio-Billing Adress block.
He can then use it to manually send the invoice.
Even better, with HotelAppz or a similar system, we can recover this Billing email adress and send the invoice automatically to that email, saving the Hotel time-consuming manual tasks.  

## What I do

At HotelAppz we simplify, automate and personalize all messaging between Apaleo Hotels and Guests all along the Guest Journey,
and 
Centralize all Guest/Customer data to improve Guest Relationship Management and Loyalty.

**Comment by nfidirko** [comment]
Hello @ruitguerra ,

That's actually a good idea.
I've created an issue in our backlog.
It will be a part of the folio debitor, so you'll be able to specify an email for each folio individually.

Btw, you've mentioned the "Guest data modified" event.
Please keep in mind that we are going to remove it: https://github.com/apaleo/announcements/issues/44

**Comment by ruitguerra** [comment]
Hello Nikita.

Thanks for the answer.
No I was not aware that the Guest data modified event was going to change.
Why are you deprecating this?
For HotelAppz as a Guest data management app this is terrible news.
All our clients risk stopping proper operation.

Which other event will replace the Guest Data Modified event?
Olivier, Nuno, can you check this out real quickly please?

April 1 is after tomorrow.

Thanks, Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>




Le lun. 30 mars 2020 à 17:31, Nikita Fidirko <notifications@github.com> a
écrit :

**Comment by nfidirko** [comment]
@ruitguerra ,
basically, we're replacing the `guest-data-modified` with the `changed` event.
So, you would still be able to receive updated when the guest data has changed.
You can find all the details in the issue I've mentioned above.

**Comment by dario-hd** [comment]
Hi @ruitguerra, it would be great if you guys could change your integration to use the new `changed` reservation event and tell us when you are ready. Everything stays the same, just the name of the event changed. For future changes, it would be ideal that you guys subscribe to https://github.com/apaleo/announcements, thanks! 💪

**Comment by ruitguerra** [comment]
Hi Dario.
We do subscribe to Apaleo and had already made the modification (thanks
@Nuno/HotelAppz tech team!). So the problem is solved.
However our roadmap is intense, and API changes/deprecation is stressful
and another thing to watch and put in sprints.
The stability - and backwards compatibility - of the (any!) external API is
an issue, part of the famous "governance" topic in systems integration.
Glad to discuss it with the Apaleo team sometime in the future.
Best, Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
