### ISSUE TITLE
Create an "External App Person/ID field" for Guests, Bookers, Billing contacts and Organisations 

### ISSUE THREAD

**Issue by ruitguerra** [apaleo/api#295]
## I want

An ID field in Apaleo that would allow an external Guest Data Management system (Ex CRM, Loyalty) to be added to any guest, booker, billing contact or company/organization.

## Use cases

This ID would be managed by the external App (ex HotelAppz) which would record it in Apaleo via the API. 
The ID would be shown to the Apaleo user in the "Search Guest/Booker" popup, along with the guest name, allowing the user to copy the "right" profile from the external Guest Data management system when managing a booking.

What do you want to use this for?

- For manually created bookings in Apaleo - The user can select the right user data in Apaleo according to HotelAppz personal profile ID

- For automatically created bookings in Apaleo - New booking and guest data are imported into HotelAppz (or other external App), which performs duplicate detection using its own algorithm. Duplicates can be manually or automatically merged in HotelAppz. Apaleo guest data for the relevant booking can be updated by HotelAppz after the merge. 
The external (HotelAppz) Guest ID stored in Apaleo simplifies verification within Apaleo, of which external  guest profile is linked to the reservation (or which booker profile is linked to the booking).

What shortcomings exist with current approaches?

The booker and guest data are distinct for each booking or reservation. 
There is NO "SHARED" guest data which can be linked to different reservations, so UPDATING the attributes of the guest in one reservation (ex. personal email adress, guest preferences, repeat guest, segment tags) is NOT be reflected in that person's data in another reservation of booking. 

## Examples 

By using HotelAppz and with the HotelAppz guest ID in Apaleo the user can :
- deduplicate new guest data with existing guest profiles (outside Apaleo)
- store the guest history for one Hotel or accross several Hotels (outside Apaleo)
- have a central guest database acting as a single source of truth for personal guest information (outside Apaleo)
- easily use the deduplicated guest profile when creating new bookings (in Apaleo)
- easily use the historical guest data to update incoming bookings (in Apaleo)

## What I do

At HotelAppz we strive to create the best guest profile management application, in order to simplify the work of both front office and marketing staff.
We simplify, automate and personalize all messaging between Apaleo Hotels and Guests all along the Guest Journey and in between stays, improving guest satisfaction and loyalty.

**Comment by WinniX** [comment]
Hello @ruitguerra 

Thank you for the detailed description. 
We are aware of this need and this topic is under discussion. We will make an announcement once this feature is implemented. Stay tuned.

Eugene / apaleo Team

**Comment by shouze** [comment]
@WinniX yes would be great to be able to store that as a correlation identifier.

Main issue here can be that many systems integrated to Apaleo would love to use that so it would be really nice that each system can store its correlation identifier independently, in perfect isolation.

This is probably the main challenge no?

**Comment by ruitguerra** [comment]
Hi Sébastien.
Actually there is a solution: each external app can have its correlation ID.
- Example HotelAppz has its correlation ID
- App XYZ has its correlation ID
Both apps can read the other Apps correlation ID

The real subject is that one one external app can be chosen as "master data
manager" for something like the master guest data, which is what HotelAppz
does  in its guest profiling and marketing platform.
This is what resulted from my talks with Apaleo (Stephan).

Glad to continue the discussion.

Best regards,
Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>




Le jeu. 7 mai 2020 à 09:56, Sébastien HOUZÉ <notifications@github.com> a
écrit :
