### ISSUE TITLE
Add filter options to InventoryPropertiesGet

### ISSUE THREAD

**Issue by LucaDe** [apaleo/api#296]
## I want

more filter options on the InventoryPropertiesGet endpoint. For our use case an array of propertyIds would be sufficient already.

## Use cases

When querying more than one property, we always need to query all of our properties / need to perform multiple single property get requests.

**Comment by pgrm** [comment]
Hello @LucaDe - for now we don't plan on introducing simple "ID" filters on list endpoints. For consistency we'd have to implement it on all endpoints and in many cases it would facilitate bad API usage.

In your case - why do you need to get multiple properties? In most cases partners cache them on their side. You can also subscribe to a webhook to be updated about changes.

In the meanwhile, please feel free to simply query the whole list.
