### ISSUE TITLE
Also pass current language in ApaleoOne-views

### ISSUE THREAD

**Issue by detcoGbR** [apaleo/api#297]
## I want

When using ApaleoOne (as described in https://blog.apaleo.com/developer/ui-integration-guide), it would be nice to also pass the current backend-language to the iframes.
(currently I see the the get-parameters accountCode and subjectId (for AccountMenuApps) and additionally propertyId for PropertyMenuApps, haven't tried the other targets)

This would allow to write multilanguage integrations, reflecting the language of the apaleo-backend. (Currently to do that would require having a separate language-selector in the iframe)

**Comment by pgrm** [comment]
Hello @detcoGbR multi language for apaleo one is something currently under development and should be available in the next 2-3 weeks

**Comment by randyrod** [comment]
Hey @detcoGbR,

We have just added this functionality and have added an announcement with all the notes and information you require here https://github.com/apaleo/announcements/issues/58

You can check our guides to get a more detailed explanation on how translations and languages work by visiting the following links:

- To see how the language is passed to your integration iframe [go here](https://apaleo.dev/guides/start/apaleo-one/client-details#language-and-translations)
- To set up translations for your integration label, [go here](https://apaleo.dev/guides/start/apaleo-one/server-details#set-up-translations)

I hope you can take advantage of this feature, and if you find any issues do not hesitate to contact us.
