### ISSUE TITLE
Can collect city tax on prepayment guarantee reservations

### ISSUE THREAD

**Issue by shouze** [apaleo/api#298]
## I want

That city tax can be automatically collected in case of prepaid reservation.
I imagine that could be done in many ways regarding the current booking api. I suggest 2 possible changes:
1. Allow to put the accomodation+cityTax amount into the reservations.prePaymentAmount. Currently we have an HTTP 422 error explaining we can't charge more than the accomodation amount. This is not BC break but may leads some existing partners to overcharge some guests if their booking implementation is sometimes buggy.
2. Same thing as 1. but also add either a reservations.collectCityTax boolean property or a reservations.cityTaxGuaranteeType string property thus to avoid possible bugs of 1.

## Use cases

We have a very digitalized guest journey (autonomous guests, no/very few staff regarding accommodation).

When our guests use our internet booking engine, we want them to pay everything at booking time. So it's very convenient for us to collect accomodation AND city tax in the same unique transaction at booking time.

Currently we can charge for both accomodation and city tax automatically, but in 2 transactions thus with 2 transaction fees. This is not very interesting in terms of business. We prefer so far to manage refunds edge cases of city tax in case of stay update or cancellation.

## Examples

This would be used for direct bookings as can can delegate city tax collection from some other channels like OTAs.

## What I do

We're working on the launch of a new hotel brand with a pretty nice digital guest journey.

**Comment by dario-hd** [comment]
Hi @shouze, so you just want to be able to prepay the city tax using the `prePaymentAmount` field, right? I guess that's a valid use case, we will add to our backlog, thanks!

**Comment by shouze** [comment]
@dario-hd yes that's it, currently a validation triggers a HTTP 422 error status code because we set an amount greater than just accommodation amount. I've just discussed it one hour ago with Peter :wink:

**Comment by dario-hd** [comment]
Hi @shouze, good news! You should now be able to prepay the city tax as well! Just use `prePaymentAmount = accomodation + cityTax`.

**Comment by shouze** [comment]
@dario-hd still not working as expected at the moment.

Here's the internal tracker id of this issue: **0HLV1AF02JM32:0000021F**

I've checked on both v1 & NSFW api endpoints.
We still have the same error response returned at the moment :sob::
![image](https://user-images.githubusercontent.com/54712/79470149-5b1a6300-8001-11ea-8616-2b5c19223b3d.png)

In this case, 79€ here is the accommodation amount, 6€ is cityTax amount.
On Adyen side we have initiated an Ecommerce unscheduleCardOnFile transaction of flowType CaptureOnly.
![image](https://user-images.githubusercontent.com/54712/79469954-1b537b80-8001-11ea-8b76-6897b1e4952e.png)
<sup>The amount is 85€ `$price->getAmount() line` returns accomodation + city tax amount.</sup>


And on Apaleo's side we've initiated a booking with a reservation of the same amount of 85€, returned by `$rate->formattedTotalToPay()` line in screenshot below:
![image](https://user-images.githubusercontent.com/54712/79470286-8309c680-8001-11ea-953e-39548e802eaa.png)

**Comment by dario-hd** [comment]
Hi @shouze, thanks for checking it and letting us know! We actually found another issue, we will let you know as soon as it's fixed.

**Comment by shouze** [comment]
Hi @dario-hd, any news on this one? :angel:

**Comment by dario-hd** [comment]
Hi @shouze, yes it should be working as expected now. Could you please check it out and let us know?

**Comment by shouze** [comment]
@dario-hd I confirm this is working like a charm now :tada: :pray:
