### ISSUE TITLE
Post bookings with price different from rateplan price

### ISSUE THREAD

**Issue by adimango** [apaleo/api#299]
## Background

We are planning to import from a different PMS a big amount of reservation to Apaleo.
For all the reservations we will create a new reservation calling the below endpoints: 

- create the booking: /booking/v1/bookings
- update the booking: we will update the status for instance for reservation already inHouse and with a room

## Question

Is it possible possible to send the create booking request with an amount that does not match the rate plan for the unit-group?
Can we create a booking without rate plans?

Can you suggest us any way to achieve this importing considering the above context?

**Comment by dario-hd** [comment]
Hi @adimango,

you can override the price per time slice when creating a booking:

```
{
  ...
  "timeSlices": [
    {
      "ratePlanId": "MUC-NONREF-DBL",
      "totalAmount": {
        "amount": "100"
        "currency": "EUR"
      }
    }],
}
```

Unfortunately, you have to specify the rate plan in any case. Please, beware that you can only import reservations in the future.

**Comment by adimango** [comment]
Can I import reservations with an active stay? For instance arrival 20 of March and departure June 2020?
