### ISSUE TITLE
How can I set a room status to dirty?

### ISSUE THREAD

**Issue by ozonni** [apaleo/api#3]
## Question

Could you, please, send me example of usage of `PATCH /inventory/v1/units/{id}` (Change the condition of a unit)? I need to set status condition to Dirty from Clean.

**Comment by andreastubbe** [comment]
For patching a room and set it to dirty to clean, try:

 ```
PATCH https://api.apaleo.io/inventory/v1/units/RCTEST-FWN
[
    {
        "op": "replace",
        "path": "/status/condition",
        "value": "Clean"
    }
]
```

Hope that helps!
