### ISSUE TITLE
403 error on /finance/v1/folios

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#300]
`Apaleo-Tracking-Id`: '0HLUNLRFJ50PK:0000014B'

**Code**
{
  response: {
    url: 'https://api.apaleo.com/finance/v1/folios',
    status: 403,
    headers: {
      'apaleo-tracking-id': '0HLUNLRFJ50PK:0000014B',
    },
    data: ''
  },
  request: {
    url: 'https://api.apaleo.com/finance/v1/folios',
    headers: {
      'Accept-Language': 'en',
      startTime: '2020-04-03T12:27:01.874Z',
    },
    params: {
      reservationIds: 'BWRWBBAA-2',
      propertyIds: 'MUC',
      onlyMain: true
    }
  },
}

**Expected behavior:**
To folios when I request `GET https://api.apaleo.com/finance/v1/folios`

**Actual behavior:**
403 response

I assume it's because we don't have the required scopes, do you mind adding the scopes to our account

- 'folios.read',
- 'folios.manage'

**Comment by XTVB** [comment]
Hi oluyoung,

Those scopes should be added to your client now.

Regards,
Abdu, apaleo support
