### ISSUE TITLE
403 error on /finance/v1/invoice/{id}/pdf

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#301]
`Apaleo-Tracking-Id`: 0HLUQ0HTMOMVA:0000001A

**Code**
```js
{
  response: {
    url: 'https://api.apaleo.com/finance/v1/invoices/<invoiceId>/pdf',
    status: 403,
    headers: {
      date: 'Mon, 06 Apr 2020 10:34:12 GMT',
      'apaleo-tracking-id': '0HLUQ0HTMOMVA:0000001A',
    },
    data: {}
  },
  request: {
    url: 'https://api.apaleo.com/finance/v1/invoices/<invoiceId>/pdf',
  }
}
```

**Expected behavior:**
To get data when I `GET https://api.apaleo.com/finance/v1/invoices/<invoiceId>/pdf`

**Actual behavior:**
403 response

I assume it's because we don't have the required scopes, do you mind adding the scopes to our account

`invoice.read`

**Comment by randyrod** [comment]
Hi @oluyoung,

We've added the scope to your client. Please verify, and let us know if it works properly for you now.

Regards,
@randyrod

**Comment by oluyoung** [comment]
It does work properly, thank you.
