### ISSUE TITLE
GET /finance/v1/folios API doc

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#302]
## Question

According to the docs: https://api.apaleo.com/swagger/index.html?urls.primaryName=Finance%20V1 -> `GET /finance/v1/folios`

1. What do you mean by main folio

2. What do the non-main folios mean/represent?

## Background

We're working on enabling our users to download invoices.

**Comment by bennetone** [comment]
Hey @oluyoung 

The main folio is the one that receives all automatic charges from what is booked on the reservation, also all the extra services. Currently this is always the first folio of a reservation. Any additional folios (non-main) are used to manually split invoices, so the front office can move posted charges from the main folio to another one or directly post manual charges from the bar or similar to this additional folio.

**Comment by oluyoung** [comment]
According to this, is there a way to identify the main invoice from the relatedInvoice's array?
