### ISSUE TITLE
The scope for /booking/v1/bookings/$force is not available in the new connected apps section

### ISSUE THREAD

**Issue by adimango** [apaleo/api#304]
We are not able to assign to our clients the force permission from the new admin UI announced last week.
https://github.com/apaleo/announcements/issues/57

Plus all our clients got a 403 and we were not able to create reservations.
We had to updated all our requests.

`POST https://api.apaleo.com/booking/v1/bookings/$force [403]`

**Comment by pgrm** [comment]
hello @adimango - the `/$force` endpoints were meant as internal endpoints. For apps we are exposing very similar functionality via the [distribution API](https://distribution.apaleo.com/swagger/).

However, if you need them, we could extend it so they'd be available for custom apps, like you are building one.

**Comment by adimango** [comment]
Hi @pgrm ,

thank you for the answer.

it would be great to make it more clear that in the api docs:

![Screenshot 2020-04-21 at 10 17 48](https://user-images.githubusercontent.com/5462772/79842729-81515180-83b9-11ea-8935-8965430b13c8.png)

**Comment by randyrod** [comment]
Hi @adimango,

We have made it possible to assign the `reservations.force-manage` to your clients. You can do it through the connected apps UI. 

Regarding the `reservations.force-create` scope, we have deprecated it, and replaced it with the `reservations.force-manage` one.

If you have further questions, please let us know.
