### ISSUE TITLE
How to create new channel codes & sources

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#306]
## Question

We need to create a new booking.channelCode value and reservation.source. Right now we can't find in the API how to add new values.

## Background

We're importing bookings from another system (PMS) and are looking identify the source of the bookings from the channel code and the the actual channel it was coming from as source.

**Comment by XTVB** [comment]
Hello nziehn,

Could you provide some more information please, which channel sources are you looking to add? We can add them for you on demand.

Regards,
apaleo Support

**Comment by nziehn** [comment]
Hi XTVB,

We're looking to create a channel called "Primeflats"

with the following sources:
Direct
Bookit
NZAA
Laterooms
Airbnb
Flipkey
Guestlink
Expedia
Wimdu
Unknown
Agoda
Travelocity
BookingCom
Tripadvisor
Unknown
Budgetplaces
Tablethotels
Hostelworld
Visitscotland
Holidaylettings
Bedandbreakfast EU
Unknown
Unknown
Homeaway
Bedandbreakfast NL
Atraveo
Feratel
Webrooms NZ
Lastminute
Hotelbeds
Housetrip
Nineflats
Homeaway
Unknown
Trivago
Hostellinginternational
Airbnb
Tomas
Ostrovok
Bookeasy AU
Ctrip
Asiatravel
Tripadvisor
Traveloka
HRS
Google


would that be possible?

**Comment by XTVB** [comment]
Hello nziehn,

Do you intend on using the 'Primeflats' in the hotel? As we don't have a direct integration with Primeflats, and we try to keep channel and sources up to date with only ones that are used right now.
