### ISSUE TITLE
Is it possible to add a source channel from the API?

### ISSUE THREAD

**Issue by adimango** [apaleo/api#308]
## Question

Calling the below I get the sources.

`curl -X GET "https://api.apaleo.com/booking/v1/types/sources" -H "accept: text/plain"`

How can I add a new source?

**Comment by XTVB** [comment]
Hello adimango,

We can add new sources for you on demand. Which channels were you looking to add?

Regards,
Abdu, apaleo Support

**Comment by adimango** [comment]
ok, thank you. 
Someone from my team will contact you.
