### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by alindback** [apaleo/api#31]
## Question

I got a few questions regarding the notification API

1) I can see there are no example of a 200 response on the `HealthCheck` request, why is that? 
(https://notifications.apaleo.com/swagger/index.html#/HealthCheck)

2) Is it safe to assume that when doing a `HealthCheck` request, it will return a 200 if the URL provided does in fact return a valid response, and if so, what is the timeout?

3) Is it possible for Apaleo to cancel a subscription, if it is, what would the reason be? How to know that it has been canceled? a specific respons on the `HealthCheck` request?

4) Is it possible to list all active subscriptions? Or at least retrieve a `subscription Id` if it somehow got lost?

**Comment by aprooks** [comment]
Hi @alindback,

1. It's a swagger misconfiguration, we'll adjust response types.
1. The timeout is 10 seconds for all delivery attempts (health check and events). 
Healthcheck endpoint will return 200 on a successful check, but I will change it 201 on successful ping. 
Also, the Healthcheck endpoint is mainly used by developers for debugging and configuration checks. "Enable subscription" request will check your endpoint with a healthcheck request as well before enabling subscription. 

1. Yes, apaleo can cancel a subscription, but as a last resort for violation of T&C. We will try to contact app developers first if we find an issue with how notifications or any other service is used. 
1. It is not possible yet, but you can use https://notifications.apaleo.com/swagger/index.html#/Subscriptions/V1SubscriptionsByIdDelete endpoint to disable subscription. This way you won't need the id. 

Thank you for reporting this swagger issue.

**Comment by aprooks** [comment]
Healthchecks have topic = "system" and type = "healthcheck" and don't have "data" field

**Comment by alindback** [comment]
Following up on the question 3), what if a hotel decide to leave Apaleo, then I guess you'll have to cancel the subscription?

**Comment by aprooks** [comment]
Yes, in this case, we'll do all the necessary cleanups.

**Comment by alindback** [comment]
Ok, does that include letting us know before the cancellation?
I'm just trying to figure out the different scenarios where we would expect a flow, and what might go wrong. So in this case, if the events / `HealthCheck` events would stop, what actions would be taken.

**Comment by aprooks** [comment]
For now, I would just add an alert to check if healthcheck is not received within first 5 minutes. Hotel signing off is very rare occasion so I would not automate it. 

In any way, we will send an email since it might be hard to debug what happened with tokens on your side.
