### ISSUE TITLE
Get a rate calendar with less API calls?

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#311]
## Background

Hey. We need to show guests a rate calendar that looks something like this:

![image](https://user-images.githubusercontent.com/412107/80951914-ad74c580-8df0-11ea-884d-65402b85f170.png)

To do that we need:

* Prices by day
* For the cheapest rates
* That are available
* Also info like CTA/CTD/LOS so we don't show them periods they can't book.

At the moment that means we need to query the offers index for every public rateplan. We don't know which ones are available, and which is cheapest, until we've queried them all.

Some hotels have a lot of public rateplans. This means we need to hit the endpoint a lot of times. It works at the moment, but it creates a lot of ratelimit responses, and it's not a superfast user experience like the rest of the journey.

## Question

Have there been any API changes I missed that could make building a rate calendar a bit faster & simpler?

Thanks!

**Comment by dario-hd** [comment]
Hi Edward,

at the moment we don't have other APIs for such use case. But there's an alternative method: using the distribution API you could subscribe to ARI data and get the up to date data. Then, you could store the data on your side and retrieve it fast. You can read more about it here: https://apaleo.dev/guides/business-cases/channel-integration/ari-data.

**Comment by EdwardIII** [comment]
Thanks @dario-hd. This would be quite a big change for us as we don't do this with any data yet, so I'll check it out :)
