### ISSUE TITLE
Booking pushed with Credit Card error response

### ISSUE THREAD

**Issue by seabdejelil** [apaleo/api#312]
I try  to push a booking but i have issue.
Error Response : 
{
  "messages": [
    "'Card Number' is not in the correct format.",
    "'Cvc' is not in the correct format.",
    "'Cvc' must be 24 characters in length. You entered 3 characters."
  ]
}

credit card section in our Json : 

  "creditCard": {
    "cardNumber": "4111111111111111",
    "cvc": "737",
    "cardHolder": "test",
    "expiryMonth": "10",
    "expiryYear": "2021",
    "cardType": "visa",
    "payerEmail": "s@mail.com",
    "isVirtual": true
  }

and i used url : https://secure-distribution.apaleo.com/v1/bookings

Thanks

**Comment by bennetone** [comment]
Dear @seabdejelil 

please refer to the documentation of our [channel integration guide](https://apaleo.dev/guides/business-cases/channel-integration/send-bookings#payment-information).

![image](https://user-images.githubusercontent.com/25197867/80963300-f176c300-8e0e-11ea-879e-34264c53c749.png)

When you are still in implementation and want to work with test credit cards you need to use https://distribution.apaleo.com/ as the base address. https://secure-distribution.apaleo.com/ can only process real credit cards and not test credit cards.

Use this for testing with CVC: 4111 1111 1111 1111 (CVC: 737) - Expiry 10/2020
Use this for testing without CVC: 4111 1111 4555 1142 - Expiry 10/2020

Kind Regards

**Comment by seabdejelil** [comment]
dear @bennetone 
Still have same issue when using https://distribution.apaleo.com/v1/bookings
and credit card infos test 
  "creditCard": {
    "cardNumber": "4111111111111111",
    "cvc": "737",
    "cardHolder": "test",
    "expiryMonth": "10",
    "expiryYear": "2020",
    "cardType": "visa",
    "payerEmail": "s@mail.com",
    "isVirtual": true
  }

same error message : 
{
  "messages": [
    "'Card Number' is not in the correct format.",
    "'Cvc' is not in the correct format.",
    "'Cvc' must be 24 characters in length. You entered 3 characters."
  ]
}

**Comment by seabdejelil** [comment]
Thanks @bennetone  we have an issue in our Json. now it works with your test credit card number.
Can we test with others credit card number?

**Comment by bennetone** [comment]
Hey @seabdejelil,

we see that you are sending the payload with uppercase letters instead of camelCase.

You are sending `CardNumber` instead of `cardNumber`. The card tokenization service we are using seems to be case sensitive. We are checking with the service provider to change that, but in the meantime you should ensure to send all json parameter in the camel case notation.

Regards

**Comment by bennetone** [comment]
> Thanks @bennetone we have an issue in our Json. now it works with your test credit card number.
> Can we test with others credit card number?

We only have those two cards I mentioned before activated for testing. What would you need other credit cards for, it should always behave the same.

**Comment by RenaudThoraval** [comment]
Hello @bennetone ! Thanks for your response ! Just after @seabdejelil question, we have identified 2 issues in our JSON generation : the camelCase and also the null property handling.
We have fixed them and it works perfectly now ! 
Thanks a lot for commitment !
Best regards !
