### ISSUE TITLE
Property Ids in Folio update webhooks as entityId

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#313]
## Question

Hi,
we're in some cases getting a property id as the entity id in the webhook on some folio events. I expected this to be always a reservation/folio id.

## Background

Here is an example:
{"id":"9c5ce1b0-dbe8-4fcb-8d4a-de098b0bcd98","topic":"Folio","type":"balance-changed","accountId":"YPTU","propertyId":"KASSEL","timestamp":1581419523466,"data":{"entityId":"KASSEL"}}

Here a few more ids:
dcd915f7-b4db-4ac5-93e4-265205b925b1
9c5ce1b0-dbe8-4fcb-8d4a-de098b0bcd98
6fe0aca3-4bf6-487b-a8fa-9701910b5e3d
c6d598ae-4ba9-455f-b094-b95185932c27
f1b0d3cc-3934-4df5-bf92-080bddf81db0
7952aba4-efb8-403d-9175-50506e3f5ef6
065487a7-0b9f-4fd9-a209-918c7e5495c4
20157a46-2473-4f87-b397-bcfae97df6d5
a608d82a-4997-427c-9263-2403c127778c
df4fb19f-5807-45ad-91d6-2ce15fdb2bea

**Comment by pgrm** [comment]
@nziehn all those events are unfortunately too far in the past - do you have any more recent event?

A folio ID can look in various ways - try fetching the folio with the ID "KASSEL" - you'll see that it exists

**Comment by nziehn** [comment]
Hmm - I just found that they all seem to be from that date - so I guess what ever it was, it's fixed.
