### ISSUE TITLE
Endtime of day-use bookings

### ISSUE THREAD

**Issue by SimBig** [apaleo/api#315]
## Question

Where is it possible to adjust the start and end time of a day-use reservation. It seems to be fixed to 17:00 endtime.
![Bildschirmfoto 2020-05-04 um 17 48 03](https://user-images.githubusercontent.com/26680884/80985975-35c68b00-8e30-11ea-8859-880d9d23aec8.png)

**Comment by WinniX** [comment]
Hello @SimBig 

`Day use` and `Over night` - are the "Time Slice Definition Template" values and they could have multiple "Time Slice Definitions" attached to them. 
Unfortunately, there is no way to edit the default time for a Time Slice Definition, once you've set up the property. But it's possible to add a new one (if you have enough permissions).
Please go to "Settings" -> "Distribution" in the menu (on Property level), you will see the "Time Slice Definition" tab. Like on the screenshot below:

![image](https://user-images.githubusercontent.com/426392/80988188-6b20a800-8e33-11ea-9130-63d06bf5dc1c.png)

Just add a new record and choose `Day use` as a Template value. After that you need to create a Rate Plan, which will utilize your newly created Time Slice Definition.

Hope this helped.

Best regards,
Eugene / apaleo Team
