### ISSUE TITLE
Problem in Cancel reservation

### ISSUE THREAD

**Issue by seabdejelil** [apaleo/api#318]
Hello,
We have a problem to cancel  reservation. 
Indeed we go through the PCI it works for creation and modification but not for cancel.
Also we can reservation when we send cancel directly without pass through PCI but when we use PCI we can't do the cancel.
Example cancel of reservation  GNUSGSRL-2.

thanks.

**Comment by dario-hd** [comment]
Hi,

I just checked our logs but I couldn't find any cancellation request for that reservation. Anyway, the reservation's status is `InHouse` and you cannot cancel it. Could you be more precise, what exactly didn't work? Are you checking responses?

**Comment by seabdejelil** [comment]
i don't understand status InHouse ?

**Comment by dario-hd** [comment]
The reservation has already been checked in, therefore you cannot cancel it.

**Comment by seabdejelil** [comment]
the problem that we send our request via PCI .
for example we put cancel https://distribution.apaleo.com/v1/reservations/TUUFYEOI-1/cancel
but i we havent any cancellation in your extranet and we haven't any log to check.

**Comment by dario-hd** [comment]
This is a different reservation, but I still cannot find any cancellation requests in our logs. What's the response you get?

**Comment by seabdejelil** [comment]
Empty response but we haven't  response status code

**Comment by dario-hd** [comment]
Oh, I just found one. You are using GET instead, you should use PUT.

![image](https://user-images.githubusercontent.com/14803089/81202454-ee263780-8fc6-11ea-8623-f3043449e9b8.png)

**Comment by seabdejelil** [comment]
no i use put method.
Now i test to put directly and cancel 2 reservations TUUFYEOI-1 and TUUFYEOI-2 and it's ok

**Comment by dario-hd** [comment]
I can now see that you cancelled the reservation via distribution, not directly.

**Comment by seabdejelil** [comment]
so wich url we must use?

**Comment by dario-hd** [comment]
You can use both. What kind of integration are you building?

**Comment by seabdejelil** [comment]
sorry, i didn't understand your question

**Comment by dario-hd** [comment]
The distribution API is a simplified API for a specific kind of integrations: channel managers. Are you integrating a new channel manager? If yes, then use https://distribution.apaleo.com/swagger/. Otherwise use the regular API https://api.apaleo.com/swagger/. You may want to check out our documentation here: https://apaleo.dev/.
