### ISSUE TITLE
Inventory/v1/units retrieve authentication 403 forbidden

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#32]
Dear Apaleo Team,

could you please send me updated scopes for our client id/secret or could you send us new credentials for the inventory/v1 api. 

Thanks, Patrick

**Comment by patrickHermannLimeHouse** [comment]
Yes as of now this would be the only one. Thanks.

**Comment by andreastubbe** [comment]
This is the cleaning-related app, right? Because I just checked, and it already has this scope.

**Comment by patrickHermannLimeHouse** [comment]
No it is the price-app. Could you provide us the scope there?

**Comment by patrickHermannLimeHouse** [comment]
Would you be able to add the units.read scope to our price-app? Thanks, Patrick.

**Comment by aprooks** [comment]
Hi @patrickHermannLimeHouse 

we've added this scope. Please check in five minutes, but be sure tokens are refreshed to get new scope set.

**Comment by patrickHermannLimeHouse** [comment]
@aprooks thx!
