### ISSUE TITLE
Modifying the guest data

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#320]
## Question

How to modify a booking, when we would like to change the guest details. Should we have to cancel the existing reservation and create a new one or can we directly send the changed data with the respective Reservation ID. Could you please provide various scenarios possible in the modifications of Reservations/Bookings. Thank You.

# Background

We have created a booking in apaleo.
BookingId : EBFTDQEZ
Reservation Id : EBFTDQEZ-1

Now we are trying to modify the reservation with the guest Data. Below is the Request and Response.

Request
=========
URL: https://distribution.apaleo.com/v1/bookings/EBFTDQEZ

```
{
    "booker": {
        "firstName": "veerareddy",
        "lastName": "pasam",
        "email": "vpasam.987180@guest.booking.com",
        "address": {
            "addressLine1": "vizag",
            "postalCode": "522413",
            "city": "vizag",
            "countryCode": "IN"
        }
    },
    "channelCode": "ChannelManager",
    "source": "Other",
    "reservations": [
        {
            "arrival": "2020-05-12",
            "departure": "2020-05-13",
            "adults": 2,
            "externalId": "2110681377-1",
            "primaryGuest": {
                "firstName": "veerareddy",
                "lastName": "fdhfdjf",
                "address": {
                    "countryCode": "IN"
                }
            },
            "timeSlices": [
                {
                    "ratePlanId": "BER-NONREF-DBL",
                    "totalAmount": {
                        "amount": 90.19999694824219,
                        "currency": "EUR"
                    }
                }
            ]
        }
    ]
}
```

Response
===========
```
{
  "messages": ["Reservation already exists: ChannelCode: ChannelManager, ExternalCode: 2110681377-1"]
}
```

Is this the right process or otherwise we need to cancel the existing reservation and create a new reservation with the modified data. Please Confirm it.

**Comment by nfidirko** [comment]
Hello @VasaviBoddeti ,

Yes, you can directly send the data using the reservation id;
No, you don't have to cancel the reservation in apaleo.
From your request, it looks like you're using external id instead of the apaleo id when trying to update the data. That's why that reservation is considered new and we're trying to add it, but fail due to the external code uniqueness restriction.

please refer to our guides for more information:
- https://apaleo.dev/guides/business-cases/channel-integration/send-bookings#external-id-your-id-apaleo-id
- https://apaleo.dev/guides/business-cases/channel-integration/modify-bookings

**Comment by VasaviBoddeti** [comment]
Dear Nikita,

Thank you very much for the quick support.

Could you please confirm the field we are supposed to use here:

https://distribution.apaleo.com/v1/bookings/EBFTDQEZ

if EBFTDQEZ, it is Apaleo booking id

or is the "externalId":"2110681377-1"

So, please confirm if we have to use Apaleo reservation id or external Id of Cultuzz.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by nfidirko** [comment]
Hello @VasaviBoddeti ,

`EBFTDQEZ` is the apaleo booking id. It should stay as-is.
`EBFTDQEZ-1` is apaleo reservation id. It should be used in the `id` field of the object inside the `reservations` array.

So, you should just add that reservation id in your request.
