### ISSUE TITLE
inventory received several times with different tokens

### ISSUE THREAD

**Issue by hbarhoumi** [apaleo/api#321]
## Question

I would like to know why do you send the same update message 2 or 3 times with different tokens.
on our side we only keep the last token.
is it possible for you to use only the last token received?

Thank you for your help :-)
**example of log :** 

2020-05-12 12:50:18.4404|IsRequestAuthenticated : False Token: XXXXXXXXXX
2020-05-12 12:50:18.4404|Start proccessing of inventory{
  "accountId": "UXLZ",
  "propertyId": "MUC",
  "timeSlices": [
    {
      "ratePlanId": "MUC-FLEX-SGL",
      "unitGroupId": "MUC-SGL",
      "from": "2020-05-12T08:00:00+00:00",
      "to": "2020-05-13T07:00:00+00:00",
      "restrictions": {
        "minAdvanceBookingPeriod": "P3D",
        "maxAdvanceBookingPeriod": "P180D",
        "minLengthOfStay": 1,
        "maxLengthOfStay": 5,
        "closed": false,
        "closedOnArrival": true,
        "closedOnDeparture": false,
        "changes": [
          "minLengthOfStay",
          "maxLengthOfStay"
        ]
      },
      "prices": [
        {
          "adults": 1,
          "price": {
            "grossAmount": 145.0,
            "beforeTax": 135.51,
            "afterTax": 145.0,
            "taxes": {
              "tax": 9.49,
              "cityTax": 0.0
            },
            "currency": "EUR"
          }
        }
      ]
    }
  ]
} ........

2020-05-12 12:51:08.5092|IsRequestAuthenticated : True Token: YYYYYYYYYY
2020-05-12 12:51:08.5092|inventory update Message {
  "accountId": "UXLZ",
  "propertyId": "MUC",
  "timeSlices": [
    {
      "ratePlanId": "MUC-FLEX-SGL",
      "unitGroupId": "MUC-SGL",
      "from": "2020-05-12T08:00:00+00:00",
      "to": "2020-05-13T07:00:00+00:00",
      "restrictions": {
        "minAdvanceBookingPeriod": "P3D",
        "maxAdvanceBookingPeriod": "P180D",
        "minLengthOfStay": 1,
        "maxLengthOfStay": 5,
        "closed": false,
        "closedOnArrival": true,
        "closedOnDeparture": false,
        "changes": [
          "minLengthOfStay",
          "maxLengthOfStay"
        ]
      },
      "prices": [
        {
          "adults": 1,
          "price": {
            "grossAmount": 145.0,
            "beforeTax": 135.51,
            "afterTax": 145.0,
            "taxes": {
              "tax": 9.49,
              "cityTax": 0.0
            },
            "currency": "EUR"
          }
        }
      ]
    }
  ]
}

**Comment by ozonni** [comment]
@hbarhoumi what do you mean by "tokens"? you need to send HTTP 200 response to the ARI notification otherwise we will keep trying to deliver it to you.

**Comment by ozonni** [comment]
@hbarhoumi ah, you mean auth token which is part of url. As i can see, you have 5 subscriptions configured right now. 

- call `GET ​/v1​/subscriptions` to get all subscriptions you have configured
- call `DELETE ​/v1​/subscriptions​/{id}` to delete the ones you don't need anymore

Once you delete the subscription, we will stop delivering data.

**Comment by hbarhoumi** [comment]
thanks so much @ozonni.
