### ISSUE TITLE
Setting AmountAfterTax

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#322]
## Question

We always accept total amount including all the taxes. So for this, please guide us where can we do this setting/configuration such that the prices are always being sent including all the taxes.

**Comment by ozonni** [comment]
@VasaviBoddeti ARI notifications always have `afterTax` that includes all the taxes in there. Also you get a tax breakdown in `taxes`.

When creating a booking, you can specify `BeforeTaxesWithVat` or `BeforeTaxes` or `AfterTaxes`. Please refer to the guide [https://apaleo.dev/guides/business-cases/channel-integration/send-bookings](https://apaleo.dev/guides/business-cases/channel-integration/send-bookings)
