### ISSUE TITLE
ARI updates in Apaleo interface

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#323]
## Question

We are almost done with the API development. While starting with the certification process, we would like to know where can we change the Availability, Prices and Booking Conditions in https://app.apaleo.com/ for a test hotel, so that we can cross check if the changed update is reflected in the response received from Apaleo. Please advise.

**Comment by ozonni** [comment]
@VasaviBoddeti you can login in [https://app.apaleo.com](https://app.apaleo.com) and change prices for specific days for some rate plans (check this guide: [https://apaleo.zendesk.com/hc/en-us/articles/360010175080-Rate-plans-rates-management](https://apaleo.zendesk.com/hc/en-us/articles/360010175080-Rate-plans-rates-management). For availability you can create reservations and availability should change.
