### ISSUE TITLE
How to detect if a service Per Person is for a child or adult or either?

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#324]
## Question

The pricing unit of services has only two options: Per Person & Per Room, Is there a way when selecting a service per person that it is for just a child or just an adult or either

## Background

In a booking for 1 adult and 1 child:

We have a list of breakfast services where some are just for children and just for adults and either, we would like to differentiate using the response which is for which so we don't end up adding two instances of a service to a booking when it's meant to be one instance just for an adult or a child.

**Comment by ozonni** [comment]
@oluyoung unfortunately there is no way to configure service only for kids. Right now a service is for everyone. We have this in mind but it's not something planned in near future.
