### ISSUE TITLE
Per day/night prices

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#325]
## Question

We would like to send Daily prices per night which are fixed. But when we set the prices here: https://apaleo.zendesk.com/hc/en-us/articles/360010175080-Rate-plans-rates-management
the prices were set per occupancy. How can change these settings from Occupany level/Guest level price settings to per day/per night prices. Please advise.

**Comment by ozonni** [comment]
@VasaviBoddeti you always set prices for single occupancy (for 1 person). If the unit group can accommodate more people, then you can also set surcharges for extra person. You can set it to `0` if you want, then the prices for 1, 2, etc. persons will be the same.

In the ARI notification you get prices for each occupancy and it's up to you which prices to take.

**Comment by VasaviBoddeti** [comment]
Dear Vasily,

Thank you very much for all the clarifications done until now.

Hope you are staying safe and have a great day.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com
