### ISSUE TITLE
AfterTaxes Setting

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#326]
## Question

Please guide us where can we set the Pricing Type to "AfterTaxes"  either in the API or in the Apaleo interface. As we always send Total Amount in "AmountAfterTax" which includes all the taxes.

## Background

I did not find where to set this here: https://apaleo.dev/guides/business-cases/channel-integration/send-bookings

**Comment by ozonni** [comment]
@VasaviBoddeti check the [swagger model](https://distribution.apaleo.com/swagger/index.html) for reservation. It's part of the `CreateReservationModel` model.

![image](https://user-images.githubusercontent.com/25206121/81937013-4f678f80-95f3-11ea-9c04-615298952ce5.png)

**Comment by VasaviBoddeti** [comment]
Dear Vasily,

Thank you very much for your prompt support.

Could you please explain us few of our queries from the below segement:

* What is the prePaymentAmount here and will this be added to the total reservation amount ?

* And why are there two totalAmount values provided, though both the Rateplans are the same

* How and Where can I specify "AfterTaxes" here in the below API, please advise.

===================
"prePaymentAmount": {
        "amount": 70.0,
        "currency": "EUR"
      },
      "timeSlices": [
        {
          "ratePlanId": "MUC-NONREF_DBL",
          "totalAmount": {
            "amount": 120.0,
            "currency": "EUR"
          }
        },
        {
          "ratePlanId": "MUC-NONREF_DBL",
          "totalAmount": {
            "amount": 125.0,
            "currency": "EUR"
          }
        }
      ],
===================

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by ozonni** [comment]
@VasaviBoddeti 
- `prePaymentAmount` is the amount that needs to be pre-paid. If let's say reservation costs 100 eur but only 70 eur has to be prepaid, then apaleo will capture only 70 eur. It doesn't change the value of reservation.

- each time slice has `totalAmount` and this amount represents daily rate. If reservation is for 2 days, then you should set price for each day, if it's the same, just set 2 time the same value.

- `pricingType` is the property on the same lvl as `prePaymentAmount`. Just set to one of the allowed value.

**Please check first swagger model definition, it really explains the whole api model.**
