### ISSUE TITLE
"System" changed booking to no-show

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#327]
## Question

Hi, 
according to the audit logs one of the reservations changed to no-show, we don't know why. Is it possible to find out why?

## Background

Account: YPTU
Reservation: PBLZQFIJ-1

**Comment by dmitry-urenev** [comment]
Hey @nziehn have you used apaleo API directly to request data for reservation change log?
Check this api request: 
`GET https://api.apaleo.com/logs/v0-nsfw/booking/reservation?reservationIds=PBLZQFIJ-1&propertyIds=ANT5&expand=changes`

Payload says:
````
2: {reservationId: "PBLZQFIJ-1", eventType: "SetToNoShow", propertyId: "ANT5",…}
      created: "2020-05-14T04:45:16.899388+02:00"
      eventType: "SetToNoShow"
      propertyId: "ANT5"
      reservationId: "PBLZQFIJ-1"
      subjectId: "BackgroundJob-NightAudit"
````

So it was set to No-Show by the system according to your automation settings during the Night Audit:

![image](https://user-images.githubusercontent.com/7558366/82029818-cd7d7200-9697-11ea-9057-7eb79f866873.png)

You can read more info about these settings here: [Automation: Check-in, check-out and night-audit](https://apaleo.zendesk.com/hc/en-us/articles/360004133972-Automation-Check-in-check-out-and-night-audit)
