### ISSUE TITLE
parent rate plan id of derived rate plan pointing to a non existing base rate plan

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#329]
By requesting the endpoint /rateplan/v1/rate-plans for property _MAL01_ i get a derived rateplan with id = _MAL01-FOURNELLLS1-MA05_ which has the parent rateplan with id _MAL01-FOURNELLSS-MA01_, but i do not get this base rateplan at all.

Maybe a scope issue for corporate rates, but if so, what is the criteria of a rate plan to be corporate?!

It seems as if the derived rateplan **is** a corporate rate plan as it is named _Corporate rate Carverion longstay MAJESTIC starting from 15 nights exclusive breakfast_, but on the other hand i do also not get a _companies_ attribute within the data set. 

Thank you very much.

Best regards,
THA

**Comment by dmitry-urenev** [comment]
Hi @t-haze please take a closer look at the payload for the this request:

`GET https://api.apaleo.com/rateplan/v0-nsfw/rate-plans?propertyId=MAL01&expand=unitGroup,cancellationPolicy,services` 

`MAL01-FOURNELLSS-MA01` rate plan is here:

![image](https://user-images.githubusercontent.com/7558366/82055481-d9c9f500-96c0-11ea-9088-2d3298d78964.png)

To became corporate a rate plan has to be connected to some company. You can read more about this here: [Companies and Corporate Rates](https://apaleo.zendesk.com/hc/en-us/articles/360028323351-Companies-and-Corporate-Rates)

Let us know if you still have this issue.

**Comment by t-haze** [comment]
Hi Dimitry,

thank you very much for your fast response. 
Your screenshot provided the essential hint and it was so obvious! 
We only got 100 values as the pageSize attribute was actively set on our side inside the GET request - do not ask why! 

Alright, now i do get all rate plans including the missing one.
Thank you very much.

Have a nice weekend,
THA
