### ISSUE TITLE
Updates are not sent

### ISSUE THREAD

**Issue by yblondeau** [apaleo/api#330]
`Apaleo-Tracking-Id`:
`Account ID`: `IRVA`

**Code**
We've tried several times to create a subscription by posting the following payload to `https://distribution.apaleo.com/v1/subscriptions`:
```{
  "propertyId": "LND",
  "channelCode": "ChannelManager",
  "endpointUrl": "***EDITED***",
  "ratePlanIds": [
    "LND-NONREF-DBL"
  ],
  "numberOfDays": 730,
  "enabled": true
}
```
Each time we receive a valid and successfull response such as:
```
{
  "id": "EDMG8O3D"
}
```

**Expected behavior:**
We expect to receive updates on price and inventory change on the test property.

**Actual behavior:**
We don't receive any request, even when triggering a full push.

**Related Issues:**

**Comment by abarbarov** [comment]
Hi @yblondeau. Sorry for the delay.
I looked through the logs - we are getting `Error response: 403 Forbidden` in responses. Could you check, if the requests are allowed on your side, please?

**Comment by yblondeau** [comment]
Hi @abarbarov, thanks for your help.
Do you have a complete log of the request that is sent?
We've made some tests on our side and haven't seen such responses.
Could you also tell me from which country the requests are sent to our system?

Thanks in advance,
Yannick

**Comment by abarbarov** [comment]
The full request payload attached
[req.json.zip](https://github.com/apaleo/api/files/4676423/req.json.zip)

You could find the list of outbound IP addresses here: https://apaleo.dev/guides/business-cases/channel-integration/setup (or check, if requests from Ireland are allowed).

**Comment by yblondeau** [comment]
Thank you @abarbarov. Can you give me also the exact URL the payload was posted to?

Thanks,
Yannick

**Comment by abarbarov** [comment]
I wouldn't recommend posting such info to the public:) But you could authorize on https://distribution.apaleo.com/swagger/ and get the configured subscription instead.

**Comment by yblondeau** [comment]
Hi @abarbarov, thanks for your help.
We are now receiving some updates, the irish origin of the requests was the root cause.
We will check if everything is now working as expected.
Have a nice day,
Yannick
