### ISSUE TITLE
GET ​/booking​/v1​/blocks documentation

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#331]
## Question

In the documentation the example of the get blocks has the following part:

      "blockedUnits": 0,
      "pickedReservations": 3,
      "created": "0001-01-01T00:00:00Z",
      "modified": "0001-01-01T00:00:00Z",
      "timeSlices": [
        {
          "from": "2020-05-23T17:00:00+02:00",
          "to": "2020-05-24T11:00:00+02:00",
          "blockedUnits": 2,
          "pickedUnits": 0
        },
        {
          "from": "2020-05-24T17:00:00+02:00",
          "to": "2020-05-25T11:00:00+02:00",
          "blockedUnits": 3,
          "pickedUnits": 0
        }
      ]

I know that blockUnits will be deprecated, but should the blockUnits in this case not have a positive integer (of at least 2)? And if pickedReservations is greater than 0, should the timeSlices have not at least one pickedUnits greater than 0?

**Comment by WinniX** [comment]
Hello @remywrevcontrol 

Thank you for spotting this discrepancy. You are perfectly right here. We will adjust the example.

BR,
Eugene / apaleo Team
