### ISSUE TITLE
blocks timeSlices: baseAmount & totalGrossAmount?

### ISSUE THREAD

**Issue by remywrevcontrol** [apaleo/api#333]
## Question

In the new timeSlices of a block I now also see this:

        ["baseAmount"]=>
        array(4) {
          ["grossAmount"]=>
          float(61)
          ["netAmount"]=>
          float(57.55)
          ["vatType"]=>
          string(11) "VeryReduced"
          ["currency"]=>
          string(3) "EUR"
        }
        ["totalGrossAmount"]=>
        array(2) {
          ["amount"]=>
          float(61)
          ["currency"]=>
          string(3) "EUR"
        }

My question. Is this now always present in every timeSlice of every block? And what is the meaning of baseAmount? Is that the base rate (i.e. exclusive any breakfast, etc.)?

**Comment by WinniX** [comment]
Hello @remywrevcontrol 

You are right, the `baseAmount` and `totalGrossAmount` recently has become a part of a time slice of every block. 
The idea behind `baseAmount` is to provide you with the room rate amount, without any included service.
With `totalGrossAmount` you could basically see the block daily price, which you could see on a block level, but we copy it on a time slice level as well.

Hope this helps.

Eugene / apaleo Team
