### ISSUE TITLE
Some reservations not updating in Apaleo when amended on booking.com

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#335]
## Question

We seem to have a couple of reservations that were amended in Booking.com but the changes did not propagate to Apaleo. We don't know how to investigate this - how would we do this?

## Background

Here are two example booking ids:
GWRJIUDX-1, RJXGRWAV-1

**Comment by dario-hd** [comment]
Hi,

as far as I can see those reservations are already checked out. If the reservations were amended after the check-out, we cannot process the changes.

I hope this helps.
