### ISSUE TITLE
Remove subscription, without subscriptionId

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#336]
## Question

Is it possible, to remove a subscription, without subscriptionId?
It would by nice if we could answer by HTTP 410 (Gone) to cancel a subscription.

## Background

There is maybe an old subscription active, for a hotel which does not exist anymore.
Normally subscriptions will be destroyed when a hotel was removed.

Now there is a subscription I cannot cancel, and we get repeating webhook messages for a reservation.
We could also answer a success, but I think it's also not your wish to have obsolete subscriptions.

Example message:
```
accountId: CPKU
entityId: CEQVIRYE-1
id: 1d31d76a-e4e7-4ce5-9696-90ce47c7d5a0
propertyId: AUGSBURG
timestamp: 1590571024390
```

It feels like spam :)
![image](https://user-images.githubusercontent.com/10913793/83079370-f9c3c600-a07b-11ea-878e-c05a0a3cbf87.png)

**Comment by pgrm** [comment]
Hello @c2ofh 

it's like those emails where the "unsubscribe" button doesn't work 😅 

sorry about that, yeah, 410 sounds like a great idea, I'll put it on our backlog. In the meanwhile, could you send en email to me or the apaleo support to ask us to delete that particular subscription manually? - we'll need to know the URL at least, then we can find it.

**Comment by c2ofh** [comment]
Hi peter,

yes, those spam newsletters for useless products, where it's better not to hit the unsubscribe link.
I've sent you an email with the needed url. Thank you very much.

Maybe there are more persons at apaleo which support the 410 idea.
