### ISSUE TITLE
POST rate plan data format

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#337]
## Question

Hello, posting a rate plan in the test account gives error 422 and says

"Sub-account MUC-DBL could not be found"

## Background

GET requests work. The command that does not:

curl -i -H "Authorization: Bearer %token%" -X POST "https://api.apaleo.com/rateplan/v0-nsfw/rate-plans" -H "accept: text/plain" -H "Content-Type: application/json-patch+json" -d "{ \"code\": \"TEST1\", \"propertyId\": \"MUC\", \"unitGroupId\": \"MUC-DBL\", \"cancellationPolicyId\": \"MUC-FLE\", \"channelCodes\": [ \"Direct\", \"BookingCom\", \"Ibe\" ], \"serviceType\": \"Accommodation\", \"vatType\": \"Reduced\", \"promoCodes\": [ \"APA55100\", \"DISCOUNT20\" ], \"isSubjectToCityTax\": true, \"timeSliceDefinitionId\": \"MUC-NIGHT\", \"name\": { \"de\": \"Das Test1\", \"en\": \"Testi1\" }, \"description\": { \"de\": \"Nicht Stornierbar\", \"en\": \"Non Refundable\" }, \"minGuaranteeType\": \"PM6Hold\", \"bookingPeriods\": [ { \"from\": \"2020-05-21T14:10:02.0955465+02:00\", \"to\": \"2020-06-04T14:10:02.0955465+02:00\" }, { \"from\": \"2020-06-07T14:10:02.0955465+02:00\", \"to\": \"2020-07-27T14:10:02.0955465+02:00\" } ], \"restrictions\": { \"minAdvance\": { \"hours\": 12, \"days\": 1 }, \"maxAdvance\": { \"months\": 24 } }, \"pricingRule\": { \"baseRatePlanId\": \"MUC-NONREF-SGL\", \"type\": \"Absolute\", \"value\": 10 }, \"surcharges\": [ { \"adults\": 2, \"type\": \"Absolute\", \"value\": 10.0 } ], \"ageCategories\": [ { \"id\": \"MUC-BABY\", \"surcharges\": [ { \"adults\": 1, \"value\": 20 } ] } ], \"includedServices\": [ { \"serviceId\": \"MUC-BRKF\", \"grossPrice\": { \"amount\": 10.0, \"currency\": \"EUR\" } } ], \"companies\": [ { \"id\": \"MUC-APA\", \"corporateCode\": \"APA-DBL\" } ], \"subAccountId\": \"MUC-DBL\"}"

Using Windows command prompt. What would be the reason for the error?

Thanks!

**Comment by bennetone** [comment]
Hi @tmmartti 

The validation message already tells you the problem, there is no sub account with the id MUC-DBL avaiable. At the very end of your payload you are sending in `"subAccountId": "MUC-DBL"`

```
{
	"code": "TEST1",
	"propertyId": "MUC",
	"unitGroupId": "MUC-DBL",
	"cancellationPolicyId": "MUC-FLE",
	"channelCodes": ["Direct", "BookingCom", "Ibe"],
	"serviceType": "Accommodation",
	"vatType": "Reduced",
	"promoCodes": ["APA55100", "DISCOUNT20"],
	"isSubjectToCityTax": true,
	"timeSliceDefinitionId": "MUC-NIGHT",
	"name": {
		"de": "Das Test1",
		"en": "Testi1"
	},
        ....,
	"subAccountId": "MUC-DBL"
}
```

You can check the available sub-accounts on the UI here: https://app.apaleo.com/MUC/settings/finance/custom-sub-accounts

Or you call the API GET https://api.apaleo.com/settings/v1/sub-accounts?propertyId=MUC
