### ISSUE TITLE
Create invoice for folio is forbidden

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#338]
## Question

I updated the process to create invoices for folios.
Locally I ran into a 403 Forbidden error without more information, why the request was forbidden.

Could you tell me, If my client does not have the right scope for this action?
I cannot say if ran into this error before my changes. 

**apaleo-tracking-id:** 0HM03R9GKIHD1:00000218

## Background

I want to send create requests, only when there is no invoice for a specific folio.
In the past we received `422 "Invoice already exists for this folio. Cannot create another one."` answers sometimes, so I want to prevent these unneeded requests.

**Comment by bennetone** [comment]
Hi @c2ofh 

you can check your access token to understand which scopes are encoded in there. If you have a token that you created via the apaleo connect flow then you mimght not have orginally authorized your API client with the necessary scopes and would have to re-authorize.

For creating an invoice you would need to have the following scopes:
![image](https://user-images.githubusercontent.com/25197867/83325181-b8453d80-a26a-11ea-8d6e-841c5af11bca.png)

You can go to your apaleo development account and navigate to Apps --> Connected Apps and select the proper API client. There you can check yourself which scopes are configured for your API client and adjust if neccessary.

Cheers!
