### ISSUE TITLE
What's the best way to pull all payments from folios

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#339]
## Question

Hi,
I'm archiving the folios into our data ware house - and in the `/finance/v1/folios` endpoint it's possible to join the charges into the response, which makes archiving the data very easy. Is there a similar way for doing this for payments, refunds, ...?

## Background

Going one by one folio would create a large amount of requests and probably would take very long given the rate limiting.

**Comment by pgrm** [comment]
@nziehn thx for your question. Unfortunately there isn't any other way around this as of now. Going forward, you can of course use webhooks to move the folios one by one whenever they changed. For the existing data you'll need to do it the way you described it. 

In a day you should be able to move 100-200 thousand folios, so yeah it won't be immediate, but it's not like it's going to take months.

But we'll keep this in mind for future development.
