### ISSUE TITLE
The request /booking/v1/offers response takes more than 10s

### ISSUE THREAD

**Issue by adimango** [apaleo/api#341]
`Apaleo-Tracking-Id`: 0HM0CFI7ODNJG:000000FC

```
curl ‘https://api.apaleo.com/booking/v1/offers?propertyId=HOY26&arrival=2020-06-10&departure=2020-06-11&channelCode=Ibe&adults=1’ \
  -H ‘Connection: keep-alive’ \
  -H ‘Pragma: no-cache’ \
  -H ‘Cache-Control: no-cache’ \
  -H ‘accept: text/plain’ \
  -H ‘User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36’ \
  -H ‘Sec-Fetch-Site: same-origin’ \
  -H ‘Sec-Fetch-Mode: cors’ \
  -H ‘Sec-Fetch-Dest: empty’ \
  -H ‘Referer: https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1’ \
  -H ‘Accept-Language: en-GB,en-US;q=0.9,en;q=0.8’ \
  -H ‘Cookie: _ga=GA1.2.230536488.1591085813; _hjid=bd7c6a7b-fb48-48ae-8cbf-10b8e0f1b1ff; _gid=GA1.2.1229486796.1591710566; _hjAbsoluteSessionInProgress=1’ \
  --compressed
```

**Expected behavior:**

The response takes less than 1s.

**Actual behavior:**

The response takes more than 10s.

**Comment by WinniX** [comment]
Hello @adimango 

You are right. We've checked the logs, and all the other requests you did today took ~1s, but it was a single request which took more than 10s. We are aware of the issue, and are actively working on it. 

Sorry for the inconvenience.

--
Eugene / apaleo Team

**Comment by adimango** [comment]
@WinniX would be nice to know when you think to fix it

**Comment by WinniX** [comment]
This is definitely one of our priority tasks at the moment. I am afraid, I can't tell you more right now. But this kind of tasks are always high-prio for us.

Sorry again for the possible troubles.

Eugene / apaleo Team
