### ISSUE TITLE
Requesting offer for properties in the same city

### ISSUE THREAD

**Issue by adimango** [apaleo/api#342]
## Question

What is the faster way to get offers for multiple properties in the same city?
In Munich we have 139 properties. How can we get the offer for a specific location?

## Background

Right now we have to call 139 times Apaleo, the same if we want to know the "https://api.apaleo.com/availability/v1/unit-groups"

**Comment by WinniX** [comment]
Hello @adimango 

Unfortunately, as of now we cannot get away of calling offers and availability endpoints per each and every property. But thank you for your question, it reveals a valid use-case, which we could address in the future.

Eugene / apaleo Team
