### ISSUE TITLE
Testing Availability, MinStay and MaxStay settings

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#343]
Please guide me in Apaleo interface as to where can I update the Availability, MinStay and MaxStay restrictions in Apaleo, so that I can check our interface whether those updates are reflected.

**Comment by ozonni** [comment]
@VasaviBoddeti you can check this [guide](https://apaleo.zendesk.com/hc/en-us/articles/360010175080-Rate-plans-rates-management) to learn how to manage rate plan restrictions. Regarding availability, just login in to [apaleo UI](https://app.apaleo.com) and create reservation for specific days, which will decrease the availability.
