### ISSUE TITLE
Time Slice Definition (Patch path, add new TSD via API)

### ISSUE THREAD

**Issue by harrinupponen** [apaleo/api#344]
## Question

What is the correct path when adding a new time slice definition to a property?

## Background

Trying:

```
PATCH https://api.apaleo.com/settings/v1/properties/MUC/time-slice-definitions
[
  {
    "value": {
      "name": "Over Test",
        "template": "OverNight",
        "checkInTime": "12:00:00",
        "checkOutTime": "10:00:00"
    },
    "path": "/timeSliceDefinitions",
    "op": "add"
  }
]
```

Getting: 

```
{
    "messages": [
        "'Add' is not allowed for path '/timeSliceDefinitions'."
    ]
}
```

Adding works in the graphic UI (app.apaleo.com).

With kind regards
Harri Nupponen

**Comment by dario-hd** [comment]
Hi Harri,

`timeSliceDefinitions` is an array, and if you want to add an item you have to append it. You can append an item in the following way according to JSON Patch specification:

```
PATCH https://api.apaleo.com/settings/v1/properties/MUC/time-slice-definitions
[
  {
    "value": {
      "name": "Over Test",
        "template": "OverNight",
        "checkInTime": "12:00:00",
        "checkOutTime": "10:00:00"
    },
    "path": "/timeSliceDefinitions/-",
    "op": "add"
  }
]
```

**Comment by harrinupponen** [comment]
Hello!

Oh my god, that was so simple... Well, this was the first time I used the PATCH :)

Thank you so much for your extremely fast response and have a nice day!

BR
Harri
