### ISSUE TITLE
Is there a way to show a guest has opted-in to marketing notifications in Apaleo?

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#345]
## Question

Is there a way to show a guest has opted-in to marketing notifications in Apaleo?

## Background

It could be handy if we could save this information to Apaleo when guests check a box like `Send me news & offers`. I'm pretty sure it's impossible because, as I understand, at the moment there's no concept of a guest profile in Apaleo, but wanted to check.

**Comment by randyrod** [comment]
Hi @EdwardIII,

Thanks for reaching out to us.

We currently do not support that functionality in our APIs.

**Comment by ruitguerra** [comment]
Hello Edward.
I just saw your question to Apaleo.
Actually *there is a solution *to your requirement *"show a guest has
opted-in to marketing notifications in Apaleo"*.
At HotelAppz we have created a *full front end and back-end integration
with Apaleo *including :

   - A "Guest Details" Tab (via Apaleo's iFrame technology) totally
   integrated in the Apalaeo front end, where you can:
      - Optin / Optout the guest to marketing communications
      - Edit, manage and view key guest data
      - Access the full guest history and profile
   - A centralized Guest database
   - A full Guest marketing automation platform, drawing from Apaleo data
   and data provided by other partners (Ex Review management apps, Live chat /
   Chatbot apps, etc.)

Below are a few relevant screenshots of HotelAppz both in Apaleo and
outside.

Hope this helps.
What was your requirement?
Are you using Apaleo for the Hotels you work with?

Would be happy to show it to you.
My contacts: 0661555460

Best regards,
Rui

----------------------------------------------

*HotelAppz is totally integrated into Apaleo*
*Direct access to Optin/Optout, and more HotelAppz guest data management *
[image: image.png]

[image: image.png]

More screenshots and details here
<https://docs.google.com/document/d/1TRnAWnPjKrp4UYqlF-Sibdlhre5EFbUZAFTnPk-QT5o/edit?usp=sharing>


*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
