### ISSUE TITLE
Search for offers based on multiple properties

### ISSUE THREAD

**Issue by oluyoung** [apaleo/api#346]
## I want

A way to search for offers across multiple properties.

## Use cases

I would like to search for offers based on city and display the options to guests.

## Examples

It would be used in the same way that this works, https://staybeyond.com/locations/birmingham/?reason=Family+Hols&arrive=2020-07-21&depart=2020-07-22&native-arrive=2020-07-21&native-depart=2020-07-22&rooms=1&adults=2&children=0

**Comment by randyrod** [comment]
Hi @oluyoung,

Thanks for reaching out.

One solution for this could be to make a request to get the offers for each property with `GET ​/booking​/v1​/offers`. Once you have the response, you can aggregate the results into a single data structure and expose or manipulate them as you wish.

I hope this information is helpful.

**Comment by oluyoung** [comment]
Thanks for the quick response, that is what we planned to do for now, but I'm also making a request to ask if it is possible for this to be implemented?

**Comment by randyrod** [comment]
Hi @oluyoung,

I have discussed it with the team, and this functionality is already in our roadmap, but it is not yet prioritised.

Thanks for the feedback we will take it into account.

**Comment by oluyoung** [comment]
Okay thank you
