### ISSUE TITLE
Effects of planned VAT change in DE on invoice API

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#347]
## Question

How will the upcoming VAT changes in Germany effect the invoicing results?
Especially for a booking that is crossing the month border.

## Background

When calling:
```
https://api.apaleo.com/finance/v1/invoices/preview?folioId=XXX
```

Example: booking from June 3th to July 2nd:

We're currently getting an object like this:
```
{
  "id": ...,
   ...
   "taxDetails": [
    {
      "vatType": "Null",
      "vatPercent": 0,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Reduced",
      "vatPercent": 7,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Normal",
      "vatPercent": 19,
      "net": {
        "amount": 65.55,
        "currency": "EUR"
      },
      "tax": {
        "amount": 12.45,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Without",
      "vatPercent": 0,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    }
  ]
}
```

How would the new response look like in this invoicePreview.taxDetails object?

Also how will existing (not-posted) charges be affected? I heard that some changes will happen during the night of the month switch --> does this mean until end of June all of the not-posted charges in July will still be showing the old VAT percentage?

**Comment by bennetone** [comment]
Hey @nziehn 

From July 1st to December 31st the VAT rates are reduced in Germany. Starting today you can find new VAT accounts in apaleo for the temporarily reduced rates.
![image](https://user-images.githubusercontent.com/25197867/85033122-e094cd80-b180-11ea-800b-be3544d99356.png)

All new reservations or newly booked extras will automatically use the new rates for the above mentioned period. In the night from June 30th to July 1st, we will then convert all reservations already in the system that are affected by the changeover and were created before June 19th to the new rates and will also recalculate the liabilities and liabilities on VAT.

If you would like to pass on the VAT advantage in whole or in part to your guests, please remember to adjust your prices accordingly for the period of July 1st to December 31st.

For reservations that are spanning June and July you can receive a tax breakdown like the following:

```
{
  "id": ...,
   ...
   "taxDetails": [
    {
      "vatType": "Null",
      "vatPercent": 0,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Reduced",
      "vatPercent": 7,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    },
    {
      "vatType": "ReducedCovid19",
      "vatPercent": 5,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Normal",
      "vatPercent": 19,
      "net": {
        "amount": 65.55,
        "currency": "EUR"
      },
      "tax": {
        "amount": 12.45,
        "currency": "EUR"
      }
    },
    {
      "vatType": "VatNormalCovid19",
      "vatPercent": 16,
      "net": {
        "amount": 67.24,
        "currency": "EUR"
      },
      "tax": {
        "amount": 10.76,
        "currency": "EUR"
      }
    },
    {
      "vatType": "Without",
      "vatPercent": 0,
      "net": {
        "amount": 0,
        "currency": "EUR"
      },
      "tax": {
        "amount": 0,
        "currency": "EUR"
      }
    }
  ]
}
```

As said above this only for reservations created starting today or for old reservations after we ran the migration in the night from June 30th to July 1st.
