### ISSUE TITLE
Restriction Updates not received

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#348]
For HotelName: BER, RatePlan :: BER-FLEX-SGL, we had made few changes in your interface w.r.t. restrictions. But we haven't received those restriction updates into our system, though we have integrated your API.

Changes: June 20th arrival closed and June 18&19 bookable closed and closed on departure

Please let us know the reason for this immediately. Thank You.

**Comment by dario-hd** [comment]
Hi, we would need to know more in order to check this. What's your account? What do you mean with "haven't received"? Are you using webhooks? Please, provide a tracking id if you have it.

**Comment by VasaviBoddeti** [comment]
Dear Partner,

Please find more details below:


Client Name: Cultuzz Simple Client
Client ID: KAFB-SP-CULTUZZ_SIMPLE_CLIENT

Yes, we have implemented webhooks and we are expecting ARI update for 
the restriction changes that we have made.

How and where can we check the tracking ID to provide it to you, please 
advise.

---
Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by VasaviBoddeti** [comment]
Please consider this as a gentle reminder.

**Comment by dario-hd** [comment]
As far as I can see there are no subscriptions configured for your account. Are you sure you are correctly subscribing to webhooks? Did you check the guide here https://apaleo.dev/guides/start/webhook/?

**Comment by dario-hd** [comment]
Or are you talking about ARI subscriptions for distribution?

**Comment by dario-hd** [comment]
Beware that you receive notifications via distribution only for rate plans mapped to channel manager. The rate plan BER-FLEX-SGL is not mapped to the channel manager:

![image](https://user-images.githubusercontent.com/14803089/85002382-1b810c00-b155-11ea-83c0-67bbf7b54dc5.png)

Please set it to channel manager:

![image](https://user-images.githubusercontent.com/14803089/85002503-40757f00-b155-11ea-9349-babeb7217fc5.png)

**Comment by VasaviBoddeti** [comment]
We have the mappings and so we have received the below given ARI update request for one restriction applied on this endpoint: 

https://backend.cultuzz.com:8081/v1/arinotif?token=123456

------------------
{
    "accountId": "KAFB",
    "propertyId": "BER",
    "timeSlices": [
        {
            "ratePlanId": "BER-FLEX-DBL",
            "unitGroupId": "BER-DBL",
            "from": "2022-06-17T17:00:00+02:00",
            "to": "2022-06-18T10:00:00+02:00",
            "available": 50,
            "restrictions": {
                "minAdvanceBookingPeriod": "P3D",
                "maxAdvanceBookingPeriod": "P180D",
                "closed": true,
                "closedOnArrival": false,
                "closedOnDeparture": false
            }
        }
    ]
}
----------------------

And we want to know, why are the other updates on restrictions not received.

**Comment by WinniX** [comment]
Hey @VasaviBoddeti 

Sorry for taking so long getting back to you. The issue was shown as "Closed". Please next time click "Reopen" button to bring this issue back, so it will be answered.

Speaking of the question, I think it's somehow related to this issue https://github.com/apaleo/api/issues/414
If not, please tell us, so we could investigate it.

--
Eugene

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

Sure, I will follow your instructions.

Yes, 414 is clarified now. Thank You for your prompt support always.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com
