### ISSUE TITLE
Rate limits for specific endpoints

### ISSUE THREAD

**Issue by Teppichseite** [apaleo/api#351]
## Question

Is the endpoint `availability/v1/unit-groups` rate limited? 

Do you have a documentation about which specific endpoints are rate limited and which are not? 

It is not really clear in the current documentation (https://apaleo.dev/guides/start/rate-limiting) which endpoints are business critical and therefore not rate limited.

## Background

Currently we are trying to speed up our endpoints at which users can request different offers and availabilities. We want to fetch multiple availabilities for one property concurrently. This could lead to the problem, that we are being rate limited by your api.

Thank you for you help!

**Comment by usmanmustafa33** [comment]
Hi @Teppichseite ,

yes, currently  `availability/v1/unit-groups` endpoint is rate limited
thanks for the headsup and that we will improve the documentation soon

Usman / apaleo Team

**Comment by Teppichseite** [comment]
Thank you for the answer. Just to be sure: The endpoint `GET booking/v1/offers` is not rate limited, isn't it?

**Comment by randyrod** [comment]
Hey @Teppichseite,

Correct, the endpoint `GET booking/v1/offers` is not rate limited.
