### ISSUE TITLE
Enum Values Management

### ISSUE THREAD

**Issue by nuno-sousaHZ** [apaleo/api#352]
## Question

Hi,

Is there any API that allow to pull all the updated enum values (e.g vatType, channel codes, travel purpose, etc) ?

The idea would be to prevent from adding manually in the model with enum values that are added on your side.

Best regards,

Nuno Sousa

**Comment by http-request** [comment]
Hi Nuno,

You can use [swagger codegen](https://swagger.io/docs/open-source-tools/swagger-codegen/) for generating models, enums etc. automatically.

Please also check our [announcements](https://github.com/apaleo/announcements/issues) about API updates.

Thank you!

Best regards,
Svyatoslav
