### ISSUE TITLE
Post Payment information

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#353]
## Question

There are two ways to collect a payment. 

1. via Adyen integration
2. via any other payment provider

To add the payment information for a collected amount for another payment provider (2) I think I need to use following request:
**POST ​/finance​/v1​/folios​/{folioId}​/payments**

Is there another way to mark a folio as paid, when the hotel has adyen (1) connected? 
What is the prefered way?

## Background

We're collecting the payment using the Adyen DropIn Form.

**Comment by ozonni** [comment]
@c2ofh the best way to have payment implemented is to use apaleo api together with Adyen Web Drop-in integration. Please check out this guide [https://apaleo.dev/guides/business-cases/ibe/getting-the-money](https://apaleo.dev/guides/business-cases/ibe/getting-the-money) where it is explained in details how to implement the whole flow.

The rest of the things, posting payment to folio, making sure that payment automation works as expected, all of this apaleo will take care of. And you don't need to do it yourself.

Let me us know if you have any further questions.

**Comment by ozonni** [comment]
@c2ofh doing those things yourself might lead to inconsistencies, also some functionality like refunds will not work anymore. So i highly recommend you to take a look at this guide [https://apaleo.dev/guides/business-cases/ibe/getting-the-money](https://apaleo.dev/guides/business-cases/ibe/getting-the-money)

**Comment by ozonni** [comment]
@c2ofh if a customer doesn't use apaleo payment (use case 2), then you are right, you can explicitly post a payment via `/finance/v1/folios/{folioId}/payments` API

**Comment by c2ofh** [comment]
Hi @ozonni 
Thank you, The documentation is not very detailed, but I'll see what I can do with it.

**Comment by ozonni** [comment]
@c2ofh if could describe your use case and what you try to achieve, then i could give you more specific information.

**Comment by c2ofh** [comment]
There are 2 usecases @ozonni :
- The guest is checking-in and have to pay the open amount to complete the check-in.
- The guest is checking-out and have to pay the open amount to complete the check-out.

For me is not clear enough, how to save the information at apaleo, after the amount was charged.

**Comment by ozonni** [comment]
@c2ofh if reservation has payment account, then you can simple call `POST /finance/v1/folios/{folioId}/payments/by-payment-account` and specify the amount. That amount will be automatically charged from the credit card that is attached to the reservation.

If reservation has no credit card, that you can pre-authorize the amount (https://apaleo.dev/guides/business-cases/ibe/getting-the-money) and then call `POST /finance/v1/folios/{folioId}/payments/by-authorization`.

You can also generate a payment link using `POST /finance/v1/folios/{folioId}/payments/by-link` and give that link to the guest. When you open that link, there will be a widget where guest can select preferred payment method and pay. In that case payment will be automatically posted to the folio.
