### ISSUE TITLE
Preferred permissions for a standard admin API access

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#354]
## Question

Which permissions are needed for creating / modifying properties, unit types, rate plans, rates, bookings etc, i.e. the standard admin work? The whole Core API but nothing else?

## Background

When creating a new API access through connected apps -> create a new app, one can define the scope of the access.

**Comment by WinniX** [comment]
Hello @tmmartti 

Based on the types of actions you've listed, I would say yes, "Core API" is enough.

I am not sure whether you need to manage ARI subscriptions using our Distribution API. This API is created to work with various channels (like Booking.com, Expedia, etc).
Also, have a look at our Identity API, maybe you would want to manage users too.

I hope this helps.

Eugene / apaleo Team

**Comment by tmmartti** [comment]
Sounds about right, thanks for the help!
