### ISSUE TITLE
Choice of Secret when creating API access

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#355]
## Question

Does it matter what does one define as the Secret? Usual password policies?

## Background

When creating a new API access through connected apps -> create a new app, one is supposed to define a secret.

**Comment by WinniX** [comment]
Hello @tmmartti 

I am not sure if I got you right, do you mean "Secret description" field?
![image](https://user-images.githubusercontent.com/426392/85952447-a938d480-b969-11ea-8588-c86bf2e97181.png)

The **secret token** will be generated for you automatically, you just need to type the secret description, so you won't forget what's the purpose of this token.

Eugene / apaleo Team

**Comment by tmmartti** [comment]
I see! Thanks for this one too.
