### ISSUE TITLE
Bad Gateway - Apaleo API is down

### ISSUE THREAD

**Issue by adimango** [apaleo/api#356]
we are experiencing several issues with the Apaleo APIs, can you please keep us informed?

**Comment by nuno-sousaHZ** [comment]
We are also experiencing the same problem.

Can you notify when the problem is resolved? Thanks

**Comment by adimango** [comment]
yeah thank you

**Comment by WinniX** [comment]
Hello @adimango and @nuno-sousaHZ 

I deeply apologies for the inconvenience caused by "502 Bad Gateway". 
We have identified the issue and the fix is just deployed. 

Please let us know if you still have any issues within our API.

Eugene / apaleo Team
