### ISSUE TITLE
access to further scopes

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#357]
Could you please add access to all scopes for the test account hotellistat-test?
It seems that we do not have access to e. g. the GET endpoint https://api.apaleo.com/booking/v1/reservations in our testing environment.

Thank you very much,
Tobias

**Comment by ozonni** [comment]
@t-haze you can manage scopes yourself directly in apaleo UI. Check this guide for more information: https://apaleo.dev/guides/start/oauth-connection/register-app
