### ISSUE TITLE
Webhooks for changed rate-plans

### ISSUE THREAD

**Issue by adimango** [apaleo/api#358]
## Question

Are there webhooks to get rateplan changed events?

## Background

We would like to reduce the calls to
https://api.apaleo.com/rateplan/v1/rate-plans

**Comment by nfidirko** [comment]
Hello @adimango ,
Have you visited https://apaleo.dev/guides/start/webhook/configuration ?
We have the `RatePlan` topic with `created` and `rate-changed` events.
Would that work for you?

**Comment by adimango** [comment]
@nfidirko yeah that should work. 
Thank you
