### ISSUE TITLE
How to write the body for PATCH rates (and specifically, restrictions)

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#359]
## Question

Writing the body any which way, PATCH restrictions either does nothing or returns an error. How to make it work?

## Background

Using 
https://api.apaleo.com/rateplan/v1/rates?ratePlanIds=MUC-APALEO123-SGL,&from=2020-08-02T17%3A00%3A00%2B02%3A00&to=2020-08-03T17%3A00%3A00%2B02%3A00

Tried e.g. this body:

```
[
  {
    "value": {
                "minLengthOfStay": 5,
                "maxLengthOfStay": 30,
                "closed": false,
                "closedOnArrival": true,
                "closedOnDeparture": true
                },
    "path": "/restrictions",
    "op": "add"
  }
]
```

**Comment by pgrm** [comment]
Hello @tmmartti I saw that the request worked for you once

```
[
  {
    "value": {
                "minLengthOfStay": 5,
                "maxLengthOfStay": 30,
                "closed": false,
                "closedOnArrival": true,
                "closedOnDeparture": true
                },
    "path": "/restrictions",
    "op": "add"
  }
]
```

you received a 204, the problem is, once you want to change them, it won't work anymore because they are already set and you can't `add` new ones, instead you need to `replace` them

This should work:

```
[
  {
    "value": {
                "minLengthOfStay": 5,
                "maxLengthOfStay": 30,
                "closed": false,
                "closedOnArrival": true,
                "closedOnDeparture": true
                },
    "path": "/restrictions",
    "op": "replace"
  }
]
```

**Comment by tmmartti** [comment]
Hi @pgrm 

Thanks for your response! I tried that, got 204, but still GET with 

https://api.apaleo.com/rateplan/v1/rate-plans/MUC-APALEO123-SGL/rates?from=2020-08-01T17%3A00%3A00%2B02%3A00&to=2020-08-04T17%3A00%3A00%2B02%3A00&pageNumber=1&pageSize=100

gives me 

{
    "rates": [
        {
            "from": "2020-08-02T13:00:00+02:00",
            "to": "2020-08-03T10:00:00+02:00"
        },
        {
            "from": "2020-08-03T13:00:00+02:00",
            "to": "2020-08-04T10:00:00+02:00"
        },
        {
            "from": "2020-08-04T13:00:00+02:00",
            "to": "2020-08-05T10:00:00+02:00"
        }
    ],
    "count": 3
}


so the restrictions are not there. Why?

**Comment by pgrm** [comment]
Hello @tmmartti 

we only return the restrictions when the price is also set. As long as you didn't set a price nobody can book that rate anyway that's why we skip all the additional information as well.

If you set the price now, you should get back the rates with the price and restrictions.

**Comment by tmmartti** [comment]
Hi @pgrm 

I tried setting the price for MUC-HARRIREF3-DBL, which is the parent rate plan of MUC-APALEO123-SGL, using 

PATCH https://api.apaleo.com/rateplan/v1/rates?ratePlanIds=MUC-HARRIREF3-DBL,&from=2020-08-02T17%3A00%3A00%2B02%3A00&to=2020-08-03T17%3A00%3A00%2B02%3A00

[
  {
    "value": {
                "amount": 102,
                "currency": "EUR"
            },
    "path": "/price",
    "op": "add"
  }
]

Still no dice. The price doesn't get added on the parent, which "isDerived": false so it should be willing to take in rates. What could the problem be now?

**Comment by pgrm** [comment]
Hello @tmmartti the prices were seemingly set correctly, but your rateplans are still not bookable

![image](https://user-images.githubusercontent.com/713456/86909914-21955780-c119-11ea-8834-cbcebb51cdba.png)

This is a bit tricky, you can also check out the apaleo business documentation on rateplans to better understand what is going on in apaleo: https://apaleo.zendesk.com/hc/en-us/articles/360001744291-Setting-up-Rate-Plans

The problem is that there are booking periods missing for the rateplan APALEO123

![image](https://user-images.githubusercontent.com/713456/86910110-7638d280-c119-11ea-99e3-072ed3971d6d.png)

that's another reason why you wouldn't get any prices. Basically no price means that the rate can't be booked, that can be either due to missing prices or due to missing booking periods

**Comment by tmmartti** [comment]
Hi @pgrm 

I'm trying to PATCH the rates on the test1 (id: MUC-HARRIREF3-DBL)-rate plan. I did manage to PATCH different booking periods but that's the /rate-plans end point. So, using 

PATCH https://api.apaleo.com/rateplan/v1/rates?ratePlanIds=MUC-HARRIREF3-DBL,&from=2020-08-02T17%3A00%3A00%2B02%3A00&to=2020-08-03T17%3A00%3A00%2B02%3A00

[
  {
    "value": {
                "amount": 102,
                "currency": "EUR"
            },
    "path": "/price",
    "op": "add"
  }
]

i get 204 all nice and tidy but still no changes.

**Comment by pgrm** [comment]
@tmmartti the rate plan is still not bookable and still doesn't contain any booking periods. You'd need to fix that first. You can also do it via the UI

- https://app.apaleo.com/MUC/rates/rate-plans/prices to see if the rate plans are bookable for the particular periods
- https://app.apaleo.com/MUC/rates/rate-plans/MUC-APALEO123-SGL to add the booking period (keep in mind booking period needs to include today)

**Comment by tmmartti** [comment]
works now, for both rate plans, the parent and the child. Thanks @pgrm!
