### ISSUE TITLE
"empty" mandatory restrictions

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#36]
## Question

Hi apaleo team,

the API request PUT /rateplan/v1/rate-plans/{id}/rates has described 3 out of 5 restrictions as mandatory and two of them as optional inside the RateRestrictionsModel.
Why is this so? Can not be all of them optional and you would assume the "default setting" in your system whenever a restriction attribute is missing, respectively "do nothing" and only update the rate without touching restriction settings? This would bring the enormous benefit, that restrictions would only be deleted/unset on your side, whenever there is an "empty" restriction, but nothing would get messed up, whenever a restriction attribute is missing at all.. but this would only work, if the other 3 will be able to become optional as well.  

## Background

i'm currently doing some refinements on our rates put mechanism to also support restrictions

**Comment by bennetone** [comment]
Hi Tobi,

this is a PUT API endpoint, so it overrides the current state by the new state you are sending. Even if you do not send an optional value it will be modified. If a certain night has a minimum length of stay restriction of 3 and you would just not send the minimum length of stay restriction you will remove the restriction for that night. For the closed restrictions it is the same. Even if we would make them optional, we would then always set them to _false_. You would still have to send _true_ if it was _true_ before and you don't want to change it.

What you are looking for is a PATCH API endpoint. Best is to perform the PATCH on your side. Load the rates, adjust the values you want to change and send them back.

Regards,
Benjamin

**Comment by t-haze** [comment]
Hi Benjamin,

thank you for clarifying. I wasn't totally familiar with the exact RFC definition of a PUT method, especially the part on "idempotence" :)

Makes sense.

Regards,
Tobi

**Comment by t-haze** [comment]
Hi Benjamin,

we just discovered some discrepancies between the [Integrations-Guide](https://blog.apaleo.com/developer/channel-integration-guide#ari) und the [api-docu (swagger)](https://api.apaleo.com/swagger/#!/Rate/RateplanRate_plansByIdRatesGet) for the `GET rate` method:

attributes `minAdvanceBookingPeriod` and `maxAdvanceBookingPeriod` are existing in the Integrations-Guide, but not on swagger (also not in NSFW dev-branch).

Are they already useable? If not, when will the gonna be available?

Thank you,
Tobi

**Comment by bennetone** [comment]
Hi Tobi,

the [channel integration guide](https://blog.apaleo.com/developer/channel-integration-guide) is for channel manager integrations and explains details about the [distribution API](https://distribution.apaleo.com/swagger/). This is the data you will receive as ARI push notifications if you create a subscription for a specific rate plan.

The core API does not have the min and max advance booking offsets on the time slices aka rates, but they are defined on the rate plan itself. It's a little bit different use case and therefore tailored API models.
