### ISSUE TITLE
Get a reservation using the `payerReference` or `transactionReference`

### ISSUE THREAD

**Issue by adimango** [apaleo/api#360]
## Question

Is it possible to query a reservation using the `payerReference` or `transactionReference`?
## Background

IBE integration Example below:

```{
  "paymentAccount": {
    "accountNumber": "1111",
    "accountHolder": "John Doe",
    "expiryMonth": "8",
    "expiryYear": "2018",
    "paymentMethod": "visa",
    "payerEmail": "s.hopper@test.com",
    "payerReference": "575b0100-b261-4a36-94cb-eeb49f7c98d3",
    "transactionReference": "564578124534890J",
    "isVirtual": false
  }```

**Comment by pgrm** [comment]
Hello @adimango that's not possible, but you could add an `externalCode` to your reservations, however, keep in mind that this code needs to be unique across the whole account.
