### ISSUE TITLE
A mix of apartment and aparthotels: can buying 1 room block out a whole apartment?

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#361]
## Question

We're talking with a client and they have a mix of properties:

1. Some might just have 1-2 rooms in a building.

If one room is sold, they don’t want the other room to be available.

2. But there are also some aparthotel type buildings with 20 rooms. In that case, they don’t want to block out the whole apartment if just 1 room is sold

Do you know if apaleo can handle this? or if we need to figure out some logic on the IBE side?

## Background

We're looking to implement a nice UI flow on the IBE side for this use case.

**Comment by pgrm** [comment]
hello @EdwardIII apaleo can't handle this out of the box. What some customers and partners implement is to add a maintenance slot for the other room, so it can't be booked anymore. But you'd need to implement that part on the IBE - or there is another integration which listens on newly created reservations and does that for the customer.

cheers
