### ISSUE TITLE
/rateplan/v1/companies is not paginated

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#362]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)
https://api.apaleo.com/swagger/index.html?urls.primaryName=Rate%20Plan%20V1#operations-Company-RateplanCompaniesGet

The property has 185 companies.

**Code**
```
GET rateplan/v1/companies
        (
            [propertyId] => XXXXXX
            [pageNumber] => 1
            [pageSize] => 100
        )
```

**Expected behavior:**

Return the first 100 companies.

**Actual behavior:**

Returns all185 companies.

All 185 companies are always returned no matter of `pageNumber` and `pageSize` query params.

**Comment by pgrm** [comment]
@Denitz that is indeed a bug, thx for reporting it

**Comment by Denitz** [comment]
@pgrm, @dario-hd  Thanks, when can we expect a fix?

**Comment by pgrm** [comment]
@Denitz my colleague (@WinniX) told me, the fix has been just deployed - since we have rolling deployment it might take couple of minutes until you'll see it working.

Cheers
