### ISSUE TITLE
GET /finance/v1/folios expand payments

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#363]
## I want

to be able to expand folio payments on `GET /finance/v1/folios`

## Use cases

Analyzing folios, we need to see charges and payments. Currently, we need an extra API call `GET /finance/v1/folios/{folioId}/payments` for each folio and it's a resource-cost operation.

## Examples

Get list of folios and analyze charges + payments.

## What I do

Financial analytics.

**Comment by XTVB** [comment]
Hello Denitz

Thank you for your feature request. We've created an issue in our backlog to implement this. However, due to the upcoming deprecations in the folio model it might take a while till we implement it.

Regards,
Abdu, apaleo support
