### ISSUE TITLE
GET reports/v1/reports/revenues not available for single day

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#364]
**Code**

```
    GET reports/v1/reports/revenues
    Array
        (
            [propertyId] => XXX
            [from] => 2020-06-01
            [to] => 2020-06-01
        )
```

**Expected behavior:**

Get data for a single day.

**Actual behavior:**

Error:  `To must be greater than From.`

**Comment by abarbarov** [comment]
Hi @Denitz,
Please take a closer look at the documentation - https://api.apaleo.com/swagger/index.html?urls.primaryName=Reports%20V1. It says that the `to` boundary is exclusive, which means that `2020-06-02` should be used in your case.
