### ISSUE TITLE
GET /finance/v1/payments

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#365]
## I want

To get the list of all payments in a single API call with required `paymentDate` from/to params, optional `status` and `type` filters.

## Use cases

Get all payments

## Examples

Payment analytics

## What I do

Payment analytics

**Comment by abarbarov** [comment]
Hi @Denitz,

Thank you for the feature request. We'll add it to the backlog. 

Meanwhile, you can check the NSFW version of the API - all the new features appear there (https://api.apaleo-staging.com/swagger/index.html?urls.primaryName=Finance%20NSFW), it should be possible to use current folios API to do the analytics. Also, keep an eye on https://github.com/apaleo/announcements in case of future API changes.


-----
Kind regards,
Afanasy / apaleo Team
