### ISSUE TITLE
GET /finance/v1/charges

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#366]
## I want

To get all charges filtered by `serviceDate` from/to params, other optional params to filter charges.

## Use cases

Charges analytics.

## Examples

Charges analytics.

## What I do

Charges analytics.

**Comment by abarbarov** [comment]
Hi @Denitz,

Thank you for the feature request. This looks pretty similar to the other of your requests. We do not charge for the number of API requests, so you can combine the existing API to achieve your goal. And meanwhile, we'll add the feature desired.


Kind regards,
Afanasy / apaleo Team
