### ISSUE TITLE
Property performance report data discrepancies

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#367]
`GET reports/v1/reports/property-performance` for a single date in the past:

`businessDays->unitGroups->soldCount` is 1 for unitGroup XXX.

But, I definitely have more than 1 room of type XXX stayed overnight at this date: 4 room nights at this date for this room type (unitGroup).

Same issues with `arrivalsCount` and `departuresCount`.

`cancellationsCount` is zero while I have two canceled reservations which were supposed to have an overnight stay at this date.

Even total `soldCount` is different from the exact number of consumed room nights at this date.

Is this a bug or not? Do you have the detailed description of the data in this report?

I understand that the revenues in this report are totally wrong compared to real revenues because they don't reflect all charges, but I supposed that at least the room nights should match?

**Comment by dario-hd** [comment]
Hi, could you send us the tracking id of your request?

**Comment by Denitz** [comment]
@dario-hd Unfortunately, your support center in Zendesk doesn't allow direct ticket creation, there is no ticket list, no chat - just nothing!

I posted a ticket via a "Contact Support" form yesterday, but still no reply and there is no ticket ID in the email received from Zendesk:

```
Thanks for reaching out! We received your request, but need a bit of time to think about it. You'll hear back from us shortly.

If you want to add more information or comments, reply to this email.

Your apaleo support team
```

**Comment by dario-hd** [comment]
For such requests is better to create issues in this repository. Unfortunately with so little information, I'm not able to help you. Whenever you call our API, you receive a response header, `apaleo-tracking-id`. We need that to find your request and analyze it.

**Comment by Denitz** [comment]
@dario-hd Request tracking id is `0e576ef7-9923-4559-958d-e240e4d34c58`
The report is for 2020-06-01, check i.e. the data for `STS` unitGroup (the first item in unitGroups array).

**Comment by dario-hd** [comment]
So, basically for June 1st, you have 4 reservations (originally) sold for the single unit group:

![image](https://user-images.githubusercontent.com/14803089/87530540-c1f6f900-c690-11ea-88ed-1d0c839e79e6.png)

If you look at the unit column, you can see that 3 out of 4 reservations have a unit assigned from a different unit group (Comfort). Those reservations count as sold for the comfort unit group. The same happens for arrival and departures. So 1 sold and 1 arrival for that date.

Cancellations are considered only on the arrival date. As far as I can see there are no cancelled reservations arriving on Jun, 1st. So 0 cancellations for that date.

I hope this clarifies your questions.

**Comment by Denitz** [comment]
@dario-hd 
OK, thanks! It's getting more clear.

Reservation `GDNORFZD-1` has Single Room 217 - it's correct.

The next one is `FCIXTICV-1` which has Comfort Room #118.

I loaded this reservation via `GET /booking/v1/reservations`, request id is  `562f04cb-08c7-4935-9ff0-8f271da7dd47`, here is the reservation data:

```
    [unitGroup] => stdClass Object
        (
            [id] => XXX-STS
            [code] => STS
            [name] => Single Room
            [description] => WIFI, FlatScreen TV, Safe, Shower, Phone,

        )

    [unit] => stdClass Object
        (
            [id] => XXX-WQV
            [name] => 118
            [description] => T2
            [unitGroupId] => XXXX-COM
        )
```
See that `unit` is correct, but why do we have `STS` in unitGroup but not `COM` ?

I expect that `ReservationModel->unitGroup` contains the unit group data of unit in `ReservationModel->unit`?

Same issue in all `timeSlices` for this reservation.

**Comment by dario-hd** [comment]
We keep that as that's the originally booked unit group. Also, consider that a reservation can potentially have a different unit group booked for every night and a unit assigned with a different unit group only for one specific night.

For example:

Night 1: Single   - Assign Single
Night 2: Double - Assign Double
Night 3: Double - Assign Triple

I hope this makes sense.

**Comment by Denitz** [comment]
@dario-hd Thanks, now it's clear! Better add the note about originally booked unit group in https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1#model-ReservationModel

Unfortunately, I have the next question: property performance report has 30 `soldCount` for 2020-06-01.

I filtered all reservations which have an overnight stay at 2020-06-01 and see only 28 reservations which consumed 28 unique rooms at this date. Here are the room numbers (unit names):

```
01
108
109
112
116
118
119
206
207
214
215
217
218
219
306
315
316
318
319
414
418
419
515
516
518
519
616
617
```

The question is: what are the missing two room nights?

**Comment by dario-hd** [comment]
As I said, a reservation can have a different unit assigned for different nights. Are you getting the unit from the correct time slice? if you are using the unit on reservation level, that only gives you the "currently assigned unit" which is, in case of a past reservation, the last. Instead, you should pick the correct time slice for that day, but that can be tricky because there some edge cases to consider. May I ask why are doing such calculations?

**Comment by Denitz** [comment]
@dario-hd Yes, sute, the room info is taken from reservations' timeSlices at serviceDate of 2020-06-01

But even if the room info is wrong, we only have 28 reservations which stayed overnight at 2020-06-01

We develop the analytics app which uses both overall performance data from property performance report + the data of individual reservations. For sure, the data should be the same: if the performance report has 30 room nights for a specific date, we need to see all the reservations involved in consuming these 30 room nights, but we see only 28.

We can skip the fact that the revenues from the performance report are different from sum of revenues in all charges consumed at the same date, but the consumed room nights should be the same!

How does the API counts `soldCount`? For now, it looks like a bug because I can't confirm that we had 30 rooms stayed overnight.

**Comment by dario-hd** [comment]
You should filter the report by the over-night time slice definition (ZJUAM-NIGHT) to get the desired results.

**Comment by Denitz** [comment]
@dario-hd Thanks, it's getting better, but still incorrect for certain dates. Can you confirm that the property performance report is 100% accurate? It looks like it can't be used as 100% correct source of consumed room nights.

**Comment by dario-hd** [comment]
It is accurate according to our logic. As I said there are several edge cases to consider when calculating those numbers. I wouldn't suggest you to mimic our logic, because it's very to keep it in sync. Consider that the "sold" is sold **units** not sold **reservations**. This means that if you have 2 reservations sold in 1 time slice (1 early check-out and 1 late check-in) that count as 1 unit.
