### ISSUE TITLE
GET /booking/v1/reservations expand folioCharges, folioPayments and folios

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#368]
## I want

To be able to expand reservation charges and payments for each reservation. Folios as well but it's not a top priority.

## Use cases

Analyze reservations.

Currently, we have to additionally load all reservation folios for each reservation, next load all payments for each folio. This results in a really enormous number of API requests.

## Examples

Reservations analytics.

## What I do

Reservations analytics.

**Comment by Denitz** [comment]
Any news?

We can't load the data for analytics because of API limits:

"API calls quota exceeded! maximum admitted 600 per 10m."

The reason is that we have to load folios and payments separately for reservations which results in enormous number of requests.

**Comment by dario-hd** [comment]
Currently, there is no way to extract all the data using a single API. Such API it's on our roadmap but it's not going to be developed soon. In the meanwhile, you can distribute your calls considering the quota e.g. trigger an API call per second for a specific endpoint.

**Comment by Denitz** [comment]
Sorry, it's weird, the scripts will take ages to load the historical data :(
