### ISSUE TITLE
How do GET Finnish rate plan names?

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#369]
## Question

How do GET Finnish rate plan names?

## Background

e.g. GET https://api.apaleo.com/rateplan/v1/rate-plans/POST-MIN1WEEK-BAS2 gives only an English name even though the rate plan has a Finnish name. How to get it?

**Comment by dario-hd** [comment]
Hi, you have to specify the `Accept-Language` request header. In your case, you should set the value to `fi`.
