### ISSUE TITLE
Inventory/v1/properties properties.read scope & authentication 403 forbidden

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#37]
Dear Apaleo Team,

could you please send me updated scopes for our client id/secret (pricing-app) for **properties.read** inventory/v1 api on the price-app.

Thanks, Patrick

**Comment by patrickHermannLimeHouse** [comment]
Hi Apaleo Team, any updates on the requested scopes? thx PH

**Comment by dmitry-urenev** [comment]
@patrickHermannLimeHouse please check the api again, the requested scope was added!
