### ISSUE TITLE
No webhook since 9:15

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#370]
We haven't received any update via webhook since about an hour. 
Please give me an update, cause some customers have problems now.

**Comment by WinniX** [comment]
Hello @c2ofh 

our monitoring has spotted this. We are investigating this case. We will keep you updated.

Eugene / apaleo Team

**Comment by WinniX** [comment]
Hello @c2ofh 

Sorry for the outage this morning. The issue was identified, and soon will be fixed.
The system is recovering, in a couple of minutes you will start receiving all the events that have been missed. 

Eugene / apaleo Team
