### ISSUE TITLE
How do GET multiple language versions (beyond DE and EN) of rate plan names and descriptions?

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#371]
## Question

How do GET multiple language versions (beyond DE and EN) of rate plan names and descriptions in one command? Is it possible?

## Background

e.g. GET https://api.apaleo.com/rateplan/v1/rate-plans/POST-MIN1WEEK-BAS2 with header: "Accept-language: en; q=1.0, fi; q=1.0" gives only the English name even though the rate plan has a Finnish name. Is it possible to make a single call that fetches both?

**Comment by dario-hd** [comment]
Hi,

when getting a single rate plan, you can specify the list of languages you are interested in, or you can just specify `all` to get them all.

Check it out on our swagger:

![image](https://user-images.githubusercontent.com/14803089/87935113-bb9dbe00-ca90-11ea-92fc-83333dc936c2.png)
