### ISSUE TITLE
GET /reports/v1/reports/property-performance filtered by sourceCode

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#372]
## I want

To get the report data for specific source code only

## Use cases

Analytics.

## Examples

Analytics.

## What I do

Currently, it's only possible to filter data by channel code but not source code.

**Comment by dario-hd** [comment]
This endpoint is supposed to be a basic report. As you can imagine is not easy for us to provide a flexible way to slice and dice the data. That would be the job of a BI tool. What you can do is use our API to feed the BI tool and then aggregate the data as you like.
