### ISSUE TITLE
Inconsistent city tax calculation (folio vs. offer)

### ISSUE THREAD

**Issue by tobeno** [apaleo/api#373]
`Apaleo-Tracking-Id`: 5b5a7691-4fff-48f0-baa0-5f1ab7e09d2c

**Code**
```
curl -X GET "https://api.apaleo.com/booking/v1/offers?propertyId=HAR45&arrival=2020-08-18&departure=2020-08-20&adults=1" -H "accept: text/plain" -H "authorization: Bearer ***"
```

**Expected behavior:**
This property has a percentage based city tax enabled.

We use the grossAmount and the city tax from the offer to calculate the total amount to be charged. We expect this to give us the full amount the customer has to pay in the end (which is also displayed in the generated folio). We need this as we currently handle the initial pre-payment on our end and do not use the Apaleo payment integration for the booking. This means we have to get the total amount including all taxes somehow.

**Actual behavior:**
When we tried this for the second offer (180 € with a city tax of 9.45 €) spanning 2 nights, we ended up with 0.01 € open in the folio. Looks like the rounding of the individual charges in the folio is different from the cityTax included in the offer. We expected them to match.

This is the offer as displayed in the Apaleo UI:
<img width="534" alt="Screenshot 2020-07-22 at 17 51 25" src="https://user-images.githubusercontent.com/2261240/88200101-fb59d680-cc45-11ea-91b2-b4c7fd1fc887.png">

---

And this is the resulting folio:
<img width="761" alt="Screenshot 2020-07-22 at 17 53 02" src="https://user-images.githubusercontent.com/2261240/88200383-5e4b6d80-cc46-11ea-9ef6-412a80c16f9a.png">

As you can see, the city tax charged do not sum up to what we get in the offer and then use in the payment.

Maybe we also misconfigured something somewhere, but at least I would not expect this behaviour, even if we were accidentally abusing one of the APIs a bit.

**Comment by nfidirko** [comment]
Hi @tobeno,

From what I can see, the exact value of the city tax per night in the case above is `4.725`.
So, when we round it to create a folio charge, we get `4.73`.
When we sum up the precise amounts (for the offer), we'll get `9.45`.

I'll create an issue about that and put it in our backlog.
In the meanwhile, you can use the `PayableAmount` from the reservation model, or `AllowedPayment` payment from the folio model to get the amount that is still to be paid.

**Comment by tobeno** [comment]
Thanks for the quick reply. Is there also a way of retrieving the payable amount **before** creating the reservation? Our current flow triggers the payment before we create the reservation in Apaleo. I suppose we could change that, but this might cause some unwanted fallout in other systems.

Just to ask: Is this issue also likely to affect bookings via connected platforms like booking.com?

**Comment by nfidirko** [comment]
Hi @tobeno,

> Is there also a way of retrieving the payable amount before creating the reservation?

unfortunately, no.



> Is this issue also likely to affect bookings via connected platforms like booking.com

The city tax value is taken from the offer (would be 9.45 in your case).
But when we capture the payment, the payable amount is taken from the reservation (we'd capture 189.4**6** in your case).

**Comment by tobeno** [comment]
Ok, thanks for the explanation. After talking in the team, sadly looks like we have to wait for a fix from your end. Our current implementation follows https://blog.apaleo.com/developer/ibe-integration-guide (including the remark about city tax) and it will be pretty hard to switch to post-payment.

**Comment by nfidirko** [comment]
Hi @tobeno,
we've deployed the fix.
The city tax for the offer should be calculated correctly now.

**Comment by tobeno** [comment]
@nfidirko Thanks a lot! You saved us a lot of headaches. With what we tested, looks like the fix works as expected. 👍
