### ISSUE TITLE
Restriction update not received

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#375]
## Question

I have set a minstay of '2' for BER-FLEX-DBL for property 'Berlin' through our account with Code: KAFB and Name: Cultuzz. But we haven't received the update into our system. 

## Background

![BER-FLEX-DBL-Restriction_update](https://user-images.githubusercontent.com/64488734/88898461-6325a800-d26a-11ea-9d2f-769ae053ab45.png)

**Comment by dmitry-urenev** [comment]
hey @VasaviBoddeti is this problem still relevant? I would recommend you to check your subscriptions in the Apaleo Distribution API - https://distribution.apaleo.com/swagger/ If you don't have any subscriptions - you won't receive any updates. For complete information about our distribution API and how you could integrate your channel manager with apaleo please check our [Integration Guids](https://apaleo.dev/guides/business-cases/channel-integration/)
