### ISSUE TITLE
Price update received for unmapped rate

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#376]
## Question

We have sent a price of 100 for Flex single today through Apaleo interface but we have received the update for Non-refundable Double room. Please find attached screenshots for your kind reference.

![berflex](https://user-images.githubusercontent.com/64488734/88904856-3e81fe00-d273-11ea-8d03-0b153edd81f2.png)
![Update_received](https://user-images.githubusercontent.com/64488734/88904869-40e45800-d273-11ea-8ec3-19cf78c5a697.png)

**Comment by dario-hd** [comment]
Hi @VasaviBoddeti,

that's because rate plan `BER-NONREF-DBL` inherits the prices from `BER-FLEX-SGL`. If you change the price for one rate plan, you will receive the update for all the rate plans that directly or indirectly inherit from it.
