### ISSUE TITLE
PUT rates keeps giving a 422

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#377]
## Question

PUT https://api.apaleo.com/rateplan/v1/rate-plans/ONLINE-STD-STD/rates with 

[
    {
        "from": "2020-08-02T17:00:00+02:00", 
        "to": "2024-12-31T11:00:00+02:00", 
        "price": {"amount": 67.0, 
            "currency": "EUR"
        }, 
        "restrictions": {"minLengthOfStay": 1, 
            "maxLengthOfStay": 30, 
            "closed": false, 
            "closedOnArrival": false, 
            "closedOnDeparture": false
        }
    }
]
keeps not working. Why?

## Background

The error message begins by: "Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Apaleo.Api.Modules.RatePlan.Models.Rate.ReplaceRateListModel' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly."

**Comment by nfidirko** [comment]
Hey @tmmartti,
you can't just send an array directly.
if should be sent as an object with a property `rates`.
here is an example of a valid request:
```
{
   "rates":[
      {
         "from":"2020-08-02T08:00:00.000Z",
         "to":"2020-08-03T07:00:00.000Z",
         "restrictions":{
            "minLengthOfStay":1,
            "closed":false,
            "closedOnArrival":false,
            "closedOnDeparture":false
         }
      }
   ]
}
```

**Comment by tmmartti** [comment]
Thanks for the advice there - it still throws an error though; sending 

{
   "rates":[
      {
         "from":"2020-08-02T08:00:00.000Z",
         "to":"2020-08-03T07:00:00.000Z",
         "price": {"amount": 55.0, "currency": "EUR"},
         "restrictions":{
            "minLengthOfStay":1,
            "closed":false,
            "closedOnArrival":false,
            "closedOnDeparture":false
         }
      }
   ]
}

to PUT https://api.apaleo.com/rateplan/v1/rate-plans/ONLINE-STD-BUD/rates 
gives 422: "Some rates might be missing or the `from` and `to` for some of them do not match the expected date and time. Do not try to construct the rates, better first request the rates for a certain time range and just fill in the price and restrictions."

**Comment by nfidirko** [comment]
@tmmartti,
you've specified the `from` and `to` periods incorrectly. Dates should match the timeslice definitions, which may vary depending on your property setup.

what you can do is:
- request the rates for the time range you're interested in;
- update the rates, specifying the `from` and `to` parameters based on what you've received.

**Comment by tmmartti** [comment]
All right, got it now. Thanks!
