### ISSUE TITLE
Unit attributes endpoint?

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#378]
## Question

Is there an endpoint for unit attributes? 

## Background

Can't find any from the swagger page or by experimenting with /inventory.

**Comment by nfidirko** [comment]
Hi @tmmartti ,
we have an API for unit attributes, but it's NSFW.
You can find it here: https://api.apaleo.com/swagger/index.html?urls.primaryName=Inventory%20NSFW

NSFW API is subject to change at any time, so, use it at your own risk.
We're planning to make unit attirbutes V1 soon.

So, you can already start developing and testing against the NSFW API.
Just, don't forget to switch the version to V1 once we release it.

**Comment by tmmartti** [comment]
Ok, nice! Thanks for the advice.
