### ISSUE TITLE
Distribution API - ARI Not Syncing

### ISSUE THREAD

**Issue by ggeorgiadis** [apaleo/api#379]
## Question

Hi, 
I have made 2 different subscriptions for 2 accounts, but I do not receive any updates when I trigger full syncs even though they are accepted. I even tried to update the rate plans associated from the UI to receive a delta push but nothing there either.

The two subscription ids are `EDM3E15K` and `QDE6139D`.

Finally, I am following [this guide](https://apaleo.dev/guides/business-cases/channel-integration/ari-data) to setup the ARI connection but it would be really helpful if you could provide with the model information of the updates, like the rest of the swagger models.

Thank you

**Comment by bennetone** [comment]
Hi @ggeorgiadis ,

could you share the response you get when you make a GET request on the above mentioned subscriptions, please?

Thanks,
@bennetone

**Comment by ggeorgiadis** [comment]
Hi @bennetone ,

thanks for your quick response. You can find them below:
```json
{
    "id": "EDM3E15K",
    "propertyId": "BER",
    "channelCode": "ChannelManager",
    "endpointUrl": "https://app-staging.katanox.com/api/subscription?token=17086",
    "ratePlanIds": [
        "BER-FLEX-SGL",
        "BER-NONREF-SGL"
    ],
    "numberOfDays": 365,
    "enabled": true
}
```
and 
```json
{
    "id": "QDE6139D",
    "propertyId": "MUC",
    "channelCode": "ChannelManager",
    "endpointUrl": "https://app-staging.katanox.com/api/subscription?token=123486",
    "ratePlanIds": [
        "MUC-FLEX-SGL"
    ],
    "numberOfDays": 365,
    "enabled": true
}
```

**Comment by ozonni** [comment]
@ggeorgiadis all requests to those endpoints are timing out. Check if you have firewall or IP restrictions, because simple `POST` requests fail due to timeout.

**Comment by ggeorgiadis** [comment]
Hi @ozonni ,

that's indeed what the problem was, I overlooked it.

Thanks for your help
