### ISSUE TITLE
New Reporting App - New Client id & secret as well as mutliple scopes required.

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#38]
Dear Apaleo Team,

our development team currently builds a **new read-only analytics and reporting application** based on our Apaleo data. Therefore we would need a **new client id and client secret** as well as a **list of scopes** belonging to the following API calls:

- GET /reports/v1/reports/gross-sales
- GET /reports/v1/reports/vat-details
- GET /reports/v1/reports/room-nights-consumed
- GET /reports/v1/reports/room-nights
- GET /reports/v1/reports/bed-nights
- GET /reports/v1/reports/arrivals
- GET /finance/v1/folios/
- GET /finance/v1/folios/$count 
- GET /booking/v1/available-units
- GET /booking/v0-nsfw/bookings
- GET /booking/v1/reservations
- GET /rateplan/rate-plans/{id}/rates

Please contact me and let me know ASAP if you have any further questions. 

It would be perfect if you could send me over the client id and secret via mail: patrick.hermann@picuscap.com.

Thx in advance!

Best, Patrick

**Comment by patrickHermannLimeHouse** [comment]
Dear Apaleo Team do you have any news for us? Thx in advance.

**Comment by dmitry-urenev** [comment]
@patrickHermannLimeHouse please check your email, I've sent you the new credentials!

**Comment by patrickHermannLimeHouse** [comment]
please send the information to sabine.pagel@limehome.de

**Comment by patrickHermannLimeHouse** [comment]
Dear Dmitry. We would additionally need the scopes attached to the **GET /rateplan/v1/rate-plans** API. Thanks Patrick

**Comment by patrickHermannLimeHouse** [comment]
@dmitry-urenev Thx!
