### ISSUE TITLE
Cannot replace primaryGuest object of reservation

### ISSUE THREAD

**Issue by ggeorgiadis** [apaleo/api#380]
`Apaleo-Tracking-Id`: `0f1767d5-9710-4ec6-a889-c0d0c7ee7495`

**Code**
```json
[
    {
        "value": {
            "title": "Mrs",
            "gender": "Female",
            "firstName": "Jane",
            "middleInitial": "D",
            "lastName": "Doe",
            "email": "jane.d@doe.com",
            "phone": "+4989123343",
            "address": {
                "addressLine1": "My Street 1",
                "postalCode": "12453",
                "city": "MyCity",
                "countryCode": "GB"
            }
        },
        "path": "primaryGuest",
        "op": "replace"
    }
]
```
**Expected behavior:**
Replacing primary guest with the new object provided in value and get 204 status code.
**Actual behavior:**
Got response: 
```json
{
    "messages": [
        "The value '{\n  \"title\": \"Mrs\",\n  \"gender\": \"Female\",\n  \"firstName\": \"Jane\",\n  \"middleInitial\": \"D\",\n  \"lastName\": \"Doe\",\n  \"email\": \"jane.d@doe.com\",\n  \"phone\": \"+4989123343\",\n  \"address\": {\n    \"addressLine1\": \"My Street 1\",\n    \"postalCode\": \"12453\",\n    \"city\": \"MyCity\",\n    \"countryCode\": \"GB\"\n  }\n}' is invalid for target location."
    ]
}
```
and 422 status code.
**Related Issues:** 
While browsing previous issues to find out if I am misusing jsonpatch, I came across [this answer](https://github.com/apaleo/api/issues/96#issuecomment-472424359) which shows the same usage as above.

Note: Replacing individual fields of primaryGuest works ok

Thanks

**Comment by https-request** [comment]
Hello,

Thank you for your request 😃 

An issue is that you are using `Mrs` value for title instead of `Ms`. The `title` field can have one of the following values: 
"Mr", "Ms", "Dr", "Prof", "Other"

**Comment by ggeorgiadis** [comment]
Hi @https-request ,

that was indeed the issue. 

Thank you
