### ISSUE TITLE
Integration API - Reservation Details tab

### ISSUE THREAD

**Issue by nuno-sousaHZ** [apaleo/api#381]
## Question

Hi,

Did you change any endpoint in your Integration API?

Because we're receiving a http response "Method Not Allowed" when performing a request to the endpoint /integration/v1/ui-integrations/{target}.

## Background

In Apaleo Click & Connect integration we have, an UI Integration resource is created in order to open the "Reservations" tab on Apaleo's app.

**Comment by https-request** [comment]
Hello,

Thanks for reaching out to us! Could you please provide us with the apaleo-tracking-id-header, which you get as part of the response?

Best regards,
Svyatoslav

**Comment by nuno-sousaHZ** [comment]
Yes, please consider the following tracking-id : cb74bddc-51c0-48cc-bbd2-e6205f8d3b93

Best regards,

Nuno Sousa

**Comment by randyrod** [comment]
Hi @nuno-sousaHZ,

The endpoint that you are trying to reach only supports `GET` and `POST` methods, so you should make sure you are using one of those.

You can see in our swagger specification here https://integration.apaleo.com/swagger/index.html the endpoints and data that you'd need to provide if you want to perform other actions like `PUT` and `DELETE`.

You can read more about apaleo one integrations in our dev guides here https://apaleo.dev/guides/start/apaleo-one/

Regards,
Randy

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Perhaps, I wasn't clear before in my first question. What I asked explicitly, is if you changed any endpoint on your side.

The reason I'm asking this, is because this part of the UI-Integration we have, isn't changed on our side over a year ago.

Thank you in advance.

Best regards,

Nuno Sousa

**Comment by randyrod** [comment]
Hi @nuno-sousaHZ,

The last deprecation announcement we made for our integration API is here https://github.com/apaleo/announcements/issues/25 there it is described the changes that were made to the endpoints and API.

The announcement repository is were we announce all the new features and deprecations made to our APIs, I would recommend subscribing to it, to be up to date with all the changes.

I hope this information is helpful.

Best regards,
Randy

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Thanks for the information.

Best regards,

Nuno Sousa
