### ISSUE TITLE
CompanyInfoModel - Schema restrictions not correct

### ISSUE THREAD

**Issue by raphaelbrand-limehome** [apaleo/api#383]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)
2b06b036-d2d6-47ba-aab7-37adba3180ec
**Code**
curl -X GET "https://api.apaleo.com/finance/v1/folios/GAETZDHC-1-1" -H "accept: application/json" 
**Expected behavior:**
Every CompanyInfoModel should have a name field set, as it is required according to the schema definition.
![image](https://user-images.githubusercontent.com/69624916/90112905-e6f29080-dd50-11ea-8438-cbd8d402418f.png)

**Actual behavior:**
Only the tax_id gets returned, name field does not exist in the json response.

**Related Issues:**

**Comment by raphaelbrand-limehome** [comment]
It seems that the problem arises, when a tax id is set but no company name. We will be manually fixing these objects on our site for now, but for the future it would be nice to update the schema to reflect the actual data.

**Comment by nfidirko** [comment]
Hello @raphaelbrand-limehome ,
Could you please check the tracking id once again?
I don't see it in the logs for the last 7 days.
I can see your requests for 12.08.2020 for the folio `GAETZDHC-1-1`, but there is no company in the response.

**Comment by raphaelbrand-limehome** [comment]
Hey @nfidirko ,
sorry i don't have the tracking id anymore. 

As i said above, we removed all the faulty company setups, so you can't see it anymore right now, as it breaks our code. But you can reproduce it by going to a reservation, click on folios and the on the top right there is the name of the debitor. Click it and in the following pop up you are able to set a tax_id without setting a name. If you pull this folio from the api you will end up with a faulty object.

Let me know if you need more information.

**Comment by nfidirko** [comment]
@raphaelbrand-limehome ,
thanks for the clarification.
I've managed to reproduce it.
Yes, it looks like a bug.

I'll let you know once the fix is ready and deployed.

**Comment by WinniX** [comment]
The issue was fixed.
