### ISSUE TITLE
Can 401 mean anything else than a bad token?

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#384]
## Question

Can 401 mean anything else than a non-accepted token?

## Background

We keep getting a 401 for a simple GET /reservations, when that is deployed on Heroku. The issue does not occur in local deploy.  The program checks (without issues) whether its token is valid and gets a new one if not, and then passes it into another skript that in turn keeps giving a 401 for a GET /reservations, and only on Heroku. Do we know for sure that the 401 means that somehow the token does not get passed on well, and can't be some other issue?

Thanks! And sorry for a big vague question.

**Comment by randyrod** [comment]
Hi @tmmartti 

Thanks for reaching out. As you mention 401 generally means that the token provided for the request is invalid. In could be invalid for reasons like it has expired, or is malformed.

Depending on which authentication flow you are using, the process to get a token is different. If you are using the recommended connect client flow described here https://apaleo.dev/guides/start/oauth-connection/auth-code-grant make sure that your application is going through the flow correctly. As maybe while creating the authorization code to exchange for an access token you could be missing something, or getting some error and not noticing it.

One thing to look into is that your client is properly configured, making sure that you have set up your `Redirect Url` to the one in your production environment, as if it is not correct you won't be able to get an authorization code. You can check the configuration of your client following the guide here https://apaleo.dev/guides/start/oauth-connection/register-app

If you have further questions, please let us know.

Regards,
Randy
