### ISSUE TITLE
API key usage on Power BI

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#385]
## Question

[If is this in the scope of valid questions:] How to use token on Power BI? 

## Background

In attempting to GET https://api.apaleo.com/reports/v1/reports/revenues?propertyId=HKIHAAGA&from=2020-07-31&to=2020-08-01 on Power BI / Power Query, I used the following connecting M-code:

let
    Source = Web.Contents("https://api.apaleo.com/reports/v1/reports/revenues?propertyId=HKIHAAGA&from=2020-07-31&to=2020-08-01",[ApiKeyName="APIToken"])
in
    Source

This one seems to work otherwise but one still (obviously) has to enter a Key. A naked (valid) token doesn't do and neither does writing Bearer <token> or Authorization: Bearer <token>. I also tried with the API secret - no dice. Every time the response is "We couldn't authenticate with the credentials provided".

If this is not in the scope of this support channel, please discard :)

**Comment by ozonni** [comment]
@tmmartti there are several ways you can send api request to apaleo
1. Setting `Authorization` header to `Bearer eyJhB...` value, which is the token you somehow get before
2. Check if Power BI supports OAuth2. Then you can create api client for Power BI, configure clientId/secret and PowerBI will do authorization for you.
3. Check if Power BI supports other authorization options.

**Comment by tmmartti** [comment]
Thanks for the advice. It wasn't easy due to the specific formal requirements of the M-language, but if someone else has the same issue then this one solved it for me:

https://community.powerbi.com/t5/Desktop/Power-Query-Open-ID-and-OAuth-2-0-Rest-API/td-p/693162
