### ISSUE TITLE
Date of departure - Inclusive/exclusive

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#386]
Please clarify me whether the departure date in the reservation API must be included or excluded.

For example, we have a reservation with the arrival date as 19th Aug 2020 and departure date as 20th Aug 2020. Based on these dates, 

(i) should the reservation be considered for two days with the departure date included i.e. booking for two days 19th and 20th Aug 2020.

Or

(ii) should the reservation be considered for one day with the departure date excluded i.e. booking for one day i.e. 19th Aug 2020.

**Comment by ozonni** [comment]
@VasaviBoddeti it's a booking for 1 night. Arrival is on 19th 17:00 (depending on time slice definition) and departure 20th at 10:00 (depending on time slice definition).
