### ISSUE TITLE
Timeslices issue

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#387]
Reservation done for one day[i.e, 19 Aug] for two units, For each unit we have provided one timeslice. But we got error from Apaleo as "Expected 2 time slices but 1 were provided". Please find the request and response.

Request :
=========
{
   "booker": {
     "firstName": "Naresh",
     "lastName": "Eriventy",
     "email": "naresh.eriventy@cultuzz.com",
     "address": {
       "addressLine1": "test",
       "postalCode": "test",
       "city": "test",
       "countryCode": "IN"
     }
   },
   "channelCode": "ChannelManager",
   "source": "Other",
   "reservations": [
     {
       "arrival": "2020-08-19",
       "departure": "2020-08-20",
       "adults": 1,
       "guestComment": "Test booking by QA",
       "externalId": "38509639281-1",
       "timeSlices": [
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 365,
             "currency": "EUR"
           }
         }
       ]
     },
     {
       "arrival": "2020-08-19",
       "departure": "2020-08-20",
       "adults": 1,
       "guestComment": "Test booking by QA",
       "externalId": "38509639281-2",
       "timeSlices": [
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 365,
             "currency": "EUR"
           }
         }
       ]
     }
   ]
}

Response:
=========
{"messages":["Expected 2 time slices but 1 were provided."]}

**Comment by ozonni** [comment]
@VasaviBoddeti you tried to create overnight booking with day use rate plan. Day use rate plans can not span over night. For regular overnight bookings please use over night rate plans. Indeed the error message is not clear and we will adjust it to show precisely what is wrong.
