### ISSUE TITLE
Reservation For DayUse rateplan for two days reservation.

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#388]
Please advise us on the error received in the below reservation:

Request
==========
```
{
   "booker": {
     "firstName": "Bhaskar",
     "lastName": "Biddiscombe",
     "email": "lesley.biddiscombe@rolls-royce.com",
     "address": {
       "addressLine1": " 52 Wenlock Ave  ",
       "postalCode": "OL6 8TD ",
       "city": "Ashton-under-Lyne",
       "countryCode": "GB"
     }
   },
   "channelCode": "ChannelManager",
   "source": "Other",
   "reservations": [
     {
       "arrival": "2020-08-20",
       "departure": "2020-08-21",
       "adults": 1,
       "guestComment": "RatePlan Code 444330 Guarantee Code CC GuaranteeType CC/DC/Voucher",
       "externalId": "124578963-1",
       "timeSlices": [
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 450,
             "currency": "EUR"
           }
         },
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 455,
             "currency": "EUR"
           }
         }
       ]
     },
     {
       "arrival": "2020-08-20",
       "departure": "2020-08-21",
       "adults": 1,
       "guestComment": "RatePlan Code 444330 Guarantee Code CC GuaranteeType CC/DC/Voucher",
       "externalId": "124578963-2",
       "timeSlices": [
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 450,
             "currency": "EUR"
           }
         },
         {
           "ratePlanId": "BER-DOUBLE-DBL",
           "totalAmount": {
             "amount": 455,
             "currency": "EUR"
           }
         }
       ]
     }
   ]
}

```

Response :
==========
`{"messages":["For one of the requested rate plans and the given stay dates we could not find exactly one specific offer. Please be aware that a reservation needs to span one continued time range. If you are booking a rate like e.g. DayUse you need to book a reservation per each day."]}`

**Comment by dmitry-urenev** [comment]
Hi @VasaviBoddeti Day use reservations can not span over night like this:
```json
"arrival": "2020-08-20",
"departure": "2020-08-21",
```
so to have a two days DayUse booking you need to create 2 reservations: 
```json
reservations: [{
"arrival": "2020-08-20",
"departure": "2020-08-20",
... }, {
"arrival": "2020-08-21",
"departure": "2020-08-21",
...}]
```

**Comment by VasaviBoddeti** [comment]
Dear Dmitry,

Thank you for the clarification.

For day use rateplan, if we had to make a reservation for one day, is it possible to have the same date for both arrival date and departure date.

Also please confirm if we can use both day use rateplans and overnight rateplans.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by dmitry-urenev** [comment]
@VasaviBoddeti 
> For day use rateplan, if we had to make a reservation for one day, is it possible to have the same date for both arrival date and departure date.

yes, you must provide the same date for DayUse template type. 

A booking itself can include multiple reservations with different template types, but within a reservation you are not allowed to mix rate plans with different template types.

**Comment by VasaviBoddeti** [comment]
Dear Dmitry,

Thank you very much for clarification.

In one booking can we include two rateplan reservations with one is overnight rateplan and another is Day use rateplan. Pleases advise.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by dmitry-urenev** [comment]
@VasaviBoddeti I answered already that you can in my previous comment. Please check `CreateBookingModel` in the swagger documentation for `POST /booking​/v1​/bookings` endpoint and construct the request payload accordingly. So at the end you will have something like that:
```
{
   "booker": {
     ...
     }
   },
   "reservations": [
   // DayUse Reservation payload
   {
        "arrival": "2020-08-20",
        "departure": "2020-08-20",
         "timeSlices": [
          {
               "ratePlanId": "YOUR-DAY-USE-RATEPLAN-ID",  ....
         }]
   }, 
   // OverNight Reservation payload
   {
        "arrival": "2020-08-21",
        "departure": "2020-08-23",
        "timeSlices": [{
               "ratePlanId": "YOUR-OVER-NIGHT-RATEPLAN-ID", ....
         }, {
               "ratePlanId": "YOUR-OVER-NIGHT-RATEPLAN-ID", ....
         }]
   }
],
...  
```
