### ISSUE TITLE
How do I get notified when an extra service is added to an in-house reservation?

### ISSUE THREAD

**Issue by eloihdez** [apaleo/api#39]
How do I get notified when an extra service is added to an in-house reservation? It seems that the reservation notification is not being triggered when I add a service.

@aprooks

**Comment by aprooks** [comment]
Hi @eloihdez 

There 2 ways of adding service. 

When a guest has not yet checked in, a reservation can be amended with extra services, like "add breakfast for each date of stay". In this case, you will receive reservation amended event.

When a guest is already in-house, adding a service means adding a single charge with a service type is added. For example (add a single extra breakfast). In this case, this is a folio event which we don't publish via notification service yet. 

So the only way to track if service is added atm is by polling each in-house reservation's folios

**Comment by aprooks** [comment]
I will add a requirement to be notified on "service added" event but cannot estimate when we have it.

**Comment by aprooks** [comment]
Hey @eloihdez 	

we've published a new event type "Balanced Changed" for a topic "Folio". 

This way you don't have to poll folio for changes. In any case, you will still have to save a set of charges reservation was created with, so that you could distinguish which charge has just been added.
