### ISSUE TITLE
over-night and day-use

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#391]
We would like to know the clear differences between Over-night and day-use rateplans in terms of defnition and API implementation as well. Could you please advise on this, thank you.

**Comment by ozonni** [comment]
@VasaviBoddeti please check out these guides to better understand rate plans:

https://apaleo.zendesk.com/hc/en-us/articles/360001744291-Setting-up-rate-plans
https://apaleo.zendesk.com/hc/en-us/articles/360010175080-Rate-plans-rates-management

And check out swagger documentation as well for Rate Plan API: https://api.apaleo.com/swagger/index.html?urls.primaryName=Rate%20Plan%20V1

**Comment by VasaviBoddeti** [comment]
Dear Vasily,

Thank you for the reply.

But I had found only one statement i.e. "The time slice definitions are automatically created for you, and you can choose between over-night, which will be from check-in to check-out time, or day-use, which is from check-out to check-in time." out of all the references that you have provided me.

Could you please elaborate the above mentioned definition for 'Over-night' and 'Day-use' rateplans. Thank You.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Hi Vasavi, Day-use rate plans are used in the situation where the room is needed for short duration like the guest wants to freshen up before heading for a customer meeting. The day-use rate has the same day check-in & check-out. Overnight reservation means that the guest is staying for the night at the hotel. You can create both the rate plans using the same /rateplan/v1/rate-plans endpoint.

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Thank you very much for the clarification.

Have a great day!

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com
