### ISSUE TITLE
App Certification Request Form

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#392]
While filling the App Certification Request Form, I need some clarification on the below mentioned to better understand before I submit the form:

Please let us know the  difference between 

(i) OAuth connect client application (apaleo store app) and OAuth simple client application (custom app)

(ii) apaleo One / UI Integration

**Comment by alokbash** [comment]
Hi Vasavi,

(1) OAuth Connect is when you use [OAuth 2.0 - Authorization code grant flow](https://apaleo.dev/guides/start/oauth-connection/auth-code-grant). It is usually used when you create an app for apaleo Store.
(2) OAuth simple client is when you use [OAuth 2.0 - Client credentials grant flow](https://apaleo.dev/guides/start/oauth-connection/client-credentials-grant). It is usually used when you create a custom app for a hotel.
(3) If you are using apaleo [One / UI Integration](https://apaleo.dev/guides/start/apaleo-one/) ( i.e., surfacing your views into the apaleo user interface), then you need to specify how you are doing it. If not, then just say that you are not using apaleo One / UI Integration.

Regards,
Alok

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Thank you very much for providing the denfitions of each one requested for.

However, we have created both Simple client and Connect client credentials with us.

So, please guide as to how and when do we use Simple Client credentials and when should we use Connect client credentials. 

Please advise.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Hi Vasavi,

If you have created the [Connect client](https://apaleo.dev/guides/start/oauth-connection/auth-code-grant), then customers will use it from the [apaleo store](https://apaleo.dev/guides/apaleo-store/) to connect to your app in apaleo. A simple client is usually used when a developer is creating a custom/local app for a specific hotel. For more information, see [https://apaleo.dev/guides/start/oauth-connection/register-app](https://apaleo.dev/guides/start/oauth-connection/register-app).

Regards,
Alok

**Comment by VasaviBoddeti** [comment]
Dear Alok,

 

Thank you for the calrification.

 

When we are done with the certification process and deploy our development into production server i.e. when we go LIVE, we don’t need to access Simple client anywhere, right ? 

 

Kind regards,

 

Vasavi Boddeti

Partner Manager

 

Cultuzz India Pvt. Ltd.

No 47-9-14, Ganta Arcade,

Dwaraka Nagar 3rd Lane,

Visakhapatnam - 530016

 

Tel. +91 8913053333

Tel. +91 9985922397

vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Correct. For details about getting on the apaleo store and certification, see [Publish your app to apaleo Store
](https://apaleo.dev/guides/apaleo-store/)
