### ISSUE TITLE
Do restriction updates to parent rate plans also apply to derived rate plans

### ISSUE THREAD

**Issue by lukhug** [apaleo/api#393]
## Question

When we update restrictions for rate plan which is a parent rate plan (ie. `"isDerived": false`) for a particular night via the API, does it also add this restriction to all derived rate plans? As prices get updated for derived rate plans I just want to confirm this.

## Background

We are currently scoping out the work for supporting restriction management in Pace.

**Comment by usmanmustafa33** [comment]
Hi lukhug,

if you update restrictions for parent rate plan it will not update the restrictions of all derived rate plans, it will only update restrictions for rate plan you try to update.


Usman  / apaleo Team

**Comment by lukhug** [comment]
Thank you!
