### ISSUE TITLE
Cancellations of bookings by Apaleo

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#396]
We do not take cancellations for the bookings from any PMS. Does Apaleo send us cancellations ? If yes, what if we do not take cancellations from Apaleo ? Is that okay, if we ignore ?

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

It's possible to receive reservation cancellations in Apaleo using our [Webhook API](https://webhook.apaleo.com/swagger/index.html). 
Please have a look at this guide: https://apaleo.dev/guides/start/webhook/configuration

The event you are talking about is probably - `Reservation` topic with type `canceled`.

If you have any more questions on this - feel free to ask.

--
Eugene / apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

Thank you for the clarification.

We have only developed Distribution API, where we only accept Availability, Rates and Restrictions from Apaleo and send Bookings, Modifications and Cancellations to Apaleo.

Will this suffice for our certification to proceed being a Channel Manager, please confirm.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Yes. We'll verify the use cases that you'll list in the [app certification request form](https://forms.office.com/Pages/ResponsePage.aspx?id=LdIozj28-U2GNwCsmwNcQu4Xa4oRlWZBvcu1Azfi6VpUNDkwVVU4SzJFQ1Q4SkJJR1hJRUo5N0RQWS4u).

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Thank you for the confirmation.

As we haven't implemented booking cancellations to receive from Apaleo, how to adjust the availability then. Please advise, whether it is mandatory for us to implement Booking cancellations to be taken from APaleo ?

**Comment by VasaviBoddeti** [comment]
Please advise on my previous query within the same issue

**Comment by alokbash** [comment]
Hi @VasaviBoddeti, We'll get back to you on this in a while.

**Comment by abarbarov** [comment]
Hi @VasaviBoddeti,

If you can manage canceled reservations on your side somehow, it is OK not to implement that flow.

BR,
Afanasy, apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Afanasy,

Thank you for the email.

We have implemented all the operations mentioned in Channel Integration Guide, where we RECEIVE ARI updates from Apaleo and we SEND bookings, modifications and cancellations to Apaleo.

But we haven't implemented any operation w.r.t. Apaleo sending Cancellations to us. In that case, how can we handle such case, please advise.

By the word "manage cancelled reservations", what did you meant exactly, please explain. Thank You.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by abarbarov** [comment]
Hi,

We can send cancellation notifications (https://apaleo.dev/guides/start/webhook/configuration). If you don't need them for some reason and or you are handling cancellations directly somehow and everything works on your side - then everything should be OK.

BR,
Afanasy, apaleo Team

**Comment by VasaviBoddeti** [comment]
Thank you for the information.

In that case, it should be mentioned in the channel integration guide or in Distribution API. If it is a mandatory operation, may be we should be informed about its implementation explicitly either.

I will discuss with our technical team, whether they can develop it now. Thank you.
