### ISSUE TITLE
Occupancy prices versus Fixed prices per night

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#398]
Until now, all the PMS that are connected to Cultuzz were sending prices as fixed prices per night. And we show as-is in our interface. But first time, we are receiving Prices per Occupancy from apaleo. So, we dont have interface to show occupancy based prices. 

During certification, how should we show you the price updates to you, please advise.

**Comment by alokbash** [comment]
Hi Vasavi, Do you have any plans to reflect occupancy-based prices in your UI?

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Yes, we are taking the prices from Apaleo and storing it into our 
database for distribution. Though we do not have this feature to 
showcase it in our interface, we have built an API that pulls the data 
from our database and shows us whether the price updates from Apaleo are 
being reflected at our end or not. So, will this suffice to proceed with 
the certification process, please confirm. Thank You.

---
Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Yes. It should suffice.
