### ISSUE TITLE
 Prices Calendar

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#399]
In the Apaleo interface, we see that the prices for each Rateplan are shown in the Calendar, as shown in the attachment. But we would like to know for which occupancy are these prices shown in the attached screen, for all the Rateplans ?

Does all the Rateplans show the price for Single Occupancy in the Prices Calendar, as in the attached screen in Property > RatePlans > Prices, please advise.
![Prices_Calendar](https://user-images.githubusercontent.com/64488734/91458540-426d6400-e8a3-11ea-9d41-ba6e4c0fbbb7.png)

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

The prices you see there are the base rates. The base rate only includes the included services. The rest, like surcharges, additional services, etc - will be added on top of it.

In order to see the price including all services and surcharges - you need to call a get offers endpoint.

---
Eugene / apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

Thank you very much for the clarification.

But you haven't given me clarity on the occupancy level, whether the price
of each Rateplan displayed in the calendar is for single occupancy ? Please
advise.

Also please confirm, if we can consider these bases prices shown in the
calendar as fixed prices per day/night for each Rateplan. 

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by VasaviBoddeti** [comment]
Gentle reminder please

**Comment by dario-hd** [comment]
Hi, yes, the price shown is for a single occupancy.

>  ... fixed prices per day/night for each Rateplan.

What do you mean with "fixed" exactly?

**Comment by VasaviBoddeti** [comment]
Dear Dario,

Thank you very much for the confirmation.

By fixed prices, we mean the standard price for a room per night per standard occupancy.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by dario-hd** [comment]
As I said, that's the price for single occupancy. And that's for a room for a specific night.

**Comment by VasaviBoddeti** [comment]
Thank you so much Dario. Similarly, can we get such base prices for double occupancy through API ? If yes, could you please share that request to retrieve the double occupancy prices for all the Rateplans of a hotel ?

**Comment by dario-hd** [comment]
Please check our swagger documentation. The GET rates endpoint in the Rate Plan API returns the data you are looking for:

![image](https://user-images.githubusercontent.com/14803089/91712529-3118a600-eb88-11ea-9de1-21e839c3e032.png)

Check the `calculatedPrices` property.

**Comment by VasaviBoddeti** [comment]
Thank you very much for the clarification.

So whenever we want the prices for only 2 occupancy, we shall use this call for all the rateplans. Thank you.
