### ISSUE TITLE
OAuth with property_id

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#40]
## Question

I've implemented the OAuth in our system. It works well.
How do I get the property_id of the hotel? It would be great if the user can choose it's property which should be connected, if there are more than one available for the user.
If there is only one property could you add the Id directly to the parameters in Step 2?

I guess, the user has to set the property_id furthermore manuelly or am I wrong?

**Comment by pgrm** [comment]
Hello @c2ofh 

OAuth currently woks only on account level. So the moment the user connected your application with their account in apaleo you have access to all the properties. If you want to let the user configure specific properties in your application you need to implement that on your side. 

You can get the list of properties via our inventory API.

**Comment by c2ofh** [comment]
Hello @pgrm 
Thank you for your Information. So I will build it on my own.
