### ISSUE TITLE
V1 version of the reservation logs api

### ISSUE THREAD

**Issue by LucaDe** [apaleo/api#400]
## I want

a stable V1 version  of the reservation logs API (OperationId: LogsBookingReservationGet)

## Use cases

We need to fetch all reservation logs generated by a specific client for custom internal reservation processing.

**Comment by usmanmustafa33** [comment]
Hi LucaDe 
releasing reservation logs v1 is already in our backlog, very soon we will release reservation logs v1 

Usman / apaleo Team
