### ISSUE TITLE
Cancellation fees and finance/v1/accounts/export-daily

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#402]
## Question

Are cancellation fees included in finance/v1/accounts/export-daily and how should one filter the response to get them?

## Background

Filtering finance/v1/accounts/export-daily by creditedAccountName and command, one can extract Revenues Accommodation. However, that doesn't include cancellation fees. Does that finance/v1/accounts/export-daily-search include cancellation fees and if yes, how to filter the response in order to extract them?

**Comment by WinniX** [comment]
Hello @tmmartti 

Sorry for the late reply.

The `finance/v1/accounts/export-daily` should return you revenues from cancellations too, in case you have them over the specified period. If you want to filter out only Cancellation revenues you can use "&accountNumber=RevenueCancellationFees_`#VatType#`" filter, for example ("accountNumber=RevenueCancellationFees_Without").

Hope this helps.

--
Eugene / apaleo Team
