### ISSUE TITLE
Webhooks for Unit Groups

### ISSUE THREAD

**Issue by Teppichseite** [apaleo/api#403]
## Question

Is there a possiblity to subscribe to inventory changes via webhook? We want to update or delete unit groups on our side, if changes were made to a unit group in Apaleo. The subscription topic "Group" seems to have the context of bookings.

**Comment by dario-hd** [comment]
Hi, that's not possible at the moment, but we will add this to our backlog. We will inform you once it's released.

**Comment by WinniX** [comment]
Hello @Teppichseite 

I am glad to tell you that from now we have `UnitGroup` events. 

--
Eugene / apaleo Team
