### ISSUE TITLE
Day Use on a non-Day Use Rate plan

### ISSUE THREAD

**Issue by lukhug** [apaleo/api#405]
## Question

We spotted that one of our shared customers had a Day Use Booking despite being booked on a rate plan which is not configured to be a Day Use (looking at the Timeslice setup of the rate plan). We are now wondering if we should add another check to spot Day Use bookings (to account for occupancy correctly) - and if so, what this check should be? Could you help us how this Day use reservation was possible to make on a non-Day Use booking rate plan

## Background

Please find the full reservation attached below. Let me know if you need any further details.

```
{
    "id": "TZRTRCBB-1",
    "bookingId": "TZRTRCBB",
    "status": "CheckedOut",
    "checkInTime": "2020-08-20T12:58:39+02:00",
    "checkOutTime": "2020-08-20T14:25:44+02:00",
    "unit": {
        "id": "HARMON-RTM",
        "name": "ROOM 54",
        "description": "DESCRIPTION",
        "unitGroupId": "HARMON-DBLDLX"
    },
    "property": {
        "id": "HARMON",
        "code": "HARMON",
        "name": "HARMON HOUSE"
    },
    "ratePlan": {
        "id": "HARMON-DBLDLXFLEX-DBLDLX",
        "code": "DBLDLXFLEX",
        "name": "DOUBLE DELUXE FLEX",
        "description": "DOUBLE DELUXE FLEX RATE",
        "isSubjectToCityTax": true
    },
    "unitGroup": {
        "id": "HARMON-DBLDLX",
        "code": "DBLDLX",
        "name": "Deluxe Double Room",
        "description": "20m, Parc and Street side "
    },
    "totalGrossAmount": {
        "amount": 50.76,
        "currency": "EUR"
    },
    "arrival": "2020-08-20T12:58:39+02:00",
    "departure": "2020-08-21T10:30:00+02:00",
    "created": "2020-08-17T10:09:34+02:00",
    "modified": "2020-08-20T14:25:44+02:00",
    "adults": 1,
    "guestComment": "Cubilis ID: 31082891 \nExternal ID: CPB-2933-011146 \nPrice for 2020-08-05: EUR 50.76 (Standard Rate)",
    "channelCode": "Direct",
    "primaryGuest": {
        "title": "Mr",
        "firstName": "redacted",
        "lastName": "redacted",
        "identificationType": "redacted"
    },
    "timeSlices": [
        {
            "from": "2020-08-20T12:58:39+02:00",
            "to": "2020-08-21T10:30:00+02:00",
            "serviceDate": "2020-08-20",
            "ratePlan": {
                "id": "HARMON-DBLDLXFLEX-DBLDLX",
                "code": "DBLDLXFLEX",
                "name": "DOUBLE DELUXE FLEX",
                "description": "DOUBLE DELUXE FLEX RATE",
                "isSubjectToCityTax": true
            },
            "unitGroup": {
                "id": "HARMON-DBLDLX",
                "code": "DBLDLX",
                "name": "Deluxe Double Room",
                "description": "20m, Parc and Street side "
            },
            "unit": {
                "id": "HARMON-RTM",
                "name": "ROOM 54",
                "description": "DESCRIPTION",
                "unitGroupId": "HARMON-DBLDLX"
            },
            "baseAmount": {
                "grossAmount": 50.76,
                "netAmount": 47.89,
                "vatType": "VeryReduced",
                "currency": "EUR"
            },
            "totalGrossAmount": {
                "amount": 50.7600000000,
                "currency": "EUR"
            }
        }
    ],
    "guaranteeType": "CreditCard",
    "cancellationFee": {
        "id": "HARMON-FLEX",
        "code": "FLEX",
        "name": "Flexible",
        "description": "Free cancellation until 48 hours prior to arrival",
        "dueDateTime": "2020-08-18T14:00:00+02:00",
        "fee": {
            "amount": 50.7600000000,
            "currency": "EUR"
        }
    },
    "noShowFee": {
        "id": "HARMON-NONREF",
        "code": "NONREF",
        "fee": {
            "amount": 50.7600000000,
            "currency": "EUR"
        }
    },
    "travelPurpose": "Business",
    "balance": {
        "amount": 0.00,
        "currency": "EUR"
    },
    "allFoliosHaveInvoice": false,
    "taxDetails": [
        {
            "vatType": "VeryReduced",
            "vatPercent": 6.0,
            "net": {
                "amount": 47.89,
                "currency": "EUR"
            },
            "tax": {
                "amount": 2.87,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Reduced",
            "vatPercent": 12.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Normal",
            "vatPercent": 21.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Null",
            "vatPercent": 0.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Without",
            "vatPercent": 0.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        }
    ],
    "hasCityTax": true,
    "payableAmount": {
        "guest": {
            "amount": 0.0000000000,
            "currency": "EUR"
        }
    }
}
```

**Comment by WinniX** [comment]
Hello @lukhug 

As far as I can see from the reservation details above it's a valid overnight reservation (not a day-use one). My conclusion based on the following:
1) arrival and departure are not on the same day;
2) there is only 1 time slice in the `timeSlices` array;
3) the rate plan was created with `Overnight` template.

Also I see that the `checkInTime` and `checkOutTime` are set for the same day, but this is a valid use-case for overnight rate plan.

Could you clarify why do you think this reservation supposed to be a day-use?

--
Eugene / apaleo Team

**Comment by lukhug** [comment]
Thanks for the quick feedback! 
We investigated this particular night as we seemed to have one more unit sold in our system vs Apaleo (for overnight stays). After closer investigation we noticed that this reservation had a check-in and check-out within 2h and therefore assumed it’s a day use booking. Sounds like we were wrong about this?

**Comment by WinniX** [comment]
Yep, a guest may want to check-out on the same day as check-in date. It doesn't mean that the reservation's rate plan template should be changed to be Day-Use.

**Comment by lukhug** [comment]
Thanks for clarifying. I will have to review this night then again to understand where this discrepancy is coming from. How would you suggest to "debug" discrepancies like this? 

I've raised another ticket earlier requesting for help in discrepancies with another property a customer has raised with us. Perhaps easier to move the conversation there and close this ticket?
https://github.com/apaleo/api/issues/406

**Comment by WinniX** [comment]
I think worth to try our General Manager report. You may find it useful, since it has an option DayUse/Overnight, and there you could see the detailed view (for each day).

**Comment by elistoilova** [comment]
Hello WinniX,

I think the issue comes from the fact that this was intended to be a regular overnight reservation but the guest checked out early so the rate plan remained to an overnight one.   You can also see that departure is the same for both  reservations so it seems it instead means “expected departure“.   Here is the other reservation for the same room later on the   same day, you can see the room in unit -> name:  
{
    "id": "LDVQIKYV-1",
    "bookingId": "LDVQIKYV",
    "status": "CheckedOut",
    "checkInTime": "2020-08-20T21:57:23+02:00",
    "checkOutTime": "2020-08-21T12:42:08+02:00",
    "unit": {
        "id": "HARMON-RTM",
        "name": "ROOM 54",
        "description": "DESCRIPTION",
        "unitGroupId": "HARMON-DBLDLX"
    },
    "property": {
        "id": "HARMON",
        "code": "HARMON",
        "name": "HARMON HOUSE"
    },
    "ratePlan": {
        "id": "HARMON-DBLDLXFLEX-DBLDLX",
        "code": "DBLDLXFLEX",
        "name": "DOUBLE DELUXE FLEX",
        "description": "DOUBLE DELUXE FLEX RATE",
        "isSubjectToCityTax": true
    },
    "unitGroup": {
        "id": "HARMON-DBLDLX",
        "code": "DBLDLX",
        "name": "Deluxe Double Room",
        "description": "20m, Parc and Street side "
    },
    "totalGrossAmount": {
        "amount": 55.00,
        "currency": "EUR"
    },
    "arrival": "2020-08-20T20:38:17+02:00",
    "departure": "2020-08-21T10:30:00+02:00",
    "created": "2020-08-20T20:39:01+02:00",
    "modified": "2020-08-21T12:42:08+02:00",
    "adults": 1,
    "channelCode": "Direct",
    "primaryGuest": {
        "gender": "Male",
        "lastName": "Kalmen",
        "email": "Adam_kalmen@outlook.fr",
        "phone": "0466275643",
        "preferredLanguage": "fr",
        "birthDate": "1998-11-04"
    },
    "guaranteeType": "CreditCard",
    "cancellationFee": {
        "id": "HARMON-FLEX",
        "code": "FLEX",
        "name": "Flexible",
        "description": "Free cancellation until 48 hours prior to arrival",
        "dueDateTime": "2020-08-20T20:39:01+02:00",
        "fee": {
            "amount": 55.0000000000,
            "currency": "EUR"
        }
    },
    "noShowFee": {
        "id": "HARMON-NONREF",
        "code": "NONREF",
        "fee": {
            "amount": 55.0000000000,
            "currency": "EUR"
        }
    },
    "balance": {
        "amount": 0.00,
        "currency": "EUR"
    },
    "allFoliosHaveInvoice": false,
    "taxDetails": [
        {
            "vatType": "VeryReduced",
            "vatPercent": 6.0,
            "net": {
                "amount": 51.89,
                "currency": "EUR"
            },
            "tax": {
                "amount": 3.11,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Reduced",
            "vatPercent": 12.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Normal",
            "vatPercent": 21.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Null",
            "vatPercent": 0.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        },
        {
            "vatType": "Without",
            "vatPercent": 0.0,
            "net": {
                "amount": 0.0,
                "currency": "EUR"
            },
            "tax": {
                "amount": 0.0,
                "currency": "EUR"
            }
        }
    ],
    "hasCityTax": true,
    "payableAmount": {
        "guest": {
            "amount": 0.0000000000,
            "currency": "EUR"
        }
    }
}

Reagards,
Eli

**Comment by elistoilova** [comment]
Hello,

I would like to follow up on how would you treat the above case?
Thanks,
Eli

**Comment by lukhug** [comment]
Hey, would be great to get an update here. I asked my colleague @elistoilova to fill in the details as I was unavailable a few days ago. Sorry if this caused confusion 😊

**Comment by WinniX** [comment]
Hey @elistoilova and @lukhug 

Sorry for the delay. 
The `departure` in the json above means "expected departure". That's why reservations also have `checkInTime` and `checkOutTime`. So, it's totally a legal case when you have 2 reservations on the same day with the same assigned unit, as long as these reservations are not conflicting with each other (based on `checkOutTime` field).

Hope this helps.

---
Eugene / apaleo Team

**Comment by lukhug** [comment]
Hey @WinniX, thanks for getting back 👍 

So, just to clarify: 
- the first example reservation TZRTRCBB-1 is on an overnight rate plan for ROOM 54. However, check-in and check-out time are on the same day. So it looks to me like a day booking on an overnight rate plan. Which you mentioned earlier is a valid case - but why would a day use booking be on an overnight rate plan? And how are you counting them in Apaleo?
- the second example reservation LDVQIKYV-1 is just a standard night reservation - but also in ROOM 54

So for us to exclude Day Use bookings we can't only rely on the rate plan (and associated time slices) but we also need to check "checkInTime" and "checkOutTime".

Is this a fair summary of the discussion above?

**Comment by WinniX** [comment]
Hey @lukhug 

Right, the reservation `TZRTRCBB-1` is an overnight, because it was created for a rate plan `DOUBLE DELUXE FLEX`. And as I mentioned earlier check-out time doesn't change time slice template of the rate plan. Meaning that the reservation is still an overnight one, and the only thing that changes is the availability of the unit, so it becomes available for another reservation later this day.
And yes, if you need to exclude the bookings, that was created for an overnight rate plan, but suddenly checked out on the same day - you need to check the `checkOutTime`. We just don't call these bookings a day-use, because they were not created with a rate plan with a Day-Use time slice template.
My suggestion here would be to create a day-use bookings for a day-use rate plans. Then you could easily keep track of them.

---
Eugene / apaleo Team

**Comment by lukhug** [comment]
Hi @WinniX, your feedback here was super helpful. We adjusted the interpretation of bookings coming in our direction to handle bookings with an early check-out appropriately. 

However, one question that just came up: What if a guest checks out the evening before the departure but still stays overnight? Is this possible? Or can we always assume that the check-out date is also the date the guest left the property? 

Just wondering as now, as described in the first paragraph, we are filtering our Day Use bookings on an overnight rate plan. But more generally, we are also updating bookings that check out a day earlier than their departure date. 
Example:
Arrival date: 01/09/2020
Check-in date: 01/09/2020
Departure date: 05/09/2020
Check-out date: 04/09/2020
We will now track this booking with 3 nights instead of 4 nights. Is this correct?
