### ISSUE TITLE
Units Sold / Revenue Discrepancies between Apaleo and our System

### ISSUE THREAD

**Issue by lukhug** [apaleo/api#406]
## Question

A shared customer reported some discrepancies on Sold Units & Revenue. To help with the investigation of this particular instance, I wanted to export some sort of report from Apaleo where we can quickly can compare daily figures (units sold and net accommodation revenue), to find nights where we have discrepancies and then filter for the reservations to see where the issue is. However, this seems to be challenging in the Apaleo UI? Can somebody please help me do some sort of data validation here and provide me with a report.
Not sure what the best way is to do this.

**Comment by abarbarov** [comment]
Hi @lukhug. 
Thank you for the question. Looks like you are talking about "General Manager" report, that could be found under "Reports" section on the menu. Basically It uses https://api.apaleo.com/swagger API internally, so if you can't find something on UI, you can try to fetch the raw data directly from swagger (Reports API).


BR, 
Afanasy, apaleo Team

**Comment by lukhug** [comment]
Hi Afanasy, yes something like that would be helpful. However, when I export a report here I only get 30 nights at once (meaning I need to run the report multiple times). And I also don't get accurate revenue figures but only aggregated & rounded to 2.2k which is useless for accurate data validation. Is there really nothing else?

**Comment by dario-hd** [comment]
Hi,

using the API you can get more days at once and the revenues are not rounded. Anyway, those revenues might not be what you are looking for because they are forecasted revenues and they do not include charges posted directly on the folio. If you are looking for real revenues you might want to take a look at the revenues report in the same reports API. Also, I just wanted to mention, that if you are calculating the number of sold units on your side there might be some discrepancies because there are different edge cases that you need to consider. I wouldn't try to mimic our logic here.

**Comment by lukhug** [comment]
Hi, thanks for sharing. Will have a look at the reports API to understand this better. 
Not sure I agree with your view on numbers between Apaleo and our system likely won't match due to a different logic. The first thing customers do is compare numbers between both systems. If they are wrong, it affects trust massively. So we should definitely strive for consistency here.

Fortunately, our units sold discrepancy is tiny and therefore neglectable. However, there are discrepancies in revenues according to the customer when comparing to another Analytics solution. We don't know who is right as we cannot see the revenue figures in Apaleo though. Hopefully, the reporting endpoint will resolve this.

**Comment by dario-hd** [comment]
I understand your point, but in to calculate such numbers we (and you) apply some logic. For example, just to name a few:
 * What do you do when you have a single reservation but you have a double unit assigned?
 * What do you do when you have multiple reservations within the same "night" (e.g. early checkout and late check-in)
 * What do you do when you have a late check-in (e.g. checking in after midnight)
So, we apply some logic, which if it doesn't match on both sides we will always have some discrepancies. I would suggest you use the results from our API here.

**Comment by lukhug** [comment]
It would be great to have documentation on this from your side so app providers like us could validate against this at least. What we are trying to do currently is implement an audit system which in regular intervals checks that we received all messages accordingly and there are no issues in the implementation. However, if we don't know how numbers are calculated, this seems impossible to achieve a 100% match. 

Regarding the reports endpoint: looks like we didn't add this to our scope initially. So we will have to ask all our Apaleo customers to go through the onboarding flow again and provide us with new refresh tokens. Or is there an easier way?
