### ISSUE TITLE
Getting reservations with dateFilter option

### ISSUE THREAD

**Issue by ikrav4ic** [apaleo/api#408]
## Question

Hi all,
I've tried to get all reservations by /booking/v1/reservations - everything is ok (getting near 1500 data rows).
So I'm looking for some filtering of these data.
At https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1
I find some options with dataFilter.
My request query looks now looks like:
`/booking/v1/reservations?propertyId=' . $id . '&dateFilter=Arrival&from=' . $date_from . '&to=' . $date_to`
$date_from and $date_to I'm sending in `Y-m-d H:m:s` format
But no data or some errors back.
Can you help me?

**Comment by WinniX** [comment]
Hello @ikrav4ic 

Please make sure the date format is [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601), e.g. `2020-09-10T12:32:03Z`
If so, please send us the TrackingId of your request.

---
Eugene / apaleo Team
