### ISSUE TITLE
No-Show

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#409]
Does Apaleo send us no-shows on Bookings sent by us ? Is this mandatory for us to implement this ?

Does Apaleo take no-shows on bookings from us ? Is this mandatory for us to implement this ?

**Comment by alokbash** [comment]
Hi @VasaviBoddeti,

Please let me know if I understand this correctly.

You are sending a booking to apaleo and you want to know whether the guest was a no-show? If yes, then you want to be notified?

For the second part, are you asking whether your booking can be a no-show? (Ans - Yes. Sometimes guests don't cancel the reservation and don't show up. In that case, apaleo automatically detects all the reservations that should have been checked in but weren't, and sets their status to no-show.)

Regards,
Alok

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Your undersstanding for the first part is right. I would like to know, if you send us such no-show on bookings to us, is it mandatory for us to take it and implement it on our end further ? Please advise.

For the second part, if we had to send no-show for any booking which is already pushed to Apaleo, how can we do so ?

**Comment by alokbash** [comment]
Hi Vasavi,

If you don't have a use case around no-show, then it is not required for the certification process. Nevertheless, if you want to get notified when a reservation is a no-show in apaleo, then you can use the `set-to-no-show` [webhook event](https://apaleo.dev/guides/start/webhook/configuration).

It is not required to send us a no-show, but if you want to do it, then you can use the `PUT /booking/v1/reservation-actions/{id}/noshow` endpoint.

Regards,
Alok
