### ISSUE TITLE
Push Reservation updates

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#41]
## Question

Is there a support for pushing reservations to us?
Currently we have to pull the data every 5 minutes.

## Background

The problem is that we have to fetch all reservations and look for updates. If there are a lot of reservations it could be problematic to do everything in 5 minutes untill the next call.
To reduce the amount of data, we added the _dateFilter=Creation_ to the request

`GET "booking/v1/reservations?propertyIds=#property_id#&dateFilter=Creation&from=#timestamp 2 weeks before"`

The problem is now following: Someone creates a reservation and arrives 4 weeks later.
So I will not get the information by this scope, because it was not created within the last 2 weeks.

**Comment by pgrm** [comment]
Hello @c2ofh 

have you seen our notifications API at https://notifications.apaleo.com/swagger/index.html ?

There you can subscribe to reservation changes. You can read more about it in https://apaleo.com/push-it-webhooks-in-apaleo/

**Comment by c2ofh** [comment]
Workes well.
