### ISSUE TITLE
Total Guest Count to be split for each room reservation

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#411]
We usually get the total guest count for the whole booking irrespective of number of rooms reserved within that booking. So, when we have to send such booking to Apaleo with multiple rooms reserved, how should we split or break-up the total guest count to each room/reservation in 'adults' filed. Please advise.

**Comment by nfidirko** [comment]
Hey @VasaviBoddeti,

Yes, you have to specify the number of adults for each room separately.
Basically, you'll have to get the max occupancy for the selected unit groups and use this information to distribute the number of guests into reservations accordingly.
There are 2 ways to do that:
- `Offer API` (`GET ​/booking​/v1​/offers`), use the `unitGroup.maxPersons` property. You're most probably already using this API;
- `Inventory API` (`GET ​/inventory​/v1​/unit-groups`).
