### ISSUE TITLE
Get Invoices without propertyId

### ISSUE THREAD

**Issue by branog68** [apaleo/api#412]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)

**API: API /finance/v1/invoices**

**Expected behavior: Since a few weeks this API can also be used for several properties at once. But I miss in the result the propertyId. I don't see which invoice belongs to which property. **

**Actual behavior:**

**Related Issues:**

**Comment by WinniX** [comment]
Hello @branog68 

I agree that `propertyId` should be a part of the response. We will add this one into our backlog. 

--
Eugene / apaleo Team

**Comment by WinniX** [comment]
Hello @branog68 

Thank you for your patience. 
The feature that you have requested recently is ready. Please check it out.

---
Eugene / apaleo Team
