### ISSUE TITLE
GET /reports/v1/reports/property-performance - `source` filter

### ISSUE THREAD

**Issue by Denitz** [apaleo/api#413]
## I want

To be able to filter property performance report data by a Source (a sub-division of ChannellManager channel).

## Use cases

We can see the data filtered by ChannellManager channel using `channelCodes` filter but not via any sub-division of this channel code.

## Examples

See the data for "Channel manager: Cubilis IBE".

## What I do

Analytics.

**Comment by dario-hd** [comment]
Hi @Denitz, I think you asked for this already :)

https://github.com/apaleo/api/issues/372
