### ISSUE TITLE
Closed for Departure not transmitted to us

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#414]
While testing observed for the below case from 'Apaleo' we have received wrong 'Closed on departure' status.

Case: Set restriction 'Closed' & 'Closed on departure' as true in 'Apaleo' extranet for any dates.

To test above case we set restriction true to 'Closed' & 'Closed on departure' for the date 17-Oct-2020 to ratePlanId":"BER-DOUBLE_ON-DB" from Apaleo extranet, And it's reflected fine in extranet but we have received restriction true only for 'Closed' and for remaining as false.

Find below json request 'Apaleo' to 'Cultuzz' for reference, please clarify on above case.

```
{
    "accountId": "KAFB",
    "propertyId": "BER",
    "timeSlices": [
        {
            "ratePlanId": "BER-DOUBLE_ON-DBL",
            "unitGroupId": "BER-DBL",
            "from": "2020-10-17T17:00:00+02:00",
            "to": "2020-10-18T10:00:00+02:00",
            "restrictions": {
                "closed": true,
                "closedOnArrival": false,
                "closedOnDeparture": false,
                "changes": [
                    "closed"
                ]
            }
        }
    ]
}
```

Find the attached screenshot for reference.
![Departure clarification](https://user-images.githubusercontent.com/64488734/94532005-f1aea980-025a-11eb-9300-56b309da24c0.png)

**Comment by WinniX** [comment]
Duplicate https://github.com/apaleo/api/issues/348

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

But the Rateplan DOUBLE_ON  is mapped to the channel manager. 

Here our case is that though we have set the restrictions "Closed" and "Closed to Departure" as "True" fr 17th October 2020 for BER-DOUBLE_ON-DB, we have received the update as "TRUE" only for "Closed" and "FLASE" for "Closed to Arrival" and "Closed to Departure".

Why is this so, please clarify. Thank You.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by abarbarov** [comment]
Hi @VasaviBoddeti,

You received a `delta` ARI notification. This means, that only changes were sent. 

What I find in logs is that you firstly you set restrictions like these `{"closed":true,"closedOnArrival":false,"closedOnDeparture":true}`, and the with the next request changed them to `{"closed":false,"closedOnArrival":false,"closedOnDeparture":true}`. 

As you may notice, the changed part is only `closed`, that is why you got only `closed` in the changes list.

Please check the guide https://apaleo.dev/guides/business-cases/channel-integration/ari-data.

**Comment by VasaviBoddeti** [comment]
Dear 

Please find my team feedback below on your clarification:
----------------
> As you may notice, the changed part is only closed, that is why you got 
> only
> closed in the changes list.

This is not correct, we have done changes at a time like 
{"closed":true,"closedOnArrival":false,"closedOnDeparture":true} and for 
that we received delta ARI notification like below (i.e received 
"changes":["closed"]).

> {"accountId":"KAFB","propertyId":"BER","timeSlices":[{"ratePlanId":"BER-DOUB
> LE_ON-DBL","unitGroupId":"BER-DBL","from":"2020-10-17T17:00:00+02:00","to":"
> 2020-10-18T10:00:00+02:00","restrictions":{"closed":true,"closedOnArrival":f
> alse,"closedOnDeparture":false,"changes":["closed"]}}]}

Before changes, status for that date:2020-10-17 is 
{"closed":false,"closedOnArrival":false,"closedOnDeparture":false}

For your better understanding see my below screen recording of same case 
for another date. And find delta ARI notification of that changes.

Screen recording: 
https://drive.google.com/file/d/1GQJ1HSYgQVpX5KEGguny8ES1zuWvuX9l/view?usp=sharing

{"accountId":"KAFB","propertyId":"BER","timeSlices":[{"ratePlanId":"BER-DOUBLE_ON-DBL","unitGroupId":"BER-DBL","from":"2020-10-01T17:00:00+02:00","to":"2020-10-02T10:00:00+02:00","restrictions":{"closed":true,"closedOnArrival":false,"closedOnDeparture":false,"changes":["closed"]}}]}
---------------------------------

Please advise.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by VasaviBoddeti** [comment]
Gentle reminder please

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

The thing is that once you receive `"closed":true` the all other restrictions do not make sense anymore, because the rate is closed. 
But don't worry about the changes you made with `closedOnDeparture`, you will receive this change once you open the rate again by setting `"closed":false`.

Hope this helps.

--
Eugene / apaleo Team

**Comment by VasaviBoddeti** [comment]
Dear Eugene,

I have a usecase, where I need to explicitly apply close for departure, though the rate is closed for a day. Please find the usecase below:

For suppose I want to apply "Close" and "Close to departure" for Double_Room_On_Rate for the date: 22nd October 2020. And lets suppose, I would like to make a booking for this same rate for 21st October 2020 with the Arrival on 21st October and Departure on 22nd October 2020. As this is rate is closed for sale for 22nd October (which means, the rate is not bookable for this date), I will still be able to make this booking for 21st October, as 22nd October is not set to Departure close for this rate, as per your logic.

But to me, as I have applied "Closed for departure" also for 22nd October, this booking should not be made possible. So that means, we are missing this case here.

Please advise, how do you handle such a case.

Thank You.
Vasavi
----
