### ISSUE TITLE
Referer in UI integration

### ISSUE THREAD

**Issue by nuno-sousaHZ** [apaleo/api#415]
`Apaleo-Tracking-Id`: (for the request which didn't work as expected)
Could not find tracking Id, here is the request context:
appId=cid-v1:e35dff32-23c8-4a08-8d79-9995b8594a05
**Code**
Current referer =  https://app.apaleo.com/
Expected referer = https://app.apaleo.com/{HotelCode}/reservations/{ReservationCode}/{AccountName}-RESERVATIONDETAILSTAB
**Expected behavior:** The Iframe should be displayed correctly on all browsers. For that the correct Referer is needed.
Referer = https://app.apaleo.com/{HotelCode}/reservations/{ReservationCode}/{AccountName}-RESERVATIONDETAILSTAB
**Actual behavior:** The Iframe is not correctly displayed in **Chrome** because the referer doesn't have the needed information to load the page (the HotelCode is only present in the referer and not in the request URL). This does not happen on other browsers.
Current referer =  https://app.apaleo.com/

**Related Issues:**  N/A

**Comment by randyrod** [comment]
Hi @nuno-sousaHZ 

Thanks for reaching out. You are getting this when trying to load the integration?

Could you share the version of chrome that you are using?

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Yes, it's when we're trying to load the integration.

The version of the Chrome is : Version 85.0.4183.121 (Official Build) (64-bit)

Thank you.

**Comment by ruitguerra** [comment]
Hi Randy. This has been open for a week and is really troubling because our clients use it to manage daily operations. Philip  von Ditfurth and others at Apaleo are also blocked in their presentations. When will you deliver the fix? Could you get back to Nuno and our team asap? Thanks, Rui

**Comment by ruitguerra** [comment]
Hi Randy.
Any news on this?
It's really urgent. We need your feedback.
Thanks, Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>




Le mar. 29 sept. 2020 à 15:54, Randy Collado <notifications@github.com> a
écrit :

**Comment by ruitguerra** [comment]
Hi Randy. Any news on this? It's been 2 weeks. Please give us some feedback.
Thanks,
Rui

**Comment by randyrod** [comment]
Hi @ruitguerra,

I'm very sorry for not getting back to you on a timely matter.

We are working on this issue from our side, and will get back to you very shortly. 

Again sorry for the delay.

**Comment by randyrod** [comment]
Hi @ruitguerra,

I wanted to get a quick idea of the reason behind having this information in the referrer.

- Are you parsing this information that you get from the referrer?
- If so, what information are you extracting from it?

We are already sending in the query parameters to your integration the `AccountCode`, `ReservationId`, and the `subjectId` of the source as query parameters.

For instance `https://www.yourintegrationurl.com?accountCode={HotelCode}&lang=en&reservationId={ReservationId}&subjectId={GUID}`

I'd recommend getting the information from the query parameters which are the ones that we have control of, and if you are missing some information we could discuss it and add it.

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Yes, we're parsing the information we get from the referer.
We're using the referer field due to the "HotelCode" parameter.

So, we need the "HotelCode" field to be added to the query parameters.

Thanks.

Best regards,

Nuno Sousa

**Comment by randyrod** [comment]
Hi,

Then let me do some quick research on our code base to see what the best solution is for it, and I will get back to you ASAP.

Regards,
Randy

**Comment by randyrod** [comment]
Hi @nuno-sousaHZ,

We will add the `propertyId` as a query parameter instead of changing the referrer header. It is a more efficient and controllable way, as the referrer may vary from browser to browser, but the query parameters we can handle ourselves.

This fix should be ready today, I will inform you once it is deployed.

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Ok, thank you for the update.

Best regards,

Nuno Sousa

**Comment by randyrod** [comment]
Hi @nuno-sousaHZ 

Just checking, was the change useful/helpful for you guys?

Regards,
Randy

**Comment by nuno-sousaHZ** [comment]
Hi Randy,

Yes, the change was helpful.

Thanks.

Best regards,

Nuno Sousa

**Comment by ruitguerra** [comment]
Thanks Randy.
It's working now.
Rui

*RUI TEIXEIRA GUERRA*
*CEO - Hotelappz*

*www.hotelappz.com <http://www.hotelappz.com/>*
rui.guerra@hotelappz.com <ruitguerra@hotelappz.com>
+33 6 6155 5460

[image: http://www.hotelappz.fr/] <http://www.hotelappz.fr/>


<https://www.linkedin.com/in/ruiteixeiraguerra/>

Want to Know you Guests better? Find out what Hoteliers think about
Hospitality CRMs
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>

*HotelAppz interviews 3 seasoned and forward looking Hoteliers*

<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>
[image: HotelAppz interviews 3 seasoned and forward looking Hoteliers]
<https://www.hotelappz.com/know-your-guests-what-do-hoteliers-say-about-crm/>




Le ven. 16 oct. 2020 à 15:36, Randy Collado <notifications@github.com> a
écrit :

**Comment by randyrod** [comment]
Hey,

Glad to know, again sorry for the delay in reply.

Best regards,
Randy
