### ISSUE TITLE
Link to app onboarding guide

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#417]
In the certification request form, as per the below point, is it must to submit the link of the on-boarding guide. Or if there is any other option to upload the document, please let us know:

11.Please provide a link to your app onboarding guide (1-2 page document).
The onboarding guide will be used by the hotels to connect to your app. For example, it might have sections on how the hotel will connect your app to apaleo, how to disconnect the app, how to contact support, and so on.

**Comment by alokbash** [comment]
Please upload it to any doc sharing site like Dropbox, Google Drive, etc., and share the link in the form.

**Comment by VasaviBoddeti** [comment]
Dear Alok,

Thank you so much.

To which email ID, should I share the document in google drive, please advise.

Kind regards,

Vasavi Boddeti
Partner Manager

Cultuzz India Pvt. Ltd.
No 47-9-14, Ganta Arcade,
Dwaraka Nagar 3rd Lane,
Visakhapatnam - 530016

Tel. +91 8913053333
Tel. +91 9985922397
vasavi.boddeti@cultuzz.com

**Comment by alokbash** [comment]
Thanks, Vasavi. We are able to access the document.
