### ISSUE TITLE
Failed payment management

### ISSUE THREAD

**Issue by Nedson202** [apaleo/api#419]
## Question

I dug through the documentation for configuring webhooks in search of an appropriate hook that notifies us of failed payments but couldn't find any. How would one manage or react to a failed payment using one of your Folio events and does such an event exist currently?
## Background

Since payment addition is asynchronous and some of our reservation processes require that a reservation is paid for already and not in a `Pending` state, for all such payments in a `Pending` state, we manage further processing under the `payment-posted` event when the payment goes through successfully.

In the event that the pending payment fails, is there a folio event that can notify us of such?

**Comment by ozonni** [comment]
@Nedson202 there is no webhook event for failed or successful payment. It is in our backlog and we are going to add it. Subscribe to [api announcements](https://github.com/apaleo/announcements) to get notified when it get's released. For now you can poll and call `get payment` api to get the payment status.
