### ISSUE TITLE
Unique guest identifier

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#420]
Hi,

yes, I know you don't have profiles with an id when we request a reservation.
But there must be a unique identifier for the attached guest inside the reservation.
This information would be nice to find out, if we already stored the guest in our database. 

We want to prevent duplicate guest profiles. But this is only possible with some kind of unique attribute. 
Is anything planned in this direction in the future?

## I want

A unique identifier for guests in a reservation

## Use cases

When we stored the reservation and reload the reservation by the api, I currently look for the email-address and update the matching guest. When there is no email-address, we can just update the guest from top to down. 
Luckily we have an email-address in almost all reservations.
There are cases I still not find the issue, where our logic fails, when there is no email-address.

**Comment by WinniX** [comment]
Hello @c2ofh 

Thanks for sharing your use-case with us. Luckily, this is the feature we are developing right now. We are working on the MVP version of it, stay tuned in order not to miss any further announcements. 

---
Eugene / apaleo Team

**Comment by c2ofh** [comment]
@WinniX Thank you for the great news :)

**Comment by martijn80** [comment]
Great news. Will be watching this update with interest as well.

**Comment by lsemaan** [comment]
hi, if you can also include the created/modified date of the guest profile, so we know when to update the profile of the guest on our side. thanks

**Comment by WinniX** [comment]
Hi @lsemaan,

Thanks for the feedback. Created/Updated dates will be there of course.

-- Eugene / apaleo Team
