### ISSUE TITLE
Possibility to add pending payments

### ISSUE THREAD

**Issue by nziehn** [apaleo/api#421]
## I want

- be able to add "pending" payments - we're using additional PSP to Apaleo and would like to include our own pending payments, similar to the exisitng pay-by-link feature implemented by Apaleo
- After creating the pending payment, I of course also need to be able to complete it via the API (cancellation is already possible)

## Use cases

- Offer more payment options and have better control over 3d secure payment authorisation, we use in some cases our own payment links (using stripe). But we can only show these payments after being completed, not while they are pending.

**Comment by ozonni** [comment]
@nziehn could you please tell us more what exactly is missing in apaleo payment? what do you mean when you say `better control over 3d secure payment authorisation,` ?
