### ISSUE TITLE
Parameter for clean room only when assigning room

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#422]
## I want

A boolean Parameter, something like `cleanRoom=true` for 
**PUT** ​/booking​/v1​/reservation-actions​/{id}​/assign-unit

## Use cases

If we want to assign a room for a check-in in the future, it does not matter if the room is dirty right now.
But when the guest wants to check in now and no room was assigned yet, we use this endpoint to assign a room to the reservation.
Because the room is needed right now, the api should assign only a clean room for the guest.

**Comment by http-request** [comment]
Hello,

Thank you for your feedback!

Can you consider the following scenario: 
get list of rooms with needed condition and unit group by `/inventory/v1/units?unitGroupId=DBL&condition=Clean`, 
pick up some unit and then assign it with reservation by `/booking/v1/reservation-actions/{id}/assign-unit/{unitId}` 
?

Best regards,
Svyatoslav

**Comment by WinniX** [comment]
Hello @c2ofh 

I would like to accompany Svyatoslav's answer here with some small detail. Whenever you call `/assign-unit` endpoint - we will try to find the clean room first, and if no clean rooms are available - we will assign any room which is available, which could be a in a dirty state.

---
Eugene / apaleo Team

**Comment by c2ofh** [comment]
Hello @WinniX 
Thank you for the info. Good to know. Thought the assigning is randomly. 

@http-request This was my plan B if the endpoint would assign the room without checking the status.
