### ISSUE TITLE
403 on GET account/v1/accounts

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#424]
## Question

Why GET account/v1/accounts gives a 403 even though the app has all possible scopes enabled?

## Background

Trying to run this on our sandbox account. Full URL: https://api.apaleo.com/account/v1/accounts

**Comment by bennetone** [comment]
Hey @tmmartti ,

all apps always work only in the context of one specific account as they are also only authorized for a subset of accounts. We cannot expose the data of all accounts available on the apaleo platform without the authorization of the resource owners, which are the apaleo customer.

For this API you would need to have the `accounts.read` scope, which you will find is not available as a scope you can set for an API client. The only scope available for public apps is `account.manage`. This one will allow you to update the data for the account that you are currently authenticated for.

![image](https://user-images.githubusercontent.com/25197867/98220334-6ce83700-1f4e-11eb-9b54-c33092c4ec78.png)

Cheers!
