### ISSUE TITLE
Closed to Departure for previous day booking

### ISSUE THREAD

**Issue by VasaviBoddeti** [apaleo/api#425]
Dear Eugene,

I have a usecase, where I need to explicitly apply close for departure, though the rate is closed for a day. Please find the usecase below:

For suppose I want to apply "Close" and "Close to departure" for Double_Room_On_Rate for the date: 22nd October 2020. And lets suppose, I would like to make a booking for this same rate for 21st October 2020 with the Arrival on 21st October and Departure on 22nd October 2020. As this is rate is closed for sale for 22nd October (which means, the rate is not bookable for this date), I will still be able to make this booking for 21st October, as 22nd October is not set to Departure close for this rate, as per your logic.

But to me, as I have applied "Closed for departure" also for 22nd October, this booking should not be made possible. So that means, we are missing this case here.

Please advise, how do you handle such a case.

Thank You.
Vasavi

**Comment by WinniX** [comment]
Hello @VasaviBoddeti 

If you want to disallow creation of a booking with arrival on 21st and departure on 22nd, you would need to apply a restriction "Closed for departure" on 21st (not 22nd). On first look, it may appear weird, but let me explain you why it's like this. As you know each date in the Rates Calendar actually dedicates to a certain time frame. For example, the 21st of October in the calendar is covering a night (for overnight templates) from 21st (arrival) to 22nd (departure). It means, if you want to set a departure restriction for 22nd of October - you need to use a 21st of October as a date in the calendar. 

Considering this, please adjust your setup and if some use-case is still not possible - just tell us about it.

--
Eugene / apaleo Team
