### ISSUE TITLE
API liefert 4xx invalid_request

### ISSUE THREAD

**Issue by t-haze** [apaleo/api#426]
Die API liefert für den Token-Endpoint https://identity.apaleo.com/connect/token seit einigen Stunden einen 400 (message-body: "invalid_request").
In der Doku sehe ich, dass dort an https://identity.apaleo.com/connect/authorize gesendet wird. Hier bekomme ich einen 415 response ohne message-body.

Vielen Dank,
TH

**Comment by bennetone** [comment]
Hey @t-haze 

can you try to adjust your php code like this:

```
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, 'grant_type=client_credentials');
curl_setopt($curl, CURLOPT_USERPWD, '<<client-id>>:<<client-secret');
curl_setopt($curl, CURLOPT_HTTPHEADER, array(
  'Content-Type: application/x-www-form-urlencoded'
));
```

Important are those lines to be added:
```
curl_setopt($curl, CURLOPT_POSTFIELDS, 'grant_type=client_credentials');
curl_setopt($curl, CURLOPT_HTTPHEADER, array(
  'Content-Type: application/x-www-form-urlencoded'
));
```

Let me know if this helped

**Comment by t-haze** [comment]
Hi, works like a charm, thank you very much!
