### ISSUE TITLE
POST rate plans gives 422 "Custom accounts are disabled"

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#427]
## Question

POST rate plans gives 422 "Custom accounts are disabled". What does that mean?

## Background

Trying to post into the test account BER.

POST data:

{"code": "FLEXBREKUX", "propertyId": "BER", "unitGroupId": "BER-SGL", "cancellationPolicyId": "BER-FLE", "channelCodes": ["Direct", "Ibe", "BookingCom"], "serviceType": "Accommodation", "vatType": "ReducedCovid19", "promoCodes": null, "isSubjectToCityTax": true, "timeSliceDefinitionId": "BER-NIGHT", "name": {"de": "Flexibel - Das Frukost", "en": "Flexible - Breakfast included"}, "description": {"de": "Bleiben Sie voll flexibel und stornieren Sie unentgeltlich bis Mitternacht einen Tag vor Anreise. Als Garantie hinterlegen Sie bitte eine Kreditkarte.", "en": "Stay fully flexible with free cancellation until midnight one day prior to arrival. Just put your CC on file to guarantee the booking."}, "minGuaranteeType": "CreditCard", "bookingPeriods": [{"from": "2020-04-08T00:00:00+02:00", "to": "2020-04-14T23:59:59+02:00"}, {"from": "2020-04-15T00:00:00+02:00", "to": "2020-10-14T23:59:59+02:00"}, {"from": "2020-11-09T00:00:00+01:00", "to": "2024-12-31T23:59:59+01:00"}], "restrictions": {"minAdvance": {"hours": 0, "days": 3, "months": 0}, "maxAdvance": {"hours": 0, "days": 180, "months": 0}}, "pricingRule": null, "surcharges": [{"adults": 2, "type": "Absolute", "value": 5}, {"adults": 3, "type": "Absolute", "value": 5}, {"adults": 4, "type": "Absolute", "value": 5}, {"adults": 5, "type": "Absolute", "value": 5}, {"adults": 6, "type": "Absolute", "value": 5}, {"adults": 7, "type": "Absolute", "value": 5}, {"adults": 8, "type": "Absolute", "value": 5}, {"adults": 9, "type": "Absolute", "value": 5}], "ageCategories": null, "includedServices": [{"serviceId": "BERBRKF", "grossPrice": {"amount": 15.0, "currency": "EUR"}, "pricingMode": "Additional"}], "companies": null, "subAccountId": "BERFLEX"}

**Comment by nfidirko** [comment]
Hi @tmmartti,
sorry for the delayed response.

You can create revenue sub-accounts to have a better understanding of the structure of your revenues.
You can set sub-account id for rate plans, services, and charges.
A charge (posted directly or created based on a rate plan/service) will be posted to a specific revenue account defined by the sub-account.

In your example, the sub-account id is here:
> "subAccountId": "BERFLEX"

The error message `Custom accounts are disabled` means that you're trying to create a rate plan with a sub-account while sub-accounts are disabled for this property.

If you want to enable the sub-accounts, then you can use `PATCH ​/settings​/v1​/features​/{propertyId}` to enable them (the setting name is `areCustomRevenueSubAccountsEnabled `).

If you want to read more about sub-accounts, then the following links might be helpful:
- https://apaleo.dev/guides/business-cases/pos-integration/setup#specify-sub-accounts-on-charges 
- https://github.com/apaleo/announcements/issues/10
