### ISSUE TITLE
Posting multiple services (extras) with a reservation

### ISSUE THREAD

**Issue by EdwardIII** [apaleo/api#428]
## Question

Is there a way we can specify how _many_ of a service/extra to post along with a reservation?

Currently we post services like this `/booking/xx/bookings`: 

```
     "services": [
        {
          "serviceId": "MUC-BRKF"
        },
        {
          "serviceId": "MUC-YOGA",
          "dates": [
            {
              "serviceDate": "2020-11-22",
              "amount": {
                "amount": 35.0,
                "currency": "EUR"
              }
            }
          ]
        }
      ],
```

I don't see anything about quantity in the model:

![image](https://user-images.githubusercontent.com/412107/99808626-0d3a8000-2b39-11eb-970b-89183f0f249e.png)

I think I already know the answer to this question 😄  But wanted to just check first.

## Background

Some hotels want to give greater control to guests, e.g. maybe 4 guests are in a room but only 3 want breakfast. 

Or to use as a workaround to guests select adult/children breakfasts as I don't think there's an automatic way for us to figure this out from the API responses.

**Comment by dario-hd** [comment]
Hi @EdwardIII,

yes, it's possible. You can specify the `count`:

![image](https://user-images.githubusercontent.com/14803089/99809310-6529b480-2b42-11eb-86a7-2fe12422c2a5.png)

The model that you pointed out is not the one that is used when creating bookings.
