### ISSUE TITLE
What is the best way to request a new scope for an app?

### ISSUE THREAD

**Issue by koskiOvaa** [apaleo/api#429]
## Question

One of our Apaleo user is having a need for our App for what I need a new scope: folios.read.

Is there a "defined process" somewhere how to ask this scope? Or is it this?

## Background

Customer wants to expand the possibilities of Apaleo and Pindora integrations. For that we need more scopes.

**Comment by alokbash** [comment]
Hi @koskiOvaa, 

This scope is already available in Core API (folios.read - Read folios, including charges and payments).

Regards,
Alok / apaleo Support

**Comment by alokbash** [comment]
Hi @koskiOvaa,

Sorry about the incomplete answer. When you change scopes of any app, the end-user will have to authorize your connection again (https://apaleo.dev/assets/images/oauth/consent.png).

Regards,
Alok / apaleo Support

**Comment by koskiOvaa** [comment]
Sorry, I don't understand. :) 


If I add folios.read to scope before doing the connection, I get this error at "https://identity.apaleo.com/".

"Something went wrong
Sorry! We could not process your request.

invalid_scope

Please verify that your clientId, secret, scopes, and redirectUrl are correct, and your authorisation code is not older than 5 minutes.

Request Id: cf4eff01-f3f1-44c4-9a8e-e0f767dbdf67"


If I remove the folios.read from the scope variable from the connection parameters, all works fine. 

So the question: how can I add new scope to my app? Do I need to ask it from you guys here or through which process?

**Comment by alokbash** [comment]
Hi @koskiOvaa,

Are you doing this in your dev account?

Regards,
Alok

**Comment by koskiOvaa** [comment]
Hi,

Yes.

Cheers,
--
Tuomas

**Comment by alokbash** [comment]
Please email your account code to alok@apaleo.com. I'll have a look at it.

**Comment by koskiOvaa** [comment]
Thanks, done. Email sent.
