### ISSUE TITLE
Reservation Post returning empty response

### ISSUE THREAD

**Issue by rutwikGit** [apaleo/api#43]
## Question

We have recently started working on integration of our application with Apaleo and using the APIs we have been able to get property details and also create subscription request.
However when we are trying to post th reservation data as following it's returning empty response or response with null ID

## Background

Property Code: SHRTSTEU1
Subcription Id : 46D19GLY
Environment: Test (https://distribution.apaleo.io/)

Request 1:
`{
  "creditCard": {
    "cardNumber": "4444333322221111",
    "cardHolder": "Test Card",
    "expiryMonth": "12",
    "expiryYear": "2018",
    "cardType": "visa",
    "payerEmail": null,
    "isVirtual": false
  },
  "booker": {
    "title": "",
    "firstName": "FirstN",
    "middleInitial": null,
    "lastName": "LastN",
    "email": "test@test.com",
    "phone": "44201234567",
    "nationalityCountryCode": null,
    "address": {
      "addressLine1": "Buckingham Palace",
      "postalCode": "SW1 1AA",
      "city": "London",
      "countryCode": "GB"
    },
    "company": {
      "name": "Big Ben company",
      "taxId": null
    },
    "preferredLanguage": null,
    "birthDate": "1900-01-01T06:00:00+00:00"
  },
  "channelCode": "ChannelManager",
  "source": "WindsurferCRS-IBE (IBE)",
  "reservations": [
    {
      "propertyId": "SHRTSTEU1",
      "extraServices": null,
      "arrival": "2018-11-27T06:00:00+00:00",
      "departure": "2018-11-28T06:00:00+00:00",
      "persons": 1,
      "guestComment": "Something special",
      "externalId": "RS4L7K61K",
      "primaryGuest": {
        "title": "",
        "firstName": "FirstN",
        "middleInitial": null,
        "lastName": "LastN",
        "email": "test@test.com",
        "phone": "44201234567",
        "nationalityCountryCode": null,
        "address": {
          "addressLine1": "Buckingham Palace",
          "postalCode": "SW1 1AA",
          "city": "London",
          "countryCode": "GB"
        },
        "company": {
          "name": "Big Ben company",
          "taxId": null
        },
        "preferredLanguage": null,
        "birthDate": "1900-01-01T06:00:00+00:00"
      },
      "travelPurpose": null,
      "timeSlices": [
        {
          "ratePlanId": "SHRTSTEU1-BAR1BR",
          "totalAmount": {
            "amount": 147.6,
            "currency": "USD"
          }
        }
      ]
    }
  ]
}`

Request 2 without CC details:
`{
    "booker": {
      "title": "",
      "firstName": "FirstN",
      "lastName": "LastN",
      "email": "test@test.com",
      "phone": "44201234567",
      "address": {
        "addressLine1": "Buckingham Palace",
        "postalCode": "SW1 1AA",
        "city": "London",
        "countryCode": "GB"
      },
      "company": {
        "name": "Big Ben company"
      },
      "birthDate": "1900-01-01T06:00:00+00:00"
    },
    "channelCode": "ChannelManager",
    "source": "WindsurferCRS-IBE (IBE)",
    "reservations": [
      {
        "propertyId": "SHRTSTEU1",
        "arrival": "2018-11-27T06:00:00+00:00",
        "departure": "2018-11-28T06:00:00+00:00",
        "persons": 1,
        "guestComment": "Something special",
        "externalId": "RS4L7K61K",
        "primaryGuest": {
          "title": "",
          "firstName": "FirstN",
          "lastName": "LastN",
          "email": "test@test.com",
          "phone": "44201234567",
          "address": {
            "addressLine1": "Buckingham Palace",
            "postalCode": "SW1 1AA",
            "city": "London",
            "countryCode": "GB"
          },
          "company": {
            "name": "Big Ben company"
          },
          "birthDate": "1900-01-01T06:00:00+00:00"
        },
        "timeSlices": [
          {
            "ratePlanId": "SHRTSTEU1-BAR1BR",
            "totalAmount": {
              "amount": 147.6,
              "currency": "USD"
            }
          }
        ]
      }
    ]
  }`

**Comment by rutwikGit** [comment]
@pgrm  thanks for the quick reply.

As you pointed out I had initially posed to the distribution.apaleo.io but later also tried posting to secure-distribution.apaleo.io but got same behaviour.

Since there is a limited options for what can be sent as "Source" (https://api.apaleo-staging.com/booking/v1/types/sources) I'll modify the code to not send that infor. Will revert back to this one the basic reservation post starts working.

I'll modify our code accordingly and also add more error logging and let you know how it goes

**Comment by rutwikGit** [comment]
@pgrm Since as per API documentation, the Source attribute is attribute
So I have now changed the code such that it no more sends the "Source" attribute, if the source of the reservation is not from one of your prescribe list (https://api.apaleo-staging.com/booking/v1/types/sources). It just send the "ChannelCode": "ChannnelManager", but I am still getting the "Source is required for ChannelManager channel and should be configured." error back
Can you please suggest if I should be sending any default value in "Source" attribute in such case like when the reservation is done via our IBE etc

**Comment by ozonni** [comment]
we can add new `Source` type. Should we call it `Windsufer Direct Booking` ?

**Comment by rutwikGit** [comment]
Can you please add source as "WindsurferCRS"

**Comment by ozonni** [comment]
We just added `WindsurferCRS`. https://api.apaleo-staging.com/booking/v1/types/sources. Now you can create booking with this `Source` type.

**Comment by rutwikGit** [comment]
I can see that my test reservation is now imported successfully in Apaleo.... Let me run few more tests

**Comment by rutwikGit** [comment]
I just posted another reservation with the following json  but I got an error saying: 
"Expected 2 time slices but 1 were provided." 
Can you please let me know what is causing this error?

Requst JSON (removed the CC details)
`{
    "booker": {
    "title": "",
    "firstName": "William",
    "lastName": "Test",
    "email": "bill@notting.hill",
    "phone": "0201234567",
    "address": {
      "addressLine1": "The Blue Door",
      "addressLine2": "280 Westbourne Park Road",
      "postalCode": "W11 1EH",
      "city": "London",
      "countryCode": "GB"
    },
    "company": {
      "name": "The Travel Company"
    },
    "birthDate": "1900-01-01T06:00:00+00:00"
  },
  "channelCode": "ChannelManager",
  "source": "WindsurferCRS",
  "reservations": [
    {
      "propertyId": "SHRTSTEU1",
      "arrival": "2018-11-26T06:00:00+00:00",
      "departure": "2018-11-28T06:00:00+00:00",
      "persons": 2,
      "guestComment": "No Orange Juice please",
      "externalId": "RS4L7K61P",
      "primaryGuest": {
        "title": "",
        "firstName": "William",
        "lastName": "Test",
        "email": "bill@notting.hill",
        "phone": "0201234567",
        "address": {
          "addressLine1": "The Blue Door",
          "addressLine2": "280 Westbourne Park Road",
          "postalCode": "W11 1EH",
          "city": "London",
          "countryCode": "GB"
        },
        "company": {
          "name": "The Travel Company"
        },
        "birthDate": "1900-01-01T06:00:00+00:00"
      },
      "timeSlices": [
        {
          "ratePlanId": "SHRTSTEU1-BAR2BR",
          "totalAmount": {
            "amount": 600.0,
            "currency": "USD"
          }
        }
      ]
    }
  ]
}`

**Comment by ozonni** [comment]
There error message is pretty clear. You try to create reservation for 2 nights and you specified only 1 time slice for first night. How about the time slice for the second night?

```
"timeSlices": [
                {
                    "ratePlanId": "SHRTSTEU1-BAR2BR",
                    "totalAmount": {
                        "amount": 600.0,
                        "currency": "USD"
                    }
                }
            ]
```

**Comment by rutwikGit** [comment]
Got it... so we need to send one timeslice per night... 
I though multiple timeslices would be requited only if it's a multi rate booking.

**Comment by ozonni** [comment]
Yes, you have to specify it for each night. If you don't have any further question, feel free to close this issue.

**Comment by rutwikGit** [comment]
Please let me post one reservation successfully before closing the issue

**Comment by pgrm** [comment]
@rutwikGit I noticed that you are getting more errors trying to create reservations:

> could not add reservation(s) to booking YUOMRSDQ. 999005: Reservation already exists: ChannelCode: ChannelManager, ExternalCode: RS4L7K61D

Please keep in mind, the external code (also sometimes called external id) needs to be unique

**Comment by rutwikGit** [comment]
I have been able to successfully test the reservation Create, Modify and Cancel flows
So we can close this issue now
Thank your for all your support
