### ISSUE TITLE
Download reservations on-demand

### ISSUE THREAD

**Issue by Lukynn** [apaleo/api#431]
## Question

Are we able to download reservation on demand? Best was to download every future or now accommodated reservations?

## Background

Hotel after connecting to Apaleo from our platform want to download existing reservation from Apaleo for starting to work with them. When we are only using webhooks, 100% sync will be after aprox. 1 year.

**Comment by abarbarov** [comment]
Hi @Lukynn,

You could download reservations via the booking API. Please check the Swagger description: https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1. The `Reservations` section contains the URL you need:

`GET /booking​/v1​/reservations` - Returns a list of all reservations, filtered by the specified parameters.

Regards,
Afanasy, apaleo Team

**Comment by Lukynn** [comment]
Hi @abarbarov,

I did not notice, thank you very much for help!!
