### ISSUE TITLE
Booker's comment - Reservation API

### ISSUE THREAD

**Issue by nuno-sousaHZ** [apaleo/api#432]
## Question

Hi,

We would like to collect the booker's comment from Apaleo's API. We've been looking in the API but we haven't found any field related to this.

Can you indicate to us from where we can pull this information?

Thank you in advance.

Best regards,

Nuno Sousa

**Comment by WinniX** [comment]
Hello @nuno-sousaHZ 

Booker comment is a part of the booking model, not reservation. Please have a look at `/booking/v1/bookings/{id}` or `/booking/v1/bookings` endpoints. They will return you a booking and there you should find `bookerComment`.

- Eugene / apaleo Team
