### ISSUE TITLE
API Health Check

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#433]
## Question

Is there an endpoint to check if the api is working?
It would be nice if there would be an endpoint to get, maybe every minute, the information, if everything is healthy on your side. 

## Background

In the last months we recognized 2 small downtimes of the api.
For a better support to our customers, it would be great to be able to detect downtimes.

**Comment by bennetone** [comment]
Hi @c2ofh 

You can call https://api.apaleo.com/health and it should return you 200 in case the system is up and runnnig and 502 in case the service is down.

You can also manually check our statusboard at https://status.apaleo.com/.
