### ISSUE TITLE
Expand folios-request by allowances

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#435]
## I want

I want to show the correct folio to the guest.
When there was a refund, and I call `GET /finance/v1/folios?reservationIds=ABCDEFG-1?expand=charges` I can't see the refund and will show the full price in the invoice preview.

It would be nice to be able expand the folios call not only by charges, also by allowances, to save "useless" requests.

## I do

I would need to to a workaround to get the folios first, and pull each folio for it's own to get also the allowances beside the charges
`GET /finance/v1/folio/ABCDEFG-1-1` , `GET /finance/v1/folio/ABCDEFG-1-2`

**Comment by randyrod** [comment]
Hey,

Thanks for the message and the feedback. We have discussed internally on future improvements that will come to the folio API and we will include this in our conversations.
