### ISSUE TITLE
Performance report: missing unit groups in the response

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#436]
## Question

Calling https://api.apaleo.com/reports/v1/reports/property-performance?propertyId=POST&from=2020-08-01&to=2020-08-10 works but produces only account-level numbers. How to get unit group -level readings?

## Background

Accroding to swagger, the response should show first some total numbers, followed by unit group specific ones. I tried adding unit groups to the URL but that only filters the response, rather than adding separate readings for each unit group; an example of what should happen but doesn't is below (copied from the swagger):

"unitGroups": [
        {
          "unitGroup": {
            "id": "MUC-DBL",
            "code": "DBL",
            "name": "Double",
            "description": "Double"
          },
          "houseCount": 4,
          "houseItemsCount": 0,
          "soldCount": 2,
          "soldItemsCount": 0,
          "unsoldCount": 1,
          "unsoldItemsCount": 0,
          "outOfOrderCount": 1,
          "outOfOrderItemsCount": 0,
          "tentativelyBlockedCount": 0,
          "tentativelyBlockedItemsCount": 0,
          "arrivalsCount": 0,
          "departuresCount": 0,
          "noShowsCount": 0,
          "cancellationsCount": 0,
          "occupancyPercentage": 66.67,
          "grossUnitRevenue": {
            "amount": 230.00,
            "currency": "EUR"
          },
          "netUnitRevenue": {
            "amount": 214.95,
            "currency": "EUR"
          },
          "grossAdr": {
            "amount": 115.00,
            "currency": "EUR"
          },
          "netAdr": {
            "amount": 107.48,
            "currency": "EUR"
          },
          "revPar": {
            "amount": 71.65,
            "currency": "EUR"
          }
        },
        {
          "unitGroup": {
            "id": "MUC-SGL",
            "code": "SGL",
            "name": "Standard",
            "description": "Standard"
          },
          "houseCount": 1,
          "houseItemsCount": 0,
          "soldCount": 1,
          "soldItemsCount": 0,
          "unsoldCount": 0,
          "unsoldItemsCount": 0,
          "outOfOrderCount": 0,
          "outOfOrderItemsCount": 0,
          "tentativelyBlockedCount": 0,
          "tentativelyBlockedItemsCount": 0,
          "arrivalsCount": 0,
          "departuresCount": 0,
          "noShowsCount": 0,
          "cancellationsCount": 0,
          "occupancyPercentage": 100.00,
          "grossUnitRevenue": {
            "amount": 120.00,
            "currency": "EUR"
          },
          "netUnitRevenue": {
            "amount": 112.15,
            "currency": "EUR"
          },
          "grossAdr": {
            "amount": 120.00,
            "currency": "EUR"
          },
          "netAdr": {
            "amount": 112.15,
            "currency": "EUR"
          },
          "revPar": {
            "amount": 112.15,
            "currency": "EUR"
          }
        }
      ]
    },

**Comment by ozonni** [comment]
@tmmartti you need to add `expand=businessDays` parameter to get the detailed breakdown

`https://api.apaleo.com/reports/v1/reports/property-performance?propertyId=POST&from=2020-08-01&to=2020-08-10&expand=businessDays`

**Comment by tmmartti** [comment]
Thanks @ozonni! That did the trick.
