### ISSUE TITLE
How to distinguish a refund from other charges on folio LMLVKZEE-1-1

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#438]
## Question

How to distinguish a 10 eur refund from other charges on folio LMLVKZEE-1-1 since the refund is NOT on the "allowances" section of that folio?

## Background

The JSON of the folio, obtained by https://api.apaleo.com/finance/v1/folios/LMLVKZEE-1-1, has a 10 eur breakfast listed 7 times. The first one, LMLVKZEE-1-1-D-1, apparently represents a refund (since that folio has 6 breakfasts and one refund, and the allowances-section of that folio doesn't include this 10 eur refund). How can I tell that LMLVKZEE-1-1-D-1 is a refund rather than a charge?

**Comment by nfidirko** [comment]
Hey @tmmartti ,

It's a regular charge but it has been moved to another folio (to the second folio). You can ignore moved charges as they don't affect the folio balance. The sign of a moved charge is the `movedTo` object in the charge model.

That will also explain why the allowance is only 60 euro.
So, what has happened:
- 7 breakfasts were posted as direct charges;
- 6 of them were refunded by a global allowance;
- 1 charge has been moved to another folio (LMLVKZEE-1-1-D-1);
- then, that charge has been refunded via a charge allowance.

**Comment by tmmartti** [comment]
Hi @nfidirko and thanks for the response! 

If I ignore moved charges then will the daily balance also reflect reality?

**Comment by nfidirko** [comment]
Hi @tmmartti ,

> If I ignore moved charges then will the daily balance also reflect reality?
yes, moved charges should be ignored.
they're on the folio just to keep track of how charges were moved around. They don't affect the balance of the folio.
