### ISSUE TITLE
How to get unit statuses per date?

### ISSUE THREAD

**Issue by tmmartti** [apaleo/api#439]
## Question

How to GET unit statuses (all of them, not just maintenance or availability) per each date; i.e., how to get a JSON version of the graphic UI's Room Rack?

## Background

GET /inventory/v1/units gives out some maintenance statuses but doesn't seem to tell e.g. if the unit had a guest in it on a given day. GET /availability/v1/units appears to give only available units or ones under maintenance but again not those that have a guest in them.

**Comment by nfidirko** [comment]
Hi @tmmartti,

Here is how our UI Room Rack screen works:
- we request all units via `/inventory/v1/units`;
- we request all maintenances via `/operations/v1/maintenances` <- here, you can specify the time range;
- additionally, you can query `/booking/v1/reservations` to check which units are occupied on a given date.
