### ISSUE TITLE
Oauth client_id missing

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#44]
I still developing the apaleo-connect.
Now there ist a bug with the response.

After I get the code to requeast the access_token, the response just conains the access_token, the expire_in value and the the named type "token".

Request:
 `"grant_type=authorization_code&client_id=my_id&client_secret=my_secret&code=code_from redirect_params&redirect_uri=encoded_redirect_url"`

Response:
```
{"access_token"=>"eyJh...OWFA",
 "expires_in"=>3600,
 "token_type"=>"Bearer"}
```
The client_id parameter is missing. So I dont know how to update the the access_token when the token is expired.

**Comment by ozonni** [comment]
you have to request `refresh token` to be able to issue new `access token` when it's expired.

Check our [Connect your app with oauth2](https://apaleo.com/connect-your-app-with-oauth-2-0/#refresh) to see how you can use `refresh tokens`.
