### ISSUE TITLE
Webhook: Created -> Confirmed

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#440]
## Question

Is the [event list](https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo) from 2019 still correct or is there another place where the webhook topics are listed?

## Background

We're using the topics to create tasks, what have to be done. 
For example: I don't want to fetch the whole reservation, when city-tax was added.

Now a customer had some reservations with the state "created". Now these reservations are confirmed, and our list of topics, which should perform an update by api does not confirm the topic "confirmed" cause it's not part of the list.
Possibly the topic "confirmed" exists, but was filtered out by us as unnecessary message.

**Comment by nfidirko** [comment]
Hi @c2ofh ,

We have a website with developer documentation which is kept-to-date (usually).
You can get the list of events here: https://apaleo.dev/guides/start/webhook/configuration

So, there are no `guest-data-modified` or `city-tax-added` events anymore.
We have a `changed` event instead.
Also, there is no event in apaleo like `confirmed`.
We have different reservation statuses. When the reservation is created in apaleo, it's already in the status `confirmed`.

**Comment by c2ofh** [comment]
Hi @nfidirko thank you for the link.

Now I know what caused the problem on our side. Hard to explain here, but your answer was very helpful.
