### ISSUE TITLE
How can I know if a payment was done with a virtual payment method (VCC)?

### ISSUE THREAD

**Issue by SimBig** [apaleo/api#445]
I remember that there was a flag like "isVirtual" but I can not find it in your API docs any more:
https://api.apaleo.com/swagger/index.html?urls.primaryName=Finance%20V1

**Comment by JonasBr68** [comment]
The PaymentAccountModel has the isVirtual property 
https://api.apaleo.com/swagger/index.html?urls.primaryName=Booking%20V1
is that the one you were looking for?

**Comment by SimBig** [comment]
Ok, yes, as i see the booking has a PaymentAccountModel and through that I know if there is a virtual credit card attached to the booking, thanks
