### ISSUE TITLE
Question about how i can allow the Microphone in Chrome in iframe ?

### ISSUE THREAD

**Issue by vincentt6paris** [apaleo/api#446]
Hi apaleo team, 
It is my first message on Github and i am not in the developpement but i thought maybe you could have an idea for my problem.
I integrated a form in my website with a chatbot and the possibility to call the user. 
My website form is ok but when i try to call, the website ask for the user to allow the microphone. 
The problem is i can't reach the button to click Ok 
![image](https://user-images.githubusercontent.com/77336928/104323628-b15ff800-54e6-11eb-8327-7e29b03aae52.png)
what do you think ? 
thanks for the help
Vincent

**Comment by dario-hd** [comment]
Hi Vincent,

is this button `Ok` on your own page?

**Comment by vincentt6paris** [comment]
> Hi Vincent,
> 
> is this button `Ok` on your own page?

Hi  Dario, yes no problem because the Microphone is already accepted when the page is displayed directly. I tried to understand why when it is launched in iframe it is not using the same settings. I thought cross domain and tried to add this type of code <iframe src="https://example.com" allow="camera;microphone"></iframe>
But i have to understand wich "Example.com' website should be set, app.apaleo or Topsys or the widget/form in my page.. I ll continue to search :)
