### ISSUE TITLE
Missing events for reservation webhook

### ISSUE THREAD

**Issue by raphaelbrand-limehome** [apaleo/api#447]
Hello, 

we noticed that not every change on a reservation triggers a Webhook event. Take the following example:

1. Create a reservation (event created)
2. Create a folio, add a charge & payment, create invoice and close folio
3. The reservation gets update, allFoliosHaveInvoice is now set to true and the modified timestamp is updated (no event)

I have two questions regarding this behaviour:
1. Is this expected ?
2. And if it is expected, is there a way to know the list of fields, which will trigger an event if changed?

Thanks for your help in advance.

**Comment by dario-hd** [comment]
Hi,

yes, this is expected. You should rather react to Folio events in such a case. A reservation event will be triggered when the change is triggered directly on the reservation resource such as PATCHing a reservation or triggering any of the reservation actions. Fields like the `allFoliosHaveInvoice` and `balance`, are more like computed fields that allow for filtering reservations.

**Comment by raphaelbrand-limehome** [comment]
Alright thank you for the answer.
