### ISSUE TITLE
'Replace' is not allowed for path 'additionalGuests/-'.

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#455]
When updating guests of a reservation I sometimes get the following error: 
`'Replace' is not allowed for path 'additionalGuests/-'.`

According to the documentation "Replace" is possible for additional guests. So where exactly is the error?
![image](https://user-images.githubusercontent.com/10913793/107184509-fe00fb00-69e0-11eb-9828-f2ce853ec3b2.png)

**Comment by dario-hd** [comment]
The path you are using is used for appending an element to an array, more details here: http://jsonpatch.com/. When replacing, you should use just `/additionalGuests`.
