### ISSUE TITLE
How to cancel a charge?

### ISSUE THREAD

**Issue by felixbrandt** [apaleo/api#47]
## Question

Is there a way to cancel a specific charge?

## Background

I am posting charges to a folio from our application. In our application it is possible to cancel the charge (for some time after it was created) but at this point it was already pushed to your API. Is there a way to cancel the charge that was created by a previous request other than posting an allowance for the same amount?

**Comment by andreastubbe** [comment]
No, this is not possible. We immediately post the revenue (& VAT, if it's not a transitory charge) to accounting, when a charge is added - and there are no deletions in accounting. Posting an allowance is what you would have to do.
