### ISSUE TITLE
how to use notification service 

### ISSUE THREAD

**Issue by padkan** [apaleo/api#49]
## Question

Dear Apaleo Team,
I like to use your push notification service, first I create an access-able link on https and after login with client ID and client secret in swagger and execute request I get this :

apaleo-tracking-id: 0HLIJGOSQ4BV0:00000001
content-length: 0
date: Fri, 07 Dec 2018 09:47:55 GMT
server: nginx
status: 401
www-authenticate: Bearer error="invalid_token", error_description="The audience is invalid"
Also, I use postman to create request and use the same token but again I get the same result may I ask you how I can find the right token for this.
Saeed

**Comment by andreastubbe** [comment]
What is you client-ID? Then I can check

**Comment by padkan** [comment]
> What is you client-ID? Then I can check
Client ID: hotelbird-sandbox

**Comment by andreastubbe** [comment]
you didn't have the scope you need - check if it works now!

**Comment by padkan** [comment]
It doesn't work yet . the result is:
apaleo-tracking-id: 0HLIJGOSQ580D:00000001 
 content-length: 0 
 date: Mon, 10 Dec 2018 14:52:21 GMT 
 server: nginx 
 status: 401 
 www-authenticate: Bearer error="invalid_token", error_description="The token is expired"

**Comment by andreastubbe** [comment]
"The token is expired" usually means exactly that. It's not valid for an infinite amount of time, because security. Try getting a new token, and then make the call.

**Comment by padkan** [comment]
Thank you it is work. I call https://notifications.apaleo.com/v1/pinger/ and get the status result 200.
I have another question about v1/pinger/ when we use it. I think after getting status 200 we can set the event in /v1/subscriptions

**Comment by andreastubbe** [comment]
Right. Once you manage to ping the URL, all looks good and you can set up the subscription.

**Comment by padkan** [comment]
That 's great. if we have two reservation at the same time we receive two separate notification or one notification for two data reservation?

**Comment by andreastubbe** [comment]
right now, it's one for every single reservation. Just out of curiosity, would you prefer having them combined?

**Comment by padkan** [comment]
I think for every reservation we have one notification is better I just wanted to check it with you.
many thanks for your help.

**Comment by padkan** [comment]
Hi,
I have a question that related to this subject, I have subscribed a link with specifying property_id then I get every minute notification with system topic Then I create a booking on Apeleo panel on HOTELBIRD organization and I have subscribed my URL :

{
  "endpointUrl": "https://2baf1fb0.ngrok.io/api/apaleo/receive_bookings",
  "topic": "Reservation",
  "propertyId": "HOTELBIRD"
}

for HOTELBIRD property with topic  Reservation but I just get the result that with the topic is system. do you have any idea why I can’t get the notification with the topic reservation that I create a new booking in Apeleo panel (https://app.apaleo.io/HOTELBIRD/reservations)?
