### ISSUE TITLE
Authentication with Swagger-JS Library

### ISSUE THREAD

**Issue by vukee** [apaleo/api#50]
## Question
I am trying to use the Swagger-JS library within a Chrome Extension. I can sent a request to the library, but it looks like that the library never adds the Authentication Bearer to the Header of the request. The Swagger-JS documentation is very unclear how to use authentication. Do you have any example code how to use Swagger-JS and authentication against the apaleo API?

## Background
I want to write a integration with AVS-Meldeschein to have an easy way to print the guest cards for the city-tax. At the moment my idea is to write a Chrome extension. So that I can inject a new button within the Apaleo Web UI. Just fetch the reservation ID from the URL and get all other data for the reservation through the API. And in a second step even update the folio with the calculated city-tax from the AVS system.

**Comment by andreastubbe** [comment]
We like the idea! Could you please check other parts of the internet for your question, though? While we know everything about the apaleo API and are happy to help, Chrome extensions and Swagger-JS are nothing we're familiar with.

We found some guides for you to get you started, but that's about all we can do.
- https://smus.com/oauth2-chrome-extensions/ looks like a nice tutorial
- https://github.com/swagger-api/swagger-js#http-client explains how to generally pass values in calls, with headers and all that
