### ISSUE TITLE
getting correct data from push-notification

### ISSUE THREAD

**Issue by padkan** [apaleo/api#51]
Hi,
I have a question about push-notification, I have subscribed a link with specifying property_id then I get every minute notification with system topic Then I create a booking on Apeleo panel on HOTELBIRD organization and I have subscribed my URL :

{
  "endpointUrl": "https://somelink/api/apaleo/somemethod",
  "topic": "Reservation",
  "propertyId": "HOTELBIRD"
}

for HOTELBIRD property with topic  Reservation but I just get the result that with the topic is system. do you have any idea why I can’t get the notification with the topic reservation that I create a new booking in Apeleo panel (https://app.apaleo.io/HOTELBIRD/reservations)?

_Originally posted by @padkan in https://github.com/apaleo/api/issues/49#issuecomment-446278794_

**Comment by aprooks** [comment]
Hi @padkan,

seems like you have enabled subscription in a production environment (.com), while the hotel is staging (.io)

**Comment by padkan** [comment]
could you guide me how can I test push notification with real data and is there some possibility how to check if the subscription creation did work?

**Comment by aprooks** [comment]
In order to test, you have to create, check in check out any reservation. 

the problem is - you have a setup issue. Subscription is one environment, while 
a hotel is an another.

**Comment by aprooks** [comment]
I consider this situation as a bug though. After fixing you won't be able to create a subscription for non-existing hotel.

What you have to do.

1. Delete subscription in notifications.apaleo.com
2. Create same subscriptio in notification.apaleo.io
3. modify/create any reservation to start receiving events.

**Comment by padkan** [comment]
I think both of them have the same propery_id, my propery_id in the subscription is  HOTELBIRD and I create a new booking on HOTELBIRD organization.

**Comment by padkan** [comment]
oh ok, I try it.

**Comment by aprooks** [comment]
yes, it is correct

**Comment by padkan** [comment]
May I ask you when I could use https://notification.apaleo.io/ for subscribing my method?

**Comment by aprooks** [comment]
You should be able to do it right away.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by padkan** [comment]
Many thanks for your answers. It 's work.

**Comment by aprooks** [comment]
Glad I could help.

Bear in mind though, that in order to remove this kind of confusion we are deprecating .io domain https://github.com/apaleo/announcements/issues/3. You are free to test with it until 4th or May.
