### ISSUE TITLE
How to retrieve number of children in a reservation?

### ISSUE THREAD

**Issue by eloihdez** [apaleo/api#52]
When fetching the reservation there is an attribute called "adults" indicating the number of adults in the reservation. I have created a reservation with 1 child but there is no attribute "children" in the get reservation call. How could I get it via the API?

Thanks

**Comment by dario-hd** [comment]
In the reservation response, there's a `childrenAges` fields. So the total number of children for the reservation is given by the length of the `childrenAges` array field.
