### ISSUE TITLE
DELETE /v1/subscriptions parameters

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#53]
**Expected behavior:**

I want to delete all Subscriptions.  
So I wanto to send a `DELETE` request to /v1/subscriptions
The Documentation says, the endpoint needs 2 parameters.  
- topic
- propertyId

Because `DELETE` has no body, I've tried the parametes in the header.
I've recieved a **401 Forbidden**. => `"apaleo-tracking-id"=>["0HLJ42ACUAJHD:00000001"]`
I've also tried the parameters as url parameters.  
The answer is also **401 Forbidden**. => `"apaleo-tracking-id"=>["0HLJ42ACU8P15:00000001"]`

Both requests included a valid Bearer Token as Authorization Header Parameter.

The scope "notifications:subscriptions.manage" was added during the oauth connect

**Comment by ozonni** [comment]
@c2ofh you need to provide `topic` and `propertyId` as query parameters.
`401` usually means that the token in not correct. I sent you an email, could you please respond with the token that you use to make API calls.

**Comment by andreastubbe** [comment]
We deleted the subscriptions for you, and will look into what was going wrong.
