### ISSUE TITLE
Connection refused by remote host: VB.NET SecurityProtocol settings

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [apaleo/api#54]
## Question

I am trying to get access token but somehow server is refusing my request.
Everything was working fine yesterday(18.12.2018) but i guess due to the high frequency of requests Server has blocked my IP.
Please advice. 
Request URL: https://identity.apaleo.com/connect/token

I am working on this
https://apaleo.com/connect-your-app-with-oauth-2-0/

**Comment by ozonni** [comment]
@zeeshan-ahmad111 could you please provide your `clientId` and the HTTP response code you are getting back.

**Comment by zeeshan-ahmad111** [comment]
ClientID :HotelNetSolutions

Response : An existing connection was forcibly closed by the remote host

**Comment by ozonni** [comment]
@zeeshan-ahmad111 do you try to get the token from `chrome-extension`.

`CorsPolicyService did not allow origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop`

**Comment by zeeshan-ahmad111** [comment]
I just tested to find the reason behind this error and i got token from Postman successfully but somehow i am getting an error from my application.
Somehow your service is blocking my IP

**Comment by ozonni** [comment]
We don't have any blocking on any IP address. Do you run Postman on the same machine where you run your app? Then it's the same IP address.

**Comment by zeeshan-ahmad111** [comment]
Yes its the same machine and same request.

**Comment by dario-hd** [comment]
What kind of application are you developing? Is it VBA?

**Comment by zeeshan-ahmad111** [comment]
Yes i am using VB.net

**Comment by dario-hd** [comment]
I just thought you were writing a macro in e.g. excel. If that's the case you can check [this](https://github.com/apaleo/api/issues/20), it seemed a similar problem.

**Comment by zeeshan-ahmad111** [comment]
So i have found the issue.
I am using HTTP method to call your API in VB.NET.
Due to security issues of latest API this piece of line should be write in code just before making an API call.
       " ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 "

**Comment by ozonni** [comment]
@zeeshan-ahmad111 thank you for the info.
