### ISSUE TITLE
IP List Serveur

### ISSUE THREAD

**Issue by apausepi** [apaleo/api#55]
Dear Apaleo Team,

You had recently changed the IP of your serveur api.apaleo.io and identity.apaleo.io.
Is it an exceptional operation ?

Because we had to change our firewall rule to add the new IP.

Is it possible to give us a IP range, or all your IP that we use to add in our firewall rules ?

Thanks

**Comment by ozonni** [comment]
@apausepi you should not rely on the ip address. Our Load Balancer changes IP address from time to time. Use only DNS name.
