### ISSUE TITLE
Is there an api to get user info for an access token?

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#57]
## Question

Dear Apaleo team,

While implementing connect flow with oauth2 I'm wondering if there is an API to get user info from an access token. 
This is something "usual" when implementing oauth2 connect with providers like LinkedIn, Facebook,...

I found /api/account/users but no method for current user. I also found that I can get user email and account code from payload data in accesstoken.

## Background

Here is my scenario : 

- User clicks on a "connect with Apaleo" button in our app
- System calls authorize and token API to get the consent screen and an access token
- System is then redirected with the redirect uri
- System use the access token for onboarding : register the new user, configure the account (properties, rates, other users,...)

What I'm missing is in point 4 : user info for the current access token.

Best regards

**Comment by ozonni** [comment]
@jeanatpi you can call GET `https://identity.apaleo.com/connect/userinfo` with the access token (you need to have `openid` scope). The response will include basic user information.

```json
{
    "sub": "5b57336e-b15c-4b4a-86a2-d1906fd2bb14",
    "name": "user@xxx.com",
    "account_code": "XXXX",
    "preferred_username": "Tony Stark",
    "role": "AccountAdmin"
}
```

**Comment by jeanatpi** [comment]
@ozonni exactly what I need. Many thanks.

**Comment by ozonni** [comment]
@jeanatpi You’re welcome!

**Comment by jeanatpi** [comment]
@ozonni made some test and with "openid" scope I only got "sub". If I send also "profile" scope I got the correct fields.

**Comment by ozonni** [comment]
@jeanatpi thank you for the info. I forgot to mention `profile` scope. We are also going to adjust our guidelines with the how to get user information.

**Comment by jeanatpi** [comment]
@ozonni cool. Thanks for this.
