### ISSUE TITLE
Missing Price Parameter in ARI update

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [apaleo/api#58]
So far i have subscribed to several subscriptions but not getting daily price parameter in ARI update.

My ClientID="HotelNetSolutions"

Received ARI Update

````
{
  "accountId": "SHJR",
  "propertyId": "MUC",
  "timeSlices": [
    {
      "ratePlanId": "MUC-PROMO_DBL",
      "unitGroupId": "MUC-DBL",
      "from": "2019-11-14T09:00:00Z",
      "to": "2019-11-15T08:00:00Z",
      "available": 27,
      "restrictions": {
        "closed": true,
        "closedOnArrival": false,
        "closedOnDeparture": false
      }
    },
    {
      "ratePlanId": "MUC-PROMO_DBL",
      "unitGroupId": "MUC-DBL",
      "from": "2019-11-15T09:00:00Z",
      "to": "2019-11-16T08:00:00Z",
      "available": 27,
      "restrictions": {
        "closed": true,
        "closedOnArrival": false,
        "closedOnDeparture": false
      }
    },
````

**Comment by pgrm** [comment]
@zeeshan-ahmad111 you don't receive prices because there aren't any. You can see that the rate is close for those dates you posted here (`"close": true)` which means, they shouldn't be sold.

You can read more about it in the [channel integration guide](https://first.apaleo.com/channel-integration-guide/) and [our official documentation](https://apaleo.zendesk.com/hc/en-us/articles/360004556171-Rate-Restrictions)

You need to set rates, and uncheck restrictions, to receive any.

**Comment by zeeshan-ahmad111** [comment]
I have removed restrictions from my Properties and then ask for the full sync using this URL
https://distribution.apaleo.com/v1/subscriptions/1QLP6PD6/trigger-full-sync
But the response does not contain Price object.

Client Id: HotelNetSolutions
RatePlanId: BER-FLEX_SGL
PropertyID: BER
SubscriptionId:1QLP6PD6

**Comment by ozonni** [comment]
@zeeshan-ahmad111 this rate plan doesn't have associated `ChannelManager` channel.

![image](https://user-images.githubusercontent.com/25206121/50839974-c76bd880-1361-11e9-96ea-bc685621c9e3.png)

**Comment by zeeshan-ahmad111** [comment]
OK i have changed it to Channel Manager and getting it now.
Can you please also check this RatePlanId= BER-HNSRATE1
I am not notification for this.
Its Subscription Id is R4L0GGKG

**Comment by ozonni** [comment]
@zeeshan-ahmad111 `BER-HNSRATE1` is a day use rate plan and unfortunately ARI notifications API doesn't support day use rate plans yet. It is in our backlog.

**Comment by zeeshan-ahmad111** [comment]
Oh Ok got it.
But can you please explain that why i am not able to get prices when Booking channels is other than channel Manager.
This is because i am getting those rateplans in API calls and also successfully subscribing and getting notification for them without price object.
Its not making any sense to me because we always need price for those subscriptions to display.

Another question
Right now i have been assigned two properties (Hotel Berlin , Hotel Munich)from your colleague.
What i need to know is that there would be multiple properties under a single account or not?

Please clarify

**Comment by zeeshan-ahmad111** [comment]
Thanks for your information!
