### ISSUE TITLE
Multiple ARI Subscription against single RatePlanId

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [apaleo/api#59]
1-Is it possible to send Multiple ARI subscriptions against single RatePlanId?
If yes
2-What would happen if someone send multiple subscriptions against single RatePlanId?

**Comment by pgrm** [comment]
@zeeshan-ahmad111 thx for the questions, @ozonni will get back to you tomorrow

**Comment by ozonni** [comment]
@zeeshan-ahmad111 yes, you can create multiple subscriptions for the same `ratePlanId` (i suppose you would like to have multiple `endpointUrl`). Nothing special would happen. It's just another subscription and apaleo will push data to configured `endpointUrl`.

**Comment by ozonni** [comment]
each subscription is treated and processed separately from other subscriptions. If for some reason you have the same rate plan configured for the same endpoint, then you will get the same data pushed two times. No updates from the beginning will be pushed.

Can i ask you, what's the reason to have several subs with the same endpoints?

**Comment by zeeshan-ahmad111** [comment]
Actually i am in initial stage of this development and i was hoping that API would be smart enough to deal with such issues automatically but now i have to save everything in my database so my support team would not subscribe for the same subscription twice by mistake.
I have to apply several checks on my site before these operations.

**Comment by ozonni** [comment]
you can query already configured subscriptions using `GET /v1/subscriptions` API and see if you need to create one or not.

**Comment by zeeshan-ahmad111** [comment]
Thanks for this quick help

**Comment by ozonni** [comment]
You can delete subscription by `id` using `DELETE /v1/subscriptions/{id}` API. Again, you can query all configured subscriptions using GET /v1/subscriptions API and the delete all subs for specific property.

**Comment by zeeshan-ahmad111** [comment]
Thanks!

**Comment by zeeshan-ahmad111** [comment]
I always receive ARI Subscription with the date difference of one day like below.
"from":"2019-01-18T16:00:00Z","to":"2019-01-19T09:00:00Z"

Just need to be assure that it this logic would remain the same for future updates or there would be any chances that you send us updates with the date difference of more than one day like below.
"from":"2019-01-18T16:00:00Z","to":"2019-01-19T09:00:00Z"

**Comment by bennetone** [comment]
Hey @zeeshan-ahmad111 

We do not aggregate overnight time slots, even if they have the same availability, price and restrictions. For overnight rate plans you will always get time slots for one night.

Hope this answers your question!

**Comment by zeeshan-ahmad111** [comment]
Thanks!
