### ISSUE TITLE
Require API Methods full description

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [apaleo/api#60]
## Question

Is there any link which describes each API method and its parameters.
Right now i am looking for description of Booking methods.
There are only examples written on Swagger but it doesn't describe their parameters.

**Comment by pgrm** [comment]
@zeeshan-ahmad111 you should be able to switch from Examples to the `Model` description (there are links above the examples, for both parameters and result values:

![image](https://user-images.githubusercontent.com/713456/51116302-07700700-180b-11e9-8d4d-6018bd4d65a8.png)

If that documentation is missing anywhere, please create a new issue here for those specific cases, thx

**Comment by zeeshan-ahmad111** [comment]
Yes there is no information written for booking methods.
