### ISSUE TITLE
Swagger API Missing Booking Methods Description

### ISSUE THREAD

**Issue by zeeshan-ahmad111** [apaleo/api#61]
## Question

I am using this link for Booking methods and i need its description.
 https://distribution.apaleo.com/swagger/#/

**Comment by pgrm** [comment]
Thank you @zeeshan-ahmad111 - could you please post a screenshot which method you mean in particular? Because those few I checked have documentation, but maybe I missed something.

**Comment by zeeshan-ahmad111** [comment]
![swagger1](https://user-images.githubusercontent.com/36439393/51118184-08effe00-1810-11e9-8cfa-c383b5952042.PNG)
![swagger2](https://user-images.githubusercontent.com/36439393/51118185-08effe00-1810-11e9-95bb-4bd86cddfcc4.PNG)


I am looking for description of parameters as shown in  image 2

**Comment by zeeshan-ahmad111** [comment]
Thanks for your quick feedback.

**Comment by zeeshan-ahmad111** [comment]
So i didn't find the information i was looking for.
I want to use this link this link https://secure-distribution.apaleo.com/v1/bookings for booking and API says that i cant send plain cardholder data using this URL so information i was looking for the technical description of each of these parameter like how many characters are allowed,what type of format i have to use to send card data.
I am also getting an error when i send cvc value as 248 for this link https://distribution.apaleo.com/v1/bookings saying minimum 24 characters are required.

Can you please specify the format  of cardholder data that need to be send using this link
https://secure-distribution.apaleo.com/v1/bookings

**Comment by bennetone** [comment]
Dear @zeeshan-ahmad111,

we are using a proxy service that is certified to be compliant with PCI-DSS requirements to secure our system from receiving plain CC data. If you send plain CC data to https://distribution.apaleo.com/v1/bookings it will fail as it does with your example above.

If you send the credit card data to https://secure-distribution.apaleo.com/v1/bookings it will be tokenized by the PCI compliant proxy service and then forwarded as a token to the service itself.

See an example of a credit card you can send to https://secure-distribution.apaleo.com/v1/bookings:
```
  "creditCard": {
    "cardNumber": "4111111111111111",
    "cvc": "737",
    "cardHolder": "John Doe",
    "expiryMonth": "10",
    "expiryYear": "2020",
    "cardType": "visa",
    "payerEmail": "s.hopper@test.com",
    "isVirtual": false
  }
```

The problem is that your account was not setup to handle credit cards yet. I just activated the test payment service. You can use the following CC now to test the integration:

Use this for testing with CVC: 4111 1111 1111 1111 (CVC: 737) - Expiry 10/2020
Use this for testing without CVC: 4111 1111 4555 1142 - Expiry 10/2020

Kind Regards!

**Comment by zeeshan-ahmad111** [comment]
Now its working.
Thanks for this information.

**Comment by bennetone** [comment]
You are welcome!

**Comment by zeeshan-ahmad111** [comment]
is it possible to send multiple bookings in one API call?
I tried it but API only process last booking data.
Please let me know if there is any way to do this.

**Comment by zeeshan-ahmad111** [comment]
Also i need to know if it is possible to send multiple guest data in a single booking?

**Comment by bennetone** [comment]
Hey @zeeshan-ahmad111 

I don't know if you read the [Channel Integration Guide](https://blog.apaleo.com/developer/channel-integration-guide), there is an explanation of what is a booking and what is a reservation. You can create one booking with multiple reservations in it, so if a guest books 2 double rooms and one single room with different rates and maybe even dates on the booking engine, you could send it over as one booking with multiple reservations. You cannot create multiple bookings with one API call though. Hope that answers your questions!

Right now you can only send the date of the primary guest as we learned that even getting enough data for the primary guest from OTAs can be a challenge. This can be different for bookings from the hotel website though. Do you allow the booker to provide the data for all guests on the booking engine?

**Comment by zeeshan-ahmad111** [comment]
Yes i am aware of that.
Just looking for this information
"You cannot create multiple bookings with one API call though."

Yes we provide booker to add guest details that may be more than one.

**Comment by bennetone** [comment]
Hey @zeeshan-ahmad111 

We will enhance the Distribution API to allow you specifying multiple guests.

Regarding your POST bookings request. I tried the same request and got the following response:
```
{
  "messages": [
    "ChannelCode: The ChannelCode field is required."
  ]
}
```

This is also the reason why the request failed. The channel code is required.
![image](https://user-images.githubusercontent.com/25197867/51306230-1e963b00-1a3d-11e9-8e91-829e37e85ac0.png)

When you set `ChannelManager` as channel code you also need to specify the source. You can find more in the [Channel Integration Guide](https://blog.apaleo.com/developer/channel-integration-guide).

**Comment by zeeshan-ahmad111** [comment]
That would be great.

Yes i am receiving this message now but i was only getting this information before without any valid description.
": Provided value is invalid."

**Comment by zeeshan-ahmad111** [comment]
One quick feedback for booking API.
**source (string, optional): Source of the reservation**
**source**  is written as optional in documentation but when i tried to send a request without it i got this message
{
    "messages": [
        "Source is required for ChannelManager channel and should be configured."
    ]
}

**Comment by bennetone** [comment]
The channel integration guide says:
> Most likely, you are connecting multiple travel agents or a Central Reservation System (CRS), and should use ChannelManager. When setting ChannelManager as the channel, you have to specify more details in the source.

So the source is optional when you set the channelCode to `BookingCom`, but mandatory when you use `ChannelManager`.

**Comment by zeeshan-ahmad111** [comment]
Thanks for information

**Comment by ozonni** [comment]
@zeeshan-ahmad111 we just released new version of distribution api with additional guests support. Now you can specify multiple guests when you create or modify reservation.

![image](https://user-images.githubusercontent.com/25206121/51386884-4d3b1100-1b24-11e9-9cd6-79f4b25d5ac1.png)
