### ISSUE TITLE
userinfo fields missing firstname and lastname

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#62]
## Question

Hi,

In the apaleo oauth2 "userinfo" method we have a field "preferred_username" which is a concatenation of Firstname and Lastname.

Whereas in identity.apaleo.com/users API method we have 2 fields.

Would it be possible to have firstname and lastname in "userinfo" method? 
Or maybe I'm missing a scope?

## Background

Implementing oauth2 flow in PI.

**Comment by ozonni** [comment]
@jeanatpi you are not missing the scope, but indeed we don't return `firstname` and `lastname` separately. I put it to our backlog. Thank you for your feedback.

**Comment by jeanatpi** [comment]
@ozonni thanks for your answer!
