### ISSUE TITLE
Using scope identity:account-users.manage

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#63]
## Question

Hi,

I was thinking of using /api/account/users API method to get users from an account for onboarding.
So I added the scope "identity:account-users.manage" to my oauth2 client but when doing it it returns "unauthorized_client".

On swagger this is working. So I'm wondering if this is related to my app client id and if this is forbidden for security reason (because by using this scope I will be able to modify users).

Can you enlighten me on this?

**Comment by ozonni** [comment]
@jeanatpi could you please describe your use case, why do you need to get list of users for the whole account?

The reason you get `unauthorized_client` because `identity:account-users.manage` scope is not configured for your client.

**Comment by jeanatpi** [comment]
@ozonni sure.

Was thinking of using users API to get a list of other users account. So that during the onboarding (on our side) process, the admin will be able to configure the hotels, the users with role and access and send invitation to them. 

So this will be only a "read" access.

**Comment by jeanatpi** [comment]
Hi @ozonni, this is not critical for us so I would say it depend on your other backlog priorities :)

**Comment by randyrod** [comment]
Hi @jeanatpi,

Hope you are doing fine. Could you please send us an email to support@apaleo.com with the `ClientId` that you would like us to add this new `read only` scope.
