### ISSUE TITLE
Apaleo connect on store

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#64]
## Question

Hi,

I was wondering where in Apaleo a user can use the "Connect" button to link his account to an app using Oauth2 flow?
I tought it was in the store but I don't see any connect button there.

Can you explain me?

Best regards

Jean

**Comment by andreastubbe** [comment]
Hi Jean,

it only appears when you configure the connect URL. Check https://blog.apaleo.com/developer/how-to-get-on-the-apaleo-store for how (excuse the bad formatting of the page, please. We just migrated and cleaning up the CSS is something I couldn't get myself to do yet :) )

HTH,
Andrea

**Comment by andreastubbe** [comment]
.. ish. I'd recommend to have a little page in between, to distinguish between existing customers of yours, that just want to connect apaleo, and new customers which probably should sign up for an account first.

Check https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0 - the connect button leads to a landing page, and then the user registers & connects, or logs in & connects.

**Comment by jeanatpi** [comment]
Yes ok.

I'm also wondering, when an Apaleo user has "linked" an app, will he see an entry menu in his Apaleo dashboard (or somewhere in a menu) to access directly to this app?

**Comment by andreastubbe** [comment]
Not out of the box, but we built something nicer than just a link :)

You can add your own tile to the dashobard, using UI integrations: https://blog.apaleo.com/developer/ui-integration-guide

We use it in our demo hotel to display everybody's favourite video, but you could display some key statistics. And a link, too.
![rick](https://user-images.githubusercontent.com/5329373/51336545-1235d080-1a85-11e9-9240-a2d305e2be36.png)

**Comment by jeanatpi** [comment]
Thanks. All is clear now.
