### ISSUE TITLE
Multiple OAuth 2.0 Subscriptions

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#65]
## Question

Is it possible in the future to use the OAuth for more than one connection?

## Background

If your customer got 2 Hotels. The user has one login for both hotels and is able to choose between one of them.
Now, the customer purchase our solution also for his two hotels and want to connect both hotels.

So the customer connects hotel 1 with OAuth. When he try to connect the second hotel with our solution, an error will be raised, because there is already a subscription. 

In my mind the subscription should not be connected with the user itself, but rather with the hotel in apaleo.

**Comment by bennetone** [comment]
Hey @c2ofh 

In such case the second hotel will most likely be in the same apaleo account, but even with one user managing multiple accounts you can differentiate for which account a certain authorization code is valid. When you exchange the authorization code for an access token you can call the `GET /account/v1/accounts/current` API to see all the details for the account you are authorized for.

On your side you need to store an authorization code per account.

**Comment by c2ofh** [comment]
Hey  @bennetone 
I understand, but this is not possible for us because you are straight user-based and we are straight hotel-based in our solution.
Is there a workaround to connect as another user with the second hotel?

- Apaleo User 1 connects to Hotel 1
- Apaleo User 2 connects to Hotel 2

**Comment by bennetone** [comment]
Hey @c2ofh 
we are not user based, we are account based, so with one authorization you will be authorized for the full account with all properties in this one account. If a chain authorizes your app, then you will have access to all hotels within this account. We might introduce authorizations limited to certain hotels of one account, but this is not the case right now.

When you say hotel, do you really mean one single property?
