### ISSUE TITLE
oauth2 : use connect client with grant_type=client_credentials

### ISSUE THREAD

**Issue by jeanatpi** [apaleo/api#70]
## Question

Hi, 

I'm trying to get a token with grant_type=client_credentials.

Whereas it works for some client ID, let's call it "basic" , for a "connect" one it does not work.

As I still want to test some things with basic and connect clients, how can I do?
Is it possible to have 2 clients : 1 basic & 1 connect?

**Comment by andreastubbe** [comment]
Yes, this is possible. You want one for your demo hotel? It sounds like it might get confusing, so keep in mind that the connect-client will *only* work as described on https://blog.apaleo.com/developer/connect-your-app-with-oauth-2-0, and the basic client *only* as described on https://blog.apaleo.com/developer/getting-started-with-apaleo-apis

**Comment by jeanatpi** [comment]
Yes. Now that's all clear :)

Thanks.

And yes please send us a "basic" client for our demo hotel.
