### ISSUE TITLE
What are the possible reservations status for a reservation?

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#72]
## Question

What are the possible reservation status for a reservation? Do you have a list of them?

**Comment by bennetone** [comment]
Dear @SimonBigelmayr 

When you view the model description on the swagger documentation you can see the list of available reservation status.

![image](https://user-images.githubusercontent.com/25197867/52266654-3c1d3d00-2937-11e9-9a2e-0ead457b5478.png)
