### ISSUE TITLE
Book Service - Pass quantity

### ISSUE THREAD

**Issue by bhaexupgreats** [apaleo/api#75]
Hi,

I'm using following call: PUT /booking/v1/reservation-actions/{id}/book-service. 
Is it possible to pass a quantity to this request?

Thank you!

**Comment by pgrm** [comment]
hello @bhaexupgreats, no at the moment it only allows to book one service at a time, so if you want to book multiple services, you'd need to call the endpoint multiple times

**Comment by bhaexupgreats** [comment]
Okay, thank you for the response!

**Comment by dario-hd** [comment]
@bhaexupgreats calling the endpoint twice will not book the service twice. Currently, whenever you book a service, it's going to be booked for all persons including children. Allowing to book a specific quantity is on our roadmap.

**Comment by pgrm** [comment]
thx @dario-hd for the clarification

@bhaexupgreats we'll update the swagger documentation to be more precise

**Comment by bhaexupgreats** [comment]
@dario-hd, thank you for the explanation! Do you know if there is a workaround for this at this moment?

**Comment by dario-hd** [comment]
@bhaexupgreats unfortunately not.

**Comment by lukeclifton** [comment]
Is there any update on this functionality being released? 

We would like to add a extra's quantity selector to the IBE as its a feature thats been requested by multiple customers.

**Comment by dario-hd** [comment]
Hi! It's now possible to book a specific quantity of services, check the example below:

![image](https://user-images.githubusercontent.com/14803089/70608052-d1e0c300-1bff-11ea-9869-5e3b51e8efee.png)

In this way, you will book 2 breakfasts for 20e in total.

Take a look at the documentation on the right side, you can even specify the quantity for each and every service date.
