### ISSUE TITLE
Can not delete notification subscription

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#78]
Right now we can not delete an existing subscription with the Swagger Notifications API

The response is: "The Request-URI could not be found.". 
It worked yesterday and the day before. Is this a bug or are we doing something wrong?

**Comment by NadiaStav** [comment]
You may send the details about your subscription per email to our support email address and we'll come back to you.

**Comment by bennetone** [comment]
Is handled with DM
