### ISSUE TITLE
How to update the test data from live system 

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#79]
Hi,
I need to update our test data from the live apaleo data. Could you please let me know what are the steps which I have to follow?

**Comment by patrickHermannLimeHouse** [comment]
any update ??

**Comment by bennetone** [comment]
Hey @patrickHermannLimeHouse 

The steps to setup a hotel are the following:
1. Create property and configure property settings
1. Create unit groups and units
1. Create cancellation policies
1. Create services
1. Create rate plans and set rates

Now you need to write a script that reads all data from the live account and then writes it back to the test account. Bear in mind that as soon as you start creating reservations, group bookings or any other transactional data you will not be able to delete the used rate plans and unit groups from the test environment anymore. Before that you can delete the setup in the reverse order as described above.

**Comment by patrickHermannLimeHouse** [comment]
@bennetone I extract the data from live system using 'https://api.apaleo.com/inventory/v1/properties' api.
But I need an automated way so that I can put this data into my test account.

**Comment by andreastubbe** [comment]
Patrick, you can just use the APIs to create the data you got. In most cases the data you retrieve is almost the same json as the ones you need for writing.

So:
1. you retrieve the data using a ton of GET calls
2. you potentially transform it as you need it
3. you create the data in your test system using a ton of POST calls

For step 2, analyse the input and output models and see which transformations you would need to do. Then, you can fully automate those steps with a scripting language of your choice.

**Comment by patrickHermannLimeHouse** [comment]
Is there is no any other way like we can import from json file or excel?
