### ISSUE TITLE
How can I modify (amend) an existing reservation?

### ISSUE THREAD

**Issue by pgrm** [apaleo/api#8]
## Question

- What is the flow to modify an existing reservation (change room type from double to suite)?
- Can it be done directly or do I first need to cancel the original reservation?
- Can I amend reservations which are already checked in?

**Comment by pgrm** [comment]
Changing the room type on a reservation is called amend. You can amend already checked in reservations, but you can only modify nights which haven't been yet posted on to the folio. (This happens usually during the night audit.)

To change the room type for a reservation, you'll first need to get the alternative offers using `GET /booking/v1/reservations/{id}/alternative-offers`

From there you can pick one, where the rate plan fits the room type you are looking for. Afterwards you can call `POST /booking/v1/reservations/{id}/amend` to change the rate plan of the reservation.

**Comment by dario-hd** [comment]
By using the v1 you cannot change the already booked time slices. In order to do that, you need to use the "new amend" which is currently only under the unstable version.

```
PUT /booking/v0-nsfw/reservation-actions/{id}/amend
{
  "arrival": "2018-08-23T17:00:00+02:00",
  "departure": "2018-08-25T11:00:00+02:00",
  "persons": 2,
  "timeSlices": [
    {
      "ratePlanId": "MUC-DBL"
    },
    {
      "ratePlanId": "MUC-SUITE"
    }
  ]
}
```

Please note that you cannot change time slices which are already posted to the folio.
