### ISSUE TITLE
I Need data Change notification api 

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#80]
Hi,
could you please provide me api which can notify any changes occurred in data.

**Comment by bennetone** [comment]
Hey @patrickHermannLimeHouse 

Please check the API documentation of our [Notification API](https://notifications.apaleo.com/swagger/index.html) to see what`s available. Also reading this [guide](https://blog.apaleo.com/developer/push-it-webhooks-in-apaleo) could be helpful.

**Comment by patrickHermannLimeHouse** [comment]
Hi @bennetone thanks for response. I could not find api which notify me when something is changed(update) in data. 
For Example. if some data is changed for particular reservation id it can notify me.

**Comment by andreastubbe** [comment]
Patrick, the notifications API really is the one you need, and the answers you are looking for are really in the guide :)

Some things to clarify:
- a "change" of a reservation can be many different things. For each, there is a separate notification we send. Check the table listing all events
- not all data changes are published as notifications. Right now, we only cover reservations. Would you need more, and could you help us out and let us know which ones, and for what? That would be cool.

Andrea

**Comment by patrickHermannLimeHouse** [comment]
OK Thanks @andreastubbe.
I am getting the below response when I execute the code. 
{
  "type": "InvalidPropertyId",
  "message": "Subscription cannot be enabled for this property id"
}
could you please help me how can I enable Subscription for particular id

**Comment by andreastubbe** [comment]
- make sure the property exists in the account you requested the access token for.
- the ID is normally all uppercase, maybe that is the problem?

From where are you making the call, the swagger UI?

**Comment by patrickHermannLimeHouse** [comment]
![image](https://user-images.githubusercontent.com/42251140/53488622-dd219280-3ab4-11e9-9995-55b995b6cf18.png)

I have put the ID 'AACHEN' exists in my account(see in image). but giving the same response
{
"type": "InvalidPropertyId",
"message": "Subscription cannot be enabled for this property id"
}

**Comment by andreastubbe** [comment]
We checked our logs, and the request you send looks good. Only two more things I can think of:
- which account-code are you using to get the token?
- the screenshot you posted, is this on app.apaleo.io, or on app.apaleo.com?

**Comment by patrickHermannLimeHouse** [comment]
The screen shot I posted it is on app.apaleo.io.
I am trying to execute the code from https://notifications.apaleo.io/swagger/index.html#/Subscriptions/V1SubscriptionsPost

**Comment by andreastubbe** [comment]
Okay, I just checked. You do not have a property with code Aachen in your account. You have one with the *name* Aachen.

To explain this a little:
- pretty much each entity in apaleo has a human readable *name*, and a *code* which is mainly used in integrations.
- .io and .com are completely separated environments. Different databases. Do not assume that entites on .com and on .io have the same code, just because you created them with the same name.

Because the code is not meant for humans, you often will not find it on the user interface, but only on the API.

**Comment by patrickHermannLimeHouse** [comment]
now I am getting the below response for "propertyId": "DG4"
{
  "type": "EnabledForAnotherEndpoint",
  "message": "Subscription is already enabled for another endpoint"
}

**Comment by patrickHermannLimeHouse** [comment]
@patrickHermannLimeHouse any update?

**Comment by pgrm** [comment]
@patrickHermannLimeHouse the endpoint for that is currently in development. We're improving the notifications API, see also https://github.com/apaleo/announcements/issues/11 for further details
