### ISSUE TITLE
we need to make around 2200 folio api requests. 

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#81]
## Question ## Background

we are building a datawarehouse at the moment and we had some troubles with the calls to the reservation api in the past. Thats why we would like to inform you in advance that we will call the folio api today. Can you check if there is a problem later and tell us, if there is one?

**Comment by pgrm** [comment]
hello @patrickHermannLimeHouse you can make 2200 filio API requests, that's going to be fine, but please throttle them. In the past you used to have multiple concurrent requests, which was the main issue. As you are building a datawarehouse and this load will only happen once, I guess it should be fine from your side to not call the API more than once every 10 seconds, that would mean that it would take a couple hours to get all the folios, but I guess as it is populating a datawarehouse, it should be fine for you and it wouldn't cause any spike on our side.

Thanks for letting us know in advance.
