### ISSUE TITLE
Additional Data Request VAS

### ISSUE THREAD

**Issue by VasilGutev** [apaleo/api#83]
## Question

Could you please add financial transactions records to the demo hotels BER and MUC for January and February 2019 as well as checking out the passed reservations for both months because currently we have only reservations with status "Reserved" and we need "Checked Out" and "Checked In".

## Background

I am Vasil Gutev from "SeedSetGroup" and I am working alongside "VAS Value Added Services GmbH" on the Apaleo integration project.

**Comment by dario-hd** [comment]
In order to do that you can enable the automation in the property settings:

![image](https://user-images.githubusercontent.com/14803089/53482483-91082b00-3a7f-11e9-8336-bb1e40ff071d.png)

After running the night audit, you will have financial transactions.
