### ISSUE TITLE
how to withdrawl consent

### ISSUE THREAD

**Issue by MSRobert** [apaleo/api#86]
## Question

Is there a way to withdrawl the consent / invalidate the refresh token?

## Background

For demonstration purposes we would like to present the consent screen to many prospects using the same user. Right now we only see the log in screen and then get directed back to our application with a new refresh token. The screen where we see and accept the required permissions does not show any more.

**Comment by ozonni** [comment]
@MSRobert right now there is no place for a user where you can to revoke the consent for specific client. As a quick workaround for your demo purposes, we can add checkbox to the consent screen indicating if the consent should be stored. If you don't store it, you will have the consent screen every time the application tries to get authorization. Let us know if that would work for you, then we can do it quickly.
