### ISSUE TITLE
Can not receive reservations from notification service

### ISSUE THREAD

**Issue by SimonBigelmayr** [apaleo/api#87]
**Actual behavior:**
Right now, we seem to not receive any reservation via the push service/notification service.
Not sure if it is a bug or a configuration error on our side but it still worked fine two days ago..

**Comment by pgrm** [comment]
hello @SimonBigelmayr are you receiving the heartbeat notifications? Could you send the clientId + subscriptionId to support@apaleo.com then we can check the logs to see if we are receiving any errors from your subscription on our side.
