### ISSUE TITLE
Issues with notification API

### ISSUE THREAD

**Issue by pgrm** [apaleo/api#90]
@patrickHermannLimeHouse - we had to delete the old issue because you published your API credentials there publicly. Original text:

Hi I am getting the error 'Auth ErrorError'.
when i check 'notifications:subscriptions.manage Create/Delete subscriptions'
Screen shot is attached. 
The above screen shot for the url https://notifications.apaleo.com/swagger/index.html#/Subscriptions/V1SubscriptionsPost

**Comment by dmitry-urenev** [comment]
@patrickHermannLimeHouse the `notifications:subscriptions.manage` scope was missing for these credentials. I've added it. Soon it will be available for use. I'll let you know

**Comment by dmitry-urenev** [comment]
@patrickHermannLimeHouse please try again. now should work.

**Comment by patrickHermannLimeHouse** [comment]
Thanks @dmitry-urenev now its working
