### ISSUE TITLE
Service for dayuse

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#92]
I've created a reservation with dayuse for the next day on apaleo.io.
Now I wanted to add a service to the reservation, but I receive just a _204_ response and no service was added.

**Request:** PUT "booking/v1/reservation-actions/MEXAGRHJ-1/book-service"
**Service:** BER-BRKF
**Reservation:** MEXAGRHJ-1

**apaleo-tracking-id:** 0HLKTQEDLU0TB:0000021B 

Then I've tried another **Service:** BER-WLAN
The Response was also _204_, but the service was added

**apaleo-tracking-id:** 0HLKTQEDLU0TB:000002BB

**Comment by dmitry-urenev** [comment]
@c2ofh thanks for the feedback! we will investigate this issue.

**Comment by bennetone** [comment]
https://github.com/apaleo/apaleo/issues/3120
