### ISSUE TITLE
LanguageISO

### ISSUE THREAD

**Issue by BrunoStardekk** [apaleo/api#93]
## Question

Hi,

I need the language of the customer of the hotel but all I find in the reservation object is countryISO. Is there a way for me to get the language?

Not sure I need to be here for this one but:
I need some changes to our credentials (an additional scope and the changing of the redirect url). Is this done through gitlab aswell?

## Background

I need the language information because we'll sent mails to this person.

**Comment by dmitry-urenev** [comment]
Hi @BrunoStardekk, 

- Hotel account model contains `defaultLanguage` property - please check `GET /account/v1/accounts/current` api
- Guest model in the reservation has also optional property `preferredLanguage`. Check `GET /booking/v1/reservations/{id}` endpoint 

What client id do you have?

**Comment by BrunoStardekk** [comment]
hi @dmitry-urenev 

Thank you for the fast response. 

Am I correct believing `defaultLanguage` can not be `null` or empty?

"stardekk-connect" is our client id.

**Comment by dmitry-urenev** [comment]
@BrunoStardekk all stays in the swagger documentation
```
AccountModel {
     code (string): The code for the account that can be shown in reports and table views ,
     ....
     description (string, optional): The description for the account ,
     defaultLanguage (string): The default language two-letter language code (ISO Alpha-2) for the account
     ....
```
in the example above:
defaultLanguage (string) - is required. that means it always contains some not empty value.
description (string, **optional**) - that means that you should take into account all possible states of the property - it can be missing or has `null` or `undefined` or `''` or any string value. 

I forgot to mention, that you can also retrieve all supported by account languages using 
`GET /settings/v1/languages` endpoint. As a result you will get something like this:
```
{
  "languages": [
    {
      "code": "en",
      "default": true,
      "mandatory": true
    }, ... 
}
```

**Comment by dmitry-urenev** [comment]
@BrunoStardekk  you can leave here also the request about changing the scopes or redirect url. What are you not allowed to write here is **any sensitive information** such as `clientSecret` or `token`.

**Comment by BrunoStardekk** [comment]
Id like to have the following scopes added: account.read and properties.read
And the redirect uri changed to "https://login.e-mailinglist.be/Customer/Settings/Partners"

Thanks again!

**Comment by dmitry-urenev** [comment]
Hey @BrunoStardekk, one more question:

Would you like to completely change the redirect uri or add the new one as an acceptable uri? If we change the old one, instead of adding, it won't work anymore.

**Comment by BrunoStardekk** [comment]
This can be completely changed. There wont be any use for the old uri

**Comment by ozonni** [comment]
@BrunoStardekk there is one thing to keep in mind. You need to re-authorize your application (forward users to authorize url with consent screen) in order to get new scopes as well as get new refresh token. Otherwise the old refresh token will only give you old scopes and new API endpoints still will be not available to you.

**Comment by dmitry-urenev** [comment]
@BrunoStardekk new scopes and redirect uri are ready to use
