### ISSUE TITLE
Notification for change in invoice or folio data

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#94]
please provide me api which notify any changes occurred in invoice or folio data.

**Comment by dmitry-urenev** [comment]
Hi @patrickHermannLimeHouse have you try to create a subscription with `Folio` topic? 
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/7558366/53948741-cbe61080-40c8-11e9-98cb-5a3cffb09a03.png">

I check also the code: you will receive two types of events: `balance-changed` and `charge-posted`. That's all what is available for now. We'll let you know if more events are implemented.

**Comment by patrickHermannLimeHouse** [comment]
OK Thanks
