### ISSUE TITLE
need availability data

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#95]
Hi what is the apaleo API to get get the availability information?

**Comment by bennetone** [comment]
Hi @patrickHermannLimeHouse 

The historical and future availability on house level and broken down to the unit groups can be retrieved with the `GET /booking/v1/available-unit-groups` API.

**Comment by patrickHermannLimeHouse** [comment]
Hi @bennetone 
Thanks for response. I am not getting any data for this API.

**Comment by bennetone** [comment]
@patrickHermannLimeHouse 
Could you share the URL you are calling or the tracking id you receive in the response header please? That would allow me to check the request in the logs and help you on this.

**Comment by patrickHermannLimeHouse** [comment]
I am using 'booking/v1/available-unit-groups' and same headers which I use for getting reservations or properties.

**Comment by andreastubbe** [comment]
Hi @patrickHermannLimeHouse , we meant the header you get in the *response*, not when you make the *request*. Each request & response in apaleo has a unique identifier which lets us find it in our log files.

Looks like this:
`Apaleo-Tracking-Id: 0H189OLL7PK71:000003E9`

Did you manage to solve this problem in the meantime?

**Comment by bennetone** [comment]
Hi @patrickHermannLimeHouse 

I checked the logs and found some request you did to the available unit groups API. In the beginning you received responses with the http status code 422 and the following messages:

```

**Comment by patrickHermannLimeHouse** [comment]
we solved the problem. Thanks for your help!
Greets Sabine
