### ISSUE TITLE
How to handle additional guests?

### ISSUE THREAD

**Issue by c2ofh** [apaleo/api#96]
## Question

How is the proper way to handle additional guests.

For example, there is a reservation with 1 additional guest.
To update the primary guest and the additional guest, I have to send 2 requests to _PATCH /booking/v1/reservations/{id}_ with each data as 'replace' operation.

But what If I don't know if there an additional guest present? Do I have to check the whole reservation to look for additional guests and it`s size of the array? When equal, I can send a 'replace' PATCH with the additional guest.

When there are 2 guests in Apaleo and I have 3 guest data, then I have to replace the primary, the first additional and add another additonal. Is there a 'find or create' method available?

What happens if I want to update an additional guest, when there is no additional guest present?

## Background

We're collecting data for the registration form and the check-in before the check-in.
This could produce a mismatch between Apaleo guest count and our guest count.

## Edit

I found an easy solution. I just compage the size of my known guests between the 'adults' counter from the reservervation. 
But When I try to Replace an AdditionalGuest, I recieve the error message `"'Replace' is not allowed for path 'AdditionalGuests'."`

The documention looks like it should be allowed to replace an AdditionalGuest
![image](https://user-images.githubusercontent.com/10913793/54155875-4efac400-4445-11e9-9d88-ec6161392696.png)

```ruby
[
 {:value=>
   {:title=>nil,
    :firstName=>"Peter",
    :lastName=>"Mayer",
    :email=>"peter_mayer@gmail.com",
    :phone=>"123124324234",
    :address=>{:addressLine1=>"Teststraße 7",
               :postalCode=>"70190", 
               :city=>"Stuttgart", 
               :countryCode=>"DE"},
    :nationalityCountryCode=>"DE",
    :birthDate=>"1979-01-01"
  },
  :path=>"primaryGuest",
  :op=>"replace"},
 {:value=>
   {:title=>"Ms",
    :firstName=>"Martina",
    :lastName=>"Mayer",
    :email=>"martina_mayer@gemail.com",
    :phone=>"123124324234",
    :address=>{:addressLine1=>"Teststraße 7",
               :postalCode=>"70190", 
               :city=>"Stuttgart", 
               :countryCode=>"DE"},
    :nationalityCountryCode=>"DE",
    :birthDate=>"1981-06-10"},
  :path=>"AdditionalGuests",
  :op=>"replace"}
]

```

**Comment by DsAekb** [comment]
Hello c2ofh,

Thank you for your question.
You should use **a**dditionalGuests instead of **A**dditionalGuests in the path. Please bear in mind also that it is an array, so if you want to replace it you should replace it with an array.

Best Regards

**Comment by c2ofh** [comment]
Hello @DsAekb 

thank you for your response.
Could you describre, how a request looks like, when I replace a primary guest, replace an additional guest and add a new additional guest in one Request?

**Comment by DsAekb** [comment]
Hello c2oft,

you can do this with the following:

```json
[
    {
        "op": "replace",
        "path": "primaryGuest",
        "value": {<your primary guest data>}
    },
    {
        "op": "replace",
        "path": "additionalGuests/0",
        "value": {<your existing additional guest data>}
    },
    {
        "op": "add",
        "path": "additionalGuests/-",
        "value": {<your new additional guest data>}
    }
]
```

**Comment by c2ofh** [comment]
Hello @DsAekb 

Thank you very much. It was not clear in swagger. 
I also didn't knew, that I have to add a counter to the path.

**Comment by DsAekb** [comment]
You're welcome, I'm glad it helped. We will revise how we can make it clearer in the future.
