### ISSUE TITLE
Identify guests by an ID field

### ISSUE THREAD

**Issue by srserx** [apaleo/api#97]
## I want

An ID field to identify a guest. This way we would avoid having to identify them by email, which is not what we would expect.

## Use cases

Updating a reservation.

## Examples

In Apaleo, you can have several guests with the same lastname and email. And thus there's no way to identify them separately when working with the API.

**Comment by andreastubbe** [comment]
Guests only exist within a reservation. In the reservation, the list of additional guests is guaranteed to always be in the same order. You could use the index as an ID. Would this work for you? An ID would be redundant, same thing as the index.

**Comment by srserx** [comment]
An ID would be needed to track the same guest across multiple reservations in different dates. We would want to be able to say "Welcome again, mr Apaleo", when the guest Apaleo visits again the hotel after some time.

**Comment by andreastubbe** [comment]
Yeah, can't do that. Guests do not have a 'global' identity within apaleo, hence on ID. Only in the context of a reservation.
Now you might find this odd, but there is a very good reason for that: apaleo is a property management system, not customer relationship management. We focus on availability, accounting and APIs, and leave the rest to the experts: integrated CRMs. All that profile matching and merging, keeping track of communication history, customer lifetime value, loyalty points... just not our thing.

If you tell me a little bit more on what you're actually building, that would help me helping you.
