### ISSUE TITLE
Gross sales calculation in apaleo reports

### ISSUE THREAD

**Issue by patrickHermannLimeHouse** [apaleo/api#99]
## Question

I want to know the logic of monthly gross amount calculations in the apaleo front end. 
Reports > Gross Sales > Value of gross amount.

## Background

I tried to perform the monthly gross sales calculations on my own for the month of Februray. For most of the properties my figures are precise and matching with the apaleo figures, but in a few cases the figures differ by Euro 0-180. 
1) As per my understanding, it is calculating figures after cancellations and not taking cancellation revenue into account. 
2) Also, I am counting revenue for arrival day and not for departure day. I am wondering whether apaleo has the same concept or it splits revenue between arrival day and departure day.

Thanks!
Best,
Anika Goyal

**Comment by andreastubbe** [comment]
The gross sales numbers from the UI (or the reports/gross-sales API) are just plain revenues, and include cancellation and direct booking of services on a folio. Revenue for a night is always recognised at the beginning of the night.

What is it you use as the basis for your calculations?

Have you checked the reports/property-performance API? It's nsfw only right now, but might be worth checking out. We do calculate some aggregates there.

**Comment by patrickHermannLimeHouse** [comment]
Hi,

I checked the property performance API. For example, for the month of February -
I added the property_id and period from 2019-02-01 to 2019-02-28.
In the result gross amount value is 2541 EUR

But at the front end, the gross amount for the month of February 2019 is shown as 2,491.00 EUR.

Why do we have this difference? Do they not mean the same thing?

**Comment by dario-hd** [comment]
In the _Property Performance Report_ you only have accommodation revenue. We planned to restructure those reports in order to have more data available in the _Property Performance Report_.

**Comment by patrickHermannLimeHouse** [comment]
So, in my example, as per property performance report, accomodation revenue is 2541. Whereas in front end, the revenue including other sources is 50 Euro lesser than accomodation revenue, i.e., 2491. 
Can you explain what other sources are being considered here? A bit of explanation at that front would be helpful.

**Comment by dario-hd** [comment]
I don't know in your case...but it could be that you have a reservation with 50e included or extra service. Or, it could be that on one of your folios somebody manually posted a 50e charge. Those things are not considered in the _Property Performance Report_ I hope that helps.

**Comment by patrickHermannLimeHouse** [comment]
Ok, we understood the difference between gross sales report in the front end and the property performance report.

But we still find a difference between our calculation and the property performance report. They both do not consider the manual charges.
For example for February in Augsburg, we have calculated a accommodation revenue of 16.510 and the property performance report gave us the value of 16.550
Another example, for February in Essen, we have calculated a accommodation revenue of 4.758 and the property performance report gave us the value of 4.739
For both examples, the number of sold count is matching and for the other properties our figures are matching for February.

**Comment by andreastubbe** [comment]
it's really hard to tell, without knowing how you calculate those. What data do you use for input, and what is that you do?

**Comment by patrickHermannLimeHouse** [comment]
[feb_data.zip](https://github.com/apaleo/api/files/2983724/feb_data.zip)
I have attached a file of my calculations here for Augsburg and Essen. It includes the reservations that I am using for calculating February revenue for the two properties. The corresponding revenue we are talking about is in the field "feb_revenue".
Now, I hope it is more clear what I am doing and then you can compare it with the reservations and corresponding revenue which performance API is calculating. 
Please help me in figuring out the reason behind delta between the two figures.
Thanks!

**Comment by andreastubbe** [comment]
A little clearer :) Thanks. What would be super helpful is the actual API calls and fields you are using.

You do get all reservations that have at least one day in February, right? Maybe there's something wrong with the filter you use. Can you post the exact call, with all of the parameters you're passing?

And then, I'm guessing you get all 'time slices' from the reservations which do start in February. Right?
From the time slices, do you take the field 'baseAmount', or 'totalGrossAmount'?

**Comment by patrickHermannLimeHouse** [comment]
We have imported data from the reservations API into our database and then I used SQL to perform some operations. 
I have taken the following fields as per this filter-
booking_id, reservation_id, property_id, channel_code, gross_amount, cancellation_fee_code, created, modified, cancellation_time, cancellation_due_datetime, arrival_date, departure_date, stay_length from apaleo_reservations_data where arrival_date<'2019-03-01 00:00:00' and departure_date>'2019-02-01 23:59:59'
Then, from the arrival_date and departure_date, I tried calculating the number of days of stay in February in the field 'feb_days' (Here, I counted the arrival day as the one generating revenue and not the departure day, so if 1st Feb was an arrival day it will be counted for February revenue and if 1st Feb was a departure day then it will not be counted for February revenue.)
Afterwards, I calculated the revenue of February as gross_amount*feb_days/stay_length and filtered the entries where cancellation time is null.

You do get all reservations that have at least one day in February, right? Yes, even the value of sold count from unit performance matches my value of sum(feb_days).
And then, I'm guessing you get all 'time slices' from the reservations which do start in February. Right? Yes
From the time slices, do you take the field 'baseAmount', or 'totalGrossAmount'? TotalGrossAmount

**Comment by andreastubbe** [comment]
Okay, two points where we do it differently:
> Afterwards, I calculated the revenue of February as gross_amount*feb_days/stay_length

By doing this, you assume that every day always has the exact same price. This might not be true, the prices per day can theoretically vary.


> TotalGrossAmount

This is, as the documentation says including services. If you are only interested in room / accommodation revenue, take the base price of the time slices.

**Comment by patrickHermannLimeHouse** [comment]
Hi Andrea,

thank you very much for your help. This was very helpful.
We understand the topic much better know.

We only have problem with the "real" daily prices for reservations that have a length of more than one night. Then we only receive the total gross amount of the total stay via reservations api. Or is there any possibility to get the "real" daily prices?

For example, when we sell via booking.com and the customer gets a genius discount, we are not able to refer to our base-price in the rateplan, because the price reduction due to genius is on a individual level.

For example: ZYOQPRRR-1
In the Frontend we see the concrete variiing daily prices according to the genius price reduction: 
08.12: 80.10 €
09.12: 79.20 €
10.12: 79.20 €   
etc.

How can we get this data?

Kind regards 
Sabine

**Comment by dario-hd** [comment]
In order to get data about the time slices, you can use the `expand` parameter of the _Reserrvations API_ to expand the `timeSlices`. Then you will receive a `timeSlices` member for all reservations. You can check more [here](https://api.apaleo.com/swagger).

**Comment by patrickHermannLimeHouse** [comment]
Perfect. Thank you very much!! That helps a lot! 

Do we get a notification via the notification API, if the prices in a timeslice in an existing reservation is changing?

**Comment by dario-hd** [comment]
In such case, you will get a notification of type `amended` in the _Reservation_ topic.
